### ISSUE TITLE
Built-in generator tests (CSharp.Gen, NamespacesDerived.Gen) randomly throwing NRE in AstVisitor on reruns

### ISSUE THREAD

**Issue by Ark-kun** [mono/CppSharp#1002]
I'm just compiling/testing CppSharp. CppSharp itself has compiled fine.
When CppSharp wants to compile tests it runs code generators.
I've seen those generators fail with null reference exception during msbuild build. In VS they sometimes run fine, but sometimes crash with exception (just re-running the same CppSHarp generator project).

This non-deterministic failures irk me a lot.

I've seen several causes for exception:

1. `VisitDeclContext`, 
                var decl = ctx.GetClasses(i);
                var _decl = Visit(decl) as AST.Class; //The returned value was actually AST.Field. Thus, null

2.  `operator=` is stated to have 1 parameter, but it's null
3. `VisitClassDecl`, @class.Methods contains a null among the methods

This non-deterministic behavior really baffles me.

OS: Windows
Target: MSVC

### Case 0.1

> PreBuildEvent:
>   "A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\build\vs2017\lib\Release_x86\NamespacesDerived.Gen.exe"
> 
>   Generating bindings for NamespacesDerived (CSharp)
>   Looking for tests in: A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\tests\NamespacesDerived
>   C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0
>   Parsed 'NamespacesBase.h'
>   Parsed 'NamespacesDerived.h'
> 
>   Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>      at CppSharp.DeclConverter.VisitDeclContext(DeclarationContext ctx, DeclarationContext _ctx) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Parser\ASTConverter.cs:line 1008
>      at CppSharp.ASTConverter.Convert() in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Parser\ASTConverter.cs:line 409
>      at CppSharp.ClangParser.ConvertASTContext(ASTContext context) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Parser\Parser.cs:line 91
>      at CppSharp.Driver.ParseCode() in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Driver.cs:line 149
>      at CppSharp.ConsoleDriver.Run(ILibrary library) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Driver.cs:line 413
>      at CppSharp.Tests.NamespacesDerived.Main(String[] args) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\tests\NamespacesDerived\NamespacesDerived.cs:line 46
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1274,5): error MSB3073: The command ""A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\build\vs2017\lib\Release_x86\NamespacesDerived.Gen.exe"" exited with code -1073741819. [A:\_All\My.Cr
> eativity.Coding.3rd-party\_Incoming\CppSharp\tests\NamespacesBase\NamespacesBase.CSharp.csproj]
> Done Building Project "A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\tests\NamespacesBase\NamespacesBase.CSharp.csproj" (default targets) -- FAILED.

### Case 0.2

> PreBuildEvent:
>   "A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\build\vs2017\lib\Release_x86\CSharp.Gen.exe"
> 
>   Generating bindings for CSharp (CSharp)
>   Looking for tests in: A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\tests\CSharp
>   C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0
>   Parsed 'AnotherUnit.h'
>   Parsed 'CSharp.h'
>   Parsed 'CSharpTemplates.h'
> 
>   Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>      at CppSharp.Passes.TranslationUnitPass.IsDeclExcluded(Declaration decl) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Passes\Pass.cs:line 50
>      at CppSharp.Passes.TranslationUnitPass.VisitDeclaration(Declaration decl) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Passes\Pass.cs:line 44
>      at CppSharp.AST.AstVisitor.VisitFunctionDecl(Function function) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\AST\ASTVisitor.cs:line 394
>      at CppSharp.AST.AstVisitor.VisitMethodDecl(Method method) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\AST\ASTVisitor.cs:line 410
>      at CppSharp.AST.AstVisitor.VisitClassDecl(Class class) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\AST\ASTVisitor.cs:line 351
>      at CppSharp.AST.Class.Visit[T](IDeclVisitor`1 visitor) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\AST\Class.cs:line 312
>      at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\AST\ASTVisitor.cs:line 557
>      at CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(TranslationUnit unit) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Passes\Pass.cs:line 37
>      at CppSharp.Passes.TranslationUnitPass.VisitASTContext(ASTContext context) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Passes\Pass.cs:line 24
>      at CppSharp.Generators.BindingContext.<RunPasses>b__33_0(TranslationUnitPass pass) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\BindingContext.cs:line 42
>      at CppSharp.PassBuilder`1.RunPasses(Action`1 action) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Passes\PassBuilder.cs:line 49
>      at CppSharp.Generators.BindingContext.RunPasses() in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\BindingContext.cs:line 36
>      at CppSharp.Driver.ProcessCode() in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Driver.cs:line 272
>      at CppSharp.ConsoleDriver.Run(ILibrary library) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\src\Generator\Driver.cs:line 429
>      at CppSharp.Tests.CSharpTestsGenerator.Main(String[] args) in A:\_All\My.Creativity.Coding.3rd-party\_Incoming\CppSharp\tests\CSharp\CSharp.cs:line 63

### Case 1:
`var d = Visit(decl);`

> {_Myend}
>     [CppSharp.AST.Field]: {_Myend}
>     Access: Public
>     Attributes: Count = 0
>     Comment: null
>     CompleteDeclaration: null
>     DebugText: "pointer _Myend"
>     DefinitionOrder: 0
>     ExcludeFromPasses: Count = 0
>     ExplicityIgnored: false
>     generationKind: null
>     GenerationKind: Generate
>     Ignore: false
>     IsDeclared: true
>     IsDependent: true
>     IsExplicitlyGenerated: false
>     IsGenerated: true
>     IsImplicit: false
>     IsIncomplete: false
>     IsInternal: false
>     LineNumberEnd: 442
>     LineNumberStart: 442
>     Location: {File ID: 484975}
>     LogicalName: "_Myend"
>     LogicalOriginalName: "_Myend"
>     MaxFieldAlignment: 0
>     Name: "_Myend"
>     name: "_Myend"
>     namespace: {_Vector_val}
>     Namespace: {_Vector_val}
>     OriginalName: "_Myend"
>     OriginalNamespace: {_Vector_val}
>     OriginalPtr: 135234160
>     PreprocessedEntities: Count = 0
>     QualifiedLogicalName: "std::_Vector_val::_Myend"
>     QualifiedLogicalOriginalName: "std::_Vector_val::_Myend"
>     QualifiedName: "std::_Vector_val::_Myend"
>     QualifiedOriginalName: "std::_Vector_val::_Myend"
>     Redeclarations: Count = 0
>     TranslationUnit: File = "vector", Ignored = false
>     USR: "c:@N@std@ST>1#T@_Vector_val@FI@_Myend"

`d is AST.Class`
>false

`var d2 = Visit(decl);`

> {DerivesFromTemplateWithExplicitSpecialization}
>     [CppSharp.AST.Class]: {DerivesFromTemplateWithExplicitSpecialization}
>     Access: Public
>     Attributes: Count = 0
>     Comment: null
>     CompleteDeclaration: null
>     DebugText: "class DerivesFromTemplateWithExplicitSpecialization : public HasDefaultTemplateArgument<T, D>\r\n{\r\npublic:\r\n    DerivesFromTemplateWithExplicitSpecialization();\r\n    ~DerivesFromTemplateWithExplicitSpecialization();\r\n}"
>     DefinitionOrder: 0
>     ExcludeFromPasses: Count = 0
>     ExplicityIgnored: false
>     generationKind: null
>     GenerationKind: Generate
>     Ignore: false
>     IsDeclared: true
>     IsDependent: true
>     IsExplicitlyGenerated: false
>     IsGenerated: true
>     IsImplicit: false
>     IsIncomplete: false
>     IsInternal: false
>     LineNumberEnd: 293
>     LineNumberStart: 288
>     Location: {File ID: 17563}
>     LogicalName: "DerivesFromTemplateWithExplicitSpecialization"
>     LogicalOriginalName: "DerivesFromTemplateWithExplicitSpecialization"
>     MaxFieldAlignment: 0
>     Name: "DerivesFromTemplateWithExplicitSpecialization"
>     name: "DerivesFromTemplateWithExplicitSpecialization"
>     namespace: File = "CSharpTemplates.h", Ignored = false
>     Namespace: File = "CSharpTemplates.h", Ignored = false
>     OriginalName: "DerivesFromTemplateWithExplicitSpecialization"
>     OriginalNamespace: File = "CSharpTemplates.h", Ignored = false
>     OriginalPtr: 135234160
>     PreprocessedEntities: Count = 0
>     QualifiedLogicalName: "DerivesFromTemplateWithExplicitSpecialization"
>     QualifiedLogicalOriginalName: "DerivesFromTemplateWithExplicitSpecialization"
>     QualifiedName: "DerivesFromTemplateWithExplicitSpecialization"
>     QualifiedOriginalName: "DerivesFromTemplateWithExplicitSpecialization"
>     Redeclarations: Count = 0
>     TranslationUnit: File = "CSharpTemplates.h", Ignored = false
>     USR: "c:@ST>2#T#T@DerivesFromTemplateWithExplicitSpecialization"

### Case 2:
`function`

> {operator=}
>     [CppSharp.AST.Method]: {operator=}
>     base {CppSharp.AST.DeclarationContext}: {operator=}
>     Body: "{\n    *this.T1::operator=();\n    this->independent = .independent;\n    return *this;\n}\n"
>     CallingConvention: ThisCall
>     Field: null
>     FriendKind: None
>     FunctionType: {Func<global::CSharp.IndependentFields<int>, global::CSharp.IndependentFields<int> >}
>     HasIndirectReturnTypeParameter: 'function.HasIndirectReturnTypeParameter' threw an exception of type 'System.NullReferenceException'
>     HasThisReturn: false
>     InstantiatedFrom: null
>     IsAmbiguous: false
>     IsCCall: false
>     IsConstExpr: false
>     IsDefaulted: true
>     IsDeleted: false
>     IsFastCall: false
>     IsInline: true
>     IsNonMemberOperator: false
>     IsOperator: true
>     IsPure: false
>     IsReturnIndirect: false
>     IsStdCall: false
>     IsSynthetized: false
>     IsThisCall: true
>     IsVariadic: false
>     Mangled: "??4?$IndependentFields@H@@QAEAAV0@ABV0@@Z"
>     OperatorKind: Equal
>     OriginalFunction: null
>     OriginalReturnType: 'function.OriginalReturnType' threw an exception of type 'System.NullReferenceException'
>     Parameters: Count = 1
>     QualifiedType: {global::CSharp.IndependentFields<int>}
>     ReturnType: {global::CSharp.IndependentFields<int>}
>     Signature: "IndependentFields"
>     SpecializationInfo: null
>     SynthKind: None
>     Type: "global::CSharp.IndependentFields<int>" ["PointerType"]

### Case 3:

`methods`

> {CppSharp.AST.Method[7]}
>     [0]: {InheritsProtectedVirtualFromSecondaryBase}
>     [1]: null
>     [2]: {operator=}
>     [3]: {operator=}
>     [4]: {~InheritsProtectedVirtualFromSecondaryBase}
>     [5]: {InheritsProtectedVirtualFromSecondaryBase}
>     [6]: {InheritsProtectedVirtualFromSecondaryBase}

> >	CppSharp.Generator.dll!CppSharp.Passes.TranslationUnitPass.IsDeclExcluded(CppSharp.AST.Declaration decl) Line 50 + 0x3 bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.Passes.TranslationUnitPass.VisitDeclaration(CppSharp.AST.Declaration decl) Line 44 + 0xb bytes	C#	Symbols loaded.
>  	CppSharp.AST.dll!CppSharp.AST.AstVisitor.VisitFunctionDecl(CppSharp.AST.Function function) Line 394 + 0xe bytes	C#	Symbols loaded.
>  	CppSharp.AST.dll!CppSharp.AST.AstVisitor.VisitMethodDecl(CppSharp.AST.Method method) Line 410 + 0xe bytes	C#	Symbols loaded.
>  	CppSharp.AST.dll!CppSharp.AST.AstVisitor.VisitClassDecl(CppSharp.AST.Class class) Line 351 + 0x11 bytes	C#	Symbols loaded.
>  	CppSharp.AST.dll!CppSharp.AST.Class.Visit<bool>(CppSharp.AST.IDeclVisitor<bool> visitor) Line 312 + 0xc bytes	C#	Symbols loaded.
>  	CppSharp.AST.dll!CppSharp.AST.AstVisitor.VisitDeclarationContext(CppSharp.AST.DeclarationContext context) Line 557 + 0x24 bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(CppSharp.AST.TranslationUnit unit) Line 37 + 0xe bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.Passes.TranslationUnitPass.VisitASTContext(CppSharp.AST.ASTContext context) Line 24 + 0xe bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.Generators.BindingContext.RunPasses.AnonymousMethod__33_0(CppSharp.Passes.TranslationUnitPass pass) Line 42 + 0x1f bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.PassBuilder<CppSharp.Passes.TranslationUnitPass>.RunPasses(System.Action<CppSharp.Passes.TranslationUnitPass> action) Line 49 + 0xe bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.Generators.BindingContext.RunPasses() Line 36 + 0x36 bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.Driver.ProcessCode() Line 272 + 0x15 bytes	C#	Symbols loaded.
>  	CppSharp.Generator.dll!CppSharp.ConsoleDriver.Run(CppSharp.ILibrary library) Line 429 + 0xa bytes	C#	Symbols loaded.
>  	CSharp.Gen.exe!CppSharp.Tests.CSharpTestsGenerator.Main(string[] args) Line 63 + 0x22 bytes	C#	Symbols loaded.

**Comment by ddobrev** [comment]
Do you use our latest code? I fixed a crash in native memory just yesterday which looks like this bug - random null references. Am I correct that you get the crash at different location on each run?

**Comment by tritao** [comment]
Hey, this is definitely not normal behaviour.

As @ddobrev said, he refactored some code the last few days which might have added some regressions. Try the latest revision and let us know if it's still an issue.

**Comment by Ark-kun** [comment]
I was at 51a109d2dba2b793521906faff8d2f32a59f9dfc (Nov 12). I'll try the latest code.

**Comment by ddobrev** [comment]
@Ark-kun you should be fine with master, the commit you've linked is precisely the one I introduced the crash at.

**Comment by Ark-kun** [comment]
me.Luck == -13
Looks like it stopped crashing on HEAD.
