### ISSUE TITLE
Windows systemversion missing from premake5.lua

### ISSUE THREAD

**Issue by trmcnealy** [mono/CppSharp#1006]
##### Brief Description
systemversion missing from premake5.lua

OS: Windows

this is a function I inserted into Helper.lua.
`
function os.winSdkVersion()
	local reg_arch = iif( os.is64bit(), "\\Wow6432Node\\", "\\" )
	local sdk_version = string.format("%s.0", os.getWindowsRegistry( "HKLM:SOFTWARE" .. reg_arch .."Microsoft\\Microsoft SDKs\\Windows\\v10.0\\ProductVersion" ))
	if sdk_version ~= nil then
		return sdk_version
	else
		return "10.0.16299.0"
	end
	-- add more versions here ( "v8.1", "v7.1A" )
end
`

In the premake5.lua under `solution "CppSharp"` add `systemversion(os.winSdkVersion())`

**Comment by ddobrev** [comment]
@trmcnealy thank you for trying to fix but I am afraid I don't understand what you're trying to fix. What problem do you get if you don't have this function of yours?

**Comment by tritao** [comment]
@ddobrev see https://github.com/premake/premake-core/issues/936 and https://github.com/premake/premake-core/issues/935

**Comment by ddobrev** [comment]
@trmcnealy thank you for pointing our attention to this. As you can tell by @tritao 's links, these are problems in premake itself which we don't have the time to fix ourselves. As soon as they are fixed, we'll update the premake binaries we contain in our repo and this will no longer be a problem.

**Comment by tritao** [comment]
I hit this issue trying to compile CppSharp out-of-the-box on VS2017 / Windows 10.

Sent a fix in https://github.com/mono/CppSharp/pull/1125/commits/8d4381c1a0cb41bea6d45844614577c6147ac389.
