### ISSUE TITLE
Const and non-const constructor overloads

### ISSUE THREAD

**Issue by stephenatwork** [mono/CppSharp#102]
When signatures clash, they're given an ordinal to disambiguate them. This doesn't work for constructors however.

``` C++
struct Overloaded
{
    Overloaded(void* p) {}
    Overloaded(const void* p) {}
};
```

I'm not sure what the best answer for this is. Add extra discriminant parameters or fallback to runtime dispatch?

``` C#
public void Overloaded(void* p, int isConst) // runtime
{
     var arg0 = p;
     if(isConst) Internal._Overloaded0(__Instance, arg0);
     else Internal._Overloaded1(__Instance, arg0);
}
```

``` C#
public void Overloaded(void* p, Const.True)
public void Overloaded(void* p, Const.False)
```

I'm not familiar with c# generics but perhaps there's a solution there?

**Comment by ddobrev** [comment]
We have now long resolved this by choosing to only generate the non-const version since it's a superset of the other.
