### ISSUE TITLE
The target should be an array but the generated Csharp file is not

### ISSUE THREAD

**Issue by pk27602017** [mono/CppSharp#1030]
##### Brief Description

![qq 20171219171633](https://user-images.githubusercontent.com/8246779/34149583-8dc5f3b4-e4e0-11e7-88b3-8566b989b3c0.png)

![qq 20171219171707](https://user-images.githubusercontent.com/8246779/34149588-92013830-e4e0-11e7-83f3-05a0cf7f2e89.png)

The target should be an array but the generated Csharp file is not
How can I solve this problem?
OS: Windows 7

Target: MSVC

**Comment by tritao** [comment]
We have no way of knowing if this is a pointer or an array, so we generate the pointer by default.

In this case you can manually extend your binding with an helper method that takes the arrays and forwards to the generated one.

It would also be possible to extend CppSharp itself so you could flag in the AST that this particular parameter represents an array with a given size, but that would be more involved. If you're interested in contributing that feature, we'd be happy to guide you on how to do it.
