### ISSUE TITLE
struct If there is a virtual function, the export will lead to errors

### ISSUE THREAD

**Issue by pk27602017** [mono/CppSharp#1031]
header 
![qq 20171229164740](https://user-images.githubusercontent.com/8246779/34433129-048e4c56-ecb8-11e7-827e-c10017bf75fc.png)

Generated code
![qq 20171229164950](https://user-images.githubusercontent.com/8246779/34433162-4e8e9ba8-ecb8-11e7-82f9-f7655b08ba60.png)

When I create a Hello instance will throw an error, can not find the entry point, when I delete this line of code everything is working, how to solve this problem

**Comment by ddobrev** [comment]
@pk27602017 you need to compile the generated cpp to get inlined symbols. For an example see https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/QtSharp.cs#L222 .

**Comment by tritao** [comment]
Or you can move the implementations of the methods to the `.cpp` file instead of the `.h` file. That way the compiler will force it to be included in `dll` and you don't need extra inline libraries.

**Comment by pk27602017** [comment]
@tritao No, this is open source code and I want to change as little code as I can

@ddobrev I tried to compile symbol files with SymbolsCodeGenerated and seemed to solve a lot of potential problems, but the above problem still remains unresolved.
![image](https://user-images.githubusercontent.com/8246779/34516417-a708e0ac-f0b1-11e7-8d37-a0cb22d5727a.png)
The generated constructor becomes
![image](https://user-images.githubusercontent.com/8246779/34516489-ecf037c8-f0b1-11e7-844a-817103127c0d.png)
