### ISSUE TITLE
Download deps doesn't work on Windows for release 0.8.17

### ISSUE THREAD

**Issue by anderskaplan** [mono/CppSharp#1032]
Dependency download script doesn't work on Windows for release 0.8.17

OS: Windows 10

Repro steps:
1. download release 0.8.17 on a Windows 10 machine with VS 2015
2. unzip
3. cd build
4. DownloadDeps.bat

expected: dependencies to be downloaded

actual: operation fails with error message:
...\CppSharp-0.8.17\build>"premake5" --file=scripts/LLVM.lua download_llvm
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo.7z
Error: .../CppSharp-0.8.17/build/scripts/Utils.lua:98: HTTP response code said error
The requested URL returned error: 404 Not Found

**Comment by tritao** [comment]
We do not have this package pre-compiled for VS2015, just for VS2017, which is what we are testing on our CI.

I sent https://github.com/mono/CppSharp/pull/1033 to improve the check to give a better error in this case.

If you want to use VS2015 you will need compile LLVM yourself using the scripts, check the docs how to do this.

**Comment by anderskaplan** [comment]
Yes that's a reasonable fix. Thanks!
