### ISSUE TITLE
StackOverflowException when running example from "Generating Bindings" with NuGet Package

### ISSUE THREAD

**Issue by dennisai** [mono/CppSharp#1035]
I created a new Visual Studio 2015 project, added the CppSharp project via NuGet (v0.8.17).  Then I created a main function as below.

    public class Program
    {
        static void Main(string[] args)
        {
            ConsoleDriver.Run(new MyLibrary());
        }
    }

My `MyLibrary` class implements `ILibrary`, but all of its functions are empty.  If I add `IncludeDirs`, `Headers`, `LibraryDirs`, and `Libraries`, the same problem happens.  When I run the program, I get:

    Process is terminated due to StackOverflowException.

If I inspect the dump file that gets produced, I see a lot of calls to `CppSharp.dll!CppSharp.MSVCToolchain.FindVSVersion(...)`.

OS: Windows 10 64-Bit

##### Used headers

N/A

##### Used settings

N/A

Target: MSVC

**Comment by pk27602017** [comment]
https://github.com/mono/CppSharp/issues/1032 
May be helpful to you

**Comment by ddobrev** [comment]
Would you be able to build CppSharp from source code and debug this? We have fixed a similar bug and I am surprised to see it again.

**Comment by dennisai** [comment]
I looked at the issue that pk27602017 brought up.  As there is no precompiled Clang/LLVM for VS2015, I am trying to build from source.  However, I am unable to compile those components from source.  According to the documentation, I first execute the following:

    premake5.exe --file=scripts/LLVM.lua clone_llvm
![cloneresult](https://user-images.githubusercontent.com/1017972/34528571-4e304c48-f077-11e7-9deb-e5a018f6b88a.PNG)

With 7-Zip, that uncompresses the .tar.gz file into .tar files.

Then, when I execute the following:

    premake5.exe --file=scripts/LLVM.lua build_llvm

    LLVM/Clang directory does not exist, cloning...
    LLVM release: 9bde5fb8f8ea44d6ef0f2edb4f54cbff7a0aee53
    Clang release: ffc5930a5cffb23df03565739b8820d14a19d4bf
    Archive llvm-9bde5fb8f8ea44d6ef0f2edb4f54cbff7a0aee53.tar.gz already exists.
    "C:\Program Files\7-Zip\7z.exe" x llvm-9bde5fb8f8ea44d6ef0f2edb4f54cbff7a0aee53.tar.gz -o. -y
    Archive clang-ffc5930a5cffb23df03565739b8820d14a19d4bf.tar.gz already exists.
    "C:\Program Files\7-Zip\7z.exe" x clang-ffc5930a5cffb23df03565739b8820d14a19d4bf.tar.gz -o. -y
    cmake -G "Ninja" -DLLVM_BUILD_TOOLS=false  -DLLVM_ENABLE_LIBEDIT=false -DLLVM_ENABLE_ZLIB=false -DLLVM_ENABLE_TERMINFO=false -DLLVM_ENABLE_LIBXML2=false -DLLVM_INCLUDE_EXAMPLES=false  -DLLVM_INCLUDE_DOCS=false  -DLLVM_INCLUDE_TESTS=false -DLLVM_TOOL_BUGPOINT_BUILD=false -DLLVM_TOOL_BUGPOINT_PASSES_BUILD=false -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=false -DLLVM_TOOL_COMPILER_RT_BUILD=false -DLLVM_TOOL_DRAGONEGG_BUILD=false -DLLVM_TOOL_DSYMUTIL_BUILD=false -DLLVM_TOOL_GOLD_BUILD=false -DLLVM_TOOL_LLC_BUILD=false -DLLVM_TOOL_LLDB_BUILD=false -DLLVM_TOOL_LLD_BUILD=false -DLLVM_TOOL_LLGO_BUILD=false -DLLVM_TOOL_LLI_BUILD=false -DLLVM_TOOL_LLVM_AR_BUILD=false -DLLVM_TOOL_LLVM_AS_BUILD=false -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=false -DLLVM_TOOL_LLVM_CONFIG_BUILD=false -DLLVM_TOOL_LLVM_COV_BUILD=false -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=false -DLLVM_TOOL_LLVM_C_TEST_BUILD=false -DLLVM_TOOL_LLVM_DIFF_BUILD=false -DLLVM_TOOL_LLVM_DIS_BUILD=false -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=false -DLLVM_TOOL_LLVM_EXTRACT_BUILD=false -DLLVM_TOOL_LLVM_GO_BUILD=false -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=false -DLLVM_TOOL_LLVM_LINK_BUILD=false -DLLVM_TOOL_LLVM_LTO_BUILD=false -DLLVM_TOOL_LLVM_MCMARKUP_BUILD=false -DLLVM_TOOL_LLVM_MC_BUILD=false -DLLVM_TOOL_LLVM_MC_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_NM_BUILD=false -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=false -DLLVM_TOOL_LLVM_PDBDUMP_BUILD=false -DLLVM_TOOL_LLVM_PROFDATA_BUILD=false -DLLVM_TOOL_LLVM_READOBJ_BUILD=false -DLLVM_TOOL_LLVM_RTDYLD_BUILD=false -DLLVM_TOOL_LLVM_SHLIB_BUILD=false -DLLVM_TOOL_LLVM_SIZE_BUILD=false -DLLVM_TOOL_LLVM_SPLIT_BUILD=false -DLLVM_TOOL_LLVM_STRESS_BUILD=false -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=false -DLLVM_TOOL_LTO_BUILD=false -DLLVM_TOOL_MSBUILD_BUILD=false -DLLVM_TOOL_OBJ2YAML_BUILD=false -DLLVM_TOOL_OPT_BUILD=false -DLLVM_TOOL_SANCOV_BUILD=false -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=false -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=false -DLLVM_TOOL_YAML2OBJ_BUILD=false -DCLANG_BUILD_EXAMPLES=false  -DCLANG_INCLUDE_DOCS=false  -DCLANG_INCLUDE_TESTS=false -DCLANG_ENABLE_ARCMT=false -DCLANG_ENABLE_STATIC_ANALYZER=false -DCLANG_TOOL_ARCMT_TEST_BUILD=false -DCLANG_TOOL_CLANG_CHECK_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_VS_BUILD=false -DCLANG_TOOL_CLANG_FUZZER_BUILD=false -DCLANG_TOOL_C_ARCMT_TEST_BUILD=false -DCLANG_TOOL_C_INDEX_TEST_BUILD=false -DCLANG_TOOL_DIAGTOOL_BUILD=false -DCLANG_TOOL_LIBCLANG_BUILD=false -DCLANG_TOOL_SCAN_BUILD_BUILD=false -DCLANG_TOOL_SCAN_VIEW_BUILD=false -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=RelWithDebInfo .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11  -DLLVM_BUILD_32_BITS=true -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0'
    CMake Error: The source directory "C:/Users/.../Documents/Visual Studio 2015/Projects/.../CppSharp-0.8.17/deps/llvm" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    Error: ...015/Projects/.../CppSharp-0.8.17/build/scripts/Utils.lua:35: Error executing shell command, aborting...

**Comment by ddobrev** [comment]
Have you tried building with our VS 2017 packages? In short, they might work.
If not, please try deleting the downloaded archives and try again. CMakeLists.txt should appear in deps/llvm.

**Comment by tritao** [comment]
Can you try also extracting the tar file? 

This looks like a regression on our scripts when running on Windows... introduced in https://github.com/mono/CppSharp/commit/1d4c2435225579b48e0ea4dc8aea4bf044868a62#diff-d57dbe7e68d12f5a74fb96afd1e027bf.

Looks like we need to improve `extract_7z` in `LLVM.lua`. If it finds a `.tar.gz` file, then it needs to call 7-Zip in two steps, to decompress and extract as 7-Zip cannot do it in just one step.

**Comment by dennisai** [comment]
I tried using the pre-compiled VS2017 package (by renaming it to 2015), and it had an error.  I then manually extracted the .tar files, re-ran the following commands:

    premake5.exe --file=scripts/LLVM.lua clone_llvm
    premake5.exe --file=scripts/LLVM.lua build_llvm
```
cmake -G "Ninja" -DLLVM_BUILD_TOOLS=false  -DLLVM_ENABLE_LIBEDIT=false -DLLVM_ENABLE_ZLIB=false -DLLVM_ENABLE_TERMINFO=false -DLLVM_ENABLE_LIBXML2=false -DLLVM_INCLUDE_EXAMPLES=false  -DLLVM_INCLUDE_DOCS=false  -DLLVM_INCLUDE_TESTS=false -DLLVM_TOOL_BUGPOINT_BUILD=false -DLLVM_TOOL_BUGPOINT_PASSES_BUILD=false -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=false -DLLVM_TOOL_COMPILER_RT_BUILD=false -DLLVM_TOOL_DRAGONEGG_BUILD=false -DLLVM_TOOL_DSYMUTIL_BUILD=false -DLLVM_TOOL_GOLD_BUILD=false -DLLVM_TOOL_LLC_BUILD=false -DLLVM_TOOL_LLDB_BUILD=false -DLLVM_TOOL_LLD_BUILD=false -DLLVM_TOOL_LLGO_BUILD=false -DLLVM_TOOL_LLI_BUILD=false -DLLVM_TOOL_LLVM_AR_BUILD=false -DLLVM_TOOL_LLVM_AS_BUILD=false -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=false -DLLVM_TOOL_LLVM_CONFIG_BUILD=false -DLLVM_TOOL_LLVM_COV_BUILD=false -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=false -DLLVM_TOOL_LLVM_C_TEST_BUILD=false -DLLVM_TOOL_LLVM_DIFF_BUILD=false -DLLVM_TOOL_LLVM_DIS_BUILD=false -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=false -DLLVM_TOOL_LLVM_EXTRACT_BUILD=false -DLLVM_TOOL_LLVM_GO_BUILD=false -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=false -DLLVM_TOOL_LLVM_LINK_BUILD=false -DLLVM_TOOL_LLVM_LTO_BUILD=false -DLLVM_TOOL_LLVM_MCMARKUP_BUILD=false -DLLVM_TOOL_LLVM_MC_BUILD=false -DLLVM_TOOL_LLVM_MC_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_NM_BUILD=false -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=false -DLLVM_TOOL_LLVM_PDBDUMP_BUILD=false -DLLVM_TOOL_LLVM_PROFDATA_BUILD=false -DLLVM_TOOL_LLVM_READOBJ_BUILD=false -DLLVM_TOOL_LLVM_RTDYLD_BUILD=false -DLLVM_TOOL_LLVM_SHLIB_BUILD=false -DLLVM_TOOL_LLVM_SIZE_BUILD=false -DLLVM_TOOL_LLVM_SPLIT_BUILD=false -DLLVM_TOOL_LLVM_STRESS_BUILD=false -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=false -DLLVM_TOOL_LTO_BUILD=false -DLLVM_TOOL_MSBUILD_BUILD=false -DLLVM_TOOL_OBJ2YAML_BUILD=false -DLLVM_TOOL_OPT_BUILD=false -DLLVM_TOOL_SANCOV_BUILD=false -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=false -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=false -DLLVM_TOOL_YAML2OBJ_BUILD=false -DCLANG_BUILD_EXAMPLES=false  -DCLANG_INCLUDE_DOCS=false  -DCLANG_INCLUDE_TESTS=false -DCLANG_ENABLE_ARCMT=false -DCLANG_ENABLE_STATIC_ANALYZER=false -DCLANG_TOOL_ARCMT_TEST_BUILD=false -DCLANG_TOOL_CLANG_CHECK_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_VS_BUILD=false -DCLANG_TOOL_CLANG_FUZZER_BUILD=false -DCLANG_TOOL_C_ARCMT_TEST_BUILD=false -DCLANG_TOOL_C_INDEX_TEST_BUILD=false -DCLANG_TOOL_DIAGTOOL_BUILD=false -DCLANG_TOOL_LIBCLANG_BUILD=false -DCLANG_TOOL_SCAN_BUILD_BUILD=false -DCLANG_TOOL_SCAN_VIEW_BUILD=false -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=RelWithDebInfo .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11  -DLLVM_BUILD_32_BITS=true -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/E29315/Documents/Visual Studio 2015/Projects/OME/CppSharp-0.8.17/deps/llvm/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo/CMakeFiles/CMakeTmp

    Run Build Command:"C:/Ninja/ninja.exe" "cmTC_8e68f"
    [1/2] Building C object CMakeFiles\cmTC_8e68f.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_8e68f.exe
    FAILED: cmTC_8e68f.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_8e68f.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_8e68f.dir\testCCompiler.c.obj  /out:cmTC_8e68f.exe /implib:cmTC_8e68f.lib /pdb:cmTC_8e68f.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_8e68f.dir/manifest.res CMakeFiles\cmTC_8e68f.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:45 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/.../Documents/Visual Studio 2015/Projects/OME/CppSharp-0.8.17/deps/llvm/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "C:/Users/.../Documents/Visual Studio 2015/Projects/OME/CppSharp-0.8.17/deps/llvm/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo/CMakeFiles/CMakeError.log".
Error: ...015/Projects/OME/CppSharp-0.8.17/build/scripts/Utils.lua:35: Error executing shell command, aborting...
```

**Comment by tritao** [comment]
Are you running it from a VS command prompt?

**Comment by dennisai** [comment]
Yes, I tried running it from a VS2015 x64 Native Tools Command Prompt and then a VS2015 x86 Native Tools Command Prompt.  I pasted the former error above, the error for the latter is below.

```
cmake -G "Ninja" -DLLVM_BUILD_TOOLS=false  -DLLVM_ENABLE_LIBEDIT=false -DLLVM_ENABLE_ZLIB=false -DLLVM_ENABLE_TERMINFO=false -DLLVM_ENABLE_LIBXML2=false -DLLVM_INCLUDE_EXAMPLES=false  -DLLVM_INCLUDE_DOCS=false  -DLLVM_INCLUDE_TESTS=false -DLLVM_TOOL_BUGPOINT_BUILD=false -DLLVM_TOOL_BUGPOINT_PASSES_BUILD=false -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=false -DLLVM_TOOL_COMPILER_RT_BUILD=false -DLLVM_TOOL_DRAGONEGG_BUILD=false -DLLVM_TOOL_DSYMUTIL_BUILD=false -DLLVM_TOOL_GOLD_BUILD=false -DLLVM_TOOL_LLC_BUILD=false -DLLVM_TOOL_LLDB_BUILD=false -DLLVM_TOOL_LLD_BUILD=false -DLLVM_TOOL_LLGO_BUILD=false -DLLVM_TOOL_LLI_BUILD=false -DLLVM_TOOL_LLVM_AR_BUILD=false -DLLVM_TOOL_LLVM_AS_BUILD=false -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=false -DLLVM_TOOL_LLVM_CONFIG_BUILD=false -DLLVM_TOOL_LLVM_COV_BUILD=false -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=false -DLLVM_TOOL_LLVM_C_TEST_BUILD=false -DLLVM_TOOL_LLVM_DIFF_BUILD=false -DLLVM_TOOL_LLVM_DIS_BUILD=false -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=false -DLLVM_TOOL_LLVM_EXTRACT_BUILD=false -DLLVM_TOOL_LLVM_GO_BUILD=false -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=false -DLLVM_TOOL_LLVM_LINK_BUILD=false -DLLVM_TOOL_LLVM_LTO_BUILD=false -DLLVM_TOOL_LLVM_MCMARKUP_BUILD=false -DLLVM_TOOL_LLVM_MC_BUILD=false -DLLVM_TOOL_LLVM_MC_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_NM_BUILD=false -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=false -DLLVM_TOOL_LLVM_PDBDUMP_BUILD=false -DLLVM_TOOL_LLVM_PROFDATA_BUILD=false -DLLVM_TOOL_LLVM_READOBJ_BUILD=false -DLLVM_TOOL_LLVM_RTDYLD_BUILD=false -DLLVM_TOOL_LLVM_SHLIB_BUILD=false -DLLVM_TOOL_LLVM_SIZE_BUILD=false -DLLVM_TOOL_LLVM_SPLIT_BUILD=false -DLLVM_TOOL_LLVM_STRESS_BUILD=false -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=false -DLLVM_TOOL_LTO_BUILD=false -DLLVM_TOOL_MSBUILD_BUILD=false -DLLVM_TOOL_OBJ2YAML_BUILD=false -DLLVM_TOOL_OPT_BUILD=false -DLLVM_TOOL_SANCOV_BUILD=false -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=false -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=false -DLLVM_TOOL_YAML2OBJ_BUILD=false -DCLANG_BUILD_EXAMPLES=false  -DCLANG_INCLUDE_DOCS=false  -DCLANG_INCLUDE_TESTS=false -DCLANG_ENABLE_ARCMT=false -DCLANG_ENABLE_STATIC_ANALYZER=false -DCLANG_TOOL_ARCMT_TEST_BUILD=false -DCLANG_TOOL_CLANG_CHECK_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_VS_BUILD=false -DCLANG_TOOL_CLANG_FUZZER_BUILD=false -DCLANG_TOOL_C_ARCMT_TEST_BUILD=false -DCLANG_TOOL_C_INDEX_TEST_BUILD=false -DCLANG_TOOL_DIAGTOOL_BUILD=false -DCLANG_TOOL_LIBCLANG_BUILD=false -DCLANG_TOOL_SCAN_BUILD_BUILD=false -DCLANG_TOOL_SCAN_VIEW_BUILD=false -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=RelWithDebInfo .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11  -DLLVM_BUILD_32_BITS=true -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/E29315/Documents/Visual Studio 2015/Projects/OME/CppSharp-0.8.17/deps/llvm/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo/CMakeFiles/CMakeTmp

    Run Build Command:"C:/Ninja/ninja.exe" "cmTC_c9d50"
    [1/2] Building C object CMakeFiles\cmTC_c9d50.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_c9d50.exe
    FAILED: cmTC_c9d50.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_c9d50.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo CMakeFiles\cmTC_c9d50.dir\testCCompiler.c.obj  /out:cmTC_c9d50.exe /implib:cmTC_c9d50.lib /pdb:cmTC_c9d50.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_c9d50.dir/manifest.res CMakeFiles\cmTC_c9d50.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:45 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/.../Documents/Visual Studio 2015/Projects/OME/CppSharp-0.8.17/deps/llvm/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "C:/Users/.../Documents/Visual Studio 2015/Projects/OME/CppSharp-0.8.17/deps/llvm/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo/CMakeFiles/CMakeError.log".
Error: ...015/Projects/OME/CppSharp-0.8.17/build/scripts/Utils.lua:35: Error executing shell command, aborting...
```

**Comment by tritao** [comment]
This looks like an issue with your VS environment, looks like it can't find the `rc` tool on the path.

**Comment by zchrissirhcz** [comment]
Late here, but same problem. It is very like that the installed Visual Studio 2015 is not with rc.exe in PATH. Consider repair VS2015 update3's installation with choosing:

>Windows and Web Development -> Universal Windows App Development Tools -> Tools (1.4.1) and Windows 10 SDK (10.0.14393)

ref: https://stackoverflow.com/questions/43847542/rc-exe-no-longer-found-in-vs-2015-command-prompt
