### ISSUE TITLE
Wrapping code in binary-only form

### ISSUE THREAD

**Issue by DaveInCaz** [mono/CppSharp#1036]
I have a Fortran DLL which I'd like to wrap & call from C#. We do not have any source code for this DLL. Is there any mechanism using CppSharp to utilize this DLL? Dependency Walker (for instance) clearly shows the exports so it seems possible at least in principle that a wrapper could be generated based on that info.

OS: Windows

Thanks

**Comment by tritao** [comment]
CppSharp relies on C headers as input to figure out the details on how to call the code.

If you can get a C declarations compatible with the Fortran DLL, then CppSharp will work for you.

**Comment by DaveInCaz** [comment]
Thanks for the quick reply.
