### ISSUE TITLE
Typemaps for template classes

### ISSUE THREAD

**Issue by rokups** [mono/CppSharp#1037]
As wrapping template classes is not supported yet, I have a hand-written generic template wrapper class that i need to use in a typemap. Basically class `Vector<T>` works with any type wrapped by `CppSharp` (neat huh?) Problem is that `TypePrinterContext` and `CSharpMarshalContext` do not provide access to template arguments passed to particular instance of a type typemap is generating mapping for. Could we get that info provided for consumption by typemaps?

**Comment by tritao** [comment]
I believe @ddobrev has improved template support and works well enough for all of the Qt libraries, but I am really not sure how well that will translate to arbitrary C++ code.

Anyway about the issue: I am not sure I understood it.

What you want is to get at a list of `TemplateArgument` from say a `TemplateSpecializationType`?

**Comment by rokups** [comment]
Say typemap is generated for `Vector<StringHash>` instance. I want to get the `StringHash` type.

Or maybe i go about this wrong.. It would be great if we could get some docs on how template support works and how users should use it.

**Comment by tritao** [comment]
I would expect you can cast the type to `TemplateSpecializationType` and just access the, through the `Arguments` property.

**Comment by tritao** [comment]
Is there anything for us to do here or can this be closed?

**Comment by rokups** [comment]
Nothing to do here. Template support makes this not needed. 👍
