### ISSUE TITLE
cmake -G "Ninja" taking forever 

### ISSUE THREAD

**Issue by amandal799** [mono/CppSharp#1042]
On Ubuntu 16.04 when i use premake5-linux-64 --file=scripts/LLVM.lua build_llvm it is taking a lot of time and i am still not able to pass through this step. I have even waited for 7 hrs once.

Here is what i have been doing -

ashish@amandal799:~/Desktop/CppSharp/build$ sudo ./premake5-linux-64 --file=scripts/LLVM.lua build_llvm
cmake -G "Ninja" -DLLVM_BUILD_TOOLS=false  -DLLVM_ENABLE_LIBEDIT=false -DLLVM_ENABLE_ZLIB=false -DLLVM_ENABLE_TERMINFO=false -DLLVM_ENABLE_LIBXML2=false -DLLVM_INCLUDE_EXAMPLES=false  -DLLVM_INCLUDE_DOCS=false  -DLLVM_INCLUDE_TESTS=false -DLLVM_TOOL_BUGPOINT_BUILD=false -DLLVM_TOOL_BUGPOINT_PASSES_BUILD=false -DLLVM_TOOL_CLANG_TOOLS_EXTRA_BUILD=false -DLLVM_TOOL_COMPILER_RT_BUILD=false -DLLVM_TOOL_DRAGONEGG_BUILD=false -DLLVM_TOOL_DSYMUTIL_BUILD=false -DLLVM_TOOL_GOLD_BUILD=false -DLLVM_TOOL_LLC_BUILD=false -DLLVM_TOOL_LLDB_BUILD=false -DLLVM_TOOL_LLD_BUILD=false -DLLVM_TOOL_LLGO_BUILD=false -DLLVM_TOOL_LLI_BUILD=false -DLLVM_TOOL_LLVM_AR_BUILD=false -DLLVM_TOOL_LLVM_AS_BUILD=false -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=false -DLLVM_TOOL_LLVM_CONFIG_BUILD=false -DLLVM_TOOL_LLVM_COV_BUILD=false -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=false -DLLVM_TOOL_LLVM_C_TEST_BUILD=false -DLLVM_TOOL_LLVM_DIFF_BUILD=false -DLLVM_TOOL_LLVM_DIS_BUILD=false -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=false -DLLVM_TOOL_LLVM_EXTRACT_BUILD=false -DLLVM_TOOL_LLVM_GO_BUILD=false -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=false -DLLVM_TOOL_LLVM_LINK_BUILD=false -DLLVM_TOOL_LLVM_LTO_BUILD=false -DLLVM_TOOL_LLVM_MCMARKUP_BUILD=false -DLLVM_TOOL_LLVM_MC_BUILD=false -DLLVM_TOOL_LLVM_MC_FUZZER_BUILD=false -DLLVM_TOOL_LLVM_NM_BUILD=false -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=false -DLLVM_TOOL_LLVM_PDBDUMP_BUILD=false -DLLVM_TOOL_LLVM_PROFDATA_BUILD=false -DLLVM_TOOL_LLVM_READOBJ_BUILD=false -DLLVM_TOOL_LLVM_RTDYLD_BUILD=false -DLLVM_TOOL_LLVM_SHLIB_BUILD=false -DLLVM_TOOL_LLVM_SIZE_BUILD=false -DLLVM_TOOL_LLVM_SPLIT_BUILD=false -DLLVM_TOOL_LLVM_STRESS_BUILD=false -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=false -DLLVM_TOOL_LTO_BUILD=false -DLLVM_TOOL_MSBUILD_BUILD=false -DLLVM_TOOL_OBJ2YAML_BUILD=false -DLLVM_TOOL_OPT_BUILD=false -DLLVM_TOOL_SANCOV_BUILD=false -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=false -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=false -DLLVM_TOOL_YAML2OBJ_BUILD=false -DCLANG_BUILD_EXAMPLES=false  -DCLANG_INCLUDE_DOCS=false  -DCLANG_INCLUDE_TESTS=false -DCLANG_ENABLE_ARCMT=false -DCLANG_ENABLE_STATIC_ANALYZER=false -DCLANG_TOOL_ARCMT_TEST_BUILD=false -DCLANG_TOOL_CLANG_CHECK_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_BUILD=false -DCLANG_TOOL_CLANG_FORMAT_VS_BUILD=false -DCLANG_TOOL_CLANG_FUZZER_BUILD=false -DCLANG_TOOL_C_ARCMT_TEST_BUILD=false -DCLANG_TOOL_C_INDEX_TEST_BUILD=false -DCLANG_TOOL_DIAGTOOL_BUILD=false -DCLANG_TOOL_LIBCLANG_BUILD=false -DCLANG_TOOL_SCAN_BUILD_BUILD=false -DCLANG_TOOL_SCAN_VIEW_BUILD=false -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=Release .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11

**Comment by ddobrev** [comment]
Hello @amandal799 . You can work on Linux but it's much easier to do so on Windows. The main advantage is that you can step from C# into C++ and vice versa while debugging.
