### ISSUE TITLE
The number of generated methods is wrong

### ISSUE THREAD

**Issue by pk27602017** [mono/CppSharp#1046]
##### Used headers

> class dtPolyQuery
{
	virtual ~dtPolyQuery() { }
	virtual void process(const dtMeshTile* tile, dtPoly** polys, dtPolyRef* refs, int count) = 0;
};

##### Brief Description
![image](https://user-images.githubusercontent.com/8246779/34906924-9ab78292-f8b1-11e7-9525-fdcbe4fdab94.png)

Why there are five Method?
I don't understand
I know there should be four methods (~ dtPolyQuery (), process (...), dtPolyQuery (), dtPolyQuery (Inptr))

The fifth method, will always throw an error can not find the symbol
![image](https://user-images.githubusercontent.com/8246779/34907030-30d3bef2-f8b3-11e7-9bee-04571f71b8d8.png)

CppSharp generate symbol file
Does not include this symbol

OS: Windows

##### Used settings

Target: MSVC

##### Stack trace or incompilable generated code

**Comment by tritao** [comment]
This is due to implicitly declared members (copy/move constructor, as well as assignment operators). You can expand the methods list in the debugger to see them.
