### ISSUE TITLE
404 Page Not Found Error while trying to premake llvm.lua

### ISSUE THREAD

**Issue by vamsibulusu** [mono/CppSharp#1050]
Problem with downloading and installing llvm and clang
$ premake5-linux-64 --file=scripts/LLVM.lua download_llvm
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-9bde5f-linux-x64-gcc-5-Release.tar.xz

Error: /home/vamsi/Github/CppSharp/build/scripts/Utils.lua:98: HTTP response code said error
The requested URL returned error: 404 Not Found

**Comment by ddobrev** [comment]
@vamsibulusu we do not have a binary package for GCC 5, I am afraid you'd need to compile LLVM yourself.

**Comment by vamsibulusu** [comment]
Ok, Thanks for the quick reply. Another question is, is there an active mailing group for CppSharp I can join? Thanks

**Comment by tritao** [comment]
No list, we use Gitter and Github issues for support.
