### ISSUE TITLE
How to ignore forward class declarations?

### ISSUE THREAD

**Issue by dennisai** [mono/CppSharp#1055]
In order to get CppSharp to work, I have attempted to take the advice of others and write a C++ library that just interfaces with only the part of the `ome-files-cpp` library that I need.  In order to do this, I created a wrapper for `OMETIFFWriter`, in which I forward declared the `ome::files::out::OMETIFFWriter` class as described below.

When I run my generator (using basic settings as described in the Generate Bindings tutorial), it creates an extra class for `ome::files::out::OMETIFFWriter`.  Is there any way to ignore these forward class declarations for the purposes of generating C# code?

```
namespace ome
{
  namespace files
    {
      namespace out
      {
        class OMETIFFWriter;
      }
  }
}

class OMETIFFWriter
{
private:
  std::unique_ptr<ome::files::out::OMETIFFWriter> writer;
...
}
```

**Comment by tritao** [comment]
You can try something like:

```
foreach (var @class in ctx.FindClass("ome::files::out::OMETIFFWriter")
    @class.ExplicitlyIgnore();
```

**Comment by dennisai** [comment]
Thank you!
