### ISSUE TITLE
Missing CppSharp.CppParser.dll in CppSharp build files

### ISSUE THREAD

**Issue by viennem** [mono/CppSharp#1060]
##### Brief Description

After building CppSharp master on Linux successfully, I noticed that I was missing the file CppSharp.CppParser.dll in my build folder (CppSharp/build/gmake/lib/Release_x64).
I need this dll in order to build QtSharp, how can I get it ?

**Comment by ddobrev** [comment]
@viennem you can't, you need to use libCppSharp.CppParser.so instead. CppSharp.CppParser.dll is a native library the name and extension of which vary per platform.

**Comment by viennem** [comment]
Do you know how to add the .so shared library to the project's references with MonoDevelop ?

**Comment by ddobrev** [comment]
@viennem you don't need to, just ensure it lies next to your executable along with the other dependencies.

**Comment by viennem** [comment]
Thank you for your help. I am also missing `CppSharp.Parser.CLI.dll`, is that an issue ?

**Comment by ddobrev** [comment]
@viennem no, on Linux you need CppSharp.Parser.CSharp.dll instead.
