### ISSUE TITLE
ClangParser.ParseHeader: System.AccessViolationException

### ISSUE THREAD

**Issue by WeitesFeld** [mono/CppSharp#1063]
Hello,

I'm trying to generate C# bindings for OpenCV 3.4.0 iOS (https://opencv.org/releases.html), using either the linked compiled package with headers or a build from source version with extra modules.
The package consist of headers and a static library .a with (dependent on which library you use) different arm targets.

My exe crashes with a System.AccessViolationException while parsing the code. Stack trace:
```
Parsing libraries...
Parsed 'arm64.a'
Parsing code...

Unbehandelte Ausnahme: System.AccessViolationException: Es wurde versucht, im geschützten Speicher zu lesen oder zu schreiben. Dies ist häufig ein Hinweis darauf, dass anderer Speicher beschädigt ist.
   bei CppSharp.CppParser.ClangParser.ParseHeader(CppParserOptions* )
   bei CppSharp.Parser.ClangParser.ParseHeader(CppParserOptions Opts)
   bei CppSharp.ClangParser.ParseSourceFiles(IEnumerable`1 files, ParserOptions options)
   bei CppSharp.ClangParser.ParseSourceFile(String file, ParserOptions options)
   bei CppSharp.Driver.ParseCode()
   bei CppSharp.ConsoleDriver.Run(ILibrary library)
   bei OpenCVBindingGenerator.Program.Main(String[] args) in [SomePath]\Program.cs:Zeile 16.
```

Is there anything I can do to provide a more helpful stacktrace or to identify the root cause (CppSharp or something else)? A better error description, not just an exception would be helpful (E.g. if it is a header issue, pointing out at which one it crashes).

Windows 10 1709 x64
VS 2017
NuGet Package 0.8.18

##### Used headers

Complete OpenCV2 headers (+ contrib modules) with entry point opencv.hpp, see settings below

##### Used settings

```
        public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = CppSharp.Generators.GeneratorKind.CSharp;

            var parserOptions = driver.ParserOptions;
            parserOptions.EnableRTTI = true;
            parserOptions.AddArguments("-fcxx-exceptions");

            var module = options.AddModule("OpenCV");
            module.IncludeDirs.Add("D:\\Headers");
            module.Headers.Add("opencv.hpp");
            module.LibraryDirs.Add("D:\\Lib");
            module.Libraries.Add("arm64.a");

        }
```

If someone test it for her/himself, you have to create a symbolic folder link in your header directory targeting to itself, otherwise errors occur for missing references:

> mklink /D opencv2 .

**Comment by tritao** [comment]
You can try running the code with lldb, something like: `lldb -- mono --debug /path/to/YourProject.exe`. You might need to compile LLVM with debug symbols to get better information.

**Comment by WeitesFeld** [comment]
The above code was with Windows and NuGet package.

I followed the instructions and compiled x86 Release CppSharp from source. For the C++ dll CppSharp.CppParser and CppSharp.Parser.CLI i deactivated the Linker and C++ optimisations to get better debugging informations.
Then I created another VS17 project like above with using the build dlls instead of the NuGet package. Same exception behaviour.

At the moment I'm trying to reproduce the steps to get the exact area where the error occurs.  That is somehow tricky because I could not get the exact location, only after which step above he crashes.

What I know:

The crash occurs in _WalkDeclarationDef(D)_ called in Parser::WalkAST() (line 3284 CppParser/Parser.cpp), when calling it the 36th time. There in WalkDeclarationDef (line 3699) he crashes directly. When stepping into it he crashes somewhere after step through the case Decl::Typedef (line 3835 to 3859) the 3rd time (last Typedef values were Point2d, value_type and value_type, where Point2d is the OpenCV definition of a point double x/y, rest don't know)

After hours I didn't step any deeper, knowing that the above information isnt useful at all. It would be nice when the underlying C++ code would write some more and useful information in verbose mode and/or the exceptions would get wrapped more nicely to the c# code.
E.g.  I'm pretty sure the crash occurs when parsing one of the header files but the verbose output didnt state what it is parsing at the moment. 

Also I guess I have to modify some more parserOptions in my Setup.

----

Searching thorugh the open and closed issues, there were some previous attempts to create bindings for OpenCV with CppSharp but the creators didn't state if they were successful or not.

**Comment by tritao** [comment]
If you can provide a stack trace of the crash, then that would be a good first step in helping you track down the crash.

**Comment by tritao** [comment]
Might be the same as https://github.com/mono/CppSharp/issues/1124.

**Comment by tritao** [comment]
Most likely fixed with https://github.com/mono/CppSharp/commit/ef0b054301cb6f9a8540dd0ef577a1fc22c73624.

Please re-open if still an issue.
