### ISSUE TITLE
when to support 64bit in visual studio?

### ISSUE THREAD

**Issue by gebogebo** [mono/CppSharp#1066]
##### Brief Description
I successfully compiled and built the cs file from visual studio 2017, but it is only on win32 platform.
I want to know, will it be ok to support x64 if i manually add x64 platform configuratio?
if not, when will it support?
thanks!

OS: Windows / OS X / Linux (include version and/or distro)

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by ddobrev** [comment]
@gebogebo if you need 64-bit C++#, you are better off with our NuGet package, otherwise you'll have to build Clang yourself.

**Comment by gebogebo** [comment]
well, thanks for your reply soon.
but, it is too complicated for me.
and I also notice that 64bit doesn't integrate as well with Visual Studio using llvm.  http://llvm.org/builds/
I am not familiar with llvm.
very hopefully, your projects can support 64bit just as win32.

**Comment by ddobrev** [comment]
@gebogebo NuGet-s are really easy to use, you just right-click your project, select "Manage NuGet packages", then find CppSharp and install it. However, if you'd still rather not use it, download it from https://www.nuget.org/api/v2/package/CppSharp/0.8.19 and then unpack, it's just a ZIP archive.

**Comment by gebogebo** [comment]
i know how to use nuget. if there are cppsharp win32 and x64, it is easy. no need steps from buildprojects.
i will try it, thank you very much

**Comment by gebogebo** [comment]
After pulling the nuget package, it reminds me another question I ever met when I built cppsharp.

In MSVCToolchain.cs file, I changed the code “var sdk = win10sdks.Last();" to "var sdk = win10sdks.First();", also, I add this path "path = Path.Combine(programFiles, "Windows Kits", "10", "include", $"10.0.10240.0");"  
that is how i successfully get all the .h files and parse them correctly. maybe it is the reason of my computer environment.

what i still want to ask is that in your visual studio configuration manager, it only supports x86. you know, after running GenerateProjects.bat as the doc suggested.
in the getting started help, it said "msbuild vs2017\CppSharp.sln /p:Configuration=Release;Platform=x86"
I was wondering if it would be ok if i set Platform=x64

**Comment by ddobrev** [comment]
I am afraid not because, again, you need Clang built for 64-bit Windows.
Do I correctly understand the NuGet does not work for you because of that missing line you filled in?

**Comment by gebogebo** [comment]
yes. I installed visual studio 2017, and upgrade several times. now, in Windows Kits\10\include, i have 10.0.10240.0 and 10.0.14393.0 and 10.0.15063.0 and 10.0.16299.0 directory. 10.0.10240.0 only has ucrt folder, some ".h" files are included here. 
if i don't modify the code, it will result in invalid path and fail to parse the .h file.

**Comment by gebogebo** [comment]
can you have a look at the files that generated with the tool?
is there any grammar error?
i hope to use it in the c# solution, but can't compile.

[Release_x86.zip](https://github.com/mono/CppSharp/files/1705433/Release_x86.zip)

**Comment by tritao** [comment]
What errors do you get?
