### ISSUE TITLE
Windows types and unknown type name

### ISSUE THREAD

**Issue by fmj02** [mono/CppSharp#1068]
I'm new to CppSharp. In my C library I have `#ifdef _WIN32` and define windows specific functions that use windows types from windows.h

How can I make it work? Or what's the best way to make it work?

> error: unknown type name 'UINT'
> error: unknown type name 'HANDLE'
> error: unknown type name 'HANDLE'

**Comment by ddobrev** [comment]
You need to add the necessary defines or undefines to the options of the parser.

**Comment by fmj02** [comment]
How should I do this? I tried:
```
var parserOptions = driver.ParserOptions;
parserOptions.Defines.Add("UINT=unsigned int");
parserOptions.Defines.Add("HANDLE=void*");
```

**Comment by ddobrev** [comment]
These are types, not macros. I was talking about _WIN32: define or undefine it as needed.

**Comment by fmj02** [comment]
Thanks. Solved.
