### ISSUE TITLE
__Internal wrapping and namespaces

### ISSUE THREAD

**Issue by fmj02** [mono/CppSharp#1070]
Is it possible to disable __Internal in the generator? I mean generating functions this way:

```csharp
public static uint DoSomething(global::System.IntPtr hLocalDevice, uint eventMode)
{
    var __ret = __Internal.DoSomething(hLocalDevice, eventMode);
    return __ret;
}
```

Is there some option to avoid `__ret =...; return __ret;` everywhere?

Also is it possible to somehow make it output code without namespaces? Like

`CallingConvention.Cdecl` instead of `global::System.Runtime.InteropServices.CallingConvention.Cdecl`

since it already adds: `using System.Runtime.InteropServices;` at the top of the file. What's the need for `global::` ?

I've tried to set `options.GenerateInternalImports = false;` but it still wraps DllImports in other methods.

I'm just looking for the simpliest output possible without all these wrapping and namespaces everywhere. Are there options for this or should I use something else? (Postprocess etc. perhaps?)

**Comment by ddobrev** [comment]
The generated code is not meant to be manually modified so these do not matter at all. The C# compiler makes all necessary optimisations. If you need to make additions to your binding, use partial classes and the CodeFiles option.

**Comment by fmj02** [comment]
Is there any documentation of all the options and what they do with any examples of them? Like what exactly CodeFiles do?

I was trying to generate a header that I can drop into my project instead of compiling it as a separate .dll as my C header is simple. with just a couple of functions.

I've noticed it doesn't generate my `#define` too.

**Comment by ddobrev** [comment]
Most options are documented in C# with XML comments.
#define-s are really difficult to support as they vary widely. If you have controls over your C header, convert your #define-s to functions or constants.
