### ISSUE TITLE
CppSharp build for Win32 broken

### ISSUE THREAD

**Issue by khReichel** [mono/CppSharp#1071]
##### Brief Description
When I try to start build for the recent CppSharp version (master) with the script 
premake5 --file=scripts/LLVM.lua download_llvm

I got the error

Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-9bde5f-windows-vs2015-x86-RelWithDebInfo.7z
Error: E:/projects/CppSharp/build/scripts/Utils.lua:98: HTTP response code said error
The requested URL returned error: 404 Not Found

It seems that the referenced resource llvm is not available at the given url

**Comment by ddobrev** [comment]
@khReichel please try now.
