### ISSUE TITLE
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.

### ISSUE THREAD

**Issue by encrypt0r** [mono/CppSharp#1072]
##### Brief Description
I am trying to create a c# wrapper for [Sekonic's OMR API](https://www.sekonic.co.jp/english/product/omr/download/download.html). I followed the getting [started page](https://github.com/mono/CppSharp/blob/master/docs/GeneratingBindings.md).However, whenever I try to run the c# app, it crashes with this exception: _System.TypeInitializationException_. I have noticed that even an empty implementation of the library causes this exception, so I thought maybe I have forgotten to set an option. Any ideas on what might be the issue?

Here is the library implementation:

```csharp
public class SekonicLibrary : ILibrary
{
    public void Postprocess(Driver driver, ASTContext ctx)
    {

    }

    public void Preprocess(Driver driver, ASTContext ctx)
    {

    }

    public void Setup(Driver driver)
    {
        var options = driver.Options;

        options.GeneratorKind = CppSharp.Generators.GeneratorKind.CSharp;
        options.OutputDir = @"csharp";

        var module = options.AddModule("SkDvSrSeries");
        module.IncludeDirs.Add(@"D:\sekonic\cpp\Include");

        module.Headers.Add(@"SkCommIoErr.h");
        module.Headers.Add(@"SkDvSr3500ImgApi.h");
        module.Headers.Add(@"SkDvSr11000Api.h");
        module.Headers.Add(@"SkDvSr11000Prm.h");
        module.Headers.Add(@"SkDvSrBaseApi.h");
        module.Headers.Add(@"SkDvSrOptionApi.h");
        module.Headers.Add(@"SkDvSrSeriesErr.h");
        module.Headers.Add(@"SkDvSrSeriesPrm.h");

        module.LibraryDirs.Add(@"D:\sekonic\cpp\lib\");
        module.Libraries.Add("SkDvSrSeries.lib");
    }

    public void SetupPasses(Driver driver)
    {

    }
}
```

OS: Windows

##### Used headers
SkCommIoErr.h
SkDvSr3500ImgApi.h
SkDvSr11000Api.h
SkDvSr11000Prm.h
SkDvSrBaseApi.h
SkDvSrOptionApi.h
SkDvSrSeriesErr.h
SkDvSrSeriesPrm.h

##### Stack trace or incompilable generated code

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load.
 ---> System.EntryPointNotFoundException: A library name must be specified in a DllImport attribute applied to non-IJW methods.
   at _getFiberPtrId()
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at CppSharp.ConsoleDriver.Run(ILibrary library)
   at BindingGenerator.Program.Main(String[] args) in C:\Users\...\Source\Repos\BindingGenerator\BindingGenerator\Program.cs:line 10
```

**Comment by ddobrev** [comment]
This exception looks like a general problem with C++ libraries. I think you might have a problem similar to https://vunvulearadu.blogspot.bg/2016/02/visual-studio-2015-plus-windows-10.html. Could you please try what is suggested there?

**Comment by encrypt0r** [comment]
@ddobrev Thank you for your suggestion, here is what I did:

1.  Target .Net Framework 4.7.1 instead of dotnet core
2.  Add the option in the article to the .config file of my app
3.  Ran the app and it crashed this time with an `System.BadImageFormatException` (similar to #910)
4.  Changed the platform to x64
5.  And now it works!

However, It can't parse some of the header files, here are some common errors:
 - SkDvSrSeriesPrm.h(34,9): error: unknown type name 'DWORD'. I get this error for `RECT`, `CALLBACK`, `LPVOID` too
 - SkDvSrSeriesPrm.h(672,9): error: C++ requires a type specifier for all declarations
 - SkDvSr3500ImgApi.h(50,18): error: expected ';' after top level declarator
 - SkDvSrOptionApi.h(76,12): error: redefinition of 'WINAPI'
 - SkDvSr11000Api.h(327,6): error: redefinition of 'WINAPI' as different kind of symbol

I there anything missing? Or are these just the result of syntax errors?

**PS:** I am attaching the header and lib files if you needed to take a look at them: [sekonic.zip](https://github.com/mono/CppSharp/files/1777153/sekonic.zip)

**Comment by tritao** [comment]
We do not support .NET Core so that was the original issue.

About the syntax errors, those are issues in the code, not CppSharp. Those usually mean that those particular headers are not meant to be included/parsed by themselves, and are included by some other "master" headers. You need to figure out the right headers that you need to include.

**Comment by ddobrev** [comment]
Another reason, which I suspect mostly because "SkDvSrSeriesPrm.h(672,9): error: C++ requires a type specifier for all declarations" and "SkDvSr3500ImgApi.h(50,18): error: expected ';' after top level declarator", is an incorrect C++ version. Please try with C++11, 14 or 17.
In general, your problem is that system types are not found. If you cannot figure out what the problem is, please build C++# from source code - it's easy - and debug SetupMSVC to see if you get the required system headers.

**Comment by encrypt0r** [comment]
@tritao I'll close the issue then, thank you for your reply 👍
