### ISSUE TITLE
[Help Wanted] Unity3d extension support

### ISSUE THREAD

**Issue by iBicha** [mono/CppSharp#1076]
Hello folks,

Thank you very much for this tool, it looks very promising to me !

I wanted to explore CppSharp as an option for a bindings generator for Unity plugins.
Followed the build instructions, and got a simple header to work through the CLI.
(Even though running the test has a bit of a weird output, says it Failed, but all tests has passed, I can post full stack trace if wanted)
```
Test Run Summary
  Overall result: Failed
  Test Count: 139, Passed: 139, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-04-09 06:16:04Z
    End time: 2018-04-09 06:16:09Z
    Duration: 4.927 seconds
``` 

My struggle is when I wanted to include CppSharp binaries in Unity, as it would help me iterate quicker, if I was to use it in an editor extension.

I had several problems, one of which includes this error in Unity:

```
Unloading broken assembly Assets/Editor/CppSharp/CppSharp.dll, this assembly can cause crashes in the runtime
```

Running `ConsoleDriver.Run(new SampleLibrary());` only triggers the `Setup` method, other methods from the interface are never called.

Looking at existing issues, I understand that CppSharp dev environment is very precise, which is why few people had trouble with it (Nuget, Visual Studio for Mac and .NET Core, etc...)

So my question is, is there any pointers I'm missing to to support this setup? It would be super convenient to add a couple of lines in a C# script in Unity
```
    [MenuItem("CppSharp/Generate Bindings for SampleLibrary")]
    public static void GenerateBindings()
    {
        ConsoleDriver.Run(new SampleLibrary());
    }
```
And be able to generate bindings from the menu.
Cheers!

OS: macOS High Sierra

**Comment by ddobrev** [comment]
Assuming you have added your headers and their include dirs, the reason other interface methods are not called can only be an early failure such as parsing errors. Please check your output.

**Comment by iBicha** [comment]
Right, I missed something really silly. Following the sample guide, I had no `Sample.lib`, so `module.Libraries.Add("Sample.lib")` so by removing that, the generation went through.
(I did find this error interesting, I don't know how relevant it is yet)
`Error loading type maps from assembly 'CppSharp': Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.`
I suppose because Unity did not load CppSharp.dll, that is.

This solves the problem, will close this for now, Thank you kind sir

**Comment by hanbim520** [comment]
Hi,guys,do you finished this project? I try one night time,but failed.
