### ISSUE TITLE
Writing errors to StdErr in ConsoleDiagnostics

### ISSUE THREAD

**Issue by iBicha** [mono/CppSharp#1077]
Looking at my output, I realized that errors are piped to the stdout instead of stderr.

https://github.com/mono/CppSharp/blob/8479ed3735b0e88b9dd816993bf8a0f0028e711f/src/Core/Diagnostics.cs#L123

I think it should look something like 

```
public void Emit(DiagnosticInfo info)
{
    if (info.Kind < Level)
        return;

    var currentIndent = Indents.Sum();
    var message = new string(' ', currentIndent) + info.Message;

    if(info.Kind == DiagnosticKind.Error)
    {
        Console.Error.WriteLine(message);
    }
    else 
    {
        Console.WriteLine(message);
    }
    Debug.WriteLine(message);
}
```

**Comment by ddobrev** [comment]
@tritao this is not devoid of sense, what do you think?

**Comment by tritao** [comment]
Seems fine to me. @iBicha feel free to send a PR with this change.

**Comment by tritao** [comment]
I think that should be fine.
