### ISSUE TITLE
Error: cannot use 'throw' with exceptions disabled

### ISSUE THREAD

**Issue by QuantumDeveloper** [mono/CppSharp#1086]
##### Brief Description
During parsing of exceptions, CppSharp outputs the following error:
"error: cannot use 'throw' with exceptions disabled".
The code in C++ is the following:
```
case Result::eErrorOutOfHostMemory: throw OutOfHostMemoryError ( message );
case Result::eErrorOutOfDeviceMemory: throw OutOfDeviceMemoryError ( message );
case Result::eErrorInitializationFailed: throw InitializationFailedError ( message );
... and so on
```
So, I think this is related to the "throw" keyword. 

How can I workaround this without changing C++ code?

OS: Windows / OS X / Linux (include version and/or distro)
Windows 10, 1803

Target: MSVC/GCC/Clang
VS 2017

**Comment by ddobrev** [comment]
You need to use AddArguments to pass a flag for exceptions.

**Comment by QuantumDeveloper** [comment]
@ddobrev Could you please give a short example? Where I should do this?

**Comment by QuantumDeveloper** [comment]
Ok, seems I already found that place: 
```
driver.ParserOptions.AddArguments("-fcxx-exceptions");
```

**Comment by ddobrev** [comment]
Correct, something like this - I don't know the compiler switch by heart - should do it.

**Comment by QuantumDeveloper** [comment]
Thanks for help. It works
