### ISSUE TITLE
CLI doesn't work

### ISSUE THREAD

**Issue by tania-hedgehog** [mono/CppSharp#1090]
I tried to generate wrapper on Windows 10 by command line with version 0.8.19 and got with output.
```
./CppSharp.CLI.exe  -o="./out.txt" -a="x86" -g=csharp -on=alignmentsubsystem -p=win -l=AlignmentSubsystemMath -d includes/*.h -iln .
Generating C# bindings for Windows x86...
Method not found: 'Void CppSharp.DriverOptions.set_UnityBuild(Boolean)'.
```

**Comment by ddobrev** [comment]
Our CLI tool in the package might be old. I am aiming for a release within a week. If you cannot wait for this long, please build C++# from source code.

**Comment by tania-hedgehog** [comment]
@ddobrev but I can't compile this from source too.  I can't download llvm via premake5.
``
Error: ...ages/CppSharp.0.8.19/lib/CppSharp/build/scripts/LLVM.lua:18: attempt to concatenate a nil value
``

**Comment by ddobrev** [comment]
This is quite strange. This line - https://github.com/mono/CppSharp/blob/master/build/scripts/LLVM.lua#L18 - is only activated when you use Vagrant, a kind of virtual machine. It shouldn't be called on Windows.

**Comment by ddobrev** [comment]
@tania-hedgehog please try our latest release.
