### ISSUE TITLE
Auto detect installed sdk in visual studio

### ISSUE THREAD

**Issue by emmauss** [mono/CppSharp#1092]
##### Brief Description
the vs solution generator currently defaults to windows 8.1 sdk. this causes build errors if win 8.1 sdk isn't installed on the system, especially since it does not come installed by default in vs2017 native desktop workload, where windows 10 10240 sdk is installed. it can manually be configured to use one of the installed sdks, but this requires modify the cproj files if building through commandline.

OS: Windows

Target: MSVC

**Comment by tritao** [comment]
This has been fixed with https://github.com/mono/CppSharp/commit/f0d3e731adeaa4a15c62a82592aa1b8262a7cd3b.
