### ISSUE TITLE
Getter and setter for object pointers missing casts

### ISSUE THREAD

**Issue by mattparks** [mono/CppSharp#1093]
##### Brief Description
In the process of generating a C++ wrapper to a C library I experienced a error where the getters and setters generated for a pointer type would generate for the correct type (in this case `global::TestState*`) but the local variable would generate as a `global::System.IntPtr`. This causes a casting error where the build fails, adding correct casts manually fixes the issue.

C++ input: https://pastebin.com/LEYY8MkW
Generated C# output: https://pastebin.com/R3NweFnL
CppSharp log: https://pastebin.com/VFhZuSnQ

Errors: 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'System.IntPtr' to 'TestState*'. An explicit conversion exists (are you missing a cast?)	Test	C:\Users\mattp\Documents\Flounder Workspace\FlounderSharp\FlounderSharp\Test.cs	122	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'TestState*' to 'System.IntPtr'. An explicit conversion exists (are you missing a cast?)	Test	C:\Users\mattp\Documents\Flounder Workspace\FlounderSharp\FlounderSharp\Test.cs	127	Active
```

OS: Windows
Target: MSVC

Driver: https://pastebin.com/vAWeTgua

**Comment by tritao** [comment]
Thanks for the well detailed issue report and repro.

This one should be easy to fix, we'll take a look when we can.
