### ISSUE TITLE
CppSharp.CLI.exe is not working properly.

### ISSUE THREAD

**Issue by wenfengliu322** [mono/CppSharp#1100]
I compiled a c++ library and got dlls, libs and .h files.
Here is the structure of folders.

-- E:\Work\luxcore(root dir)
                        |
                        |----- dll -------- dll files
                        | 
                        |
                        |----- include---- .h files
                        |
                        |----- lib---------  .lib files

To get C# wrapper from this library, I used following command.

CppSharp.CLI.exe -I="E:\Work\luxcore\include\" -l="E:\Work\luxcore\dll\" -L="E:\Work\luxcore\lib\" -o="E:\Work\Result\test.txt" -p="win" -a="x64" -g="csharp" -on="Test" "E:\Work\luxcore\include\luxcore\luxcore.h"

 But I got this error message.

Directory 'E:\Work\luxcore\include" -l=E:\Work\luxcore\dll"' doesn't exist. Ignoring as include directory.

What is wrong in my command line and how to fix this?
Should I use source code to generate wrapper, not dll or lib?

**Comment by ddobrev** [comment]
You pass different values for the same parameter: -I="E:\Work\luxcore\include", -l="E:\Work\luxcore\dll".

**Comment by wenfengliu322** [comment]
Sorry, first is upper case of i and second is lower case of L. Not same parameter.

**Comment by ddobrev** [comment]
Are you sure we support both upper- and lowercase L?

**Comment by wenfengliu322** [comment]
I got that from --help option.
If not, how can I write command line?

**Comment by wenfengliu322** [comment]
Would you like to suggest correct command line for me?

**Comment by wenfengliu322** [comment]
I got following message.
Input library name not specified and check symbols option not enabled.
Either set the input library name or the check symbols flag.

**Comment by wenfengliu322** [comment]
So, I tried to specify input library name, but got another error message.
e:\Work\CppSharp-0.8.20-vs2017-x86>CppSharp.CLI.exe -I="E:\Work\luxcore\include" -L="E:\Work\luxcore\dll" --iln="luxcore.dll" -o="E:\Work\Result\test.txt" -p="win" -a="x64" -g="csharp" -on="Test" "E:\Work\luxcore\include\luxcore\luxcore.h"

Generating C# bindings for Windows x64...


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Setup.Configuration.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at CppSharp.CLI.Main(String[] args) in C:\projects\cppsharp\src\CLI\CLI.cs:line 286

**Comment by ddobrev** [comment]
This is a dependency we use to get the paths to MSVC. It requires Visual Studio to be installed. We've had requests to make C++# work without VS but we haven't had the time to complete it.

**Comment by softlion** [comment]
I found the missing file in  ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Xamarin\AndroidDeviceManager```. Copy it in the tool folder.

**Comment by tritao** [comment]
Please re-open if still an issue.
