### ISSUE TITLE
macOS: SDL example issues

### ISSUE THREAD

**Issue by RotsiserMho** [mono/CppSharp#1102]
##### Brief Description
I followed the directions in *GettingStarted.md* and ran into [some problems](https://github.com/mono/CppSharp/issues/1101). Those instructions also did not build the SDL example. I had to follow the instructions [here](https://github.com/mono/CppSharp/issues/710#issuecomment-368059998) to build it manually (as well as add some assembly references). Then, after running it, I'm unable to generate the example SDL bindings. See the output below. I ran the commands from the build directory.

CppSharp: 0.8.20
OS: macOS High Sierra 10.13.4, Xcode: 9.3.1, Mono: 5.2.0.215

##### Input
```
mcs -lib:gmake/lib/Release_x64 -r:CppSharp -r:CppSharp.AST -r:CppSharp.Generator -r:CppSharp.Parser -r:CppSharp.Parser.CSharp ../examples/SDL/SDL.cs
MONO_PATH=./gmake/lib/Release_x64 mono ../examples/SDL/SDL.exe
```

##### Output
```
Parsing libraries...
Parsing code...
Error parsing 'SDL.h'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/emmintrin.h(2261,19): error: use of undeclared identifier '__builtin_ia32_pavgb128'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/emmintrin.h(2281,19): error: use of undeclared identifier '__builtin_ia32_pavgw128'
CppSharp has encountered an error while parsing code.
```

**Comment by tritao** [comment]
I think this is due to a too recent version of Xcode being used. Our parser seems to be choking on `__builtin_ia32_pavgb128` which is probably a recent feature. 
@ddobrev Any timeline on us updating Clang revision?

**Comment by ddobrev** [comment]
The timeline is as usual - as needed. I can build all packages, I just need some time. I think I can build a Windows package today, I'll let it compile while I'm out. Then the rest, one by one.

**Comment by ddobrev** [comment]
@RotsiserMho we updated Clang a month ago, the source code is up. I am also going to update the NuGet by the end of the week. Please try it and close this if it's no longer an issue.
