### ISSUE TITLE
Is 64-bit llvm static library build available for downloading ? 

### ISSUE THREAD

**Issue by hs3366677** [mono/CppSharp#1103]
##### Brief Description
I'm trying to change some code in the native part and build a 64-bit version. It requires a 64-bit clang build and I built it. All compilation worked but once I used it, the MemoryAccessVilotionException prompts. The 64-bit version on Nuget is good. So I wonder if the problem lies in the llvm build. Can I have you guys' build ? 

OS: Windows / OS X / Linux (include version and/or distro)

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by hs3366677** [comment]
I built LLVM 64-bit using their cmake scripts. The .lib files are all smaller than your build. Where can I find your llvm make files ? can you provide your pre-compiled 64 bits llvm packages for good ? I have been stuck on it for a while 8-(

**Comment by tritao** [comment]
Try our documented process: https://github.com/mono/CppSharp/blob/master/docs/BuildingLLVM.md#compiling-using-the-build-script

Let me know if you hit any issue.

**Comment by hs3366677** [comment]
I followed the instruction to build a x64 version. The folder name is different with x86 version. It is `llvm-9bde5f-windows-vs2017-x64-RelWithDebInfo`. But the .lib inside the folder are still x86.

**Comment by ddobrev** [comment]
@hs3366677 I use a 64-bit copy of Clang locally, I'll see about packing it and uploading it for you next week.

**Comment by tritao** [comment]
We'll be moving our CI to 64-bits only in the future so packages will be provided for 64-bits going forward.
