### ISSUE TITLE
what is the xxx-symbol.cpp for ? 

### ISSUE THREAD

**Issue by hs3366677** [mono/CppSharp#1104]
##### Brief Description
After I convert the cpp code into c#, there is always a namespace-symbo.cpp file generated. It seems useless and what is it exactly ? 

OS: Windows / OS X / Linux (include version and/or distro)

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by tritao** [comment]
Some inline C++ symbols are not compiled down to the DLL files. They are instead inlined into the target executable from the code of included header files.

Thus you will not be able to call them using P/Invoke from the DLL. This is why we generate the `-symbols.cpp` file, so you can compile it yourself into a `-symbols.dll` used for inlined symbols.
