### ISSUE TITLE
C++ name mangling

### ISSUE THREAD

**Issue by loicmorvan** [mono/CppSharp#1105]
##### Brief Description

I may have missed something, but **is CppSharp able to manage C++ name mangling so that the exact same C# code can be used with different libraries on different platforms (Windows, Linux, etc)?**

I know SWIG generates a `.cxx` file which maps C++ functions to C ones with unique names marked as `extern "C"` to avoid mangling.
This way, the names of the procedures do not depend on the compiler nor on the OS.

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by tritao** [comment]
CppSharp generates direct C++ ABI bindings, so it requires different generate code / managed binding DLL per platform/architecture. 

As you mentioned, SWIG generates a C layer first, which simplifies binding generation, but also requires a compiled version of the generated native code per platform.

Each approach generates different tradeoffs, but in the end, both need platform-specific code, be it managed or native code.

**Comment by loicmorvan** [comment]
> Each approach generates different tradeoffs, but in the end, both need platform-specific code, be it managed or native code.

Indeed, native code will be platform-specific, but with a C layer, the generated managed code could be shared on all platform (using something like .NetCore or .NetStandard) which is easier to use.

I used to include the C layer directly inside the library itself at build time so that I don't have another native library to link.

I had my answers, thanks!
