### ISSUE TITLE
Debugger error message for Block class

### ISSUE THREAD

**Issue by jspohr** [mono/CppSharp#1113]
In the Visual Studio debugger, there's an error message in the variable view for instances of Block:
`error CS0119: 'BlockKind' is a type, which is not valid in the given context`

[The class has a DebuggerDisplayAttribute](https://github.com/mono/CppSharp/blob/6a28909dd5fc45a4743bbdb78780ff5364898447/src/Generator/Utils/BlockGenerator.cs#L55):
`[DebuggerDisplay("{BlockKind} | {Object}")]`

I'm assuming it should say
`[DebuggerDisplay("{Kind} | {Object}")]`
instead.

**Comment by tritao** [comment]
Thanks, should be fixed now.
