### ISSUE TITLE
How do I generate pure c bindings.

### ISSUE THREAD

**Issue by ChrisDill** [mono/CppSharp#1115]
##### Brief Description
Is there a built in way to generate pure c bindings? 
I found this issue #158 from back in 2014. Was a generator added?

I tried ```options.GeneratorKind = GeneratorKind.C``` but that crashes with a ```System.NullReferenceException```.

I am using the nuget package at the moment so I can't easily debug it.

Thanks!

**Comment by tritao** [comment]
Hey @ChrisDill.

We never got around to adding C support to CppSharp.

You can try this fork https://github.com/InitialForce/CppSharp, which I think provides C support.
