### ISSUE TITLE
hello word  dll  binding error

### ISSUE THREAD

**Issue by gitlsl** [mono/CppSharp#1116]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)

Windows    latest nuget cppsharp
dll project created by vs2017 wizard
##### Used settings
````
     public void Setup(Driver driver)
        {
            var options = driver.Options;
           
            options.GeneratorKind = GeneratorKind.CSharp;
            options.Encoding = Encoding.Unicode;
             var module = options.AddModule("TestDll");
            module.Headers.Add(@"E:\vsproject\WeChat\TestDll\TestDll.h");
            module.IncludeDirs.Add(@"E:\vsproject\WeChat\TestDll");
        
        }
````
Target: MSVC/GCC/Clang
MSVC
````
#ifdef TESTDLL_EXPORTS
#define TESTDLL_API __declspec(dllexport)
#else
#define TESTDLL_API __declspec(dllimport)
#endif

class TESTDLL_API CTestDll {
public:
	CTestDll(void);
	// TODO:  
	void go();
};
 
extern TESTDLL_API int nTestDll;

TESTDLL_API int fnTestDll(void);
````
Other settings 

##### Stack trace or incompilable generated code

````
   [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("TestDll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0CTestDll@@QEAA@XZ")]// "??0CTestDll@@QAE@XZ"  in export function name
            internal static extern global::System.IntPtr ctor(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("TestDll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0CTestDll@@QEAA@AEBV0@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("TestDll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?go@CTestDll@@QEAAXXZ")]
            internal static extern void Go(global::System.IntPtr instance);
        }
````

I use   generated code  in c# and get error  [`wrong EntryPoint`],so I see the export function name by `cff explorer` 

`??0CTestDll@@QEAA@XZ`                  shoule be  `??0CTestDll@@QAE@XZ`
`??0CTestDll@@QEAA@AEBV0@@Z`  shoule be `??4CTestDll@@QAEAAV0@ABV0@@Z`
`?go@CTestDll@@QEAAXXZ`               shoule be `?go@CTestDll@@QAEXXZ`
only wrong with class,
export function and global var  is  OK

is there anything wrong with my  code? can you help me thank you

**Comment by gitlsl** [comment]
after some search , `https://github.com/mono/CppSharp/issues/619` it seem like this,
`The NuGet version is Windows 64-bit only for the time being. Binary 32-bit releases for Windows can be found at https://github.com/mono/CppSharp/releases .`
can you provide 32bit in releases page

**Comment by tritao** [comment]
Hey @gitlsl, that should not make any difference.

The 64-bit release of CppSharp can generate code for 32 or 64-bit targets.

**Comment by gitlsl** [comment]
@tritao   yes, but I can not find where to place the code generate 32bit targets,
wiki of this repo too short to find answer..

**Comment by gitlsl** [comment]
@tritao after some search,
 `driver.ParserOptions.TargetTriple = "i686-pc-win32-msvc";`  
above code will generate 32bit targets

**Comment by ddobrev** [comment]
@gitlsl is this one solved?
