### ISSUE TITLE
EntryPointNotFoundException when using generated bindings

### ISSUE THREAD

**Issue by dominic-morin** [mono/CppSharp#1117]
Hello,
I use **all x64** binaries. All on **Windows**, using **Visual Studio**. I have a very simple project to explore how to work with CppSharp. I have:

- SanboxLib - Cpp project to generate dll.
    - Foo.hpp
    - Funk.h
    - Funk.cpp
- BindingsGenerator - C# project to generate bindings, depends on CppSharp. Bindings generation seem to work.
- CoreConsoleSandbox - .net core console project to consume SandboxLib.dll

My problem is: After multiple attempts, I can create Funk objects and call Funk methods on them. When I try to instantiate Foo, I get:

> Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named '??0Foo@SandboxLib@@QEAA@XZ' in DLL 'SandboxLib'.
   at SandboxLib.SandboxLib.Foo.__Internal.ctor(IntPtr instance)
   at SandboxLib.SandboxLib.Foo..ctor() in C:\Users\domorin\source\repos\CppSandbox\CoreConsoleSandbox\SandboxLib.cs:line 85
   at CoreConsoleSandbox.Program.Main(String[] args) in C:\Users\domorin\source\repos\CppSandbox\CoreConsoleSandbox\Program.cs:line 10

I tried playing with the options (ABI, TargetTriple, etc.). 

**Note: I don't know what to do with the SandboxLib-symbols.cpp file. Maybe that is the cause of my struggle? I tried rebuilding the c++ project with this file but it gives me errors because of the new(instance) syntax.** 

Here is my code. I played with the commented options, trying to make this work.
C++
Foo.hpp

	class __declspec(dllexport) Foo
	{
	public:
		Foo();
		~Foo();
		int Bar();
	};`

	Foo::Foo()
	{
	}

	Foo::~Foo()
	{
	}

	__declspec(dllexport) int Foo::Bar()
	{
		return rand() % 100;
	}

Funk.h

    class __declspec(dllexport) Funk
	{
	public:
		Funk();
		~Funk();
		int Dance();
	};

Funk.cpp

	Funk::Funk()
	{
	}

	Funk::~Funk()
	{
	}

	int Funk::Dance()
	{
		return rand() % 200;
	}

C# Bindings Generator

            public void Setup(Driver driver)
            {
                var parserOptions = driver.ParserOptions;
                parserOptions.LanguageVersion = LanguageVersion.CPP17;
                parserOptions.Verbose = true;
                // parserOptions.Abi = CppSharp.Parser.AST.CppAbi.Microsoft;
                // parserOptions.TargetTriple = "x86_64-pc-win64-msvc"; //"i686-pc-win32"

                var options = driver.Options;
                options.GeneratorKind = GeneratorKind.CSharp;
                options.GenerateClassTemplates = true;
                options.OutputDir = OutputCpp;
                // options.CompileCode = false;
                // options.GenerateDefaultValuesForArguments = true;
                // options.CheckSymbols = false;
                //options.GenerateDebugOutput = true;

                var module = options.AddModule(ModuleName);
                module.IncludeDirs.Add(IncludeDir);
                foreach (var header in Headers)
                {
                    module.Headers.Add(header);
                }
                
                module.LibraryDirs.Add(LibraryDir);
                foreach (var lib in Libraries)
                {
                    module.Libraries.Add(lib);
                }
            }

C# .NET Core - Console (includes the generated bindings/cs (and SandboxLib-symbols.cpp) files)

        static void Main(string[] args)
        {
            var funk = new Funk();    // succeed!!!
            var foo = new Foo();       // fails!!!!
            Console.WriteLine("Hello World! foobar={0} funkdance={1}", foo.Bar, funk.Dance);
        }

Thanks!

**Comment by tritao** [comment]
Move these to `Foo.cpp`:

```cpp
Foo::Foo()
{
}


Foo::~Foo()
{
}

__declspec(dllexport) int Foo::Bar()
{
	return rand() % 100;
}
```

Having them in the header files causes them to be inlined by MSVC and not exported in the DLL.

You can use DLL Export Viewer software to check your symbols in DLL file.

**Comment by dominic-morin** [comment]
Thanks! I expected such answer (since this is basically the only difference between Foo and Funk classes). If I understand correctly, to export inline methods, I would need to create a wrapper methods that are not inline (considering a bigger project).

What about the Lib-symbols.cpp file? What is it used for?

**Comment by tritao** [comment]
We generate that file to export symbols like this one that are not exported by the original code.
