### ISSUE TITLE
Should I call Dispose function manual? 

### ISSUE THREAD

**Issue by setlin** [mono/CppSharp#1118]
I Saw the tests codes, with

C++ Struct
`
struct DLL_API Bar
{

};
`

C#
`
var bar = new Bar();
bar.Dispose();
`

should I call Dispose function after new?

**Comment by ddobrev** [comment]
@setlin yes. We have planned generation of code which implements the IDisposable pattern but there are some difficulties. Until we've overcome them, Dispose() must be called on anything new or any returned value which is documented as a responsibility of the caller in the original C++ library.

**Comment by setlin** [comment]
Thank you very much, I do believe we can overcome them!
