### ISSUE TITLE
Lots of unknown / incomplete types

### ISSUE THREAD

**Issue by simonbuehler** [mono/CppSharp#1122]
##### Brief Description

Hi,

trying to get a wrapper around this 64bit dll but lots of errors are in my way, any hint what i do wrong? vs2017 nuget package

##### Used headers
```
#ifndef _CPUSBXPM_h_
#define _CPUSBXPM_h_

#ifdef __cplusplus
extern "C" {
#endif
#pragma pack(8)	

void WINAPI CPUXInit( void );
typedef void (WINAPI* PFNCPUXInit)( void );

void WINAPI CPUXInit2( void );
typedef void (WINAPI* PFNCPUXInit2)( void );

typedef struct tagCPDIDinfo{
short		usbNo;		
short		printerID;			
CHAR		serialNo[6];	
WORD		mediaType;	
}CPDIDinfo, *PCPDIDinfo;

DWORD WINAPI CPUXSearchPrinters( PCPDIDinfo pIDInfo, DWORD infoSize, LPDWORD pSizeNeeded, LPDWORD pinfoNum );
typedef DWORD (WINAPI* PFNCPUXSearchPrinters)( PCPDIDinfo pIDInfo, DWORD infoSize, LPDWORD pSizeNeeded, LPDWORD pinfoNum );
```
##### Used settings

```
 var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            driver.ParserOptions.Verbose = true;

            var module = options.AddModule("CPUSBXPM");
            module.IncludeDirs.Add(@"C:\Sample\");
            module.Headers.Add("CPUSBXPM.h");
            module.LibraryDirs.Add(@"C:\Sample\");
            module.Libraries.Add("CPUSBXPM.lib");
```
Target: MSVC

Other settings 

##### Stack trace or incompilable generated code

C:\Sample\CPUSBXPM.h(23,6): error: variable has incomplete type 'void'
C:\Sample\CPUSBXPM.h(23,12): error: expected ';' after top level declarator
C:\Sample\CPUSBXPM.h(24,21): error: expected ')'
C:\Sample\CPUSBXPM.h(24,15): error: redefinition of 'WINAPI' as different kind of symbol
C:\Sample\CPUSBXPM.h(31,6): error: variable has incomplete type 'void'
C:\Sample\CPUSBXPM.h(31,12): error: expected ';' after top level declarator
C:\Sample\CPUSBXPM.h(32,21): error: expected ')'
C:\Sample\CPUSBXPM.h(102,1): error: unknown type name 'CHAR'
C:\Sample\CPUSBXPM.h(103,1): error: unknown type name 'WORD'
C:\Sample\CPUSBXPM.h(106,1): error: unknown type name 'DWORD'
C:\Sample\CPUSBXPM.h(106,13): error: expected ';' after top level declarator
C:\Sample\CPUSBXPM.h(107,68): error: unknown type name 'DWORD'
C:\Sample\CPUSBXPM.h(107,84): error: unknown type name 'LPDWORD'
C:\Sample\CPUSBXPM.h(107,105): error: unknown type name 'LPDWORD'
C:\Sample\CPUSBXPM.h(107,9): error: C++ requires a type specifier for all declarations

**Comment by tritao** [comment]
The original source code is incomplete.

You have to include `#include <Windows.h>` to get a definition for `DWORD`.

Either that or just replace the `DWORD` symbols in your code with concrete built-in types, like `int` or `long`..

**Comment by simonbuehler** [comment]
thanks for your inputs, for testing the header and lib can be downloaded [from here](http://www.mitsubishi-photo.cz/drivers/drivers_printers/cz_en/dll_prohibited/CP9K_USBDLLVer573_6_Win7x64_130305.zip), including windows.h didn't fix the ` error: variable has incomplete type 'void'` error and others

**Comment by simonbuehler** [comment]
hi, just to let someone know how to fix this:
i added 
```
# ifndef WIN32_LEAN_AND_MEAN
#   define WIN32_LEAN_AND_MEAN
# endif
# ifndef VC_EXTRALEAN
#   define VC_EXTRALEAN
# endif
# ifndef NOMINMAX
#   define NOMINMAX
# endif
#include <windows.h>
```

to the header file so not all windows.h declarations got build and to fix the "missing ctype.h" err that followed up i set `module.IncludeDirs.Add(@"C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt");` where the ctype.h file is located  and it generated the code with out an error.

closing this, again thanks for your input !
