### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by rickomax** [mono/CppSharp#1124]
##### Brief Description

I'm getting an AccessViolationException when trying to generate the interop classes for [FBX SDK 2019](http://download.autodesk.com/us/fbx/2019/2019.0/fbx20190_fbxsdk_vs2015_win.exe).

The error is thrown when reaching this CppSharp method:
```
CppSharp::Parser::ParserResult^ CppSharp::Parser::ClangParser::ParseHeader(CppSharp::Parser::CppParserOptions^ Opts)
{
    auto __arg0 = (::CppSharp::CppParser::CppParserOptions*)Opts->NativePtr;
    auto __ret = ::CppSharp::CppParser::ClangParser::ParseHeader(__arg0);
    if (__ret == nullptr) return nullptr;
    return (__ret == nullptr) ? nullptr : gcnew CppSharp::Parser::ParserResult((::CppSharp::CppParser::ParserResult*)__ret);
}
```

Specifically, this line:
`auto __arg0 = (::CppSharp::CppParser::CppParserOptions*)Opts->NativePtr;`

I'm looking for a way to compile LLVM with debug symbols, so I could check what's happening internally, but I can't find a LLVM debug source package on CppSharp repo, and couldn't compile LLVM debug from sources either.

OS: Windows / OS X / Linux (include version and/or distro)
Windows

##### Used headers
`fbxsdk.h`

##### Used settings
```
var options = driver.Options;
options.Verbose = true;
var module = options.AddModule("FBXSDK");
module.IncludeDirs.Add("C:\\Program Files\\Autodesk\\FBX\\FBX SDK\\2019.0\\include");
module.IncludeDirs.Add("C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.14.26428\\include");
module.LibraryDirs.Add("C:\\Program Files\\Autodesk\\FBX\\FBX SDK\\2019.0\\lib\\vs2015\\x86\\release");
module.Libraries.Add("libfbxsdk.lib");
```

Target: MSVC/GCC/Clang
MSVC
Other settings 

##### Stack trace or incompilable generated code
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0
Parsing libraries...
Parsed 'libfbxsdk.lib'
Parsing code...
Parsed 'fbxsdk/core/base/fbxarray.h'
Parsed 'fbxsdk/core/base/fbxbitset.h'
Parsed 'fbxsdk/core/base/fbxcharptrset.h'
Parsed 'fbxsdk/core/base/fbxcontainerallocators.h'
Parsed 'fbxsdk/core/base/fbxdynamicarray.h'
Parsed 'fbxsdk/core/base/fbxstatus.h'
Parsed 'fbxsdk/core/base/fbxfile.h'
Parsed 'fbxsdk/core/base/fbxhashmap.h'
Parsed 'fbxsdk/core/base/fbxintrusivelist.h'
Parsed 'fbxsdk/core/base/fbxmap.h'
Parsed 'fbxsdk/core/base/fbxmemorypool.h'
Parsed 'fbxsdk/core/base/fbxpair.h'
Parsed 'fbxsdk/core/base/fbxset.h'
Parsed 'fbxsdk/core/base/fbxstring.h'
Parsed 'fbxsdk/core/base/fbxstringlist.h'
Parsed 'fbxsdk/core/base/fbxtime.h'
Parsed 'fbxsdk/core/base/fbxtimecode.h'
Parsed 'fbxsdk/core/base/fbxutils.h'
Parsed 'fbxsdk/core/math/fbxmath.h'
Parsed 'fbxsdk/core/math/fbxdualquaternion.h'
Parsed 'fbxsdk/core/math/fbxmatrix.h'
Parsed 'fbxsdk/core/math/fbxquaternion.h'
Parsed 'fbxsdk/core/math/fbxvector2.h'
Parsed 'fbxsdk/core/math/fbxvector4.h'
Parsed 'fbxsdk/core/fbxclassid.h'
Parsed 'fbxsdk/core/fbxconnectionpoint.h'
Parsed 'fbxsdk/core/fbxdatatypes.h'
```

**Comment by tritao** [comment]
What issue did you get when compiling LLVM from source in debug mode?

We provide some build scripts which you can try to use:

https://github.com/mono/CppSharp/blob/master/docs/BuildingLLVM.md#compiling-using-the-build-script

If you hit any issue, please me know.

To force debug LLVM you can add `debug = true` in the Lua build script: https://github.com/mono/CppSharp/blob/master/build/scripts/LLVM.lua#L142

**Comment by rickomax** [comment]
I'm facing some issues when trying to compile LLVM from source.

First, if I use the provided scripts to download LLVM and Clang, I get the right files downloaded, but 7Zip don't extract the Tarballs automatically.

If I extract the Tarballs at the "Scripts" folder, the build_llvm command will fail, so I have to extract them at "deps/llvm" and "deps/clang" respectively, this way the compilation proccess will start just fine, but at the end of the compilation it will throw the message:

`ninja -C "C:/Repos/CppSharp/deps/llvm/llvm-bfd4fd-windows-vs2017-x86-Debug" clang-headers
ninja: Entering directory `C:/Repos/CppSharp/deps/llvm/llvm-bfd4fd-windows-vs2017-x86-Debug'
ninja: error: unknown target 'clang-headers'`

**Comment by rickomax** [comment]
I've been able to debug the issue, but I'm not very familiar with LLVM, so here comes the call stack:
`
>	CppSharp.CppParser.dll!clang::Parser::ParseLateTemplatedFuncDef(clang::LateParsedTemplate & LPT)Linha 1369	C++
 	CppSharp.CppParser.dll!clang::Parser::LateTemplateParserCallback(void * P, clang::LateParsedTemplate & LPT)Linha 1356	C++
 	CppSharp.CppParser.dll!clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation PointOfInstantiation, clang::FunctionDecl * Function, bool Recursive, bool DefinitionRequired, bool AtEndOfTU)Linha 3852	C++
 	CppSharp.CppParser.dll!clang::Sema::PerformPendingInstantiations(bool LocalOnly)Linha 5180	C++
 	CppSharp.CppParser.dll!clang::Sema::GlobalEagerInstantiationScope::perform()Linha 7628	C++
 	CppSharp.CppParser.dll!clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation PointOfInstantiation, clang::FunctionDecl * Function, bool Recursive, bool DefinitionRequired, bool AtEndOfTU)Linha 3973	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::MarkValidity(CppSharp::CppParser::AST::Function * F)Linha 3065	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkFunction(const clang::FunctionDecl * FD, CppSharp::CppParser::AST::Function * F, bool IsDependent)Linha 3217	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkMethodCXX(const clang::CXXMethodDecl * MD)Linha 1787	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecord(const clang::RecordDecl * Record, CppSharp::CppParser::AST::Class * RC)Linha 987	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecordCXX(const clang::CXXRecordDecl * Record, CppSharp::CppParser::AST::Class * RC)Linha 1048	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkClassTemplateSpecialization(const clang::ClassTemplateSpecializationDecl * CTS)Linha 1196	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3749	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2297	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2479	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3854	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2258	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkFieldCXX(const clang::FieldDecl * FD, CppSharp::CppParser::AST::Class * Class)Linha 1827	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::ReadClassLayout(CppSharp::CppParser::AST::Class * Class, const clang::RecordDecl * RD, clang::CharUnits Offset, bool IncludeVirtualBases)Linha 164	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecord(const clang::RecordDecl * Record, CppSharp::CppParser::AST::Class * RC)Linha 949	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecordCXX(const clang::CXXRecordDecl * Record, CppSharp::CppParser::AST::Class * RC)Linha 1048	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkClassTemplateSpecialization(const clang::ClassTemplateSpecializationDecl * CTS)Linha 1196	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3749	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2297	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2479	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2683	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkParameter(const clang::ParmVarDecl * PVD, const clang::SourceLocation & ParamStartLoc)Linha 2956	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkType(clang::QualType QualType, const clang::TypeLoc * TL, bool DesugarType)Linha 2422	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetQualifiedType(const clang::QualType & qual, const clang::TypeLoc * TL)Linha 575	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkFunction(const clang::FunctionDecl * FD, CppSharp::CppParser::AST::Function * F, bool IsDependent)Linha 3128	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkFunction(const clang::FunctionDecl * FD, bool IsDependent, bool AddToNamespace)Linha 3243	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3824	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclarationDef(clang::Decl * D)Linha 3703	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetDeclarationFromFriend(clang::NamedDecl * FriendDecl)Linha 4436	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkFriend(const clang::FriendDecl * FD)Linha 3352	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3930	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecord(const clang::RecordDecl * Record, CppSharp::CppParser::AST::Class * RC)Linha 1020	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecordCXX(const clang::CXXRecordDecl * Record, CppSharp::CppParser::AST::Class * RC)Linha 1048	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecordCXX(const clang::CXXRecordDecl * Record)Linha 826	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3735	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::EnsureCompleteRecord(const clang::RecordDecl * Record, CppSharp::CppParser::AST::DeclarationContext * NS, CppSharp::CppParser::AST::Class * RC)Linha 743	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::GetRecord(const clang::RecordDecl * Record, bool & Process)Linha 782	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkRecordCXX(const clang::CXXRecordDecl * Record)Linha 819	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3735	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclarationDef(clang::Decl * D)Linha 3703	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclaration(const clang::Decl * D)Linha 3904	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkDeclarationDef(clang::Decl * D)Linha 3703	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::WalkAST()Linha 3289	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::Parser::ParseHeader(const std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > & SourceFiles)Linha 4152	C++
 	CppSharp.CppParser.dll!CppSharp::CppParser::ClangParser::ParseHeader(CppSharp::CppParser::CppParserOptions * Opts)Linha 4371	C++
 	[Transição Gerenciado para Nativo]	
 	CppSharp.Parser.CLI.dll!CppSharp::Parser::ClangParser::ParseHeader(CppSharp::Parser::CppParserOptions^ Opts)Linha 771	C++
 	CppSharp.Parser.dll!CppSharp.ClangParser.ParseSourceFiles(System.Collections.Generic.IEnumerable<string> files, CppSharp.Parser.ParserOptions options)Linha 56	C#
 	CppSharp.Parser.dll!CppSharp.ClangParser.ParseSourceFile(string file, CppSharp.Parser.ParserOptions options)Linha 43	C#
 	CppSharp.Generator.dll!CppSharp.Driver.ParseCode()Linha 146	C#
 	CppSharp.Generator.dll!CppSharp.ConsoleDriver.Run(CppSharp.ILibrary library)Linha 425	C#
 	FBXSDKBindings.exe!FBXSDKBindings.Program.Main(string[] args)Linha 10	C#
 	[Transição Nativo para Gerenciado]	
 	mscoreei.dll!00007ffa639a7b2d()	Desconhecido
 	mscoree.dll!00007ffa63a4a4cc()	Desconhecido
 	kernel32.dll!00007ffa90313034()	Desconhecido
 	ntdll.dll!00007ffa92201461()	Desconhecido
`
There I get the error:
`
"Exception thrown: read access violation. 
this->Actions was 0xFFFFFFFFFFFFFFB7.
`

**Comment by ddobrev** [comment]
@rickomax you've most probably hit https://github.com/mono/CppSharp/issues/1123. But to be sure, could you reduce the test case?

**Comment by tritao** [comment]
Can you check if this is still an issue with master?

**Comment by rickomax** [comment]
Hi @tritao
I will be back to my office in three days, so I will check your solution.

Thanks!

**Comment by rickomax** [comment]
Hi @tritao.
The Master version have fixed the issue.
There are some issues related to the FBX library code itself, but I'll mark this one as resolved.
Ty!

**Comment by rickomax** [comment]
Hi @tritao!

The latest commits fixes the issue. There are some other issues related to the FBX library itself, but it has nothing to do with the memory access exception.
How can I proceed with BountySource?

**Comment by tritao** [comment]
I see this on BountySource: `You will be able to claim this bounty as soon as the original issue is marked as closed.`

Can you try closing it?

**Comment by rickomax** [comment]
Done!
