### ISSUE TITLE
Is there a way to prepare a large library?

### ISSUE THREAD

**Issue by AleXr64** [mono/CppSharp#1143]
I want to wrap [ReHLDS](https://github.com/dreamstalker/rehlds). This is written with preservation of compatibility with the original hlsdk and contains many typedefs, templates, and preprocessor definitions (for building on different operating systems, enabling options, etc.). How can I prepare this before wrapping and reduce the volume of customization of the wrapping process? Tools, compiler options / flags?

**Comment by tritao** [comment]
I would start by identifying the subset of types that you need to bind to C# and ignore the rest of the "useless" types in CppSharp. Usually if the codebase is too much template-based its easier to write a new clean C++ layer that wraps those templates and pass that to CppSharp.
