### ISSUE TITLE
Wrong generation of virtual table function addresses

### ISSUE THREAD

**Issue by TheTimmy** [mono/CppSharp#1151]
I might miss something in my code, but it may also be a bug., because on my setup (Windows, Visual Studio 2017 x64 code generation) it seems that the current implementation generates the wrong Thunks entries in the SetupVTables function. This happens with the libraries the Nuget package as well as in a self compiled version of CppSharp with an current implementation of Clang. Therefore inheriting an abstract c++ class in c# will result in a wrong function being called or a wrong address, if a virtual function of the abstract class gets called from the c++ implementation.

It happens even for a simple example as:

```cpp
class DLL_EXPORT SimpleInterface {
  public:
    virtual std::size_t size() const = 0;
    virtual std::size_t capacity() const = 0;
    virtual void* get(std::size_t n) = 0;
};

class DLL_EXPORT InterfaceTester {
  public:
    InterfaceTester() {}
    std::size_t capacity() { return interface->capacity(); }
    std::size_t size() { return interface->size(); }
    void* get(std::size_t n) { return interface->get(n); }
    void setInterface(SimpleInterface* i) { interface = i; };
  private:
    SimpleInterface* interface;
};
```

```csharp
class Program {
  public class Inter : SimpleInterface {
    public override ulong Size => s;
    public override ulong Capacity => s;
    public override IntPtr Get(ulong n) { return new IntPtr(0); }
    private ulong s = 0;
  }
 static unsafe void Main(string[] args) {
   Inter i = new Inter();
   InterfaceTester tester = new InterfaceTester();
   tester.SetInterface(i);
   tester.Get(10);
  }
}
```
the call tester.Get(10) will result in Capacity being called instead of the Get implementation. 
The option for the generation where set to
```csharp
var parser = driver.ParserOptions;
parser.MicrosoftMode = true;
parser.UnityBuild = true;
parser.EnableRTTI = true;

var options = driver.Options;
options.GeneratorKind = GeneratorKind.CSharp;
options.CheckSymbols = true;
options.GenerateClassTemplates = true;
options.CompileCode = true;
options.Compilation.DebugMode = true;
options.Compilation.Platform = TargetPlatform.Windows;
options.Compilation.VsVersion = VisualStudioVersion.Latest;
```

**Comment by tritao** [comment]
Hey @TheTimmy, thanks for the detailed description of the issue.

My first guess is that this is due to mismatch between 32/64 bits.

Try:
```csharp
parser.TargetTriple = "x86_64-pc-win32-msvc";
```

**Comment by TheTimmy** [comment]
Thank you @tritao for the fast answer.
I did what you suggested and set the target triple to "x86_64-pc-win32-msvc" and reevaluated the settings for all three of the projects, but it still results in an runtime error. The only option which got it to work was manually reordering the Thunks entries. I also tried setting the Abi to Microsoft, but this also got me to an runtime error.

**Comment by ddobrev** [comment]
@TheTimmy I have added your test at https://github.com/mono/CppSharp/commit/7817b52ce3a79d7f2f99fd3b92ce0a864e8da32e and it all works fine. Could you try removing your options and see if it still works? I suggest you start with RTTI.

**Comment by tritao** [comment]
Could you post your generated C# code for the sample?

It would also help debug this if you can post the output of the native vtable offsets.

You can do this with `clang`/`clang-cl`: `clang -c t.cpp -Xclang -fdump-vtable-layouts`
Or with `cl.exe`: `cl.exe /d1reportAllClassLayout t.cpp`

**Comment by TheTimmy** [comment]
I can confirm, that the RTTI option is causing the wrong virtual tables.
Here are the vtables which got generated by clang and cl:
```
CLANG WITH RTTI
VFTable for 'Interface::SimpleInterface' (4 entries).
   0 | Interface::SimpleInterface RTTI
   1 | std::size_t Interface::SimpleInterface::size() const [pure]
   2 | std::size_t Interface::SimpleInterface::capacity() const [pure]
   3 | void *Interface::SimpleInterface::get(std::size_t) [pure]

VFTable indices for 'Interface::SimpleInterface' (3 entries).
   0 | std::size_t Interface::SimpleInterface::size() const
   1 | std::size_t Interface::SimpleInterface::capacity() const
   2 | void *Interface::SimpleInterface::get(std::size_t)

   
CLANG WITHOUT RTTI
VFTable for 'Interface::SimpleInterface' (3 entries).
   0 | std::size_t Interface::SimpleInterface::size() const [pure]
   1 | std::size_t Interface::SimpleInterface::capacity() const [pure]
   2 | void *Interface::SimpleInterface::get(std::size_t) [pure]

VFTable indices for 'Interface::SimpleInterface' (3 entries).
   0 | std::size_t Interface::SimpleInterface::size() const
   1 | std::size_t Interface::SimpleInterface::capacity() const
   2 | void *Interface::SimpleInterface::get(std::size_t)
   
   
CL:
class Interface::SimpleInterface        size(4):
        +---
 0      | {vfptr}
        +---

Interface::SimpleInterface::$vftable@:
        | &SimpleInterface_meta
        |  0
 0      | &Interface::SimpleInterface::size
 1      | &Interface::SimpleInterface::capacity
 2      | &Interface::SimpleInterface::get

Interface::SimpleInterface::size this adjustor: 0
Interface::SimpleInterface::capacity this adjustor: 0
Interface::SimpleInterface::get this adjustor: 0

class Interface::InterfaceTester        size(4):
        +---
 0      | interface
        +---
```

The requested code is here:
[Core-With-RTTI.txt](https://github.com/mono/CppSharp/files/2759692/Core-With-RTTI.txt)
[Core-Without-RTTI.txt](https://github.com/mono/CppSharp/files/2759693/Core-Without-RTTI.txt)

Also a diff of the generated code revealed, that the only difference between the generated code with and without rtti, is the virtual table generation:
```csharp
// generated code with rtti option
__ManagedVTables = new void*[1];
var vfptr0 = Marshal.AllocHGlobal(4 * 8);
__ManagedVTables[0] = vfptr0.ToPointer();
*(void**) (vfptr0 + 0) = *(void**) (new IntPtr(*(void**) __Instance) + 0 + 0);
*(void**) (vfptr0 + 8) = _Thunks[0];
*(void**) (vfptr0 + 16) = _Thunks[1];
*(void**) (vfptr0 + 24) = _Thunks[2];

// generated code without rtti option
__ManagedVTables = new void*[1];
var vfptr0 = Marshal.AllocHGlobal(3 * 8);
__ManagedVTables[0] = vfptr0.ToPointer();
*(void**) (vfptr0 + 0) = _Thunks[0];
*(void**) (vfptr0 + 8) = _Thunks[1];
*(void**) (vfptr0 + 16) = _Thunks[2];
```

**Comment by ddobrev** [comment]
@TheTimmy have you been able to work around or fix this? We've been overwhelmed with work, both C++#-related and not, so I cannot tell when we'd been able to resolve this ourselves. You, on the other hand, have the correct layout by Clang and should be therefore able to track our bug down.

**Comment by TheTimmy** [comment]
@ddobrev Yes, thanks to your suggestion to turn off RTTI and the factor that I currently don't expose any RTTI specific features, I could call the wrapper without RTTI, while the library itself is still able to use the feature. Regarding a fix, I wil try to fix the bug if I find the time for it.
