### ISSUE TITLE
Difficulty finding custom Type in TypeMapDatabase in 0.8.23

### ISSUE THREAD

**Issue by xsacha** [mono/CppSharp#1167]
##### Brief Description
When generating from a typemap, using the new Type signatures of 0.8.23, I have difficulty finding custom types in the type database.

**Working Code from 0.8.22**
```C#
if (TypeMapDatabase.FindTypeMap("CustomType", out TypeMap map))
```
Correctly finds CustomType and outputs map.

**Attempted conversion to 0.8.23**
```C#
if (TypeMapDatabase.FindTypeMap(new CustomType("CustomType"), out TypeMap map))
```
Fails to find the CustomType, despite a key existing in the database with the string "CustomType".

**Workaround for 0.8.23**
```C#
var customTypeDoesNotWork = new Field("CustomType", new QualifiedType(), AccessSpecifier.Public);
if (TypeMapDatabase.FindTypeMap(customTypeDoesNotWork, out TypeMap map))
```
This successfully finds the type in the database.

OS: Windows (0.8.23)

##### Used settings

Target: MSVC

**Comment by ddobrev** [comment]
Hello @xsacha . The overload with a string is still there but it's private. You could call it through reflection or make it public and build C++# from source code.
However, type maps are not meant too be manually obtained by users. After all, the whole point of C++# is automation. So could you please let us know why you need to find it yourself? There might be a totally unrelated bug of ours which made you do this by hand, or there might be an undocumented feature which would do what you need.

**Comment by xsacha** [comment]
For me, this doesn't explain why a CustomType differs to a Field. I'd expect them both to work.

This is in a method for a callback type, in CSharpMarshalToNative, to check if the type is in the map. It uses a string to represent a callback type with multiple parameters.

**Comment by ddobrev** [comment]
You can directly use `TypeMapDatabase.TypeMaps.TryGetValue` instead.

**Comment by ddobrev** [comment]
I've also restored that overload to be public again.

**Comment by xsacha** [comment]
Thanks.

.TypeMaps wasn't available for me.
