### ISSUE TITLE
error: static_assert expression is not an integral constant expression?

### ISSUE THREAD

**Issue by srxqds** [mono/CppSharp#1171]
##### Brief Description

I use CppSharp to analysis UE4 code, but output the error:
error: static_assert expression is not an integral constant expression?
![image](https://user-images.githubusercontent.com/5187024/52934756-5ffa6d00-3392-11e9-8cf0-1c20bcfdd00f.png)

OS: Windows(x86)

The soure code:

``` c++
```
![image](https://user-images.githubusercontent.com/5187024/52934807-802a2c00-3392-11e9-9610-53e29d228c1b.png)

How can I make (walkaround) the clang not generate with modify unreal engine source code

**Comment by tritao** [comment]
Try changing your `ParserOptions.LanguageVersion` to `C++14`.

**Comment by srxqds** [comment]
The languageVersion is setting CPP14,
I found the workaround: Redefine the  **STRUCT_OFFSET**

thank you!
