### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by srxqds** [mono/CppSharp#1172]
##### Brief Description

I use CppSharp.Parser.CLI parse ue4 source code and generate the exception

OS: Windows (x86)

##### Used settings

Target: MSVC

Other settings 

##### Stack trace or incompilable generated code

![image](https://user-images.githubusercontent.com/5187024/52942192-7b22a800-33a5-11e9-8f87-0a6e0b9e34b5.png)

**Comment by tritao** [comment]
Hey @srxqds.

Please enable "Enable native code debugging" option in your VS project options, and see if you get a better stack trace.

**Comment by srxqds** [comment]
hi, thank you @tritao 
It is crashed in clang 
![image](https://user-images.githubusercontent.com/5187024/52949511-6fd87800-33b7-11e9-9836-375d608e7e34.png)

**Comment by tritao** [comment]
@srxqds 

Please try LLVM debug packages to get better stack traces.

Add `debug = true` here:
https://github.com/mono/CppSharp/blob/master/build/scripts/LLVM.lua#L141

Then you can re-download packages with `DownloadDeps.bat`, re-generate the projects and try again in Debug configuration.

**Comment by srxqds** [comment]
There is no debug package?

F:\trunk_branch\custom_software\CppSharp-0.8.22\build>"premake5" --file=scripts/LLVM.lua download_llvm 
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-bfd4fd-windows-vs2017-x86-Debug.7z
Error: .../custom_software/CppSharp-0.8.22/build/scripts/Utils.lua:98: HTTP response code said error
The requested URL returned error: 404 Not Found

**Comment by tritao** [comment]
Yeah, we updated the version of LLVM since 0.8.22 and the old debug package is gone.

You can upgrade to the latest master or 0.8.23 which supports the latest binary packages.

**Comment by srxqds** [comment]
hi, @tritao 
When I upgrade to 0.8.23, the error disappear!
Thank you
