### ISSUE TITLE
System.Exception: FBufferArchive::GetArchiveName is not virtual while the getter is. 

### ISSUE THREAD

**Issue by srxqds** [mono/CppSharp#1175]
I use CppSharp 0.8.23 parser UE4 source code, When parsing Core/Serialization/BufferArchive.h, it throw the exectption
**System.Exception: FBufferArchive::GetArchiveName is not virtual while the getter is.**

The BufferArchive.h code:
``` c++
/**
 * Buffer archiver.
 */
class FBufferArchive : public FMemoryWriter, public TArray<uint8>
{
public:
	FBufferArchive( bool bIsPersistent = false, const FName InArchiveName = NAME_None )
	: FMemoryWriter( (TArray<uint8>&)*this, bIsPersistent, false, InArchiveName )
	{}
	/**
  	 * Returns the name of the Archive.  Useful for getting the name of the package a struct or object
	 * is in when a loading error occurs.
	 *
	 * This is overridden for the specific Archive Types
	 **/
	virtual FString GetArchiveName() const { return *FString::Printf( TEXT("FBufferArchive %s"), *ArchiveName.ToString()); }
};
```

And the base class **FMemoryWriter** has the virtual GetArchiveName() method:
![image](https://user-images.githubusercontent.com/5187024/52990357-cf2f9a00-3442-11e9-978c-fc3038caa13a.png)

OS: Windows 

Target: MSVC

Other Setting
I has use debug mode with LLVM debug lib and enable native debug

![image](https://user-images.githubusercontent.com/5187024/52990155-d3a78300-3441-11e9-8f18-34c52899e1e5.png)

**Comment by srxqds** [comment]
oh, I coment the **try catch**  and then find the problem: In the base class has ArchiveName
![image](https://user-images.githubusercontent.com/5187024/52994354-3c96f700-3452-11e9-85cd-5f1d69238884.png)


how can I fix it?

**Comment by srxqds** [comment]
In **GetterSetterToPropertyPass.cs**, This will always throw the Exception, because the **property** always is not virtual
![Uploading image.png…]()

**Comment by tritao** [comment]
Hey @srxqds, can you try to isolate a small test case that demonstrates this issue?

Then @ddobrev, the author of this pass, could take a look.

**Comment by srxqds** [comment]
hey @tritao  @ddobrev I made the the demonstrates
The test case code:

``` c++
class TestGetBase
{
protected:
	const int ArchiveName;
public:
	virtual int GetArchiveName() const;
};

class TestGetterChild: TestGetBase
{
public:
	virtual int GetArchiveName() const;
};

```
It must throw the exception,

**Comment by tritao** [comment]
Thanks, this helps a lot.

**Comment by ddobrev** [comment]
@srxqds I have reproduced the issue but it might take a while to fix. If you need this working right away, you must have control over the C++ code and rename the field called "ArchiveName".
