### ISSUE TITLE
Does clang has cache mechanism？

### ISSUE THREAD

**Issue by srxqds** [mono/CppSharp#1178]
When I use it parse a large project source code, for example: 
**header1.h** include **header2.h**
when i modify header1.h but header2.h not modified, can It just re-parse header1.h and use header2.h  cache parse result(saved by first times parse)?

It can save many time !

**Comment by tritao** [comment]
Yes, Clang has AST cache that can save much time when parsing.

I started adding some support for it in https://github.com/mono/CppSharp/pull/1164 but more work still needs to be done.
