### ISSUE TITLE
error: use of undeclared identifier 'memset'

### ISSUE THREAD

**Issue by zjmsky** [mono/CppSharp#1181]
OS: Windows  Version 0.8.23
Hi:
   When i user CppSharp,it show error like this " error: use of undeclared identifier 'memset'",how can i solved this error?Thanks!

**Comment by tritao** [comment]
Looks like you're missing some includes in the code you're trying to parse.

Try adding include to `cstring`.

**Comment by zjmsky** [comment]
Thanks,it's works
