### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by zjmsky** [mono/CppSharp#1184]
Hi,I used CppSharp convert an third native dll. I can invoke the third dll function,but when i used on function to set callback,it show error System.AccessViolationException.who can help me resolve this problem?thanks.The Project GitHub address is [https://github.com/zjmsky/TapTradeSharp](https://github.com/zjmsky/TapTradeSharp)
![123](https://user-images.githubusercontent.com/18650697/53775349-28142d80-3f2d-11e9-8cbb-f8e33535d817.png)

**Comment by tritao** [comment]
Hello @zjmsky , sorry I do not have time to research why it throws the exception.

Have you been able to figure anything out?

**Comment by srxqds** [comment]
@zjmsky 这个可能是native报错了，你用debug模式试下吧
This is may be crash by native error, may you try to use debug mode?

**Comment by zjmsky** [comment]
谢谢，已经可以正常了，很奇怪的问题。
