### ISSUE TITLE
CppSharp.CLI.exe --rtti sets -fno-rtti to clang

### ISSUE THREAD

**Issue by codingdave** [mono/CppSharp#1191]
##### Brief Description
The command line tool seems to not process --rtti correctly. Even if the parameter --rtti is given the parameter is lost on its way to clang.

OS: Windows

I have used the pre-compiled version inside the nuget package (packages\CppSharp.0.9.0\tools\CppSharp.CLI.exe) but I remember having the same issue on linux.

**Comment by tritao** [comment]
It seems to be handled here: https://github.com/mono/CppSharp/blob/master/src/CLI/Generator.cs#L178

Can you debug it a bit to see what's going on?

**Comment by codingdave** [comment]
Hi @tritao,

Ive just checked with the latest master build and see that the boolean value of rtti is being kept fine. However, I still get this error during processing:

Error parsing '/xxx.hpp'
yyy.hpp(69,19): error: use of typeid requires -frtti

Modifying ParserOptions.cs also did not solve the above error:

            if (!EnableRTTI)
            {
                AddArguments("-fno-rtti");
            }
            else
            {
                AddArguments("-frtti");
            }

**Comment by tritao** [comment]
I think I've had this exact issue a couple weeks ago.

If I remember correctly, I could not get Clang to recognize any `-frtti` option, only the negative `-fno-rtti` option.

I just checked it again.

In our `Parser.Bootstrap` driver, we do `driver.ParserOptions.EnableRTTI = true;`.

If I set this to false, then I get the same error as you.

So the option seems to be working correctly on my machine.

**Comment by codingdave** [comment]
Hmm, I see. What would probably help is to see the final call to clang and to call another clang instance with that and see how it reacts. How can I assemble the final parameter list that cmake is passed to?

**Comment by codingdave** [comment]
Ive tried to debug the linux build further, on which I can reproduce the error 

        if (!EnableRTTI)
        {
            AddArguments("-fno-rtti");
        }
        else
        {
            AddArguments("-frtti");
        }

I can see that options.EnableRTTI=true but Parser.ClangParser.ParseHeader(options) will generate the error above. You can see before and after screenshots attached below.

![1](https://user-images.githubusercontent.com/3075641/54261913-400f3100-456d-11e9-981b-41e36efa3b63.png)
![2](https://user-images.githubusercontent.com/3075641/54261914-400f3100-456d-11e9-910c-94dc6a6ca919.png)

On windows using the nuget package I have been using dnSpy to disassemble and change the assembly CppSharp.CLI.exe. I did not want to compile llvm + clang on windows which is needed because the download links to the precompiled archives dont work. So I have removed "--fno-rtti" from the assembly, compiled it again and was able to run CppSharp.CLI.exe without any problems any longer.

**Comment by codingdave** [comment]
Issue has been fixed with the pr
