### ISSUE TITLE
Stackoverflow FindVSVersion - infinite loop

### ISSUE THREAD

**Issue by jlarbi** [mono/CppSharp#1200]
The VS version check always returns  VisualStudioVersion.VS2017 and recurse, so if no VS2017 installed, it loops infinitely. The while visualStudioVersion-- is never done to pass to a previous version

Decompiled and bug-ed code :

public static VisualStudioVersion FindVSVersion(VisualStudioVersion vsVersion)
{
	VisualStudioVersion visualStudioVersion;
	if (vsVersion != VisualStudioVersion.Latest)
	{
		if (MSVCToolchain.GetVSToolchain(vsVersion).IsValid)
		{
			visualStudioVersion = vsVersion;
			return visualStudioVersion;
		}
	}
	VisualStudioVersion visualStudioVersion1 = VisualStudioVersion.VS2017;
	while (visualStudioVersion1 >= VisualStudioVersion.VS2012)
	{
		vsVersion = MSVCToolchain.FindVSVersion(visualStudioVersion1);
		if (vsVersion == VisualStudioVersion.Latest)
		{
			visualStudioVersion1--;
		}
		else
		{
			visualStudioVersion = vsVersion;
			return visualStudioVersion;
		}
	}
	visualStudioVersion = VisualStudioVersion.Latest;
	return visualStudioVersion;
}

OS: Windows 10
VS: 2015
Target: MSVC 140

Stacktrace sample:
>	CppSharp.dll!CppSharp.MSVCToolchain.FindVSVersion(CppSharp.VisualStudioVersion vsVersion) Ligne 113	C#
 	CppSharp.dll!CppSharp.MSVCToolchain.FindVSVersion(CppSharp.VisualStudioVersion vsVersion) Ligne 116 + 0x8 octets	C#
 	CppSharp.dll!CppSharp.MSVCToolchain.FindVSVersion(CppSharp.VisualStudioVersion vsVersion) Ligne 116 + 0x8 octets	C#
 	CppSharp.dll!CppSharp.MSVCToolchain.FindVSVersion(CppSharp.VisualStudioVersion vsVersion) Ligne 116 + 0x8 octets	C#
 	CppSharp.Parser.dll!CppSharp.Parser.ParserOptions.SetupMSVC(CppSharp.VisualStudioVersion vsVersion) Ligne 363 + 0xb octets	C#
 	CppSharp.Parser.dll!CppSharp.Parser.ParserOptions.SetupMSVC() Ligne 350 + 0xc octets	C#
 	CppSharp.Parser.dll!CppSharp.Parser.ParserOptions.SetupIncludes() Ligne 276 + 0x9 octets	C#
 	CppSharp.Parser.dll!CppSharp.Parser.ParserOptions.Setup() Ligne 183 + 0x9 octets	C#
 	CppSharp.Generator.dll!CppSharp.Driver.Setup() + 0x5b octets	
 	CppSharp.Generator.dll!CppSharp.ConsoleDriver.Run(CppSharp.ILibrary library) + 0x10d octets	
 	SharpKDIS.exe!SharpKDIS.EntryPoint.Main() Ligne 19 + 0x25 octets	C#
 	[Transition Natif à Managé]	
 	[Transition Managé à Natif]	
 	mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile, System.Security.Policy.Evidence assemblySecurity, string[] args) Ligne 1967 + 0x1f octets	C#
 	Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly() + 0x3a octets	
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Ligne 954 + 0xd octets	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Ligne 901 + 0x9 octets	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Ligne 890 + 0x11 octets	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart() Ligne 105 + 0x24 octets	C#
 	[Transition Natif à Managé]

**Comment by tritao** [comment]
Hey @jlarbi, can you try and fix the issue / send a PR?

**Comment by tritao** [comment]
We now rely on Clang to find VS headers via https://github.com/mono/CppSharp/commit/8fca42afe549473d6ff32390b177e149f93a76d3.

Please test again and re-open if still an issue.
