### ISSUE TITLE
Support delegates as type arguments

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#1201]
Code such as:
```c++
Template<int(*)(int)>
```
is generated as
```cs
Template<IntPtr>
```
just so that it compiles. We need proper support by using our generated delegates.

**Comment by AleXr64** [comment]
Related https://github.com/mono/CppSharp/issues/1144 https://github.com/mono/CppSharp/issues/1188

**Comment by AleXr64** [comment]
Not only templates.
```
struct FieldsPointers
{
	int(*FuncInt)(int(*bug));
};
```
`public unsafe delegate int Func_int_intPtr(int* _0);`

**Comment by AleXr64** [comment]
I think this is a variation of https://github.com/mono/CppSharp/issues/1144 and https://github.com/mono/CppSharp/issues/1188

**Comment by ddobrev** [comment]
Fixed in https://github.com/mono/CppSharp/commit/3caa8c5da27441469bff1b65b4482291e4c92364.
