### ISSUE TITLE
Failed generating `BasicString` from `std::string`

### ISSUE THREAD

**Issue by jingkecn** [mono/CppSharp#1209]
##### Brief Description

When generating a cs `String` from `std::string` (originally as a class field), it fails generating `BasicString` in `Std.cs`.

> cc @ddobrev 

Confirmed by @tritao :

> Looks related to TrimSpecializationsPass
> It only looks in parameters and return types to see if a particular specialization is needed

An a tempo workaround is suggested by @tritao : 

```cs
public virtual void SetupPasses(Driver driver)
{
    driver.Context.TranslationUnitPasses.Passes.Remove( 
        driver.Context.TranslationUnitPasses.Passes.Find(m => m.GetType() == typeof(TrimSpecializationsPass))
    );
}
```

OS: Windows / OS X / Linux (include version and/or distro)

> Windows

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by tritao** [comment]
@ddobrev This one has affected another user yesterday, @thejuskambi.

Take a look when you can.
