### ISSUE TITLE
Error from STL Library

### ISSUE THREAD

**Issue by mscc** [mono/CppSharp#122]
My C++ code contains Standard Library functions and I am having a trouble running CppSharp due to that.
On my header file, I have something like:
int testFunc(std::string x);

Then my C# code, I did similar as what the example did, include Library and header files with correct directory. After running the problem, I get errors like:

error CS0246: The type or namespace name 'std' could not be f
ound (are you missing a using directive or an assembly reference?)

error CS0208: Cannot take the address of, get the size of, or
 declare a pointer to a managed type ('std.basic_string.Internal')
c:\Users<myFilePath>

error CS1061: 'Std.String' does not contain a definition for
 __Instance' and no extension method __Instance' accepting a first argument of
 type 'Std.String' could be found (are you missing a using directive or an assem
bly reference?)

When I look at the .cs file, it generates to:
internal static extern int testFunc1_0(global::System.IntPtr instance, Std.String x);

I just downloaded the latest VS dlls (Nov 13th ver 423). I am also having similar error messages when I use stl <vector>, and others. Do I need to do some customization or something? How to make CppSharp recognizes my STL stuff? Thanks

**Comment by mohtamohit** [comment]
@tritao @ddobrev I think we have fixed this one now. :)
