### ISSUE TITLE
32 bit Linux Cpp sharp dlls not provided

### ISSUE THREAD

**Issue by upretyrohan** [mono/CppSharp#1222]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by ddobrev** [comment]
@upretyrohan I'm sorry that I have to disappoint you but we're not providing binaries for 323-bit Linux. This would require us to build Clang for one more architecture, and building Clang requires a significant amount of time. We cannot take such a burden. In fact, [we're switching to a 64-bit build for Windows as well](https://github.com/mono/CppSharp/pull/1224). This leaves you with 3 options:

1. Switch to a 64-bit version of Linux;
2. Build Clang yourself following [our instructions](https://github.com/mono/CppSharp/blob/master/docs/BuildingLLVM.md) and proceed with [building C++# itself](https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md);
3. Contact our paid support.
