### ISSUE TITLE
Methods that return function pointers generate invalid code

### ISSUE THREAD

**Issue by NickApps** [mono/CppSharp#1226]
Given the following C++ code:
```
typedef int(*SomeFunctionPtr)(int p1);

class TESTDLL_API CallbackFunctions
{
  SomeFunctionPtr callback = nullptr;

public:
  virtual SomeFunctionPtr getCallback() const = 0;
};
```
The generator will produce code such as the following:
```
private static global::SampleLibrary.SomeFunctionPtr _GetCallbackDelegateHook(global::System.IntPtr __instance)
{
    if (!NativeToManagedMap.ContainsKey(__instance))
        throw new global::System.Exception("No managed instance was found");

    var __target = (global::SampleLibrary.CallbackFunctions) NativeToManagedMap[__instance];
    if (__target.__ownsNativeInstance)
        __target.SetupVTables();
    var __ret = __target.Callback;
    return __ret == null ? global::System.IntPtr.Zero : Marshal.GetFunctionPointerForDelegate(__ret);
}
```
The last line is invalid, due to it trying to cast from IntPtr to the delegate type.  In this case it seems '__ret' can be returned directly.

In the generated CallbackFunctionsInternal class there is a similar issue:
```
public override global::SampleLibrary.SomeFunctionPtr Callback
{
    get
    {
        var __slot = *(void**) ((IntPtr) __OriginalVTables[0] + 0 * 4);
        var ___GetCallbackDelegate = (global::SampleLibrary.Delegates.Func_SampleLibrary_SomeFunctionPtr_IntPtr) Marshal.GetDelegateForFunctionPointer(new IntPtr(__slot), typeof(global::SampleLibrary.Delegates.Func_SampleLibrary_SomeFunctionPtr_IntPtr));
        var __ret = ___GetCallbackDelegate((__Instance + __PointerAdjustment));
        var __ptr0 = __ret;
        return __ptr0 == IntPtr.Zero? null : (global::SampleLibrary.SomeFunctionPtr) Marshal.GetDelegateForFunctionPointer(__ptr0, typeof(global::SampleLibrary.SomeFunctionPtr));
    }
}
```
The last line fails to compile due to invalid cast (__ptr0 and IntPtr).  Again, it seems that '__ret' could simply be returned.

I've made the changes manually to test these assertions and it appears to work correctly, both deriving from the generated class in C# and calling from C++ and deriving in C++ and calling from the C#.

OS: Windows 10
Built on VS2019 from recent source (< 1 week).

**Comment by ddobrev** [comment]
@NickApps thank you for your simple test and detailed explanation. Unfortunately, we've been too busy to fix this in our spare time. So your options are to either fix it yourself or contact our support.
