### ISSUE TITLE
Access violation on MSVC 64-bit when trying to parse Qt's QScopedPointer

### ISSUE THREAD

**Issue by kuukunen** [mono/CppSharp#1231]
Windows 10
Visual Studio 2019 64-bit (Tried 2017 too.)
Also tried both the suggested LLVM/clang versions and the current HEADs.

I tried getting QtSharp working on MSVC 64-bit, but it seems some of the headers are not parsed properly and will crash with access violation.

In debug configuration, the assert in MicrosoftCXXABI.cpp, line 171 triggers:
`assert(IA && "Expected MSInheritanceAttr on the CXXRecordDecl!");`
I added the stacktrace as a file, since it was so long and messy.

I also went through the headers and stripped down all non-contributing parts and it seems like the problem is an ugly special case in QScopedPointer. I also attached the stripped down header that causes a crash for me.

[qt_stacktrace.txt](https://github.com/mono/CppSharp/files/3348093/qt_stacktrace.txt)
[problem_qt_header.txt](https://github.com/mono/CppSharp/files/3348094/problem_qt_header.txt)

**Comment by tritao** [comment]
Thanks for the report. 

We have dealt with this kind of crash in the past, see: https://github.com/mono/CppSharp/blob/547a9f28192140209cff6227b0c318cf7a42d19d/src/CppParser/Parser.cpp#L2946

We use `RequireCompleteType` to make sure these attributes are synthesized by Clang.

A more in-depth crash analysis needs to be made, to see why it's not working here.
