### ISSUE TITLE
Question about MSVC std StructLayout sizes

### ISSUE THREAD

**Issue by sichbo** [mono/CppSharp#1233]
I'm seeing heap corruption due to size discrepancies with the MSVC 14.16.27023 std::vector and std::string implementations being 32 bytes rather than 24 bytes as CppSharp presumes when generating stubs for the "x86_64-pc-win32-msvc" TargetTriple. 

This file here has the same sort of mismatched layout sizes:

https://github.com/mono/CppSharp/blob/cae9431cd81c62df5e0900dc00f7e7a0ac0940ca/src/CppParser/Bindings/CSharp/x86_64-pc-win32-msvc/Std.cs

So for instance:
```
    namespace VectorVal
    {
        [StructLayout(LayoutKind.Explicit, Size = 24)]
        public unsafe partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::System.IntPtr _Myfirst;
            [FieldOffset(8)]
            internal global::System.IntPtr _Mylast;
            [FieldOffset(16)]
            internal global::System.IntPtr _Myend;
        }
    }
```

With the 2017 MSVC version I happen to have installed 14.16.27023, the struct would look more like this:
```
    namespace VectorVal
    {
        [StructLayout(LayoutKind.Explicit, Size = 32)]
        public unsafe partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::System.IntPtr _Myproxy;  // <-- from std::_Container_base12 
            [FieldOffset(8)]
            internal global::System.IntPtr _Myfirst;
            [FieldOffset(16)]
            internal global::System.IntPtr _Mylast;
            [FieldOffset(24)]
            internal global::System.IntPtr _Myend;
        }
    }
```
Is there a configuration trick for getting correct structure sizes emitted? 

Any thoughts/insights appreciated.

Thank you,

Simon

**Comment by ddobrev** [comment]
The issue is most probably that [we've made certain assumptions about the VS version when generating the bindings](https://github.com/mono/CppSharp/blob/master/src/CppParser/Parser.cpp#L356). Please check if setting `toolSetToUse` yourself to your won VS version changes anything.

**Comment by sichbo** [comment]
Awesome, thank you for the tip! It turns out your version assumptions are fine 👍 Rather the problem is that I simply needed to add:
```
 driver.ParserOptions.AddDefines("_DEBUG");
```
Because regardless of MSVC version their std templates appear to have a _Myproxy container only for debug mode builds, which of course creates a problem when CppSharp isn't compiling with the same flag. 

Many thanks for assistance and your excellent work.
