### ISSUE TITLE
Failure to download deps

### ISSUE THREAD

**Issue by WattsC-90** [mono/CppSharp#1234]
##### Brief Description
0.10.1 Appears to fail to download the dependencies, running from VS2015 command prompt.
Running from 2019 shows unsupported MSVC error, but just get 404 not found from 2015 command prompt.

Building from source isnt viable given the dependencies required for building the LLVM etc deps.

IS there a solution for downloading the requirements for running this on windows?

Are there any precompiled binaries available as a .zip to just run out of box?

Thanks in advance

**Comment by tritao** [comment]
Building LLVM is basically a single command process so its pretty easy, given you have some disk space available.

https://github.com/mono/CppSharp/blob/master/docs/BuildingLLVM.md#compiling-using-the-build-script

The only other alternative, is for you to try use our VS 2017 packages:

https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-815d4b-windows-vs2017-x64-RelWithDebInfo.7z

https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-815d4b-windows-vs2017-x86-RelWithDebInfo.7z

But beware that sometimes there might be some linking issues between VS versions, worth a try though.

**Comment by WattsC-90** [comment]
Thanks for this, the issue is simply installing ninja, cmake etc when trying to simply generate an interop class from someone elses code, rather than compiling there code. Ill give the 2017 a try though.. Cue mega download...
