### ISSUE TITLE
NullReferenceException attempting to process `using typename` followed by `using` (for aliasing)

### ISSUE THREAD

**Issue by lostmsu** [mono/CppSharp#1235]
##### Brief Description

NullReferenceException is thrown in `AstVisitor.VisitTypedefType` when visiting `using` referencing a `using typename` in the previous line during `CheckIgnoredDeclsPass`

[Full stack trace](https://pastebin.com/qWXEpFf7)

OS: Windows

##### Used headers

I narrowed down the sample to the following:

```cpp
#include <functional>

template <typename X, typename Y>
class TemplateClassBase {
  public:
    using XType = X;
};

template <typename A, typename B = A>
class TemplateClass : TemplateClassBase<A,B> {
  public:
    using typename TemplateClassBase<A,B>::XType;
    using Func = std::function<B(XType)>;
    explicit TemplateClass(Func function) {}
};
```

##### Used settings
```csharp
            driver.ParserOptions.LanguageVersion = LanguageVersion.CPP14;
            driver.ParserOptions.ForceClangToolchainLookup = false;
            driver.ParserOptions.EnableRTTI = true;
            driver.ParserOptions.AddArguments("-fexceptions");
            driver.ParserOptions.AddArguments("-fcxx-exceptions");

            module.Defines.Add("WIN32");
            module.Defines.Add("_WINDOWS");
```

`Generate*Templates` seem to have no effect on that issue.

##### Stack trace or incompilable generated code
[Full stack trace](https://pastebin.com/qWXEpFf7)

##### Own research
I tried to do a research for this issue, and at the first glance of a person with 0 experience with CppSharp or clang APIs, it looks like `Parser.WalkType` in `src\CppParser\Parser.cpp` does not handle `clang::Type::UnresolvedUsing`, and also `Parser.WalkDeclaration` for `Decl::UnresolvedUsingTypename` is empty.

**Comment by tritao** [comment]
Thanks for the bug report and for narrowing it down.

Your research seems correct, we need to add support for this.
