### ISSUE TITLE
unique_ptr not identified by parser

### ISSUE THREAD

**Issue by asafshefi** [mono/CppSharp#1240]
##### Brief Description
When I try to parse an .h file that includes a private member of unique_ptr I get:
error: no template named 'unique_ptr' in namespace 'std'

OS: Windows / OS X / Linux (include version and/or distro)
Windows 10

##### Used settings

Target: MSVC/GCC/Clang

Other settings

**Comment by tritao** [comment]
By the description, it sounds like you're missing an include of `<memory>` somewhere.

**Comment by asafshefi** [comment]
Adding #include <memory> to the .h file  solved it!
Thanks for the fast and helpful reply
