### ISSUE TITLE
Generated wrapper entry points do not exist in the actually binary

### ISSUE THREAD

**Issue by Swoboderz** [mono/CppSharp#1248]
the generated cs file on MacOSX using clang does not generate accurate entry points

When i try to use the wrapper with the .dylib or .so (tried both) im met with 

`EntryPointNotFoundException: _ZN9FixedVec2C2Exx`

when i `nm -gU` the binary all the FixedVec2 signatures are as follow

`
0000000000000ca0 T __ZN9FixedVec23SetExx
0000000000000c80 T __ZN9FixedVec27SetZeroEv
0000000000000e40 T __ZN9FixedVec29NormalizeEv
0000000000000ff0 T __ZN9FixedVec2aSEOS_
0000000000000fd0 T __ZN9FixedVec2aSERKS_
0000000000000ce0 T __ZN9FixedVec2clEi
0000000000000d10 T __ZN9FixedVec2mIERKS_
0000000000000d30 T __ZN9FixedVec2mLEx
0000000000000cf0 T __ZN9FixedVec2pLERKS_
`

**Comment by tritao** [comment]
`_ZN9FixedVec2C2Exx` demangled reads as: `FixedVec2::FixedVec2(long long, long long)`

I think what's happening is that this constructor is only defined in the header file and the compiler opts to inline it, thus never reaching the library.

Try moving it out of the header file and into a `.cpp` file so it doesn't get inlined by the compiler.

**Comment by Swoboderz** [comment]
odd, even with -O0 it still inlined that. seems to have worked though.
