### ISSUE TITLE
Assertion: should not be reached at metadata.c:2998

### ISSUE THREAD

**Issue by joo0ne** [mono/CppSharp#1250]
##### Brief Description
Program fault  in line
https://github.com/mono/mono/blob/fe64a4765e6d1dbb41d5c86708fcb02aa519247a/mono/metadata/metadata.c#L2998

##### Steps to reproduce:

1. Create new console app.
2, Add nuget package CppSharp.
3. Add `using CppSharp.Parser` and replace main method body with
4. `var parserOptions = new ParserOptions();`
5. Run

>$ uname -a
>Linux deb-len 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
>$ mono --version
>Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:20:06 UTC 2019)
>Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>TLS: __thread
>SIGSEGV: altstack
>Notifications: epoll
>Architecture: amd64
>Disabled: none
>Misc: softdebug
>Interpreter: yes
>LLVM: yes(610)
>Suspend: hybrid
>GC: sgen (concurrent by default)

##### Used settings
Target: Clang

**Comment by tritao** [comment]
@vargaz Any chance you could help us track this Mono crasher?

**Comment by ddobrev** [comment]
@joo0ne the table at https://github.com/mono/CppSharp explains that our NuGet only works on 64-bit Windows. We've planned to make it cross-platform but haven't got to it yet (help is always welcome). Even though C# is cross-platform, C++# has pieces of C++ and there's no way you can run its Windows version on Unix.

**Comment by tritao** [comment]
Closing this as source version works fine with Mono on Linux.
