### ISSUE TITLE
Unknown type name error

### ISSUE THREAD

**Issue by IIFE** [mono/CppSharp#1254]
##### Brief Description

OS: Windows 10

I'm trying to use CppSharp to generate C++/CLI bindings for a native C++ header. I have a repo that reproduces the issue, which can be found [here](https://github.com/IIFE/CppSharpTest). If you pull down the repo, build it and run the `CppSharpTest` app, you should an output similar to the following:

```
Parsing libraries...
Parsing code...
Compiler argument: -fms-extensions
Compiler argument: -fms-compatibility
Compiler argument: -fdelayed-template-parsing
Compiler argument: -xc++
Compiler argument: -std=c++14
Compiler argument: -fms-extensions
Compiler argument: -fms-compatibility
Compiler argument: -fdelayed-template-parsing
ignoring duplicate directory "lib\clang\9.0.0\include"
#include "..." search starts here:
#include <...> search starts here:
 ..\..\..\CppSharpTestNative
 lib\clang\9.0.0\include
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.22.27905\include
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um
 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt
End of search list.
Error parsing 'Consumer.h'
..\..\..\CppSharpTestNative\Consumer.h(13,5): error: unknown type name 'Description'
..\..\..\CppSharpTestNative\Consumer.h(15,5): error: unknown type name 'DWORD'
CppSharp has encountered an error while parsing code.`
```

I have the following setup in the native C++ project:
- `Sizeofs.h`, which contains `#define` for a constant defining the size for an array
- `Typedefs.h`, which contains a `typedef` that creates an alias for a char array with the size from `Sizeofs.h`
- `Consumer.h` which has two fields, one is the typedef from `Typedefs.h`, and one is a `DWORD` from the windows headers, which are included in the precompiled header.
- None of the headers are included in `Consumer.h` itself, but rather are included in `Consumer.cpp` before the incldue for `Consumer.h`. This includes the windows headers included via the precompiled header.

When parsing `Consumer.h`, CppSharp doesn't appear to know of the types used in the header because these types' headers are not included in the parsed header. Is there a way to tell CppSharp about these headers (i.e. `Windows.h, Sizeofs.h, Typedefs.h`)? From the output above, it appears that CppSharp is aware for example of the directories containing the `Windows.h` header, but doesn't seem use it for the `DWORD` type.

##### Used settings

Target: MSVC

**Comment by tritao** [comment]
The error is because you are not including what is necessary in your header file.

Header files should be self-contained, that is, they should include whatever is necessary for them to be fully parsed.

In your case, you should either include `framework.h` or `pch.h` in your header files.

**Comment by IIFE** [comment]
@tritao Hi. Yes I'm aware the cause of the error is because the precompiled header is not included in the parsed header file. My issue is why the types from precompiled headers are not picked up by CppSharp?

It's normal C++ practice to only include precompiled headers in the source file, **not** the header file. In fact Visual Studio will produce a compilation error if you attempt to include a precompiled header in a the header file, rather than the source one.

If it's a requirement for CppSharp to have precompiled headers included in the header files, then I think this makes CppSharp extremely limited, or even unusable. Your suggestion is transforming normal C++ code to work with CppSharp, rather than allowing CppSharp to support precompiled headers use.

**Comment by tritao** [comment]
Precompiled headers are usually just for compilation, not really used for consumption of external headers.

CppSharp does not require any precompiled headers included in header files, it only requires that your header files include the types that they actually need, like a regular C++ compiled would.

You can still use precompiled headers in your source files, and the compiler will skip the "extra" headers included due to directives like `#pragma once`.

Your code is not normal/well-formed C++, you are just relying on a "hack", the fact that the precompiled headers are included by the compiler and assuming that's what normal code looks like.

So I suggest you just fix your code, its way easier than adding some sort of precompiled header feature to CppSharp.

My suggestion is for you to write actual well formed

**Comment by IIFE** [comment]
> CppSharp does not require any precompiled headers included in header files, it only requires that your header files include the types that they actually need, like a regular C++ compiler would.

Visual Studio compiler does not required header files to include all types they need. This is exactly how precompiled headers work.

> You can still use precompiled headers in your source files, and the compiler will skip the "extra" headers included due to directives like #pragma once.

Not really a good practice even if #prgama once causes the skip. This is just duplication and a hack really.

> Your code is not normal/well-formed C++, you are just relying on a "hack", the fact that the precompiled headers are included by the compiler and assuming that's what normal code looks like.

I'm afraid I disagree. This is the way precompiled headers are used for application development on Windows. I have yet to see C++ source compiled under Visual Studio with precompiled headers, where precompiled headers are included in the header files.

> So I suggest you just fix your code, its way easier than adding some sort of precompiled header feature to CppSharp.

Unrealistic requirement for **very** large application code bases that rely on the Visual Studio mechanism of using precompiled headers.

If the issue won't be looked at, then it might be worth flagging this issue in the documentation, because as it stands CppSharp cannot be used on code bases that rely on precompiled headers.

Thanks.

**Comment by tritao** [comment]
> Visual Studio compiler does not require header files to include all types they need. This is exactly how precompiled headers work.
> 
> >

Like I said previously, precompiled headers are for compilation, not for consumption of external headers. CppSharp uses external headers, so precompiled headers are not really applicable.

> Not really a good practice even if #prgama once causes the skip. This is just duplication and a hack really.
> 
> >

How is it not a good practice? It's how pretty much all C/C++ libraries work, headers need to include what they use...

> Unrealistic requirement for **very** large application code bases that rely on the Visual Studio mechanism of using precompiled headers.

As a workaround, you can try to pass the `.cpp` files directly to CppSharp, that might work.

Alternatively, we use Clang as a frontend, so you can try to use their precompiled headers feature, by passing some custom arguments via the parser options:
https://stackoverflow.com/questions/28868049/decrease-clang-compile-time-with-precompiled-headers

> If the issue won't be looked at, then it might be worth flagging this issue in the documentation, because as it stands CppSharp cannot be used on code bases that rely on precompiled headers.

We're not against support it, feel free to send us a patch and we'll happily merge it.

**Comment by IIFE** [comment]
> Like I said previously, precompiled headers are for compilation, not for consumption of external headers. CppSharp uses external headers, so precompiled headers are not really applicable.

If that's the case this should be pointed out in the documentation/limitation sections because it's a major stopper for large code bases that make use of precompiled headers. Saves times.

> How is it not a good practice? It's how pretty much all C/C++ libraries work, headers need to include what they use...

Not really the case for **_all_** C++ development. Forward declarations and precompiled headers don't require headers to include what they use and allow those to be only included in the source files. Also library development != application development.

> As a workaround, you can try to pass the .cpp files directly to CppSharp, that might work.

Haven't tried it yet. Will try it but can foresee it causing more issues (i.e. code gets generated for things not intended for code generation).

> We're not against support it, feel free to send us a patch and we'll happily merge it.

Unfortunately don't have time given my work commitments. Is this repo not being actively maintained by a dedicated team?

Thanks.

**Comment by travnick** [comment]
@IIFE I'm not going to be as polite as @tritao is, but I hope it will help with your project and will save you a lot of time and headaches:

Sorry for saying that, but You've got the whole pch idea wrong: https://docs.microsoft.com/pl-pl/cpp/build/creating-precompiled-header-files?view=msvc-160
`The purpose of the file is to speed up the build process.` - it's the *only* purpose.

So if you are using it to put there all includes and do not bother about them in each header file, then you are shooting in your own foot. Sorry!
You are going to have a hard time when trying to share the code, refactor or use the tool like CppSharp.
Unfortunately the only thing is broken is the code you've created without providing required includes in the headers.

If you don't believe me then simply take a look at any properly written library like boost, Qt, std.
The pch *does not exist* in the public interface at all, so everything should compile *without* this feature - it's only for compilation speed up.
