### ISSUE TITLE
Constructor taking LPCSTR (i.e const char*) no imported correctly

### ISSUE THREAD

**Issue by IIFE** [mono/CppSharp#1256]
##### Brief Description
Please refer to [this repo](https://github.com/IIFE/CppSharpTest) for a reproducible example. If you build and run the app you'll get the issue faced.

I have a simple class with one constructor that takes a `LPCSTR` (typedef for `const char*`) param, and has a member of the same type.

The member generation is fine, however the constructor generation is incorrect. The constructor is imported as:
`internal static extern global::System.IntPtr ctor(global::System.IntPtr __instance, global::System.IntPtr lpsz);`

With the generated C# equivalent looking like:
```
        public Consumer(string lpsz)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::CppSharpTestNative.dll.Consumer.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            __Internal.ctor((__Instance + __PointerAdjustment), lpsz);
        }
```

The last line is failing because the imported signature is expecting an `IntPtr`, but the generated class is using a `System.String`.

Is there a way to generate the import signature with the correct type, or modify the generated code to correctly convert to and from `LPCSTR`.

The `LPCSTR` member is generated fine with the correct marshaling:
```
        public string MLpsz
        {
            get
            {
                return Marshal.PtrToStringAnsi(((global::CppSharpTestNative.dll.Consumer.__Internal*) __Instance)->m_lpsz);
            }

            set
            {
                ((global::CppSharpTestNative.dll.Consumer.__Internal*)__Instance)->m_lpsz = (global::System.IntPtr) Marshal.StringToHGlobalAnsi(value);
            }
        }
```

The constructor however is not.

Thanks.

OS: Windows

Target: MSVC

**Comment by tritao** [comment]
Thanks for the sample, it needs to be fixed.

**Comment by ddobrev** [comment]
@IIFE the project you've linked is the binding itself rather than its generator. Regardless, I wrote my own test and I can no longer reproduce this, it's been apparently fixed somewhere along the way. Please reopen if you encounter it again.
