### ISSUE TITLE
Usage of a const char* now incorrectly takes address

### ISSUE THREAD

**Issue by xsacha** [mono/CppSharp#1258]
##### Brief Description

Previously I had been using CppSharp 0.8.23. After upgrading to 0.10.1, I noticed this bug:

This is the diff in generation after updating:
```diff
        public static string UUIDToChar(global::System.Guid uid, char* str, ulong len)
        {
            var __arg0 = iFaceRec.FixGuid(uid);
-            var __arg1 = (sbyte*) str;
+            var __arg1 = (sbyte*) &str;
            var __ret = __Internal.UUIDToChar(__arg0, __arg1, len);
            return __ret;
        }
```

Original function prototype is:
```C
extern const char *ifr_UUIDToChar(IFR_UUID uid, char *str, size_t len);
```
I also apply a rename to IFR_UUID with a FixGUID, which I don't think is relevant here because this affects the char*. If you need info about the IFR_UUID type, please mention this.

OS: Windows

##### Used headers

string.h

##### Used settings

Target: MSVC 2017

**Comment by tritao** [comment]
@ddobrev Could you check this regression?

**Comment by ddobrev** [comment]
@tritao I have no time this month, I'm afraid. However, the test case is excellent – thank you, @xsacha .
