### ISSUE TITLE
Problem generating correct Entrypoint for method.

### ISSUE THREAD

**Issue by polar** [mono/CppSharp#1260]
I'm using templates on Linux, using the CLI.exe to generate C# and the correct -Symbols.cpp files. I added the following to the `CppCharp.Generator#Setup(Driver)` method:
   
            driver.Options.GenerateClassTemplates = true;

My simple class:

```
#include <string>
class Example
{
public:
  Example() {};
  void print(std::string &x);
};
```
I use the following command:
```
mono --debug ~/src/CppSharp/build/gmake/lib/Release_x64/CppSharp.CLI.exe -ax64  -o=build/cppsharp Example.hpp Example.cpp
```
This problem is that the following lines get generated in the `cppsharp.cs` file:

```
[SuppressUnmanagedCodeSecurity]
[DllImport("cppsharp", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
   EntryPoint="_ZN7Example5printERSs")]
internal static extern void print(global::System.IntPtr __instance, global::System.IntPtr x);
```

The **actual** entry point to this function in the` libcppsharp.so` file is 
`_ZN7Example5printERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`. 

Changing the `_ZN7Example5printERSs` in the `cppsharp.cs` file to the above value rectifies this problem.

Is there a way to get this entry point to generate correctly?

**Comment by tritao** [comment]
@ddobrev Any idea about this?

**Comment by polar** [comment]
I imagine finding the mangled name has to be done by types somewhere. I imagine "RSs" meaning "Reference to Standard string", but as @ddobrev mentioned,  `std::string` is defined as `std::basic_string<char, std::allocator<char>>` on all platforms.

I added another `std::string`` parameter:
```
   print(std::string &x, std::string &y);
```
and corresponding mangled names are:
```_ZN7Example5printERSsS0_```
and the correct one is:
```_ZN7Example5printERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_```
.

**Comment by tritao** [comment]
@polar If you run `nm` on the native library, does `_ZN7Example5printERSsS0_`  show up as a symbol?

**Comment by polar** [comment]
No, it does not. 
```$ nm cmake-build-debug/libcppsharp.so  | grep Example
0000000000000e11 T Example_Example
0000000000000e65 T Example__Example
0000000000000e3e T Example_Example___1__S_Example
0000000000000daa T _ZN7Example5printERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_
0000000000000f20 W _ZN7ExampleaSEOS_
0000000000000f0e W _ZN7ExampleaSERKS_
0000000000000f02 W _ZN7ExampleC1Ev
0000000000000f02 W _ZN7ExampleC2Ev
```

**Comment by polar** [comment]
I don't really know why. It seems that std::string is supposed to mangle to "Ss". 
Maybe I have a bad option in compiling these?

**Comment by polar** [comment]
I have compiled Example.cpp with c++, g++, and clang++ with absolutely no options, and I get the same complicated mangled name for print.

**Comment by polar** [comment]
Never mind. I needed "--c++11" in the flags, which got the proper ABI configured for the parser.
