### ISSUE TITLE
CppSharp assemblies don't have versions

### ISSUE THREAD

**Issue by IIFE** [mono/CppSharp#1262]
##### Brief Description
Hi,

When using the CppSharp libs through NuGet, looking at the assemblies files properties it appears that the version is always set as 0.0.0.0. Any good reason for that behaviour?

Also, is there an available build pipeline that someone can use to create a test release/artifact of CppSharp when making changes, rather than building it locally?

Thanks.

**Comment by tritao** [comment]
This is implemented now, thanks to @josetr.
