### ISSUE TITLE
GenerateEnumFromMacros generates enum with zeros for hex numbers

### ISSUE THREAD

**Issue by Ghasan** [mono/CppSharp#1264]
##### Brief Description

`GenerateEnumFromMacros` return enum with zeros for macros that defines hex numbers with numeric suffix such as `#define MY_NUMBER 0xFFU`.

OS: All

##### Used headers

[fribidi.h](https://github.com/fribidi/fribidi)

##### Used settings

Target: MSVC/GCC/Clang

**Comment by Ghasan** [comment]
Submitting a fix soon

**Comment by ddobrev** [comment]
@Ghasan thank you very much, we do welcome any help. Please just make sure to add a test too so that we don't regress in the future.

**Comment by Ghasan** [comment]
@ddobrev Thanks :) I am not sure where to add the tests, could you please let me know where to add them. Could not find a tests file for Library.cs.

**Comment by ddobrev** [comment]
@Ghasan our tests consist of adding offending C++ code and then checking if it's properly mapped. You could take a look at one of our test projects, such as Common. Please, however, do not add a new commit to your PR but rather amend and force push.
