### ISSUE TITLE
clang does not see includes in format <dir>/header.h

### ISSUE THREAD

**Issue by QuantumDeveloper** [mono/CppSharp#1271]
I have kind of a question here. I dont know how to ask original clang developers about this, so I decided maybe you guys know the answer.

Often I seen such situation: I have headers in path: `M:\GitHUB\LLVM\llvm-project\clang\include\clang-c` and header files contains include in format` #include "clang-c/Index.h"` So, clang seems looking for folder clang-c inside clang-c and didnt find it because there is no such folder.

I tried to set include path by `-IM:\GitHUB\LLVM\llvm-project\clang\include\clang-c, -I., -I../clang, -iM:\GitHUB\LLVM\llvm-project\clang\include\clang-c` and all I could find, but nothing works - clang just dont see includes.

Obviously I am missing something, but I dont understand what exactly.

I think you faced with such issues. How did you resolve them?

**Comment by tritao** [comment]
Hello Denis,

Have you tried setting an include path to `-IM:\GitHUB\LLVM\llvm-project\clang\include`?

**Comment by QuantumDeveloper** [comment]
Hi,

Issue is that `Index.h` is located inside `M:\GitHUB\LLVM\llvm-project\clang\include\clang`
And inside `Index.h` includes is like:
`#import "clang/Documents.h"`
`#import "clang/etc.h"`
And issue here is that clang is now inside `M:\GitHUB\LLVM\llvm-project\clang\include\clang` and tries to find headers inside that directory, but should find on one level upper.

**Comment by tritao** [comment]
Looks to me like if you add `M:\GitHUB\LLVM\llvm-project\clang\include` as an  include folder then those headers should be found.

Closing this for now, re-open if still an issue.

**Comment by QuantumDeveloper** [comment]
@tritao Thanks for your help. This seems to be correct answer!
