### ISSUE TITLE
Missing LLVM packages for 815d4b revision

### ISSUE THREAD

**Issue by polar** [mono/CppSharp#1290]
Could be a temporary problem. Or some sort of the Github site changed.

The premake script fails because of a bad Github URL. This process worked a few days ago. 

```
~/src/CppSharp/build$ ./premake5-linux-64 --file=scripts/LLVM.lua download_llvm
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-815d4b-linux-x64-gcc-7-Release.tar.xz

Error: /home/polar/src/CppSharp/build/scripts/Utils.lua:98: HTTP response code said error
The requested URL returned error: 404 Not Found

```

**Comment by tritao** [comment]
I'm guessing @ddobrev deleted some previous LLVM packages when updating to the most recent LLVM this week.

**Comment by befedo** [comment]
Same here, there's nothing LLVM related on the release page. Is anyone into that?

**Comment by ddobrev** [comment]
@tritao I did. @befedo @polar we don't like keeping too old packages around because we don't want to encourage people to keep using old versions. Is there anything preventing you from using our newer code?

**Comment by polar** [comment]
@ddobrev Yes, for now. I have a branch on my own fork with "enhancements" to do specific things, like address the generic use of std::vector<T> and other classes specific templates to my application. I just don't yet have the time to merge your master back into it yet and check to see if it works. :) I'll get around to it eventually, but right now I've got other fires to address.

**Comment by ddobrev** [comment]
@polar I understand. I might have some of the packages lying around so I'll try finding them tomorrow. This way the build will be restored.
Could you please tell more about your support for `std::vector<T>`. We intend to support it ourselves, we already support templates and we just need to generate convenient wrappers for it. I would be curious to compare our approach to yours.

**Comment by tritao** [comment]
@befedo You need to go to the last page of releases to find the LLVM packages: https://github.com/mono/CppSharp/releases/tag/CppSharp

Sorry for the breakage, we certainly don't want to break folk who are still using earlier versions. I've discussed with @ddobrev and we will make sure going forward we will do a better job of keeping earlier versions around.

I've also restored the macOS version package `llvm-815d4b-macosx-x64-Release.tar.xz` that I had still on my local machine.

**Comment by ddobrev** [comment]
@polar I've restored the Linux package, let me know if it fails to work.

**Comment by befedo** [comment]
@tritao Thanks for the hint ...
In the meantime I've build LLVM from source, and all CppSharp test went through.

Thanks for your time and best regards,
Befedo
