### ISSUE TITLE
Method called Get() causes IndexOutOfRangeException

### ISSUE THREAD

**Issue by JPorter812** [mono/CppSharp#1291]
##### Brief Description

If I parse a header file with a method called Get(), this throws an IndexOutOfRangeException in the GetterSetterToPropertyPass. since it tries to access name[3]. 

![image](https://user-images.githubusercontent.com/26573452/75367075-a04ece00-58b7-11ea-90b9-00bd59d61017.png)
![image](https://user-images.githubusercontent.com/26573452/75367181-cf653f80-58b7-11ea-96ac-a8786711a14f.png)

OS: Windows

##### Used headers

myheader.h

Class myclass
{
public: 

int Get() const {return 3;};

}

##### Used settings

driver.Options.DryRun = true; 
No passes added. 

##### Stack trace or incompilable generated code

>	CppSharp.Generator.dll!CppSharp.Passes.GetterSetterToPropertyPass.PropertyGenerator.GetPropertyName(string name) Line 244	C#
 	CppSharp.Generator.dll!CppSharp.Passes.GetterSetterToPropertyPass.PropertyGenerator.GetReadWritePropertyName(CppSharp.AST.INamedDecl getter, string afterSet) Line 156	C#
 	CppSharp.Generator.dll!CppSharp.Passes.GetterSetterToPropertyPass.PropertyGenerator.GenerateProperties(System.Collections.Generic.IEnumerable<CppSharp.AST.Method> settersToUse, bool readOnly) Line 106	C#
 	CppSharp.Generator.dll!CppSharp.Passes.GetterSetterToPropertyPass.PropertyGenerator.GenerateProperties() Line 87	C#
 	CppSharp.Generator.dll!CppSharp.Passes.GetterSetterToPropertyPass.VisitClassDecl(CppSharp.AST.Class class) Line 66	C#
 	CppSharp.AST.dll!CppSharp.AST.Class.Visit<bool>(CppSharp.AST.IDeclVisitor<bool> visitor) Line 224	C#
 	CppSharp.AST.dll!CppSharp.AST.AstVisitor.VisitDeclarationContext(CppSharp.AST.DeclarationContext context) Line 439	C#
 	CppSharp.Generator.dll!CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(CppSharp.AST.TranslationUnit unit) Line 56	C#
 	CppSharp.Generator.dll!CppSharp.Passes.TranslationUnitPass.VisitASTContext(CppSharp.AST.ASTContext context) Line 46	C#
 	CppSharp.Generator.dll!CppSharp.Generators.BindingContext.RunPasses.AnonymousMethod__29_0(CppSharp.Passes.TranslationUnitPass pass) Line 49	C#
 	CppSharp.Generator.dll!CppSharp.PassBuilder<CppSharp.Passes.TranslationUnitPass>.RunPasses(System.Action<CppSharp.Passes.TranslationUnitPass> action) Line 42	C#
 	CppSharp.Generator.dll!CppSharp.Generators.BindingContext.RunPasses() Line 44	C#
 	CppSharp.Generator.dll!CppSharp.Driver.ProcessCode() Line 263	C#
 	CppSharp.Generator.dll!CppSharp.ConsoleDriver.Run(CppSharp.ILibrary library) Line 47	C#
 	FirmwareInterfacer.ConsoleApp.exe!FirmwareInterfacer.ConsoleApp.Program.Main(string[] args) Line 68	C#

**Comment by ddobrev** [comment]
@JPorter812 thank you for your excellent report along with a test case. I would actually encourage you to send a PR because you're now just a step away.
