### ISSUE TITLE
Missing llvm-80c3ea-windows-vs2019-x64-RelWithDebInfo.7z

### ISSUE THREAD

**Issue by Tennyleaz** [mono/CppSharp#1293]
##### Brief Description

Tried following the steps in readme, in the first step "Setting up LLVM and Clang dependencies"
I did:

```
C:\Workspace\CppSharp-master\build>DownloadDeps.bat
```
Then I see this error:
```
C:\Workspace\CppSharp-master\build>"premake5" --file=scripts/LLVM.lua download_llvm
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-80c3ea-windows-vs2019-x64-RelWithDebInfo.7z
Error: .../CppSharp-master/build/scripts/Utils.lua:98: HTTP response code said error
The requested URL returned error: 404 Not Found

C:\Workspace\CppSharp-master\build>goto quit
```

OS: Windows 10 64bit
Visual Studio Community 2019

**Comment by tritao** [comment]
Related to https://github.com/mono/CppSharp/issues/1290.

**Comment by tritao** [comment]
@Tennyleaz You can get the VS2017 package and rename it for now from: https://github.com/mono/CppSharp/releases/tag/CppSharp
