### ISSUE TITLE
PR for multiple bug fixes

### ISSUE THREAD

**Issue by IIFE** [mono/CppSharp#1308]
Hi,

This is more of a question than an issue.

We've evaluated CppSharp for a use case. During the evaluation we needed to make some fixes to CppSharp itself to cater for some of the use cases we have. They are generic fixes and not specific to us.

What is the best way of doing a PR for the fixes? Should I do a PR for each fix separately, or one PR that contains all fixes?

Thanks.

**Comment by ddobrev** [comment]
A PR per fix is the correct way because thus it's much easier to amend the commit after any remarks.

**Comment by IIFE** [comment]
OK thanks, I'll start creating the PRs.
