### ISSUE TITLE
Questions about Example

### ISSUE THREAD

**Issue by Deusald** [mono/CppSharp#1336]
Hi,
I've just started to play around with CppSharp. I'm trying to make the example working:
https://github.com/mono/CppSharp/blob/master/docs/GeneratingBindings.md
I've created smaple dll project in c++, created all filed, build the dll. Created the generator project. Generated the C# classes. But when I want to use thoose methods I got an exception:
`Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry
 point named '?FooAdd@@YAHPEAVFoo@@@Z' in DLL 'Sample'.
   at Sample.Foo.__Internal.FooAdd(IntPtr foo)
   at Sample.Foo.FooAdd(Foo foo) in C:\Users\AdamR\Desktop\Test\Ge

nerateBindings
\GenerateBindings\Generated\Foo.cs:line 107
   at GenerateBindings.Program.Main(String[] args) in C:\Users\AdamR\Desktop\Tes
t\GenerateBindings\GenerateBindings\Program.cs:line 18
`
What am I doing wrong? And what I need to adjust in those projects to make it work?
Here are my project files:
https://www.dropbox.com/s/w9rnsrbv6v2y2do/CppSharp.zip?dl=0

For what purpose is the generated file "Sample-symbols.cpp"?
I tried to add before method the __declspec(dllexport) wrapped with extern c but I still got the same error.

**Comment by tritao** [comment]
Hey @Deusald, it might be the `extern "C"`, that causes exports to have a simple C mangling, yet it seems the generated bindings are using C++ mangled names.

**Comment by Deusald** [comment]
@tritao I've tried to generate and have compiled dll with and without extern "C" and __declspec(dllexport). In both cases I got the same error as above. The error occurs also if I put the Add method without arguments inside the Foo class. So I can't figure out how it should be done :(

**Comment by tritao** [comment]
I recommend you use https://www.nirsoft.net/utils/dll_export_viewer.html or `dumpbin` to check the exports of your DLL.

That will help you troubleshoot where the issue might lie.

The problem might be because of 32/64-bit differences.

Do something like:

 `parserOptions.TargetTriple = "x86_64-pc-win32-msvc";`

When setting the parser up for targeting the 64-bit MSVC ABI.
