### ISSUE TITLE
[Question] What is the purpose of the std-generated.cpp file?

### ISSUE THREAD

**Issue by StephenHodgson** [mono/CppSharp#1348]
##### Brief Description

What is the purpose of the `std-generated.cpp` file?

**Comment by ddobrev** [comment]
@StephenHodgson for interop with `std::string` and, in the future, other system templates. The latter need compiled symbols to call which aren't available in `STD` itself as C++ is a compiled language and specializations of templates are created as necessary.

**Comment by StephenHodgson** [comment]
What about the `genterated-symbols.cpp` file?

**Comment by ddobrev** [comment]
@StephenHodgson it's the same but for templates (and inlines) in the bound library itself.

**Comment by StephenHodgson** [comment]
So to use the C# bindings I need to call into the native library I compile using the generated cpp files, correct?

**Comment by ddobrev** [comment]
@StephenHodgson you would need it in addition to the original native library. The generated `C++` only contains symbols missing in the original library, not all of them.

**Comment by StephenHodgson** [comment]
I noticed all the DllImports for the generated c# only point a dll that doesn't exist. (I'm guessing if I add in compile into the options it'll generate one for me?)

Do those DllImport calls need to be updated to use the original or the interop, and if so, why doesn't the generated bindings automatically reference the original library?
