### ISSUE TITLE
Creating alpha NuGet release on succesful merge into master

### ISSUE THREAD

**Issue by IIFE** [mono/CppSharp#1356]
Hi,

This is more a suggestion than a question/issue.

Currently NuGet releases are only done periodically when there are several merges that go into master.

This causes delay in consuming important fixes if a NuGet release is not done once a fix goes in master.

One suggestion I have is to publish an alpha version NuGet release on every successful merge into master. I believe this can be done using the AppVeyor CI?

This means that consumers needing important fixes can get them through NuGet once they're available in master.

The latest alpha release can then be promoted to the main NuGet release once you feel it's appropeiate to do so.

Any thoughts?

**Comment by tritao** [comment]
Thanks for the suggestion, we definitely want to publish a package for every CI build.

We don't want to use any CI-specific features but implement a NuGet packaging script, like was done on Embeddinator: https://github.com/mono/Embeddinator-4000/blob/master/build/Packaging.cake

We just have not gotten to it yet, is this something you could help with?

**Comment by IIFE** [comment]
@tritao Potentially. Do you have an existing script you use to publish NuGet packages, or how do you publish them at the minute? Is it not a matter of running whatever you are doing now within the AppVeyor CI?

**Comment by tritao** [comment]
@IIFE At the moment we have no packaging script, @ddobrev does the releases manually.

**Comment by IIFE** [comment]
@tritao If it's a matter of using the same script from Embeddinator but changing the argument values for the Create-Package and Publish-Package tasks (don't think Build-ObjC is needed) then I can possibly look into it. I'm not familiar with Cake, so it'll reusing the example script and changing arguments.

**Comment by IIFE** [comment]
@tritao There also appears to be an existing preliminary nuget script in this repo with some TODOs. Why not start from there?

**Comment by tritao** [comment]
@IIFE Good find, I had forgotten about it, makes sense to start from it.

Let me know if you have any questions.

**Comment by tritao** [comment]
This is done now, https://github.com/mono/CppSharp/packages/

**Comment by hellozyemlya** [comment]
A quick question here - what URL I need to enter in nuget config in order to get latest builds?
