### ISSUE TITLE
FieldOffset is incorrect, windows.

### ISSUE THREAD

**Issue by polar** [mono/CppSharp#1365]
##### Brief Description

The field offset is wrong for the Windows compiler for std::string when placed in structures.

This is only windows, but I've only run the vs2019 compiler. 

On windows the std::string has the size of 32, so one would think that 
consecutive strings would have FieldOffsets multiples of 32. On Windows, I find that they are 40 bytes apart. I've created a the following structure:

```
struct Test { std::string item1; std::string item2; std::string item3; }
```
As expected, it generates the following:
```
[FieldOffset(0)]
internal global::std.basic_string.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C item1;

[FieldOffset(32)]
internal global::std.basic_string.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C item2;

[FieldOffset(64)]
internal global::std.basic_string.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C item3;
```

However, I find that these items on the C++ side are 40 bytes apart. That is, in the struct Test:
```
(int) (&item1 - this) == 0
(int) (&item2 - this) == 40
(int) (&item3 - this) == 80
```
Obviously this screws things up. 

So, in an effort to see if this is the case, if I manually edit my generated file and change the above FieldOffsets, to 0, 40, 80, respectively, and recompile. It works. 

Am I  doing something **wrong**? Am I missing a pointer alignment option somewhere? 

There may also be another related problem:
The content of an std::basic_string.__Internal is generated as:
```
[StructLayout(LayoutKind.Explicit, Size = 32)]
 public unsafe partial struct __Internalc__N_std_S__String_val____N_std_S__Simple_types__C
 {
    [FieldOffset(0)]
     internal global::Std.StringVal.Bxty.__Internal _Bx;

    [FieldOffset(16)]
    internal ulong _Mysize;

    [FieldOffset(24)]
    internal ulong _Myres;
}
```
However, if I try to use these elements, the FieldOffsets are wrong. Unless I'm doing something wrong they are actually:
```
[StructLayout(LayoutKind.Explicit, Size = 32)]
public unsafe partial struct __Internalc__N_std_S__String_val____N_std_S__Simple_types__C
{
    [FieldOffset(8)]
    internal global::std._String_val._Bxty.__Internal _Bx;

    [FieldOffset(24)]
    internal ulong _Mysize;

    [FieldOffset(0)]
    internal ulong _Myres;
 }
```
I don't know why. However, when I manually change the above in the Std.cs file I can generate the correct string from the __Internal, __ret using the following:
```
return (((int) __ret._Mypair._Myval2._Mysize) > 15 ? global::System.Text.Encoding.UTF8.GetString((byte*) __ret._Mypair._Myval2._Bx._Ptr, (int) __ret._Mypair._Myval2._Mysize) : global::System.Text.Encoding.UTF8.GetString((byte*) __ret._Mypair._Myval2._Bx._Buf, (int) __ret._Mypair._Myval2._Mysize));

```
Otherwise, it is wrong. 
Although I know you defer to the stringExtension.data() to actually get the result of the call to _Mypair._Myval2._MyPtr() on the C++ side. However, I was playing around to make sure things were working correctly. I use this method on the Linux side without a problem. The FieldOffsets are correct for GCC.

**Comment by tritao** [comment]
Can you post the command line invocation for MSVC (`cl.exe`) for the source files that have these 40-byte offsets?

Tried a quick and dirty test (https://rextester.com/l/cpp_online_compiler_visual) and I get 32-byte offsets between subsequent strings.

```cpp
#include <string>
struct S {
    std::string s0, s1, s2;
};
int main(void) {
    S s;
    printf("%zd %zd %zd\n", offsetof(S, s0), offsetof(S, s1), offsetof(S, s2));
}
```

Output: `0 32 64`

**Comment by polar** [comment]
Strangely enough, I get
Output: 0 28 56

**Comment by polar** [comment]
I should note that I am using a version from a while back. I am not using the current master, due to the issue I had with the TypeMaps, but after merging again I have some NullPointer exceptions I've been getting.  Also, I'm not doing this Test structure in isolation. It's part of a much larger project, generating 64K lines of code. I added it to see what is going wrong on Windows, while Linux works. 

I should try to set up a complete isolated example to see what is happening.

**Comment by polar** [comment]
I have a repository that illustrates the problem, if you would like to look at it. 

As always setting one of these projects up is a nightmare, but I believe I made it somewhat easy and thorough, at least with some executable Ruby/Rake. At least it's an executable specification.

https://github.com/polar/CppSharpTest

It builds and runs on both Linux  and and Windows using vs2019 tools. The Readme should take you though it. Please feel free to tell me what I'm doing wrong. I'd like to know. 

Windows is the bane of my existence!

**Comment by polar** [comment]
There seems to be a difference with building through CMake and using the VS2019 IDE in pure Visual C++ form. 

If I build with CMake, the size of std::string is 40. This case is also valid for using VS2019 IDE to run the cmake project.
 
However, if I build with a purely generated VS2019 project, the size of std::string is 28. 

In either case, that would not match the 32 that is coming from CppSharp. 

What is going on with Windoze? Ugg...

**Comment by tritao** [comment]
Hey, haven't had the time to go through your test yet.

Anyway: could you figure out the difference in parameters that are being passed to the compiler driver in each case (https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2019).

That is likely to be the missing explanation for the different offsets. My guess would be that there's different runtime options (i.e. `/MT` vs `/MD`) or debug/release modes.

**Comment by polar** [comment]
Thanks, I think it's actually the Release/Debug thing. 

Actually, the 28 number comes from x86 vs 40 for x64. That makes sense there. 

However, I've been able to compile the pure VS2019 version with **Release** and it comes out as 32. So, that seems to be the issue here.

This is important and a pain, because it means that you cannot cross pollinate shared libraries. I have to make sure that I have a Release and a Debug version of everything all the way down the line!

Really? Ugg.

So, how do I direct CppSharp to generate a Debug version so I can get the `sizeof(std::string)==40`? 
Is it simply a -DDEBUG flag?

**Comment by polar** [comment]
I had thought I needed to pass a CFLAGS option such as --A=" /D_DEBUG ". That did not work.

It's not actually a CLang option that matters, It's a preprocessor option for CppSharp's processing of the intended header files. 

So it's just plain -D_DEBUG (note, the underbar) to the CppSharp.CLI.exe.

That seems to work! 

Thanks for the hints and the extra eyes.
