### ISSUE TITLE
int* parameters as ref IntPtr

### ISSUE THREAD

**Issue by jbhunter52** [mono/CppSharp#1372]
I am having troubles with getting bindings to take handle int* parameters as ref IntPtr.  Any suggestions?

I have read through the manuals, but I have to admit I am a bit lost.  There is a large number of functions with the same logic as below so this would be a big help.  

From the header file the signature looks like this.  Focusing on the second argument of this function...
`int EIB7Open(unsigned long ip, int *eib, long timeout, char *ident, unsigned long len);`

The binding looks like this
```
public static global::EIB7.EIB7ERR EIB7Open(uint ip, ref int eib, int timeout, sbyte* ident, uint len)
{
    fixed (int* __eib1 = &eib)
    {
        var __arg1 = __eib1;
        var __ret = __Internal.EIB7Open(ip, __arg1, timeout, ident, len);
        return __ret;
    }
}

[SuppressUnmanagedCodeSecurity]
[DllImport("EIB7", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,EntryPoint="EIB7Open")]
internal static extern global::EIB7.EIB7ERR EIB7Open(uint ip, int* eib, int timeout, sbyte* ident, uint len);
```

My c++ library is giving me back an error, "Invalid Handle".  However if I change the above generated bindings to the below it works.

```
public static global::EIB7.EIB7ERR EIB7Open(uint ip, ref IntPtr eib, int timeout, sbyte* ident, uint len)
{
     var __ret = __Internal.EIB7Open(ip, ref eib, timeout, ident, len);
     return __ret;
}

[SuppressUnmanagedCodeSecurity]
[DllImport("EIB7", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, EntryPoint="EIB7Open")]
internal static extern global::EIB7.EIB7ERR EIB7Open(uint ip, ref IntPtr eib, int timeout, sbyte* ident, uint len);
```

**Comment by ddobrev** [comment]
@jbhunter52 thank you for your report. It's quite puzzling because this functionality is deliberate and tested. Would you be able to reproduce it in our tests?

**Comment by tritao** [comment]
@jbhunter52 Are the other parameters after `eib` correct, even when you get `Invalid handle`? I wonder if its a 32/64-bit issue.

Even if `IntPtr` is working for you in this particular case, I don't think it would be the most correct binding, because it size changes depending on 32-bit/64-bit runtime, while `int` in C++ is always 32-bit (see https://en.cppreference.com/w/cpp/language/types).

**Comment by jbhunter52** [comment]
ddobrev, I am not sure I understand what functionality is deliberate, the use of "ref int"?  What should I try to reproduce?

tritao, I am compiling the c# code as AnyCpu.  I do have access to a 32 and 64-bit compiled library.  So far I have only been using the 32-bit library.

**Comment by ddobrev** [comment]
@jbhunter52 I meant that our representation of primitive pointers (`int*` in this case) as `ref int` isn't accidental but deliberate. For reproduction I was thinking about adding our function inn our test headers and then call it from our unit tests to see if you get the same incorrect behaviour.

**Comment by tritao** [comment]
It would help if you can put a breakpoint in the native function, and see what gets passed by CppSharp to the native side in the ref parameter.

**Comment by jbhunter52** [comment]
Unfortunately I only have the headers, so I could not debug the native side.

I have switched to the 64-bit library and reverted back to the previous code (bindings as generated) and it is working.  I am not having any problems now, no Invalid Handle error.  I am not sure I completely understood the issue, but glad to see this working.  I am making small strides understanding how to work between the unmanaged/managed code.  And this project has been a big help.  Thanks!

If I can figure out what exactly was going on I will report back.

**Comment by tritao** [comment]
By the way, are you are using the same generated binding for both the 32-bit and 64-bit? 

If so that is not recommended as it can cause problems, you should generate separate versions, changing the target triple passed to CppSharp.
