### ISSUE TITLE
Generating .NET interfaces for generated C++/CLI classes.

### ISSUE THREAD

**Issue by IIFE** [mono/CppSharp#1374]
Hi,

This is more of a question than an issue.

One of the things I want to achieve with the generated C++/CLI code is expose an interface for each of the generated class, which is useful for dependency injection/mocking.

I was thinking that a translation unit pass can be leveraged to do so. What would be the best way of approaching this problem? Is it something worth doing in CppSharp itself?

Thanks.

**Comment by ddobrev** [comment]
@IIFE at present I think it serves specific needs so a custom pass seems to be the better solution. Later on we might decide to adopt it should you be willing to share.
You could take some insight and even code from our pass for multiple inheritance. The main or possibly even the only difference there is that it only generates interfaces for classes used as secondary bases rather than all classes.

**Comment by tritao** [comment]
Like @ddobrev said, you can probably re-use most of the code from https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/MultipleInheritancePass.cs.

Might make sense to generalize this code, and extract it to a separate pass.

**Comment by IIFE** [comment]
@ddobrev @tritao  Thanks. So essentially very similar to the multi inheritance pass, but inside `VisitClassDecl` instead of generating interfaces for secondary bases, I just generate one for the class being visited itself.

**Comment by IIFE** [comment]
@ddobrev @tritao 

Hi both.

I've been trying to reuse the multiple inheritance pass so that I can generate interfaces for the actual class (rather than its bases).

I have only modified `VisitASTContext` and `VisitClassDecl` in the following way (rest of pass stays the same):

```
        public override bool VisitASTContext(ASTContext context)
        {
            bool result = base.VisitASTContext(context);
            foreach (var @interface in interfaces.Where(i => !(i is ClassTemplateSpecialization)))
            {
                int index = @interface.Namespace.Declarations.IndexOf(@interface.OriginalClass);
                @interface.Namespace.Declarations.Insert(index, @interface);
            }

            foreach (Class @class in classesWithSecondaryBases)
            {
                Class @interface = interfaces.FirstOrDefault(iface => iface.OriginalClass == @class);
                if (@interface == null)
                    continue;

                ImplementInterfaceMethods(@class, @interface);
                ImplementInterfaceProperties(@class, @interface);                
            }

            interfaces.Clear();
            classesWithSecondaryBases.Clear();
            return result;
        }

        public override bool VisitClassDecl(Class @class)
        {
            if (!base.VisitClassDecl(@class) || !@class.IsGenerated)
                return false;

            if (@class.IsInterface)
            {
                return false;
            }

            classesWithSecondaryBases.Add(@class);
            GetInterface(@class);

            return true;
        }
```

However, that's not giving me the expected result. I have tested with the following simple native class:
```
class TestInterface
{
public:
    int GetFoo();
};
```

The generated C++/CLI code looks like this:
```
    public ref class ITestInterface
    {
    public:

        ITestInterface(::ITestInterface* native);
        ITestInterface(::ITestInterface* native, bool ownNativeInstance);
        static ITestInterface^ __CreateInstance(::System::IntPtr native);
        static ITestInterface^ __CreateInstance(::System::IntPtr native, bool __ownsNativeInstance);
        property IntPtr __Instance
        {
            IntPtr get();
        }

        property IntPtr __PointerToTestInterface
        {
            IntPtr get();
        }

        property int Foo
        {
            int get();
        }

        void Dispose();
    };

    // DEBUG: class TestInterface
    // DEBUG: {
    // DEBUG: public:
    // DEBUG:     int GetFoo();
    // DEBUG: }
    public ref class TestInterface : ICppInstance
    {
    public:

        property ::TestInterface* NativePtr;
        property System::IntPtr __Instance
        {
            virtual System::IntPtr get();
            virtual void set(System::IntPtr instance);
        }

        TestInterface(::TestInterface* native);
        TestInterface(::TestInterface* native, bool ownNativeInstance);
        static TestInterface^ __CreateInstance(::System::IntPtr native);
        static TestInterface^ __CreateInstance(::System::IntPtr native, bool __ownsNativeInstance);
        // DEBUG: TestInterface
        TestInterface();

        ~TestInterface();

        !TestInterface();

        property IntPtr __PointerToTestInterface
        {
            IntPtr get();
        }

        property IntPtr __PointerToTestInterface
        {
            IntPtr get();
        }

        property int Foo
        {
            int get();
        }

    protected:
        bool __ownsNativeInstance;
    };
```

As you can see the interface part is still getting generated as a class rather than an interface, and it's not being implemented by the actual class.

Any pointers to where I may be going wrong. This is for C++/CLI only, not C#.

Thanks.

**Comment by MattKey95** [comment]
I am also trying to achieve this for the same reason. Would be great to see it added to the project.

**Comment by tritao** [comment]
@IIFE Could you share your pass and/or send a PR?

**Comment by MattKey95** [comment]
I have a pass working with this now for this much like @IIFE 's version, although I did away with the recursion in the VisitClassDecl method. I can create a PR if that would be useful. 

I'm having a small problem where classes that are generated for global C++ in  aren't getting an interface created for them. I tried running the pass in the post process step but it doesn't create interfaces at all then. Sorry if this is obvious, I only found the project yesterday and I'm still trying to wrap my head around it. Thanks.

**Comment by tritao** [comment]
Since this seems to be a common request, I think it would be good to have a builtin pass, so if you can send a PR that would be great.

Abour your issue, it's hard to say what the issue might be, maybe those classes not being generated by the pass are ignored?

Some code and/or a test case reproducing the issue would be great to be able to help.

**Comment by MattKey95** [comment]
https://github.com/mono/CppSharp/pull/1571 Created a PR :) I also have some thoughts about how this works with muti inheritance pass that I commented there.
