### ISSUE TITLE
NuGet: Mismatch between architectures

### ISSUE THREAD

**Issue by PeterDraex** [mono/CppSharp#1378]
##### Brief Description
I'm trying to create wrapper for [a header file](https://github.com/microsoft/webauthn/blob/master/webauthn.h).

1. I create a new console project for .NET Framework 4.7.2 in Visual Studio
2. I install CppSharp NuGet package, version 0.10.4 to my project
3. I get the following warning:
> There was a **mismatch between the processor architecture** of the project being built "MSIL" and the processor architecture of the reference "CppSharp.Generator, Version=0.0.0.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
4. I add `ConsoleDriver.Run(new SampleLibrary());` to `Program.Main()`
5. I start the app and the following exception is thrown:
![image](https://user-images.githubusercontent.com/18402223/84357243-a4340100-abc5-11ea-9c0d-f0290e8831aa.png)

Is there a way to target `Any CPU`, while using the NuGet package?
How can I use the NuGet package?

**Comment by ddobrev** [comment]
@PeterDraex please ensure you've unchecked _Use 32-bit_ in the settings of your executable.

**Comment by PeterDraex** [comment]
@ddobrev Changing the platform target to x64 fixed the issue! (32-bit didn't work)
Thank you.
