### ISSUE TITLE
CppSharp.CppParser.dll Memory access conflict

### ISSUE THREAD

**Issue by Lanch97** [mono/CppSharp#1385]
##### Brief Description
OS: Windows 
##### Used headers

Plan to simply bind Point Cloud Library IO modules,But there is a memory conflict.
I have never used C++,What should I do?

 error message:0xC0000005: An access conflict occurs while reading location 0x0000000000000000.

\ \ \GAC_MSIL\ system. Core\v4.0_4.0.0 / B77A5c561934e089 \ system. core. DLL ".
The load symbol has been skipped.The module is optimized, and the debugger option "My code only" is enabled.
"Consoleapp2.exe" (CLR v4.0.30319: consoleapp2.exe): c: Windows \  Microsoft.net \GAC_MSIL\mscorlib. Resources \ v4.0_4.0.0.0.0 _zh-hans_b77a5c561934e089 \mscorlib.resources.dll The module is generated and contains no symbols.
Exception: "System. AccessViolationException" (located in CppSharp. Parser. CLI. DLL)
"System. AccessViolationException" type of untreated abnormalities in CppSharp. Parser. CLI. DLL
Attempt to read or write to protected memory.This usually indicates that other memory is corrupted.
##### Used settings###
Follow the documentation example:

string pcl_root_path = @"C:\Program Files\PCL1.11.0\";
 string pcl_include_path = pcl_root_path + @"include\pcl-1.11\pcl";
var options = driver.Options;
options.GeneratorKind = GeneratorKind.CSharp;
options.Verbose = true;
var module = options.AddModule("pcl");
module.IncludeDirs.Add(pcl_include_path);
module.IncludeDirs.Add(pcl_include_path);
module.Headers.Add(@"io\pcd_io.h");
module.Headers.Add(@"memory.h"); 
module.Headers.Add(@"type_traits.h");
 module.LibraryDirs.Add(@"C:\Program Files\PCL1.11.0\lib");
module.Libraries.Add("pcl_io.lib")

**Comment by ddobrev** [comment]
@Lanch97 I'm afraid your description of the problem itself is too vague. I could guess it's an issue of architecture, trying to run C++# in a 32-bit process. Ensure to uncheck _Use 32-bit_ in your executable. If it doesn't help, please describe in more detail the error you get.
