### ISSUE TITLE
Build warning in C# bindings generated from c++ code

### ISSUE THREAD

**Issue by upretyrohan** [mono/CppSharp#1387]
##### Brief Description

I get a Build warning  " warning CS0649: Field 'InternalVariableTypeSmall.__PointerAdjustment' is never assigned to, and will always have its default value 0"
in C# bindings generated from c++ code

Is there way we can ignore warnings in generated code, while generating

**Comment by ddobrev** [comment]
They're harmless but we'll try fixing them later on.
