### ISSUE TITLE
Unable to compile CppSharp with VS2017 and precompiled LLVM+Clang

### ISSUE THREAD

**Issue by strentler** [mono/CppSharp#1390]
I tried to compile CppSharp version 0.10.15

I used a dev enviroment for VS2017 x64.

The steps to reproduce are this:

`
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26228.102
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

_

>cd c:\Users\strentler\Downloads\CppSharp-0.10.5\build

_

>premake5 --file=scripts/LLVM.lua download_llvm

__

>GenerateProjects.bat

Selected Visual Studio 2017

__

>msbuild vs2017\CppSharp.sln /p:Configuration=Release;Platform=x64

This gives this error:

c:\Users\strentler\Downloads\CppSharp-0.10.5\build\scripts\llvm-80c3ea-windows-vs2017-x64-RelWithDebInfo\include\llvm/Support/raw_ostream.h(467): error
C3431: 'Colors': a scoped enumeration cannot be redeclared as an unscoped enumeration [c:\Users\strentler\Downloads\CppSharp-0.10.5\build\vs2017\projects\
CppSharp.CppParser.vcxproj]

After fixing this i get this errors:

Build FAILED.

"c:\Users\strentler\Downloads\CppSharp-0.10.5\build\vs2017\CppSharp.sln" (default target) (1) ->
"c:\Users\strentler\Downloads\CppSharp-0.10.5\src\CLI\CppSharp.CLI.csproj" (default target) (4) ->
"c:\Users\strentler\Downloads\CppSharp-0.10.5\src\Generator\CppSharp.Generator.csproj" (default target) (5:2) ->
"c:\Users\strentler\Downloads\CppSharp-0.10.5\src\Parser\CppSharp.Parser.csproj" (default target) (6:3) ->
"c:\Users\strentler\Downloads\CppSharp-0.10.5\build\vs2017\projects\CppSharp.Parser.CLI.vcxproj" (default target) (8) ->
"c:\Users\strentler\Downloads\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj" (default target) (9) ->
(Link target) ->
  LLVMTextAPI.lib(InterfaceFile.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSupport.lib(APFloat.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10
.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSupport.lib(ItaniumManglingCanonicalizer.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Do
wnloads\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSupport.lib(ScaledNumber.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp
-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMDemangle.lib(ItaniumDemangle.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(DebugInfoMetadata.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSha
rp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(InlineAsm.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(LLVMContextImpl.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp
-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSupport.lib(APInt.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.5
\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCoverage.lib(CoverageMapping.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(Type.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.5\bui
ld\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(Constants.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(Metadata.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.5
\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMTransformUtils.lib(Local.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp
-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMTransformUtils.lib(BasicBlockUtils.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Download
s\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMAnalysis.lib(MemorySSA.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMMC.lib(MCDwarf.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.5\bu
ild\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MachineSink.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-
0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(LiveDebugValues.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSh
arp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MIRVRegNamerUtils.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\Cpp
Sharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMGlobalISel.lib(RegisterBankInfo.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\C
ppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(ParentMapContext.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangLex.lib(HeaderSearch.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.
10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMX86CodeGen.lib(X86OptimizeLEAs.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\Cp
pSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MachineOperand.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSha
rp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaCUDA.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(APValue.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.10.5\
build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(ExprConstant.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0.
10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(ItaniumCXXABI.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangFrontend.lib(CompilerInvocation.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\
CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangFrontend.lib(TestModuleFileExtension.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downl
oads\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSerialization.lib(ASTReader.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSerialization.lib(ASTWriter.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_1 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCore.lib(MDBuilder.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSupport.lib(Statistic.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.
10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMAnalysis.lib(ScalarEvolution.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMAnalysis.lib(LoopInfo.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.
10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMAnalysis.lib(BlockFrequencyInfo.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\C
ppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCoverage.lib(CoverageMapping.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MachineBlockFrequencyInfo.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downl
oads\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(DFAPacketizer.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSelectionDAG.lib(ScheduleDAGRRList.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Download
s\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSelectionDAG.lib(ScheduleDAGSDNodes.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloa
ds\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MachineSink.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-
0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(StackColoring.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MachineBlockPlacement.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads
\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(StackSlotColoring.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\Cpp
Sharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(ParentMapContext.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangLex.lib(PPMacroExpansion.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMBitReader.lib(BitcodeReader.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSh
arp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(MachineLoopInfo.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSh
arp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaAvailability.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSha
rp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(DeclBase.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.10.5
\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(RecordLayoutBuilder.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppS
harp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangAST.lib(VTableBuilder.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaTemplateVariadic.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\Cp
pSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaTemplateDeduction.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\C
ppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaOverload.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(AnalysisBasedWarnings.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\C
ppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaExprCXX.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.
10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaTemplate.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaStmt.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaExpr.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaDeclObjC.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaDeclCXX.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.
10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaDecl.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0.10.
5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangSema.lib(SemaDeclAttr.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangFrontend.lib(ASTConsumers.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSha
rp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangCodeGen.lib(CodeGenModule.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSha
rp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangCodeGen.lib(CodeGenPGO.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-
0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  clangCodeGen.lib(CGBuiltin.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [c:\Users\strentler\Downloads\CppSharp-0
.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMX86Desc.lib(X86AsmBackend.obj) : error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_4 referenced in function "void __cdecl
std::reverse<unsigned int *>(unsigned int * const,unsigned int * const)" (??$reverse@PEAI@std@@YAXQEAI0@Z) [c:\Users\strentler\Downloads\CppSharp-0.10.5\b
uild\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMX86CodeGen.lib(X86FrameLowering.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_4 [c:\Users\strentler\Downloads\C
ppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMCodeGen.lib(StackColoring.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_4 [c:\Users\strentler\Downloads\CppShar
p-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMAnalysis.lib(LoopAccessAnalysis.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_4 [c:\Users\strentler\Downloads\C
ppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  LLVMSupport.lib(SmallPtrSet.obj) : error LNK2019: unresolved external symbol __std_swap_ranges_trivially_swappable_noalias referenced in function "void
const * * __cdecl std::_Swap_ranges_unchecked<void const *,0>(void const * * const,void const * * const,void const * * const)" (??$_Swap_ranges_unchecked@
PEBX$0A@@std@@YAPEAPEBXQEAPEBX00@Z) [c:\Users\strentler\Downloads\CppSharp-0.10.5\build\vs2017\projects\CppSharp.CppParser.vcxproj]
  ..\lib\Release_x64\CppSharp.CppParser.dll : fatal error LNK1120: 4 unresolved externals [c:\Users\strentler\Downloads\CppSharp-0.10.5\build\vs2017\proje
cts\CppSharp.CppParser.vcxproj]

    0 Warning(s)
    77 Error(s)
__
`

**Comment by ddobrev** [comment]
The errors you get are not from our code but from LLVM. Its version we use is fairly recent and it's perfectly possible that it doesn't support VS 2017. If possible, I advise you try with 2019.

**Comment by strentler** [comment]
@ddobrev . After upgrading the VS2017 solution to VS2019 it now compiles.

Would be nice when GenerateProjects.bat also support VS2019. Otherwise you are required to have VS2017 installed to initially create a VS2017 solution which then needs to be upgraded in VS2019 before it can be compiled.

**Comment by ddobrev** [comment]
You're right, we'll fix it.

**Comment by liamdx** [comment]
+1 vs2019 generator would be much appreciated.
