### ISSUE TITLE
gcc 10 is not supported

### ISSUE THREAD

**Issue by schmitch** [mono/CppSharp#1394]
##### Brief Description

linux opensuse or any distribution which installs gcc 10

Call:
```
./premake5-linux-64 gmake
```
```
Error: /home/schmitch/RiderProjects/CppSharp/build/Helpers.lua:251: bad argument #1 to 'sub' (string expected, got nil)
```
Offending Code:
```
function GccVersion()
  local compiler = os.getenv("CXX")
  if compiler == nil then
    compiler = "gcc"
  end
  local out = os.outputof(compiler.." -v")
  local version = string.match(out, "gcc version [0-9\\.]+")
  if version == nil then
    version = string.match(out, "clang version [0-9\\.]+")
  end
  return string.sub(version, 13)
end
```

**EDIT:**: the error is that I use `openSUSE Leap 15.2` which basically returns `gcc -v` differently and thus a lot of things are broken aswell.
even with `gcc 9`. also gcc 10 is really not supported since there is no llvm binary release ;-)

**Comment by tritao** [comment]
Thanks for the report, we'll take a look.

**Comment by schmitch** [comment]
btw. I also can't use gcc 9 because:

versions string:
`gcc-Version 9` instead **V**ersion instead of **v**ersion

**Comment by josetr** [comment]
@schmitch Thanks for providing us with the exact version. https://github.com/mono/CppSharp/commit/64f237db0f4c05d80d0fb6d3fd8471014c035fad should fix this.
