### ISSUE TITLE
No preprocessor defines

### ISSUE THREAD

**Issue by sipsorcery** [mono/CppSharp#1399]
Firstly thanks for this library! I got about 1% of the way through hand crafting the PInvoke signatures before I recalled seeing `CppSharp` used in another project. So far I'd guess it's saved me days of effort just for one C library and I've got at least two more to go!

##### Brief Description
I'm generating signatures for [libvpx](https://github.com/webmproject/libvpx). Most of the required signatures have come across well put all of the preprocessor defines are missing. The defines are generally simple numeric ones.

OS: Windows 10, Visual Studio 2019, nuget package v0.10.5.

##### Used headers

vpx_encoder.h
vpx_decoder.h
vp8cx.h
vp8dx.h

All from https://github.com/webmproject/libvpx/tree/master/vpx

##### Used settings

This is my first attempt at using `CppSharp` so I've literally just copied the example from the Getting Started Guide:

````
public void Setup(Driver driver)
{
	var options = driver.Options;
	options.GeneratorKind = GeneratorKind.CSharp;
	var module = options.AddModule("vpxmd");
	module.IncludeDirs.Add(@"C:\Dev\github\libvpx\vpx\");
	module.Headers.Add("vpx_encoder.h");
	module.Headers.Add("vpx_decoder.h");
	module.Headers.Add("vp8cx.h");
	module.Headers.Add("vp8dx.h");
	module.LibraryDirs.Add(@"C:\Dev\github\libvpx\build-win-x64\x64\Release");
	module.Libraries.Add("vpxmd.dll");
}
````

Target: C library built with MSVC

##### Stack trace or incompilable generated code

The generated C# class does not have any of the preprocessor defines. For example `VPX_ENCODER_ABI_VERSION` defined in the `vpx_encoder.h` does not exist in the generated C# class.

https://github.com/webmproject/libvpx/blob/c413c8f18eb1932b100850505031980e27160d5f/vpx/vpx_encoder.h#L59

**Comment by tritao** [comment]
I don't think we do any processing for preprocessor defines by default.

However we do provide some helper methods to help with this:

See `GenerateEnumItemFromMacro` for example, in https://github.com/mono/CppSharp/blob/master/src/Generator/Library.cs#L144.

You can pass regex patterns that match the defines you want to convert.

It should support arbitrary expressions too, but depending on the complexity of the define, it may or not work out-of-the box.

**Comment by sipsorcery** [comment]
Thx for the tip.

I can find the defines I need but how should I include them so that they get added to the auto-generated code? Ideally I'd like to have them declared as constants in the top level namespace.

```csharp
public static string[] _requiredDefines = {
	"VPX_CODEC_ABI_VERSION",
	"VPX_ENCODER_ABI_VERSION",
	"VPX_DECODER_ABI_VERSION",
	"VPX_DL_REALTIME",
	"VPX_EFLAG_FORCE_KF",
	"VPX_FRAME_IS_KEY"
};

public void Postprocess(Driver driver, ASTContext ctx)
{
	foreach(var tu in ctx.TranslationUnits)
	{
		foreach (var macro in tu.PreprocessedEntities.OfType<MacroDefinition>().Where(x => _requiredDefines.Any(y => y == x.Name)))
		{
			Console.WriteLine($"{macro.Name}->{macro.Expression}");

			// Do Something?
		}
	}
}
```

**Comment by tritao** [comment]
Right now, the supporting code to deal with parsing macro expressions has some dependencies on an `Enumeration`, since we originally built this infrastructure to convert defines to enums.

Since you want top-level constants (staic fields, I assume?), you would need to either refactor this code, or just create a fake enumeration to pass that code (see [`ParseToNumber`](https://github.com/mono/CppSharp/blob/master/src/Generator/Library.cs#L99)). And then you can create the top-level constants out of the enum, as long as you don't attach the enum to the AST it will not be generated.

It would look something like:

```csharp
// Create an enum from the macro defines
var defines = ctx.GenerateEnumFromMacros("VPXDefines", _requiredDefines); 

// Now create top level constants from each enum entry
for (var enumEntry in defines.Items)
{
    var field = new Field();
    field.Namespace =  field.Class =  ...; // Pass decl for class you want here
    field.Class = 
    field.Name = enumEntry.Name;
    field.QualifiedType = new QualifiedType(new BuiltinType(PrimitiveType.Int));
    field.Expression = new IntegerLiteral() { Value = enumEntry.Value }; // This line won't work right now.
}
```

Now... right now that won't work, since we have no way to specify an expression in a field, it would be relatively easy to add and update the C# generator to deal with it. But since we have not needed this before, it's not available right now.

A PR would be welcome if that is something you could help with.

**Comment by sipsorcery** [comment]
Thx again.

> A PR would be welcome if that is something you could help with.

I would like to become more familiar with `CppSharp`. If/when I get a good enough understanding I'd be happy to submit a PR.
