### ISSUE TITLE
How to convert std::map to C++/CLI

### ISSUE THREAD

**Issue by linwe2012** [mono/CppSharp#1403]
##### Brief Description

I tried to convert a std::map to CLI, which looks like this:

```c++
class EXPORT SomeClass
{
public:
    std::map<std::string, double*> maps;
};
```

but this field can't be found in generated files.

I'm using CppSharp built from source (lastest master branch)

Also, `std::vector` works but `std::set<std::string>` has the same issue as above.

OS: Windows 19041.450

##### Used settings

Target: MSVC

Options I used: `-g cli -a x64`

**Comment by tritao** [comment]
`std::set` and `std::map` have not been implemented yet for C++/CLI.

You can check the code here: https://github.com/mono/CppSharp/blob/master/src/Generator/Types/Std/Stdlib.cs#L626

**Comment by linwe2012** [comment]
Thanks for the information
