### ISSUE TITLE
Copy constructor symbol is not exported in linux

### ISSUE THREAD

**Issue by josetr** [mono/CppSharp#1456]
`Test: 
```.cs
new Bar(new Bar())
```

Output:
```
System.EntryPointNotFoundException : _ZN3BarC2ERKS_ assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) CSharp.Bar+__Internal.cctor_1(intptr,intptr)
```

**Comment by ddobrev** [comment]
@josetr for the time being there's no other way short adding an explicit implementation. The automated approach works on 2/3 (Linux remains) so I'm going to work with @tritao on merging it hopefully by the end of the week.
