### ISSUE TITLE
Unable to run the build script, llvm download link not found (404)

### ISSUE THREAD

**Issue by 8bitkitkat** [mono/CppSharp#1526]
##### Brief Description

Unable to run the build script, llvm download link not found (404)

OS: Linux

When running `./build.sh generate -configuration Release -platform x64` on Linux, I get:
```
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-0c8f9b-linux-x64-gcc-10.2-Release.tar.xz
Error: .../CSharp/AQEngine/Vendor/CppSharp/build/scripts/Utils.lua:106: HTTP response code said error
The requested URL returned error: 404 Not Found
```

**Comment by tritao** [comment]
Our current LLVM builds are for GCC 9, we will see about adding a new build for GCC 10.

**Comment by josetr** [comment]
@8bitkitkat The new LLVM package for linux-64-gcc-10 is now available. It should work well as we are now using this exact package in our linux builds.

Please try it and let us know if you find any issues.

**Comment by 8bitkitkat** [comment]
Thanks, all working now
