### ISSUE TITLE
Improve intrin.h fix.

### ISSUE THREAD

**Issue by SnGmng** [mono/CppSharp#1556]
##### Brief Description
https://github.com/mono/CppSharp/pull/1514 doesnt work for all possible intrin.h paths.

Possible intrin.h paths include (but are not limited to):

- C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/include/intrin0.h
- C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include/intrin0.h
- C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29333/include/intrin0.h

The current fix only supports one path and not all of the above.
https://github.com/mono/CppSharp/blob/86835469ac4a79904fc8e5d08ce134f74554ae0f/build/intrin.ps1#L1-L8

##### Stack trace or incompilable generated code
Not patching intrin.h results in an error:
`intrin.h(56,1): error: expected function body after function declarator`
Read more: https://github.com/microsoft/STL/issues/1300

**Comment by tritao** [comment]
Can you send a PR with this fix?

**Comment by tritao** [comment]
Thanks, much appreciated!
