### ISSUE TITLE
Exception when using the new 0.11 NuGet package

### ISSUE THREAD

**Issue by VincentMarmen** [mono/CppSharp#1573]
Hello,

I recently started converting the small console application I had previously created to generate bindings to .NET Core 3.1 and updated to the new version of the CppSharp NuGet package (0.11). However I keep getting an exception when calling ConsoleDriver.Run() with the message "Clang resource folder 'lib/clang/12.0.0/include' was not found." From what I can find in the source code (src/Parser/ParserOptions.cs line 380), it seems to be assumed that this "lib" folder is beside the location of CppSharp.Parser.dll. However in the file structure that is created when importing the NuGet package and building the application, the clang files are in "lib/clang/12.0.0/include/" while the DLL is in "runtimes/win-x64/lib/netcoreapp3.1/" (all paths relative to my EXE file). I tried manually moving the "lib/clang" folder to the folder where the DLL is placed and the application now works.

Is this normal? Should I always have to copy these files manually when building my application with the Nuget package? Or did the way to use CppSharp change and "ConsoleDriver.Run()" no longer works?

Thanks

OS: Windows 10
Visual Studio 2019 (Version 16.7.3)
CppSharp NuGet version 0.11

The headers and the settings seem irrevelant. I include an empty test application I made that when built and executed triggers the exception [TestCppSharp.zip](https://github.com/mono/CppSharp/files/5900118/TestCppSharp.zip)

### Exception
System.Exception
  HResult=0x80131500
  Message=Clang resource folder 'lib/clang/12.0.0/include' was not found.
  Source=CppSharp.Parser
  Arborescence des appels de procédure :
   at CppSharp.Parser.ParserOptions.SetupIncludes()
   at CppSharp.Parser.ParserOptions.Setup()
   at CppSharp.Driver.Setup()
   at CppSharp.ConsoleDriver.Run(ILibrary library)
   at NativeBindingsGenerator.Program.Main(String[] args) in Program.cs:line 146

**Comment by ddobrev** [comment]
Hello, @VincentMarmen . Thank you for this bug report, it's extremely important.
No, it isn't normal, we've made a mistake. We'll fix our structure. I'm happy you've found a way to make it work nevertheless. We'll let you know when we've updated the NuGet.

**Comment by ddobrev** [comment]
Fixed by https://github.com/mono/CppSharp/commit/33e94b5f1f86accd55f222503f6fa0ec5a2da2ac.

**Comment by VincentMarmen** [comment]
I updated to the 0.11.1 NuGet package and can confirm it now works as expected. Thank you @ddobrev for the quick support.
