### ISSUE TITLE
Clang resource folder 'lib/clang/12.0.0/include' was not found

### ISSUE THREAD

**Issue by netcorefan1** [mono/CppSharp#1577]
##### Brief Description
I am trying to run a very basic example, but when I call the ConsoleDriver I get:
```
Exception thrown: 'System.Exception' in CppSharp.Parser.dll
An unhandled exception of type 'System.Exception' occurred in CppSharp.Parser.dll
Clang resource folder 'lib/clang/12.0.0/include' was not found.
```
OS: Windows / OS X / Linux (include version and/or distro)
I am running Windows 10 Pro x64 (20H2 - 19042.746)
Net SDK 5.0.102

##### Used headers
https://github.com/Broihon/GH-Injector-Library/raw/master/Injection.h

##### Used settings
```
class CppSharp : ILibrary
{
        public void Preprocess(Driver driver, ASTContext ctx) => throw new NotImplementedException();

        public void Postprocess(Driver driver, ASTContext ctx) => throw new NotImplementedException();

        public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            var module = options.AddModule("GH Injector - x64"); // "GH Injector - x64.dll"
            module.Headers.Add("Injection.h");
            //module.LibraryDirs.Add(@"C:\Sample\lib");
            //module.Libraries.Add("Sample.lib");
        }

        public void SetupPasses(Driver driver) => throw new NotImplementedException();
}
```
Target: MSVC/GCC/Clang
In Windows I would like to use its own MSVC, but when I run the sample it failed with that error related to missing Clang. So I opened the VS installer and installed "C++ Clang Compiler for Windows (10.0.0.)", but I still get the same error.

Other settings 
Nothing

##### Stack trace or incompilable generated code
Not applicable

**Comment by ddobrev** [comment]
[We've fixed this](https://github.com/mono/CppSharp/commit/33e94b5f1f86accd55f222503f6fa0ec5a2da2ac), please try our latest NuGet.

**Comment by netcorefan1** [comment]
Thanks, it works now, but do I really need the Clang compiler? It's more than 3Gb and since I am on Windows I would like to use MSVC. Is there a way to make CppSharp to use MSVC?

**Comment by ddobrev** [comment]
You don't. As I understand, you only installed Clang in an attempt to fix the problem which means you don't need it any more.

**Comment by netcorefan1** [comment]
Yes, it was just a quick attempt to fix the problem. I am glad that I don't need anymore. What about the new interface I saw in this version? It changed the way to generate the code. Because once `ConsoleDriver.Run(new SampleLibrary());` return I don't get anything. Thanks

**Comment by netcorefan1** [comment]
Nevermind, it's an error due to the header not found (my fault). That why I didn't got anything.
Ok, I will not make further questions since it will go outside of the scope of this issue.
Thanks for the fast help! I really appreciate!
Keep the good work!
