### ISSUE TITLE
Cannot run dotnet project on ARM64

### ISSUE THREAD

**Issue by Exless** [mono/CppSharp#1582]
##### Brief Description

I have a simple "tryout" project where i compile a few simple c++ classes then "wrap" them with CppSharp on my Linux x86 machine. It works pretty well with no major issues.

However when i try to do the same thing on my Jetson Nano [ Linux(ARM64) ] i get this error message when i try to run it

```

$ dotnet run 


Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'CppSharp.Generator, Version=0.10.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'CppSharp.Generator, Version=0.10.6.0, Culture=neutral, PublicKeyToken=null'
```

OS: Linux - Debian (ARM64)

Target: G++

Could anyone kindly explain what is happening? I can of course give more info if needed.

**Comment by tritao** [comment]
CppSharp needs some native components like the C++ parser to generate its code, so you will need to compile it from source on Jetson Nano since we provide no binary builds for ARM platforms atm.

Or you can do cross-generation of the ARM bindings from an x86 machine.

**Comment by Exless** [comment]
> CppSharp needs some native components like the C++ parser to generate its code, so you will need to compile it from source on Jetson Nano since we provide no binary builds for ARM platforms atm.
> 
> Or you can do cross-generation of the ARM bindings from an x86 machine.

It seems to me that the build scripts aren't made of arm in mind as i tried making use of them but with no success. 

How could you do cross-generation?
As i looked at it even the generated .cs files depend on CppSharp. 
For example vtables etc.. require the runtime. (Which then would not be available if i just include the bindings in an arm64 project) 
![image](https://user-images.githubusercontent.com/50926889/108722105-0c8ffc00-7523-11eb-9b49-23cf7f5d020b.png)

**Comment by tritao** [comment]
For cross-generation you can use `parserOptions.TargetTriple` and set it to a GCC-compatible triple, like `x86_64-linux-gnu`.

As for the runtime, you can just include the Runtime C# files from `src/Runtime` and bundle them in your repo.

Or maybe you can reference the `csproj` from your solution, as long as those files get compiled.

**Comment by Exless** [comment]
> For cross-generation you can use `parserOptions.TargetTriple` and set it to a GCC-compatible triple, like `x86_64-linux-gnu`.
> 
> As for the runtime, you can just include the Runtime C# files from `src/Runtime` and bundle them in your repo.
> 
> Or maybe you can reference the `csproj` from your solution, as long as those files get compiled.

Thank you very much for helping out sir. Referencing the the csproj of the src/Runtime indeed solved it :).

**Comment by XzuluX** [comment]
@Exless @tritao  I have the same issue on Raspberry CM4. Could you please describe in more detail how you solved the problem. Did you have to compile CppSharp on the ARM target? Currently, I am only using the CppSharp NuGet package and generating the bindings as shown in this example: https://github.com/mono/CppSharp/blob/main/docs/GeneratingBindings.md.
What steps do I need to perform for cross-generation?

**Comment by XzuluX** [comment]
@tritao Thank's, it's working now. I cross generated the bindings code on x64 Ubuntu. The crucial step to use the bindings code on Arm was to compile just the CppSharp.Runtime on the ARM target (like Exless mentioned, I integrated the Runtime Project src/Runtime into my Project).
It seems, however, that the value of the triple does not have a significant influence on the cross-generation output ....
