### ISSUE TITLE
Unable to load shared library 'CppSharp.CppParser' on Linux

### ISSUE THREAD

**Issue by vaceal** [mono/CppSharp#1586]
##### Brief Description

I am trying to generate the C# code for the [LLDB](https://lldb.llvm.org/) (version 9.0.0) library under Linux and it seems that the library is looking for DiaSymReader : 

```txt
4805:	find library=Microsoft.DiaSymReader.Native.amd64.dll [0]; searching
4805:	 search cache=/etc/ld.so.cache
4805:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
4805:	  trying file=/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
4805:	  trying file=/usr/lib/x86_64-linux-gnu/Microsoft.DiaSymReader.Native.amd64.dll
4805:	  trying file=/lib/Microsoft.DiaSymReader.Native.amd64.dll
4805:	  trying file=/usr/lib/Microsoft.DiaSymReader.Native.amd64.dll
4805:	
```

**I don't have a problem generating the code under Windows, that works fine.**

This is probably a case of misconfiguration on my side but I can't pin point the problem.  Is the current nuget package 0.11 support Linux out of the box or I need to compile cppSharp on my side?

**OS :** Linux, Ubuntu 18.04.1 LTS
**cppSharp Version :** 0.11

**Target:** Clang?

If you need more information, I would be happy to share the code if you  need it.

Thanks,

Alex

**Comment by ddobrev** [comment]
It isn't clear if the generating or generated code fails for you, I'll assume the former. One possible reason would be that you rely on Mono which we don't support any more as the host. You would need .NET Core 3.1+ for Linux instead.

**Comment by tritao** [comment]
It's hard to say what the problem could be...

Can you share the Dockerfile so we can take a look?

By the way, since you are binding LLDB you might be interested in https://github.com/tritao/LLDBSharp.

It has not been worked on for a couple of years, but could be useful.

**Comment by vaceal** [comment]
Hello @tritao ,

So, I was running in a docker container via the interactive mode and making the Dockerfile made me test something I did not test before.

All of my tests ran on Ubuntu bionic (18.04) and it seems the problem was there.

Using the following Dockerfile is working : 

```docker
FROM mcr.microsoft.com/dotnet/sdk:3.1-focal

RUN apt update && apt install -y build-essential

COPY source/Lldb.Sharp.Generator /lldbsharp
COPY Lldb /Lldb

RUN mkdir /output

RUN dotnet build lldbsharp/Lldb.Sharp.Generator.csproj
RUN dotnet run -p lldbsharp -l /Lldb/9.0.0/linux/lib/lldb.so -i /Lldb/9.0.0/include/ -o /output
```

But if we change the source image for `mcr.microsoft.com/dotnet/sdk:3.1-bionic`, I have the error mentionned above.  Since my WSL is running on the same version (Ubuntu 18.04), I got the same problem locally as well.

To be honest, I am no sure why I have this behavior,  It looks like the bionic image does not return the proper platform to the cppsharp parser. otherwise, why loading microsoft DIA library...

If you think this would helpfull, I would be happy to share the project with you.

Thanks for you help!

Alex

**Comment by tritao** [comment]
Our binary packages are currently compiled with Ubuntu 20.04: https://github.com/mono/CppSharp/blob/master/.github/workflows/llvm.yml#L12

So it's probably a binary compatibility issue, you can try compiling LLVM from source using our build scripts: https://github.com/mono/CppSharp/blob/master/docs/LLVM.md
