### ISSUE TITLE
The default branch has been renamed from 'master' to 'main'

### ISSUE THREAD

**Issue by rolfbjarne** [mono/CppSharp#1588]
On Friday, March 12th 2021, we're going to rename the default branch in this repository to `main`. For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172). Expect the process to begin after 7AM Central European Time.

If any additional things have to be done as well, please comment on this issue.

**Comment by tritao** [comment]
Thanks for the heads up, I don't see any problems with this so please go ahead.

**Comment by rolfbjarne** [comment]
This has now been done.

@tritao A quick search for `master` found a few things: https://github.com/mono/CppSharp/search?q=master, do any of these need fixing?
