### ISSUE TITLE
The namespace 'Std.Vector' cannot be used with type arguments

### ISSUE THREAD

**Issue by qingfengxia** [mono/CppSharp#1590]
##### Brief Description

C# binding for `std::vector<>` as parameter does not compile on Windows.
C++ API `ErrorCode get_vertex_coordinates( std::vector< double >& coords )`

On Linux (CppSharp 0.10.5, Nov 2020), `std::vector<double>` as a field was binded to a long named type, `internal global::Std.Vector.__Internalc__N_std_S_vector_____N_moab_S_SetIterator___N_std_S_allocator__S0_ setIterators;
`, not a C# template, seems  `std::vector<double>` as function parameter has been ignored.

but on Windows CppSharp (v0.11, Feb 2021),  it seems C# template is emit. e.g. 
 ` options.GenerateClassTemplates = false;  `  make no difference. 

This issue may also related with https://github.com/mono/CppSharp/issues/651
`std::vector<double>` should be map to C# `List<double>`

`public abstract global::MOAB.Moab.ErrorCode GetVertexCoordinates(global::Std.Vector<double, global::Std.Allocator<double>> coords);`

> error CS0307: The namespace 'Std.Vector' cannot be used with type arguments
Std.cs has been generated,         This may be related to the error:
> error CS0400: The type or namespace name 'type_info' could not be found in the global namespace

In std.cs, std.vector related code is:
`
    namespace Vector
    {
        [StructLayout(LayoutKind.Sequential, Size = 24, Pack = 8)]
        public unsafe partial struct __Internalc__N_std_S_vector__k___N_std_S_allocator__k
        {
            internal global::Std.CompressedPair.__Internalc__N_std_S__Compressed_pair____N_std_S_allocator__k___N_std_S__Vector_val____N_std_S__Simple_types__k_Vb1 _Mypair;
        }

        [StructLayout(LayoutKind.Sequential, Size = 24, Pack = 8)]
        public unsafe partial struct __Internalc__N_std_S_vector_____N_moab_S_SetIterator___N_std_S_allocator__S0_
        {
            internal global::Std.CompressedPair.__Internalc__N_std_S__Compressed_pair____N_std_S_allocator_____N_moab_S_SetIterator___N_std_S__Vector_val____N_std_S__Simple_types__S1__Vb1 _Mypair;
        }
    }
`
PS: during code generation, there are some messages like:

>  Function 'allocator' was ignored due to ignored return decl type global::std.allocator<global::std.pair<ulong, ulong>>
    Field '_Compressed_pair::_Myval2' was ignored due to ignored type '::std::_Vector_val<::std::_Simple_types<double>>'
    Field '_Compressed_pair::_Myval2' was ignored due to ignored type '::std::_Vector_val<::std::_Simple_types<int>>'

OS: Windows 10 (CppSharp 0.11 compiled from source) / Linux (Ubuntu 20.04, CppSharp 0.10.5 compiled from source)

##### Used settings

Target: MSVC

Other settings 

##### Stack trace or incompilable generated code

`
            // ErrorCode get_vertex_coordinates( std::vector< double >& coords ) const = 0
            private static global::MOAB.Delegates.Func_MOAB_moab_ErrorCode___IntPtr___IntPtr _GetVertexCoordinatesDelegateInstance;

            private static global::MOAB.Moab.ErrorCode _GetVertexCoordinatesDelegateHook(__IntPtr __instance, __IntPtr coords)
            {
                var __target = global::MOAB.Moab.Interface.__GetInstance(__instance);
                var __result0 = global::Std.Vector<double, global::Std.Allocator<double>>.__GetOrCreateInstance(coords, false);
                var __ret = __target.GetVertexCoordinates(__result0);
                return __ret;
            }
`

**Comment by qingfengxia** [comment]
read again the document,    `std::vector` is not supported by C# generator,  but C++/CLI generator (thank to CLRSTL assembly). So I need to find a way to ignore all function signature with `std::vector` for the moment.  

Meanwhile, not sure if std::string is supported or not, that is such a common C++ type, can not be ignored.

**Comment by qingfengxia** [comment]
Is there a switch to ignore  std::vector,   if C# generator does not support `std::vector`,    STL except string should be ignored.  in CppSharp 0.10,  it is ignored, in CppSharp 0.11,  `std::vector`, then I need  monkey patch to ignore API signature contains "std.vector".    

```
       private bool IsDeclIgnored(Declaration decl)
        {
            var parameter = decl as Parameter;
            if (parameter != null)
            {
                if (parameter.Type.Desugar().IsPrimitiveType(PrimitiveType.Null))
                    return true;

                if (TypeMaps.FindTypeMap(parameter.Type, out var typeMap))
                    return typeMap.IsIgnored;
            }

            return decl.Ignore;
        }
```

**Comment by qingfengxia** [comment]
is there an parse Option, to suppress STL (skip any function with stl container as parameter or return type) if generator is C#, that will avoid user to patch CppSharp.Generator.

**Comment by tritao** [comment]
You can try adding a new typemap to https://github.com/mono/CppSharp/blob/main/src/Generator/Types/Std/Stdlib.CSharp.cs.

Something like:

```csharp
[TypeMap("std::vector", GeneratorKind = GeneratorKind.CSharp)]
public partial class Vector : TypeMap
{
    public override bool IsIgnored { get { return true; } }
}
```
