### ISSUE TITLE
Visual Studio .sln file not generating

### ISSUE THREAD

**Issue by LukeRl** [mono/CppSharp#1592]
Hi, I'm following the "Getting Started" page and I'm already stuck at step 1. I have cULR and 7-zip installed (on my windows 10 system) and when I run the  "./build.sh generate -configuration Release -platform x64" command from inside the build folder (via PowerShell, which I ran as Admin), it downloads some files for a second then closes but there is no CppSharp.sln anywhere on my computer. I'm trying to use CppSharp for a school project and have asked my team of 7 other people to try the same thing and no one is able to generate the .sln file.

Surely we are all making some sort of stupid mistake, does anyone have any idea what it could be?

**Comment by tritao** [comment]
Please paste the output of the build command.

**Comment by LukeRl** [comment]
> Please paste the output of the build command.

Well, that was enough to solve the issue for me. I had a screen recording from last night of the output that I watched frame-by-frame to see what it said but it would always close too fast. This time I recorded in a higher fps to see if I could catch it and I saw the message saying "unknown MSVC compiler, please use VS command prompt."

The issue is I was using regular cmd or powershell, not the terminal within VS, but the output was closing too fast for me to see that error. Thanks!
