### ISSUE TITLE
Using shared_ptr inside wrapped class does not work as expected

### ISSUE THREAD

**Issue by TillAlex** [mono/CppSharp#1600]
When wrapping a class having a private shared_ptr field I am experiencing strange effects. It seems that calling the destructor from C# and C++ decrements different reference counts.

To give an example: An instance of the class is created inside a C++ method. It's reference count starts at 1. When this instance is used as the methods return value a copy is created and the reference count is incremented to 2. After the method returns the original (local) instance should be destroyed and the reference count should be decremented to 1. However, when calling this method from C# using the wrapper the object returned has a reference count of 2.

Is this behaviour expected? What can I do to make the shared_ptr work correctly? Thanks for your help in advance!

**Comment by tritao** [comment]
Is this with C# or C++/CLI backend?

**Comment by TillAlex** [comment]
That's with the C# backend.

**Comment by tritao** [comment]
We do not provide support for `std::shared_ptr` at this time, in fact we seem to ignore them in C++/CLI.

I don't think it would be very difficult to add support for them, but no one has done the work so far.

**Comment by TillAlex** [comment]
Do I understand you correctly: 

`std::shared_ptr` is not only unsupported for the case of `shared:ptr` in the public interface of classes, but also for internal fields?

To illustrate my usage case here is an example class:

```
class Foo {
private:
    std::shared_ptr<int> _ptr;
public:
    Foo();
    ~Foo();

    int* getPointer() { return _ptr.get();}
    int getUseCount() { return _ptr.use_count();}
};
```

**Comment by tritao** [comment]
OK,  I misunderstood.

Using them as private fields should work, thought this was about using them as part of the public API.

Maybe there is some issue where we call the wrong constructor.

Can you send an example that shows the issue you described originally then?

If you can, add the generated code as well, that should give us something we can start investigating.

**Comment by TillAlex** [comment]
Attached you find a more or less minimal reproducer. It contains a C++ project, a C# project generating the bindings and a C# project using the bindings. A prebuild native DLL build with VS2019 and the generated bindings are included as well. Please let me know if anything is missing.

[CppSharpTest.zip](https://github.com/mono/CppSharp/files/6318381/CppSharpTest.zip)

**Comment by ddobrev** [comment]
@TillAlex thank you for your exemplary reproduction. I hope we can react soon.

**Comment by ddobrev** [comment]
I've reproduced it immediately, an outstanding test case. The problem might be related to the ABI signature of the method:
```C#
internal static extern void GenerateFoo(__IntPtr @return);
```
We pass a pointer, not a value. It points to a locally created `var __ret = new global::CppSharpTest.Foo.__Internal();`, the internal structure of the type. Perhaps we should call the native constructor instead. We'll investigate further.

**Comment by tritao** [comment]
Just FIY, We have identified the issue and are working on a fix, no idea when it will land yet though.

**Comment by codecalvin** [comment]
Any updating? 

shared_ptr is a common feature. Our team currently is blocking on this problem.
It would be awesome if shared_ptr could be supported!

**Comment by tritao** [comment]
Should be fixed by https://github.com/mono/CppSharp/pull/1623.

Please let us know if there's still issues.
