### ISSUE TITLE
mangled names not correct for visual studio

### ISSUE THREAD

**Issue by ehaufler** [mono/CppSharp#1606]
##### Brief Description
With version 0.11.2 of cppSharp  I tried to wrap a small c++ test dll for csharp. Native dll was compiled with visual studio 2019 msvc compiler. 
The produced binding source Sample.cs did not work. 
The mangled names in for P/Invoke in Sample.cs  e.g. contain @@QEAA, 
while the native dll exports @@QAE
(the header files as well as the native .lib were given to ILibrary.Setup() )

Should cppSharp work with msvc in general, or are there settings possible for this?

OS: Windows 10

class SampleLibrary: ILibrary
{
public override void Setup(Driver driver)
{
      var options = driver.Options;
      options.GeneratorKind = CppSharp.Generators.GeneratorKind.CSharp;
      var module = options.AddModule("Sample");
      module.IncludeDirs.Add(@"..\..\..\..\cd_native\src");
      module.Headers.Add("ICurve.h");
      module.Headers.Add("CCurve.h");
      module.Headers.Add("Sample.h");
      module.LibraryDirs.Add(@"..\..\..\..\Debug");
      module.Libraries.Add("cd_native.lib");
    }
...

export of a class constructor e.g.
          ??0CCurve@@QAE@ABV0@@Z = @ILT+2175(??0CCurve@@QAE@ABV0@@Z)

does not match generated sample.cs:
            [SuppressUnmanagedCodeSecurity, DllImport("Sample", EntryPoint = "??0CCurve@@QEAA@AEBV0@@Z", CallingConvention = __CallingConvention.Cdecl)]

Thank you for any hints

**Comment by tritao** [comment]
This seems like a 32/64-bit mismatch.

Set your target triple to either `x86_64-pc-win32-msvc` or `i686-pc-win32-msvc`.

Like so: `parserOptions.TargetTriple = "triple";`

**Comment by ehaufler** [comment]
This was the amazingly fastest answer I've ever got, thank you !
And it works indeed. 

I didn't find that point in the documentation it there  another documentation place that I have missed?
And so I understood correctly: I cannot build a C# wrapper, that works as AnyCPU  with 32bit and 64bit (by loading the correct native dll), because the native names are different?

Thank you very much!

**Comment by tritao** [comment]
Indeed, we do not support universal AnyCPU C# wrappers since the symbols and offsets are different per architecture/OS.

It wasn't documented so far, I've updated the users manual with this information now: https://github.com/mono/CppSharp/blob/main/docs/UsersManual.md#3-native-targets

**Comment by ehaufler** [comment]
Thank you very much again!
