### ISSUE TITLE
Error during compilation with VS2019  Unable to load DLL 'CppSharp.CppParser' or one of its dependencies:

### ISSUE THREAD

**Issue by reno77** [mono/CppSharp#1608]
I tried compiling the master branch on Windows and got this error, 

7>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)

I installed Ubuntu 16.04 as WSL in Windows in order to generate the VS Solution (bash build.sh generate -configuration Release -platform x64) 

Next I opened the solution in VS2019 16.9.4 to compile it. 
 
Full compile output is : 
 
Build started...
1>------ Build started: Project: CppSharp.Runtime, Configuration: Release x64 ------
2>------ Build started: Project: CppSharp, Configuration: Release x64 ------
3>------ Build started: Project: CppSharp.AST, Configuration: Release x64 ------
1>CppSharp.Runtime -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Runtime.dll
4>------ Build started: Project: CppSharp.Parser.CSharp, Configuration: Release x64 ------
2>CppSharp -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.dll
3>CppSharp.AST -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.AST.dll
4>CppSharp.Parser.CSharp -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Parser.CSharp.dll
5>------ Build started: Project: CppSharp.Parser, Configuration: Release x64 ------
5>CppSharp.Parser -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Parser.dll
6>------ Build started: Project: CppSharp.Generator, Configuration: Release x64 ------
6>CppSharp.Generator -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Generator.dll
7>------ Build started: Project: CSharp.Gen, Configuration: Release x64 ------
8>------ Build started: Project: Common.Gen, Configuration: Release x64 ------
9>------ Build started: Project: Encodings.Gen, Configuration: Release x64 ------
10>------ Build started: Project: VTables.Gen, Configuration: Release x64 ------
11>------ Build started: Project: NamespacesDerived.Gen, Configuration: Release x64 ------
12>------ Build started: Project: CLI.Gen, Configuration: Release x64 ------
13>------ Build started: Project: CppSharp.CLI, Configuration: Release x64 ------
14>------ Build started: Project: CppSharp.Generator.Tests, Configuration: Release x64 ------
14>CppSharp.Generator.Tests -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Generator.Tests.dll
15>------ Build started: Project: CppSharp.Parser.Bootstrap, Configuration: Release x64 ------
15>CppSharp.Parser.Bootstrap -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Parser.Bootstrap.dll
16>------ Build started: Project: StandardLib.Gen, Configuration: Release x64 ------
7>CSharp.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\CSharp.Gen.dll
9>Encodings.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\Encodings.Gen.dll
13>CppSharp.CLI -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.CLI.dll
12>CLI.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\CLI.Gen.dll
10>VTables.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\VTables.Gen.dll
17>------ Build started: Project: CppSharp.Parser.Gen, Configuration: Release x64 ------
8>Common.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\Common.Gen.dll
7>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
11>NamespacesDerived.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\NamespacesDerived.Gen.dll
9>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
9>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
9>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
9>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
9>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
9>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
9>   at CppSharp.Tests.EncodingsTestsGenerator.Main(String[] args) in D:\CppSharp\CppSharp-main\tests\Encodings\Encodings.Gen.cs:line 27
7>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
7>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
7>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
7>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
7>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
7>   at CppSharp.Tests.CSharpTestsGenerator.Main(String[] args) in D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Gen.cs:line 79
16>StandardLib.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\StandardLib.Gen.dll
12>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
12>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
12>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
12>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
12>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
12>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
12>   at CppSharp.Tests.CLITestsGenerator.Main(String[] args) in D:\CppSharp\CppSharp-main\tests\CLI\CLI.Gen.cs:line 82
17>CppSharp.Parser.Gen -> D:\CppSharp\CppSharp-main\bin\Release_x64\CppSharp.Parser.Gen.dll
10>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
11>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
11>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
11>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
11>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
11>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
11>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
11>   at CppSharp.Tests.NamespacesDerived.Main() in D:\CppSharp\CppSharp-main\tests\NamespacesDerived\NamespacesDerived.Gen.cs:line 36
10>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
10>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
10>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
10>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
10>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
10>   at CppSharp.Tests.VTableTests.Main(String[] args) in D:\CppSharp\CppSharp-main\tests\VTables\VTables.Gen.cs:line 34
8>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
8>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
8>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
8>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
8>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
8>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
8>   at CppSharp.Tests.CommonTestsGenerator.Main(String[] args) in D:\CppSharp\CppSharp-main\tests\Common\Common.Gen.cs:line 85
11>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\NamespacesDerived.Gen.dll"" exited with code -532462766.
11>Done building project "NamespacesDerived.Gen.csproj" -- FAILED.
8>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\Common.Gen.dll"" exited with code -532462766.
8>Done building project "Common.Gen.csproj" -- FAILED.
16>Unhandled exception. System.DllNotFoundException: Unable to load DLL 'CppSharp.CppParser' or one of its dependencies: The specified module could not be found. (0x8007007E)
16>   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
16>   at CppSharp.Parser.CppParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\CppParser\Bindings\CSharp\x86_64-linux-gnu-cxx11abi\CppSharp.CppParser.cs:line 39263
16>   at CppSharp.Parser.ParserOptions..ctor() in D:\CppSharp\CppSharp-main\src\Parser\ParserOptions.cs:line 68
16>   at CppSharp.Driver..ctor(DriverOptions options) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 31
16>   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\CppSharp\CppSharp-main\src\Generator\Driver.cs:line 413
16>   at CppSharp.Tests.StandardLibTestsGenerator.Main(String[] args) in D:\CppSharp\CppSharp-main\tests\StandardLib\StandardLib.Gen.cs:line 21
18>------ Build started: Project: NamespacesDerived.Tests.CSharp, Configuration: Release x64 ------
19>------ Build started: Project: Common.CSharp, Configuration: Release x64 ------
16>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\StandardLib.Gen.dll"" exited with code -532462766.
16>Done building project "StandardLib.Gen.csproj" -- FAILED.
18>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "NamespacesBase". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
18>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "NamespacesDerived". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
18>D:\CppSharp\CppSharp-main\tests\NamespacesDerived\NamespacesDerived.Tests.cs(7,7,7,24): error CS0246: The type or namespace name 'NamespacesDerived' could not be found (are you missing a using directive or an assembly reference?)
18>D:\CppSharp\CppSharp-main\tests\NamespacesDerived\NamespacesDerived.Tests.cs(178,50,178,72): error CS0246: The type or namespace name 'HasVirtualInDependency' could not be found (are you missing a using directive or an assembly reference?)
18>D:\CppSharp\CppSharp-main\tests\NamespacesDerived\NamespacesDerived.Tests.cs(180,29,180,42): error CS0115: 'NamespaceDerivedTests.OverrideMethodFromDependency.VirtualInCore(int)': no suitable method found to override
18>Done building project "NamespacesDerived.Tests.CSharp.csproj" -- FAILED.
19>Common.CSharp -> D:\CppSharp\CppSharp-main\build\gen\Common\Common.CSharp.dll
20>------ Build started: Project: Common.Tests.CSharp, Configuration: Release x64 ------
20>D:\CppSharp\CppSharp-main\tests\Common\Common.Tests.cs(5,14,5,24): error CS0246: The type or namespace name 'CommonTest' could not be found (are you missing a using directive or an assembly reference?)
20>D:\CppSharp\CppSharp-main\tests\Common\Common.Tests.cs(3,7,3,17): error CS0246: The type or namespace name 'CommonTest' could not be found (are you missing a using directive or an assembly reference?)
20>D:\CppSharp\CppSharp-main\tests\Common\Common.Tests.cs(999,46,999,69): error CS0246: The type or namespace name 'AbstractWithVirtualDtor' could not be found (are you missing a using directive or an assembly reference?)
20>D:\CppSharp\CppSharp-main\tests\Common\Common.Tests.cs(1001,30,1001,38): error CS0115: 'CommonTests.CustomDerivedFromVirtual.Abstract()': no suitable method found to override
20>Done building project "Common.Tests.CSharp.csproj" -- FAILED.
7>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\CSharp.Gen.dll"" exited with code -532462766.
7>Done building project "CSharp.Gen.csproj" -- FAILED.
21>------ Build started: Project: CSharp.CSharp, Configuration: Release x64 ------
9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\Encodings.Gen.dll"" exited with code -532462766.
9>Done building project "Encodings.Gen.csproj" -- FAILED.
22>------ Build started: Project: Encodings.CSharp, Configuration: Release x64 ------
10>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\VTables.Gen.dll"" exited with code -532462766.
10>Done building project "VTables.Gen.csproj" -- FAILED.
23>------ Build started: Project: VTables.CSharp, Configuration: Release x64 ------
22>Encodings.CSharp -> D:\CppSharp\CppSharp-main\build\gen\Encodings\Encodings.CSharp.dll
21>CSharp.CSharp -> D:\CppSharp\CppSharp-main\build\gen\CSharp\CSharp.CSharp.dll
24>------ Build started: Project: Encodings.Tests.CSharp, Configuration: Release x64 ------
25>------ Build started: Project: CSharp.Tests.CSharp, Configuration: Release x64 ------
23>VTables.CSharp -> D:\CppSharp\CppSharp-main\build\gen\VTables\VTables.CSharp.dll
26>------ Build started: Project: VTables.Tests.CSharp, Configuration: Release x64 ------
24>D:\CppSharp\CppSharp-main\tests\Encodings\Encodings.Tests.cs(2,13,2,22): error CS0246: The type or namespace name 'Encodings' could not be found (are you missing a using directive or an assembly reference?)
24>Done building project "Encodings.Tests.CSharp.csproj" -- FAILED.
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(7,7,7,13): error CS0246: The type or namespace name 'CSharp' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(13,35,13,64): error CS0246: The type or namespace name 'TestOverrideFromSecondaryBase' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(107,41,107,44): error CS0246: The type or namespace name 'Baz' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1354,47,1354,85): error CS0246: The type or namespace name 'HasVirtualTakesReturnsProblematicTypes' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1367,46,1367,79): error CS0246: The type or namespace name 'UsesPointerToEnumInParamOfVirtual' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1369,55,1369,60): error CS0246: The type or namespace name 'Flags' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1369,25,1369,30): error CS0246: The type or namespace name 'Flags' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1705,26,1705,41): error CS0246: The type or namespace name 'SimpleInterface' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1713,45,1713,65): error CS0246: The type or namespace name 'VirtualTemplate<>' could not be found (are you missing a using directive or an assembly reference?)
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(109,29,109,33): error CS0115: 'CSharpTests.OverriddenInManaged.Type': no suitable method found to override
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1356,32,1356,60): error CS0115: 'CSharpTests.OverrideVirtualWithString.VirtualTakesAndReturnsString(string)': no suitable method found to override
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1361,30,1361,56): error CS0115: 'CSharpTests.OverrideVirtualWithString.VirtualTakesAndReturnsBool(bool)': no suitable method found to override
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1707,29,1707,33): error CS0115: 'CSharpTests.Inter.Size': no suitable method found to override
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1708,29,1708,37): error CS0115: 'CSharpTests.Inter.Capacity': no suitable method found to override
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1709,32,1709,35): error CS0115: 'CSharpTests.Inter.Get(int)': no suitable method found to override
25>D:\CppSharp\CppSharp-main\tests\CSharp\CSharp.Tests.cs(1715,29,1715,37): error CS0115: 'CSharpTests.OverrideVirtualTemplate.Function()': no suitable method found to override
25>Done building project "CSharp.Tests.CSharp.csproj" -- FAILED.
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(3,7,3,14): error CS0246: The type or namespace name 'VTables' could not be found (are you missing a using directive or an assembly reference?)
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(5,27,5,30): error CS0246: The type or namespace name 'Foo' could not be found (are you missing a using directive or an assembly reference?)
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(25,50,25,69): error CS0246: The type or namespace name 'DerivedClassVirtual' could not be found (are you missing a using directive or an assembly reference?)
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(17,43,17,62): error CS0246: The type or namespace name 'DerivedClassVirtual' could not be found (are you missing a using directive or an assembly reference?)
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(27,32,27,38): error CS0115: 'ManagedDerivedClassVirtualRetBase.RetInt()': no suitable method found to override
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(19,32,19,38): error CS0115: 'ManagedDerivedClassVirtual.RetInt()': no suitable method found to override
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(7,25,7,29): error CS0115: 'FooDerived.vfoo': no suitable method found to override
26>D:\CppSharp\CppSharp-main\tests\VTables\VTables.Tests.cs(53,30,53,46): error CS0246: The type or namespace name 'BaseClassVirtual' could not be found (are you missing a using directive or an assembly reference?)
26>Done building project "VTables.Tests.CSharp.csproj" -- FAILED.
12>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5534,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" "D:\CppSharp\CppSharp-main\bin\Release_x64\CLI.Gen.dll"" exited with code -532462766.
12>Done building project "CLI.Gen.csproj" -- FAILED.
========== Build: 14 succeeded, 12 failed, 0 up-to-date, 0 skipped ==========

**Comment by ddobrev** [comment]
@reno77 I'm a little confused: you use windows but generate your solution on Linux? This cannot work. Is there a reason you don't generate your solution directly on windows?

**Comment by reno77** [comment]
HI , I wasn't sure how to run the bash command in Windows, I'm using Windows Server 2019.. 
I assumed I had to install WSL in Windows in order to run it ?

**Comment by ddobrev** [comment]
@reno77 I'm glad you've built it now. By the way, we also have a NuGet package you can use.
In case you have no further trouble, please close this report.
