### ISSUE TITLE
Assistance needed with getting started on a C# wrapper project

### ISSUE THREAD

**Issue by kmgallahan** [mono/CppSharp#1617]
##### Brief Description

Hi there. I'm trying to create a wrapper for [Sony's Camera Remote SDK](https://support.d-imaging.sony.co.jp/app/sdk/licenseagreement_d/en-US.html) via CppSharp for consumption on Windows. 

Part of my problem is that the generated code isn't usable as-is, so I'm manually tweaking it. I'm semi-competent with C#, but haven't worked with C++ since ~2003. I've made some progress in that I can initiate a connection to a camera, but now I'm hitting memory access related errors during VTable setup, so I want to step back and see if there are any problems with my code gen config.

I sent an email to the CppSharp support address but haven't heard back yet. Also checked the Gitter channel but it doesn't appear to be very active.

Thanks for your time.

[**Project repo with VS solution, SDK headers, and current output**](https://github.com/kmgallahan/AllSystemsGo.SonyCameraRemoteCSharp)

First two issues I could use help with:

[CppSharp generates code with compilation error CS0213](https://github.com/kmgallahan/AllSystemsGo.SonyCameraRemoteCSharp/issues/1)

[Generated code for IDeviceCallback has multiple problems](https://github.com/kmgallahan/AllSystemsGo.SonyCameraRemoteCSharp/issues/2)

OS: Windows

##### Used headers

https://github.com/kmgallahan/AllSystemsGo.SonyCameraRemoteCSharp/tree/master/SonyCameraRemoteCSGen/src/CRSDK

##### Used settings

https://github.com/kmgallahan/AllSystemsGo.SonyCameraRemoteCSharp/blob/master/SonyCameraRemoteCSGen/src/Program.cs

Target: MSVC

##### Stack trace or incompilable generated code

See above linked issues

**Comment by tritao** [comment]
Hey @kmgallahan, sorry I never got back to you on this, I missed this issue.

Did you get things to work and/or do you still need support?
