### ISSUE TITLE
Does CppSharp 0.11.2 support the .net framework 4.8

### ISSUE THREAD

**Issue by zzsailor** [mono/CppSharp#1618]
Recently we use the CppSharp in our project.  We tried first the latest version(0.11.2), but it seems not working when the project is targeted on the .net framework 4.8. So we have to revert to the old CppSharp 0.10.5.

But I checked the cppshapr nuget package [homepage](https://www.nuget.org/packages/CppSharp/), one of its dependency is .net standard 2.0, which means the .net framework 4.8 should be supported.

 Does the cppsharp 0.11.2 support .net framewrok 4.8?  Or is the description in the nuget package homepage wrong?  Any clarification is appreciated.

**Comment by tritao** [comment]
Newer versions are only compatible with .NET Core, use the older versions for .NET Framework.

**Comment by Mihi** [comment]
The release notes of CppSharp 0.11.1 state:
"Restore backwards compatibility with .NET Framework"
https://www.nuget.org/packages/CppSharp/0.11.1
It also lists .NET Standard 2.0 as dependency. According to https://docs.microsoft.com/en-us/dotnet/standard/net-standard this means that .NET Framework 4.6.1+ should be supported.

If only .NET Core 3.0 and .NET 5 are supported then it should list a dependency to .NET Standard 2.1.

So for future releases is there really no support for .NET Framework even though you state that backwards compatibility with .NET Framework was restored?

**Comment by tritao** [comment]
To be honest I don't know, @ddobrev are newer releases supposed to still work with .NET Framework?

**Comment by ddobrev** [comment]
@tritao to make it clear: we're talking about the generators here, not the generated code. Then the answer is no, we don't. You might remember I wanted to about 9 months ago, but you blocked the only way of .NET Standard 2.0 because it lacks default interface implementations. You said you needed them for some supposed refactoring or feature, neither of which are done to this day.

**Comment by tritao** [comment]
OK, so to make it clear: You can still use CppSharp generated code with .NET Framework.
But to generate the code, going forward, only .NET Core is supported.

**Comment by Mihi** [comment]
Sad to hear it but thanks for clearing that up.
You might still want to change the dependency on nuget.org to .NET Standard 2.1 to avoid confusion.
Problem is that I'm stuck with .NET Framework for the time being but the old version of CppSharp seems to have problems with PackageReferences and/or SDK style projects.
The post build task to copy the CppSharp dlls does not work properly and it is only possible to use with a workaround. I've seen later versions of CppSharp don't need Nuget.contrib anymore for deployment but they don't work with .NET Framework.
