### ISSUE TITLE
UserManual.md says std::wstring is supported, but this is not ture

### ISSUE THREAD

**Issue by strentler** [mono/CppSharp#1620]
The UserMaunal.md says that there is support for std:::wstring.

When looking at this PR:
**https://github.com/mono/CppSharp/pull/983**

the documentation seems to be wrong.

This feature is still in development right?!

**Comment by tritao** [comment]
That part of the manual was written when it was C++/CLI only, I've updated it now with correct information for C# too.

https://github.com/mono/CppSharp/commit/37103805d9c830c5fdf3cd5fa17ec7d58d3e0f11
