### ISSUE TITLE
 fatal: 'xxx' file not found

### ISSUE THREAD

**Issue by fallingrust** [mono/CppSharp#1638]
##### Brief Description
I built a project to test,but got error.Is there a wrong setting?

OS: Windows / OS X / Linux (include version and/or distro)
Windows 10  VS2019 16.11.5    CppSharp 1.0.0

##### Used headers
 string

##### Used settings
```
 var options = driver.Options;
  var parserOptions = driver.ParserOptions;
 
  parserOptions.SetupMSVC(VisualStudioVersion.VS2019);           
  options.OutputDir = @"C:\Users\CXJ\Desktop\player\OUTPUT";
  var module = options.AddModule("CalculateLib");
  options.GeneratorKind = GeneratorKind.CSharp;
  module.Libraries.Add("CalculateLib.dll");
  module.LibraryDirs.Add(@"C:\Users\CXJ\source\repos\CalculateLib\x64\Release");
  module.Headers.Add("calculate.h");
  module.IncludeDirs.Add(@"C:\Users\CXJ\source\repos\CalculateLib\CalculateLib");
```

Target: MSVC/GCC/Clang

Other settings 

##### Stack trace or incompilable generated code

```
Parsing libraries...
Parsed 'CalculateLib.dll'
Parsing code...
Error parsing 'calculate.h'
C:\Users\CXJ\source\repos\CalculateLib\CalculateLib\calculate.h(1,9): fatal: 'string' file not found
```

**Comment by tritao** [comment]
Try again with `parserOptions.Verbose = true` and paste the output of the includes setup.

**Comment by fallingrust** [comment]
I try with parserOptions.Verbose = true  and I know the problem caused by the lack of MSVC tool(14.25.28610).I download this tool but  crtdbg.h file not found,so i try with module.IncludeDirs.Add(@"C:\Windows Kits\10\Include\10.0.19041.0\ucrt"),and it worked well.

Parsing libraries...
Parsed 'CalculateLib.dll'
Parsing code...
Compiler argument: -fms-extensions
Compiler argument: -fms-compatibility
Compiler argument: -fdelayed-template-parsing
Compiler argument: -xc++
Compiler argument: -std=gnu++14
Compiler argument: -fno-rtti
Compiler argument: -fms-extensions
Compiler argument: -fms-compatibility
Compiler argument: -fdelayed-template-parsing
Target triple: x86_64-pc-windows-msvc
#include "..." search starts here:
#include <...> search starts here:
 C:\Users\CXJ\source\repos\CalculateLib\CalculateLib
 lib\clang\14.0.0\include
 C:\VS2019 Community\Commutity\VC\Tools\MSVC\14.25.28610\include
End of search list.
Error parsing 'calculate.h'
C:\VS2019 Community\Commutity\VC\Tools\MSVC\14.25.28610\include\yvals.h(12,10): fatal: 'crtdbg.h' file not found
CppSharp has encountered an error while parsing code.
