### ISSUE TITLE
dont  throw exceptions in the C# code generated by cppsharp

### ISSUE THREAD

**Issue by upretyrohan** [mono/CppSharp#1652]
Is there way we can tweak some settings while generating the CSharp Bindings, so that cppsharp dont  throw exceptions in the generated C# code 

CppSharp throws exception in copy constructors like
if (ReferenceEquals(_0, null))
                    throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");

and in some methods related to VTables
if (!NativeToManagedMap.ContainsKey(instance))
                    throw new global::System.Exception("No managed instance was found");

Can we avoid this, so that these exceptions are not there.

**Comment by tritao** [comment]
Why are these exceptions a problem?

It would be possible to implement an option for this, but it would be good to understand the use case first.

**Comment by upretyrohan** [comment]
I don't throw exceptions in production code, because many users disable exception handling.
Since only cppsharp is throwing it , i need to catch them and map it to an error and return it to the user.
If Cppsharp only provides a way to disable this, it would make my work easier.

**Comment by upretyrohan** [comment]
I don't  throw exception in production code, since many users disable exception handling.
Since only cppsharp is throwing exception, i need to map cppsharp exceptions to error and return it to user.
If CppSharp has an option to disable exception, it would reduce my effort.

**Comment by tritao** [comment]
I had never heard of people disabling exceptions in .NET / C# code before, which platform are you targetting?

Anyway since this is such a niche case I don't think it makes sense for us to add an option for this.
