### ISSUE TITLE
All documentation out of date and fully incomplete

### ISSUE THREAD

**Issue by GideonUng** [mono/CppSharp#1653]
##### Brief Description

is this project even maintained?
all documentation seems to be out of date to some degree and completely lacking.
wiki and files under docs/ are out of sync.
there are also no comments that could lead me anywhere. function naming doesnt seem this projects strong suit either.
Examples dont build.
My example which tries to follow the very lacking `GeneratingBindings.md` runs outputs all kind of things to the console but no target file ever gets generated. But there is aboslutely nothing that helps me find out why since thats all the documentation seems to say about it.

OS: Windows / OS X / Linux (include version and/or distro)
-

##### Used headers
-

##### Used settings
-

Target: MSVC/GCC/Clang
-

Other settings 
-

##### Stack trace or incompilable generated code
-

**Comment by tritao** [comment]
> is this project even maintained?

As you can see we have PRs being merged as recent as a few days ago.

> all documentation seems to be out of date to some degree and completely lacking.

Please file an issue about which sections are out of date, and what you find lacking and maybe we can improve it.

> wiki and files under docs/ are out of sync.

This is from the main wiki page: **`The Wiki is outdated! Please use the docs inside the repository instead.`**

I am sorry you are not having a good experience, but overall you are coming across as just complaining.
Remember this is an open source project, we are not getting paid for anything.

Anyone is free to help improve the project by sending PRs.

Feel free to open other issues with some more concrete issues you are facing or suggestions.

**Comment by GideonUng** [comment]
> Please file an issue about which sections are out of date, and what you find lacking and maybe we can improve it.
lol literally everything. 
and yes i am complaining since i have a hard time understanding the level of incompetence at play here
