### ISSUE TITLE
Generating 32-bit bindings: FileNotFoundException for CppSharpGenerator.dll

### ISSUE THREAD

**Issue by aybe** [mono/CppSharp#1704]
##### Brief Description

I realized that I had to generate the code twice because mangled names are different for 64-bit.

However, when switching the generator to 32-bit, I get FileNotFoundException for CppSharpGenerator.dll.

Looking at the [nuget package](https://github.com/mono/CppSharp/pkgs/nuget/CppSharp), it isn't present, hence the error.

So, how does one generates code for 32-bit? Build the project by myself but in 32-bit?

Thank you.

**Comment by aybe** [comment]
Works amazingly well!

Now I have another problem, having an AnyCPU assembly won't work because of differing imports.

I've been thinking to generate twice, then have an upper assembly that would load the appropriate bit-ness.

In your opinion, is that a good approach or maybe there's a better one?

Thank you :)

**Comment by Tyrion3000** [comment]
@tritao Sorry to bother you but what method would be best used to combine the MSIL into a single Dynamic Library? ILDASM? ILSpy?

**Comment by aybe** [comment]
@tritao

I just gave it a try today but then I faced a wall, let me explain:

Generating the bindings for both 32-bit and 64-bit ✔
Creating separate assemblies producing respective binaries ✔
Creating an outer assembly with [embedded resource strategy](https://learn.microsoft.com/en-us/archive/blogs/microsoft_press/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition) ✔

Then I made a little test app but then realized that there are no classes at all in the outer assembly. 🤣
Somehow, that outer assembly should be a [reference assembly](https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies) for the test program else it would never build, i.e.🐔🥚

I thought about two alternative options:

- generate two different assemblies and two nuget packages
  - very easy, no changes necessary, immediately doable
  - the downside is that there will be two packages and so on
- rewrite the bindings with Roslyn
  - generate a wrapper class that dispatches calls to either the class with 32-bit imports or the one with 64-bit imports
  - not sure, sounds like it's a bit overkill though not impossible

Or, as one suggested, drop off 32-bit binaries; just as you guys did with CppSharp, problem is immediately solved 😁

I think I'll give a last try with the Roslyn approach, if that fails somehow, I'll have two options to fallback on.

Anyway, thank you for your support! 😀

**Comment by aybe** [comment]
@tritao 

Hello and happy new year! 🥳

Long story short, Roslyn worked out, it was slightly more involved than I expected though...

Basically that's how I rewrote everything to accommodate decorated names: 

```
public class Whatever
{
	internal partial struct __Internal
	{
		// keep fields
		// remove methods
	}

	internal partial struct __Internal32
	{
		// remove fields
                // insert 32-bit methods
	}
	
	internal partial struct __Internal64
	{
		// remove fields
                // insert 64-bit methods
	}
	
	public static void Test()
	{
		if (IntPtr.Size == 4)
		{
			__Internal.__Internal32.Test();
		}
		else
		{
			__Internal.__Internal64.Test();
		}
	}
}
```

The rewriter is only about 200 lines of code but getting it right was tedious due to how incredibly detailed Roslyn is.

It can be thrown against any generated module and will work, I rewrote two projects with it and it just worked.

For those interested,

The part that parses the two trees, 32-bit and 64-bit then passes them to the rewriter:
https://github.com/aybe/DearImGui/blob/develop/DearGenerator/CodeGenerator.cs#L348

The rewriter itself: 
https://github.com/aybe/DearImGui/blob/develop/DearGenerator/CodeGeneratorRewriter.cs

The kind of Frankenstein module it then produces:
https://github.com/aybe/DearImGui/blob/develop/DearImPlot/ImPlot.g.cs

The generator project itself, quite polished now though it could always be improved:
https://github.com/aybe/DearImGui

I then encountered two errors while trying to build the the AnyCPU which I solved like so:

- `size_t`: CppSharp translates this but that's inappropriate, solution was a type map to `UIntPtr`
- for some reason, during 64-bit generation, CppSharp uses `IntPtr` instead of passing a struct, solved with regex

Finally, the last thing I did is replace stock `SymbolResolver` by a [custom one](https://github.com/aybe/DearImGui/blob/develop/DearImGui/SymbolResolver.cs) so it loads 32-bit and 64-bit accordingly.

The result is great, you just change `<PlatformTarget>` in the consumer app as you'd usually so and it just works 😎.

Thanks for your help and have a good year!
