### ISSUE TITLE
Lots of ignored functions, due to std::shared_ptr

### ISSUE THREAD

**Issue by frankenherm** [mono/CppSharp#1738]
##### Brief Description
I tried to use CppSharp for a wrapper for some Orbbec SDKs and am struggling with some of the functions missing. Mostly the functions are missing because of returning `std::shared_ptr<>`, which seems to be not supported.

Is there anything I can do to continue to work?

OS: Windows / OS X / Linux (include version and/or distro)
Win 11

##### Used headers
[libobsensor.zip](https://github.com/mono/CppSharp/files/11781622/libobsensor.zip)

##### Used settings

            driver.Options.Verbose = true;
            driver.ParserOptions.Verbose = true;
            driver.ParserOptions.AddArguments("-fcxx-exceptions");

            var options = driver.Options;
            options.DryRun = false;
            options.GenerationOutputMode = GenerationOutputMode.FilePerUnit;
            options.OutputDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "out");
            options.GeneratorKind = GeneratorKind.CSharp;

            options.CheckSymbols = true;

Target: MSVC/GCC/Clang
I used the current nuget package with VS2022, running with ` x64_x86 Cross Tools Command Prompt for VS 2019`
(MSVC 14.29.30133)

Other settings 

##### Stack trace or incompilable generated code
[cppsharp.log](https://github.com/mono/CppSharp/files/11781614/cppsharp.log)

**Comment by frankenherm** [comment]
thats what I did, thanks.

**Comment by jcyuan** [comment]
> options.CheckSymbols = true;

hi @frankenherm  how did you fix this please? i'm encountering the same.

**Comment by frankenherm** [comment]
I wrote a wrapper class layer, which manages the `std::shared_ptr` of each object and just expose a regular pointer instead.
