### ISSUE TITLE
MinGW symbols not found

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#21]
While wrapping QtCore, no symbol is found. The searched for symbols (that is, the parameter "symbol" of Library.FindSymbol) have a format similar to:

??0QForeachContainerBase@@QEAA@XZ

while the keys of Library.Symbols are of the formats:

__imp___Zls6QDebugRK21QPersistentModelIndex
_z_inflatePrime

Changing Driver.Options.Abi to Itanium (the default is Microsoft) makes no difference.

**Comment by TechnikEmpire** [comment]
Could you clarify this? I don't want name mangling at all. I tried to set the LanguageVersion to C and that just crashes everything with warnings about using the GNU standard C library with "C++ objects"

**Comment by tritao** [comment]
Based on what you said I cannot tell what the issue might be or it is related to this issue.

Please open a new issue and provide more information so that we can help.

**Comment by TechnikEmpire** [comment]
@tritao Done, thanks for your time.
