### ISSUE TITLE
Ability to mark generated methods as internal

### ISSUE THREAD

**Issue by JamesLupiani** [mono/CppSharp#264]
First off, thanks for your work on CppSharp, it's been a breeze to work with!

I'd like to request a macro (perhaps CS_INTERNAL?) to mark generated methods as internal so they aren't visible outside an assembly. The reason is sometimes I want to make the API a little more C#-like and hide some details to prevent user confusion with overloads.

**Comment by tritao** [comment]
Fixed by https://github.com/mono/CppSharp/pull/448

**Comment by JamesLupiani** [comment]
Thanks @genuinelucifer and @tritao!
