### ISSUE TITLE
Fix the calls of explicit destructors to avoid double freeing

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#312]
Only the most derived destructor has to be called.

**Comment by tomspilman** [comment]
I've run into this too.  Basically the top most overloaded `Dispose(bool disposing)` is all that needs to be called...  it needs to handle calling the destructor and it needs to free the object memory.

My fix was a change in `CSharpTextTemplate.GenerateDisposeMethods()`...

https://github.com/mono/CppSharp/blob/4e7896b8b6aae94140ed5bfc6c8ac96455f9ac2f/src/Generator/Generators/CSharp/CSharpTextTemplate.cs#L1711

```
            if (!@class.IsStatic && @class.IsRefType) // REPLACED ShouldGenerateClassNativeField(@class))
            {
                var dtor = @class.Methods.FirstOrDefault(method => method.IsDestructor);
                if (dtor != null)
                {
                    if (dtor.Access != AccessSpecifier.Private && @class.HasNonTrivialDestructor)
                    {
                        NativeLibrary library;
                        if (!Options.CheckSymbols ||
                            Driver.Symbols.FindLibraryBySymbol(dtor.Mangled, out library))
                        {
                            WriteLine("Internal.{0}({1});", GetFunctionNativeIdentifier(dtor),
                                Helpers.InstanceIdentifier);
                        }
                    }
                }

                WriteLine("Marshal.FreeHGlobal({0});", Helpers.InstanceIdentifier);
            }
            
            // REMOVED!            
            //if (hasBaseClass)
                //WriteLine("base.Dispose(disposing);");
```
There could be a better fix. Like maybe just testing for the existence of a destructor and making sure it is called.

Thoughts @tritao ?

**Comment by tritao** [comment]
Fix makes sense and looks good to me. I'll try to come up with a test case and push this in later.

**Comment by tomspilman** [comment]
Thanks @tritao !

**Comment by ddobrev** [comment]
I cannot remember since when but we no longer call base `Dispose` methods, if any.
