### ISSUE TITLE
Improve ParamTypeToInterfacePass to only ignore the first param of operators

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#334]
C# requires the first param to match the containing type but the rest can be anything so we'd better map them to their interfaces, if any.

**Comment by genuinelucifer** [comment]
@ddobrev 
Did you mean to ignore the 1st param for Operators and for the rest params do as for other functions?
Something like:
```Diff
diff --git a/src/Generator/Passes/ParamTypeToInterfacePass.cs b/src/Generator/Pa
index 34f1cea..6717097 100644
--- a/src/Generator/Passes/ParamTypeToInterfacePass.cs
+++ b/src/Generator/Passes/ParamTypeToInterfacePass.cs
@@ -7,13 +7,13 @@ public class ParamTypeToInterfacePass : TranslationUnitPass
     {
         public override bool VisitFunctionDecl(Function function)
         {
-            if (!function.IsOperator)
+            ChangeToInterfaceType(function.ReturnType);
+            bool isFirstParam = true;
+            foreach (Parameter parameter in function.Parameters)
             {
-                ChangeToInterfaceType(function.ReturnType);
-                foreach (Parameter parameter in function.Parameters)
-                {
+                if(!function.IsOperator || !isFirstParam)
                     ChangeToInterfaceType(parameter.QualifiedType);
-                }
+                isFirstParam = false;
             }
             return base.VisitFunctionDecl(function);
         }
```

**Comment by ddobrev** [comment]
@genuinelucifer yes, this is exactly what I mean. However, please do not check for the first parameter this way but rather by checking Parameter.Kind for OperatorParameter. In fact, you should be able to remove the check for an operator and simply exclude any operator parameters from the loop:

        public override bool VisitFunctionDecl(Function function)
        {
            ChangeToInterfaceType(function.ReturnType);
            foreach (Parameter parameter in function.Parameters.Where(p => p.Kind != ParameterKind.OperatorParameter))
                ChangeToInterfaceType(parameter.QualifiedType);
            return base.VisitFunctionDecl(function);
        }

**Comment by genuinelucifer** [comment]
@ddobrev wouldn't it exclude all the parameters (not just the first) for any operator?

**Comment by ddobrev** [comment]
OperatorParameter is used only for the special first parameter C# requires to be of the containing type.

**Comment by genuinelucifer** [comment]
@ddobrev So, this is the final solution what you gave! Should i open a pull request only with this? or is there something more to it?

**Comment by ddobrev** [comment]
@genuinelucifer there's just a test to add to verify my solution actually works, I wrote it in the blind, you know.

**Comment by genuinelucifer** [comment]
@ddobrev This might seem silly but what does this function actually do? I mean how do i define an interface in C++ and what is @interface for a parameter??

**Comment by ddobrev** [comment]
I assume you're asking this question just to be clear, not that you need it for the fix itself.
C++ does not have interfaces. It has multiple inheritance. C# doesn't so we have to emulate secondary base classes with C# interfaces.

**Comment by genuinelucifer** [comment]
Well, partly because of both reasons. I could not find why we have to use
ParamTypeToInterfacePass at all!
Because I thought C++ doesn't have interfaces so how are interfaces coming
into picture!

**Comment by genuinelucifer** [comment]
@ddobrev  Thanks..
Well, I had to change a few bits here and there and it is working okay.
Except that "ParameterKind.OperatorParameter" is set only for first param of normal operators. For constructors such as:
```C#
class DLL_API P : Proprietor
{
public:
    P(const Qux& qux);
    P(Qux* qux);                          //This one
```
following is generated:
```C#
public static implicit operator P(Qux qux)
```
and the function is marked with IsOperator but the first parameter is NOT marked with ParameterKind.OperatorParameter...
Should I mark the first param for this declaration with ParameterKind.OperatorParameter or should I check for first parameter in some other way?

**Comment by genuinelucifer** [comment]
@ddobrev  Please see #495.

**Comment by tritao** [comment]
https://github.com/mono/CppSharp/pull/495
