### ISSUE TITLE
Build website status?

### ISSUE THREAD

**Issue by gpetrou** [mono/CppSharp#396]
Hello,
has the build website (builds.tritao.eu) changed? It does not seem to be available anymore.

**Comment by teichgraf** [comment]
Would appreciate if you get it up and running again. :)

**Comment by Dreamwalker666** [comment]
+1 :)

**Comment by kevkon3** [comment]
+1

**Comment by hima3024** [comment]
+1

**Comment by tritao** [comment]
We have a Travis and AppVeyor build bots now.
