### ISSUE TITLE
A bug introduced by the recent base classes offset commit

### ISSUE THREAD

**Issue by golddranks** [mono/CppSharp#403]
Hi, now Qt generation crashes with this kind of code:

(from QtCore's global.h)

    template <class T>
    struct AlignOf_Default
    {
        enum { Value = sizeof(AlignOfHelper<T>) - sizeof(T) };
    };

    template <class T> struct AlignOf : AlignOf_Default<T> { };

For reason or another, the 

        auto BaseDecl = BS.getType()->getAsCXXRecordDecl();

line in the parser.cpp, introduced in the newest commit, returns NULL for AlignOf's base type's declaration. It seems that the check isn't exhaustive, so AlignOf_Default which is a TemplateSpecialization itself, comes out as NULL.

I have no time to fix it right away, but at least the problem seems to be clear.

**Comment by tritao** [comment]
Thanks for the bug report, I had tested with Qt but for some reason did not catch this before.
