### ISSUE TITLE
QtCore regression introduced by friend classes support

### ISSUE THREAD

**Issue by golddranks** [mono/CppSharp#409]
Before friend classes support, the generated QMap wrapper looked like this: 

    public unsafe partial class QMap
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct Internal
        {
            [FieldOffset(391495169)]
            public global::System.IntPtr d;
        }

        public unsafe partial class Const_iterator
        {
            [StructLayout(LayoutKind.Explicit, Size = 0)]
            public partial struct Internal
            {
                [FieldOffset(391495169)]
                public global::System.IntPtr i;
            }
        }

        public unsafe partial class Iterator
        {
            [StructLayout(LayoutKind.Explicit, Size = 0)]
            public partial struct Internal
            {
                [FieldOffset(391495169)]
                public global::System.IntPtr i;
            }
        }
    }

After the support landed, it reduced to this:

    public unsafe partial class QMap
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct Internal
        {
        }
    }

...but the code still tries to access QMap.Const_iterator. I don't know yet what causes this regression, but I'll try to reproduce it as a test.

**Comment by golddranks** [comment]
I think that the same problem manifests with another bug:

    public unsafe partial class QList
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct Internal
        {
            [FieldOffset(391495169)]
            internal QList._.Internal _0;
        }

        internal unsafe partial class Node
        {
            [StructLayout(LayoutKind.Explicit, Size = 0)]
            public partial struct Internal
            {
                [FieldOffset(391495169)]
                public global::System.IntPtr v;
            }
        }

        internal unsafe partial struct _
        {
            [StructLayout(LayoutKind.Explicit, Size = 0)]
            public partial struct Internal
            {
                [FieldOffset(391495169)]
                public QListData.Internal p;

                [FieldOffset(391495169)]
                public global::System.IntPtr d;
            }
        }

        public unsafe partial class Const_iterator
        {
            [StructLayout(LayoutKind.Explicit, Size = 0)]
            public partial struct Internal
            {
                [FieldOffset(391495169)]
                public global::System.IntPtr i;
            }
        }

        public unsafe partial class Iterator
        {
            [StructLayout(LayoutKind.Explicit, Size = 0)]
            public partial struct Internal
            {
                [FieldOffset(391495169)]
                public global::System.IntPtr i;
            }
        }
    }

    public unsafe static partial class QListSpecialMethods
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct Internal
        {
        }
    }

Turns into

    public unsafe static partial class QList
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct Internal
        {
        }
    }

**Comment by tritao** [comment]
Thanks for spending some time on this regression, I'll look into this today.

**Comment by golddranks** [comment]
Has this advanced at all?

**Comment by golddranks** [comment]
https://github.com/golddranks/CppSharp/tree/friend_test 

I made a simple test to help diagnosing. Placed it to CSharpTemp, but I'm unsure what that project is for? Is Temp short for templates or for temporary?

**Comment by tritao** [comment]
Temporary. We really should remove the Temp from the test names, they're not temporary anymore and keep CLI and CSharp-specific tests.
