### ISSUE TITLE
Provide support for collections for P/Invoke bindings

### ISSUE THREAD

**Issue by teichgraf** [mono/CppSharp#410]
std::vector or std::array is quite common and it would be great if it can be used to pass collections between C/C++ and C#. Please add support for std::vector (or std::array) and that the CppSharp Runtime supports a proper wrapper implementing IList, ICollection, etc. 

C++
            std::vector<MyModel> GetModels() {return _models; }

Should generate C#:
            Std.Vector<MyModel> Models { get { return ... } }

The Std.Vector class would be part of the CppSharp Runtime and implement IList<>, ICollection<>, etc.
It seems like this is actually partly supported for C++/CLI. Would be great if you can extend it to support P/Invokes as well. 

If std::vector or std:array is an issue and needs to much work to handle then something like this would also work where you pass raw pointers:

```
    void GetArrayModels(MyModels** result, int* length) 
    { 
         *result = _models.data(); 
         *length = _models.size() 
    }
```

You parser code could search for the magic sting "GetArray" in methods / functions and use it to generate the right Models property handling the array interop. Or a similar convention for a method signature.

Makes sense?

**Comment by tritao** [comment]
Closing, collection support is coming with template support.
