### ISSUE TITLE
Recent patch fix the regression when parsing class templates but introduced a new one

### ISSUE THREAD

**Issue by golddranks** [mono/CppSharp#411]
Commit bf9fb6412085771c3174aababe95b37ae719a89a, a simple change, patches the regression, but now QtCore generation crashes right away.

It fixes the patch by circumventing a check that is done inside `Class* Parser::WalkRecordCXX(clang::CXXRecordDecl* Record)`. The check is about if the `Process` bool returned by `GetRecord` is false or true. The patched version continues processing regardless of the check and crashes while trying to access the Record->IsPOD() getter when processing a templated struct called `QIntegerForSize`. The Process is false because `isCompleteDefinition` isn't true.

So, the processing SHOULD continue for some classes, i.e. for QMap but SHOULDN'T continue for some, i.e. QIntegerForSize? What separates them?

I made a test to ease up the bugfixing, again:

https://github.com/golddranks/CppSharp/tree/test_regression

**Comment by tritao** [comment]
`So, the processing SHOULD continue for some classes, i.e. for QMap but SHOULDN'T continue for some, i.e. QIntegerForSize? What separates them?`

The problem is that we should not continue processing forward declarations, which is what the `Process` check was actually doing.
