### ISSUE TITLE
Easier entry level.

### ISSUE THREAD

**Issue by txdv** [mono/CppSharp#421]
Hey, I have finally been able to compile your project, however, the only way is to use the command line.

This makes a few things hard, like, one can't browse the code with VisualStudio or MonoDevelop in order to learn it.

Is there any way to create the solutions files for all the projects so one can explore/browse the code with a normal IDE?

**Comment by tritao** [comment]
Yes, run `premake vs2012`and you will get solutions that you can use with MonoDevelop/Xamarin Studio. You'll still probably need to compile via the command line but at least that'll allow you to get some code-completion. I use that technique on OSX myself.

**Comment by txdv** [comment]
Well, good enough for me. Thanks.
