### ISSUE TITLE
Header included more than once breaks method names.

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#435]
ClassA.h defines ClassA and includes ClassY.h
ClassB.h defines ClassB and includes ClassY.h
ClassA, ClassB, and ClassY are all marked for export.

The C# class generated for ClassY ends up appending '1' to all its method names. Eg, ClassY::Init() in C++ becomes ClassY.Init1() in C#.

Note that ClassY.h is protected by header guards, since it needs to be included in more than one other header file. I assume this situation is not dealt with well by CppSharp and/or may be related to the problem.

**Comment by tomspilman** [comment]
This is still a problem almost a year later.  This causes all sorts of confusion when using CppSharp.

**Comment by genuinelucifer** [comment]
@ddobrev I created the 3 headers in the same folder as the CSharp test project files. But, I could not generate their C# files. I also tried to add them to premake4.lua in the CSharp folder by changing
```SetupTestCSharp("CSharp")```
to
```SetupTestCSharp("CSharp", {"ClassA", "ClassB", "ClassY"})```
but it didn't work.
How do I add them to any test to generate the output c# files?

**Comment by ddobrev** [comment]
Where exactly are your new headers located? If you place them in CppSharp/tests/CSharp, they should appear as soon as you have regenerated your C++# solution.

**Comment by tritao** [comment]
Hey guys (cc @jamesford42 @tomspilman)

We'd like to get this fixed but @genuinelucifer is having trouble reproducing the issue.

Can you look at https://github.com/mono/CppSharp/pull/620/files and see what we're missing?

**Comment by tomspilman** [comment]
@tritao - Maybe using `#pragma once` instead of header guards?

**Comment by tritao** [comment]
I can't see it making any difference, it should be equivalent, but give it a shot @genuinelucifer.

**Comment by genuinelucifer** [comment]
Tried, didn't work. @tritao @tomspilman

**Comment by tomspilman** [comment]
@genuinelucifer - Maybe it is in how we normally include the files in the generation process:
```
            options.Headers.Add(@"ClassA.h ");
            options.Headers.Add(@"ClassB.h ");
            options.Headers.Add(@"ClassY.h");
```

**Comment by genuinelucifer** [comment]
Umm. In tests the exact same thing is done via ```GeneratorTest.cs```
So, probably won't make much difference. I'll to test anyway.

**Comment by ddobrev** [comment]
@tomspilman could you perhaps gradually decrease your real code to a test case?

**Comment by tomspilman** [comment]
@ddobrev - Will do...  should have a test case for you in an hour or so.

**Comment by ddobrev** [comment]
@tomspilman thank you very much. @genuinelucifer could you please try with @tomspilman 's test case when it's been completed?

**Comment by ddobrev** [comment]
Hello @tomspilman . Have you had any success with the test case?

**Comment by tomspilman** [comment]
Sorry... got sucked into another problem.  I'll get you a test case tonight.

**Comment by ddobrev** [comment]
@tomspilman there apparently are some specifics in your code which cause the error. I am afraid we cannot proceed with this issue without a test case. So feel free to let us know when you have it.
