### ISSUE TITLE
Incorrect line number of friends

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#439]
Steps to reproduce:

1. Add the following code:

```cplusplus
friend inline const TestTemplateClass2 operator+(const TestTemplateClass2& f1, const TestTemplateClass2& f2);
```

to HasConstFunction in AST.h;

2. Add the following code:

```cplusplus
inline const TestTemplateClass2 operator+(const TestTemplateClass2& f1, const TestTemplateClass2& f2)
{
    return TestTemplateClass2();
}
```
 at the end of AST.h;

3. Add the following code:

```csharp
[Test]
public void TestLineNumberOfFriend()
{
    Assert.AreEqual(81, AstContext.FindFunction("operator+").First().LineNumber);
}
```
to TestAST.cs;

4. Run the test from 3.

The test fails because the reported location is 74 - the location of the friend declaration. However, the friend itself is located at about 81 (depending on the number of inserted empty lines).

**Comment by tritao** [comment]
Fixed by https://github.com/mono/CppSharp/commit/99c124eb53876f94b122d088a3180e2bf1b2a078.
