### ISSUE TITLE
Generate delegates in a separate file and reuse them instead of generating them each time

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#498]
At the moment when we need a delegate - v-tables, abstract impls, etc, we generate it in the same file. This leads to repetition, bloated API-s and binaries, etc. So we need to generate such delegates in a location independent of the bound API, and reuse them if possible. That is, maintain a dictionary of those delegates, and whenever we need one for a function, check by its signature - if a match is found, use it, if not, add it. This dictionary needs to be static so that it lasts for the lifetime of the generator app. This would allow it to be reused in dependent modules. When generating code at the end, the list of these delegates has to be generated too, best in a separate file.

We could use a convention similar to .NET's:

for functions returning a value: Func_<return_type>_<parameter_type1>_<parameter_type2>_...
for functions not returning a value: Action_<parameter_type1>_<parameter_type2>_...

The reason we cannot use the real Func<> and Action<> is that .NET 4.0, which we want to support because of Windows XP, cannot marshal generic delegates. On the other hand, Mono for Windows dropped XP support not long ago. So we need to stick to generated delegates.

**Comment by genuinelucifer** [comment]
It might be silly. But, I tried a lot to see how to generate a new file using the already present classes and methods but could not do so.
Please help @ddobrev @tritao

**Comment by genuinelucifer** [comment]
@ddobrev I am not certain but I read somewhere online that generic delegates were introduced in .NET 3.5 so i guess .NET 4.0 would be able to Marshal them. Isn't it the case?

**Comment by ddobrev** [comment]
I am afraid that regardless of the time of their introduction, they cannot be marshalled. I myself have wondered how they could add this feature in half but they did.
If you have trouble with a new file, we can start without one. You could, for example, collect all delegates you're going to need and print them at the end of the last code file.

**Comment by genuinelucifer** [comment]
@ddobrev Thanks. Then I will try to generate all the delegates at one place
first...

**Comment by genuinelucifer** [comment]
@ddobrev I am really quite confused on this task. I read much about delegates but that didn't help.
Do we wish to move all the instantiations of the delegates to a separate file/class and call them from each class when needed? If so, how does it help? I know I am missing something here but I actually am unable to get what to do here.

**Comment by ddobrev** [comment]
Hello @genuinelucifer , glad to hear back from you. :)
You have understood it correctly - we want all delegates moved to a separate file and reused as needed. Just in case, here's an example.
What we now do is generate delegates:

protected delegate void _delegate_sampleFunction();

in the class to which functions (void sampleFunction() ) belong. So let's call this class here Class1. Let's also have a class called Class2 with void sampleFunction2(). As you can see, Class1.sampleFunction() and Class2.sampleFunction2() both return void and take no parameters. That is, they both have the same signature. This means the same delegate can be used for both. But since we generate a local delegate for each function, we don't do that at the moment.

Let me know if you have further questions.

**Comment by genuinelucifer** [comment]
After GSoC i was a bit busy with some other projects and college exams.
Finally i am free and would like to resume contributing to Cpp# :)
.
Thanks for the explanation. I'll get back to u if i get stuck.

**Comment by ddobrev** [comment]
Hello @genuinelucifer. A few days ago we found out that the repetition of delegates generates an extremely high amount of warnings in the generated code. This fact raises the priority of issue. I would like to therefore ask you if you have been able to start working on it and if you need any help.

**Comment by genuinelucifer** [comment]
@ddobrev Pls look at #564 . If it doesn't look convincing, you may take over.

**Comment by ddobrev** [comment]
@genuinelucifer don't worry, we're not that much in a hurry. :) I am going to check it out in a few minutes and help you as necessary but I am confident you can do this one too.

**Comment by ddobrev** [comment]
Fixed by fbb2f941c49ee5d034880cd38f1935964d128fa8.
@genuinelucifer I had to make quite a few changes after a discussion with @tritao but your work remained at the core of the solution. Thank you. Let me know when you are ready for your next assigment. :)
