### ISSUE TITLE
Name conflict with generated property with same name as enclosing class

### ISSUE THREAD

**Issue by tritao** [mono/CppSharp#507]
This can happen under the following conditions:
- C++ class: `SBError`, renamed to `Error` in C#
- C++ member with signature `GetError () const;``
- Property generation pass enabled

Generated code:

```
class Error
{
        public uint Error {}
}
```

Error:

`/Users/joao/Dev/LLDBSharp/LLDBSharp/SBError.cs(21,21): Error CS0542: `LLDB.Error.Error': member names cannot be the same as their enclosing type (CS0542) (LLDBSharp)`

**Comment by genuinelucifer** [comment]
@tritao @ddobrev  What would be the acceptable solution? I thought adding '_' would suffice. Any other views?

**Comment by ddobrev** [comment]
This works now as we generate the property lower-cased.
