### ISSUE TITLE
Marshal parameters of type pointers to primitives (int*) as ref params (ref int)

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#509]
Should be pretty straightforward: get the addresses of ref params using unsafe code and pass that to the native code. The only corner case is default argument values because C# ref types cannot have them.

**Comment by genuinelucifer** [comment]
@ddobrev Please review #512 Is it acceptable? I merely changed the parameter usage to InOut for the pointers to primitives without a default value!

**Comment by tritao** [comment]
Fixed by https://github.com/mono/CppSharp/commit/dd941d9191dc8d8e97db07828f2804cba72b7237.
