### ISSUE TITLE
Passing null to a function pointer causes a crash

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#514]
We don't check what we pass to Marshal.GetFunctionPointerForDelegate. To reproduce, set CSharpTemp.Foo.AttributedFunctionPtr to null.

**Comment by genuinelucifer** [comment]
@ddobrev  Please clarify a bit more. It is a typedef. SO how to set it to null?

**Comment by ddobrev** [comment]
@genuinelucifer it's not a typedef - that's how one defines a field with a function pointer type in C++. So that field is wrapped as a property in C# - that's what I meant by setting it to null.

**Comment by xistoso** [comment]
@genuinelucifer 
in CSharpTemp.Tests.cs use this test and you can see it explode
```csharp
    [Test]
    public void TestNullAttributedFunctionPtr()
    {
        var foo = new Foo();
        foo.AttributedFunctionPtr = null;
    }
```

**Comment by genuinelucifer** [comment]
@ddobrev @xistoso Thanks.
