### ISSUE TITLE
Got error "not find lbxml2" when building llvm

### ISSUE THREAD

**Issue by Kiddinglife** [mono/CppSharp#524]

**Comment by Kiddinglife** [comment]
I used build command shown on the "get started " html
cd <CppSharp>\deps\llvm\build
cmake -G "Visual Studio 12" -DCLANG_BUILD_EXAMPLES=false -DCLANG_INCLUDE_DOCS=false -DCLANG_INCLUDE_TESTS=false -DCLANG_INCLUDE_DOCS=false -DCLANG_BUILD_EXAMPLES=false -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_INCLUDE_EXAMPLES=false -DLLVM_INCLUDE_DOCS=false -DLLVM_INCLUDE_TESTS=false

**Comment by ddobrev** [comment]
Are you sure it's not just a warning? Anyway, if you repeatedly have trouble, you can find LLVM x86 binaries at https://dl.dropboxusercontent.com/u/194502/CppSharp/llvm.7z .

**Comment by Kiddinglife** [comment]
this link "https://dl.dropboxusercontent.com/u/194502/CppSharp/llvm.7z " is inaccessiable in China with the warning message showing up in front of my eyes that the server reject the connection of the link.

Man, do you have some other links where downloading can be finished successfully?

**Comment by Kiddinglife** [comment]
i am eager to applying cppsharp in my own game server project....So, help me, hero coder !

**Comment by ddobrev** [comment]
I have no idea where to upload it so that you are guaranteed to have access. Have you tried with https://www.torproject.org/index.html.en ?
