### ISSUE TITLE
The C++/CLI end cannot handle types without public constructors

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#527]
To reproduce, add a class without public ctors (for example, protected ones) to Basic.h or CLITemp.h.

**Comment by genuinelucifer** [comment]
@ddobrev I added following to CLITemp.h and also to Basic.h
```C++
DLL_API class CheckNonPublicConstructors
{
protected:
	CheckNonPublicConstructors();
};
```
But, there were no build errors. Is the code i used not sufficient or is the error meant to be something else?
