### ISSUE TITLE
Anyone knows where are APIs documents?

### ISSUE THREAD

**Issue by Kiddinglife** [mono/CppSharp#529]
i found there are many exposed methods in driver.Options object like options.Libraries.Add() but the meaning of each of them is not well-self-explained. I an now trying to find if there is a API document that introduce the role of every method or variable?

**Comment by Kiddinglife** [comment]
oh, a thing i forgot to say is that whether cppsharp supports static native lib like xxx.so in linux or xxx.lib in win?

**Comment by ddobrev** [comment]
.libs are supported in the sense that they can be read to obtain symbols but they are not executable. .so are supported normally.

You can find some documentation in https://github.com/mono/CppSharp/tree/master/docs. Other than that, you can copy code from Qt# and adjust for your case.
