### ISSUE TITLE
does a generated c-sharp-dll works in embedded mono?

### ISSUE THREAD

**Issue by Kiddinglife** [mono/CppSharp#531]
where my question comes from:
I saw a line of sample code like this:        
[DllImport("Basic.Native.dll", 
CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
EntryPoint="?GetANSI@Foo@@QEAAPEBDXZ")]

My Question:
Say I have a DLL named MonoEmbedCsharp.dll that is built based on a CppSharp-Generated c-sharp file named MonoEmbedCsharp.cs that wraps everything in a c++ file named MonoEmbed.h. The mono env is also embedded in my C++ application. In this case,  can I call a C++ function written in MonoEmbed.h from C# side without using MonoEmbed.Native.dll ? Hopefully, I make myself understood.

Thanks.

**Comment by tritao** [comment]
Yes, that's supported. See the `GenerateInternalImports` option at https://github.com/mono/CppSharp/blob/a1d7e685bca96634724367faaa472e3fe6f0e64a/src/Generator/Options.cs#L96.
