### ISSUE TITLE
Implement IDisposable in the C++/CLI front end

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#538]
Unlike the C# front end, the C++/CLI one does not provide a Dispose method. This is a serious problem because we heavily leak memory and we cannot call Dispose in the AST converter because the code wouldn't compile on platforms (Windows) which use C++/CLI (). So we need a flag marking whether the instance was allocated by the user (as in the C# end) and a Dispose deleting the native pointer if the flag is raised.

**Comment by ddobrev** [comment]
@genuinelucifer could you please take this one after the one for the delegates in case there is time?

**Comment by genuinelucifer** [comment]
@ddobrev I wish to work on CppSharp after GSoC too. So, i guess there will be enough time.. :)

**Comment by genuinelucifer** [comment]
@ddobrev I wish to work on CppSharp after GSoC too. So, i guess there will be enough time.. :)

**Comment by tritao** [comment]
C++/CLI has both destructors and finalizers. It might be work reading https://msdn.microsoft.com/en-us/library/ke3a209d.aspx#BKMK_Destructors_and_finalizers.

**Comment by ddobrev** [comment]
Thank you, Abnihav. :) I appreciate it, you've been of great help and I could only rejoice if you decide to continue working with us.
@tritao I think we should start simple - just implement what we have for the C# end by default. That is, calling the native destructor which in C++/CLI is done as in C++, though the "delete" keyword. About finalisers, we're going to need that too but at a later stage - when I implement automatic memory management.

**Comment by genuinelucifer** [comment]
@ddobrev @tritao  It has really been a great learning experience working with you guys! And really I can say that the past 3.5 months has been the one of the awesomest experiences of my life! ^_^
