### ISSUE TITLE
Regression: uncompilable code for variables (static fields) with a type a fixed array

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#542]
I get this in Qt# after pulling the code for fixed arrays for complex types:

        public static QArrayData[] Shared_null
        {
            get
            {
                var __ptr = (fixed byte*)CppSharp.SymbolResolver.ResolveSymbol("Qt5Core", "_ZN10QArrayData11shared_nullE");
                QArrayData[] __value = null;
                if (*__ptr != null)
                {
                    __value = new QArrayData[2];
                    for (int i = 0; i < 2; i++)
                        __value[i] = QArrayData.__CreateInstance(*((QArrayData.Internal*)&(*__ptr[i * sizeof(QArrayData.Internal)])));
                }
                return __value;
            }
        }

That fails at the "(fixed byte*)" spot. @genuinelucifer could you please make this your top priority? I believe you should be able to reproduce it using:

static Foo[2] variableWithFixedArrayType;

**Comment by genuinelucifer** [comment]
@ddobrev i have fixed the compiling issue. [Will submit the PR in a while]
But, i see that only getter is generated and NOT a setter. Is it intended?

**Comment by ddobrev** [comment]
An excellent question. I think it should have but it's a separate issue. @tritao variables should be writeable, correct?

**Comment by ddobrev** [comment]
@genuinelucifer I've merged your pull and filed https://github.com/mono/CppSharp/issues/545 for the missing setter.
