### ISSUE TITLE
Incorrect sizeof(std::string) in VS2015

### ISSUE THREAD

**Issue by vonzepp** [mono/CppSharp#555]
I have simple class:
```
	class DLL_API ClassWithString
	{
		std::string _str;
		long _long_field;
	};
```
Generated CSharp code is (x64 platform):
```
        public unsafe partial class ClassWithString : IDisposable
        {
            [StructLayout(LayoutKind.Explicit, Size = 40)]
            public partial struct Internal
            {
                [FieldOffset(32)]
                public int _long_field;
...
...
```
The problem is that   sizeof(std::string) == 40   for VC14 compiler. Not 32 bytes!!! So I've got AccessViolation exception in runtime due to memory corruption. Problem is definetely not with "Struct member alignment" setting of visual c++ compiler.

Should be:
```
        public unsafe partial class ClassWithString : IDisposable
        {
            [StructLayout(LayoutKind.Explicit, Size = 48)]
            public partial struct Internal
            {
                [FieldOffset(40)]
                public int _long_field;
```
There are similar problems with other STL types, like: std::vector etc.

**Comment by tritao** [comment]
Did you change your target triple to x86_64?

**Comment by vonzepp** [comment]
Yes, I tried. No changes at all. (with and without "x86_64-pc-win32-msvc" - the same offsets)

**Comment by tritao** [comment]
Enable `options.Verbose = true` and paste the headers paths here so we can make sure it's not some headers paths mismatch.

Also make sure it's not related to any missing defines that you set on VS that might be influencing the size of string (debug checks for instance).

**Comment by vonzepp** [comment]
```
 #include <...> search starts here:
2>   C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt
2>   C:\src\TestProject
2>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
2>  End of search list.
2>  Parsed 'ClassWithString.h'
2>  ignoring nonexistent directory "lib\clang\3.8.0\include"
```
Ok, I've got your idea about things, related to size. I tried to play with  "Struct member alignment", with no result. Also I tried to compile Native c++ code with clang for Windows instead of VC++ (using "Platform Toolset" = LLVM-vs2014). sizeof(std::string) is also 40 for clang compiler.

**Comment by vonzepp** [comment]
I found out that 32 - is Release size of std::string and 40 - is Debug size.
So I generated wrappers for Release code, but used it with Debug version of DLL.
So, the solution is to add into c# generator:
```
        public void Setup(Driver driver)
        {
#if DEBUG
            driver.Options.addArguments("-D_DEBUG");
#endif
```
