### ISSUE TITLE
MS Visual Studio 2015 issues

### ISSUE THREAD

**Issue by vonzepp** [mono/CppSharp#556]
I have final release of VS2015 (14.0.23107.0).
I found 2 problems in cppSharp with VS2015:

1) I have Windows 7 x64 SP1. No addition SDK were installed (except SDK's, shipped with Visual Studio). cppSharp crashes in:
    MSVCToolchain.GetSystemIncludes
I specified function parameter vsVersion = VisualStudioVersion.VS2015 explicitly, due to code:
```
            // Clang cannot deal yet with VS 2015, so remove it from SDKs.
            if (vsVersion == VisualStudioVersion.Latest)
                vsSdks.Remove(vsSdks.Find(version =>
                    (int) version.Version == GetVisualStudioVersion(vsVersion)));
```
![untitled](https://cloud.githubusercontent.com/assets/6917052/9991500/2c129eb8-6073-11e5-91e8-780c690b7f1f.png)
Another problem is with windowsKitSDK, code generated path:
"C:\\Program Files (x86)\\Windows Kits\\10\\include\\%UCRTVersion%\\ucrt"
should be: c:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10150.0\ucrt\
so %UCRTVersion% is not replaced with numeric value.

Workaround is not to use automatic lookup of Include directories and adding them manually (with hardcoded paths).

2) The second problem is with undefined 'char32_t' and 'char16_t'. Those types are internal for VC++14 and not defined by typedefs.
clang errors:
```
5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(231,22): error : use of undeclared identifier 'char16_t'
5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(237,22): error : use of undeclared identifier 'char32_t'
5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(408,14): error : use of undeclared identifier 'char16_t'
5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(414,14): error : use of undeclared identifier 'char32_t'
5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(615,33): error : use of undeclared identifier 'char16_t'
```
I found clang fix for that:
https://llvm.org/bugs/show_bug.cgi?id=22939
But it's still an issue in cppSharp.

My workaround is not use '-fms-compatibility' clang switch. So I commented line in Parser.cpp:
```
    // Enable the Microsoft parsing extensions
    if (Opts->MicrosoftMode)
    {
        args.push_back("-fms-extensions");
//        args.push_back("-fms-compatibility");
        args.push_back("-fdelayed-template-parsing");
    }

```

**Comment by ddobrev** [comment]
As it says in the comment, we cannot just enable VS 2015, Clang has to support it first. You could check if it already does and if so, removing this limitation would not be difficult.

**Comment by vonzepp** [comment]
The first issue (with Include directories) is not related to clang. It's just about correct determining of Include directories of installed SDK's through registry keys, vcvars*.bat files etc.

The second issue with  'char32_t' and 'char16_t' seems to be a problem of flag or compiler switches configuration. I tried to use:
http://llvm.org/pre-releases/win-snapshots/LLVM-3.8.0-r247596-win64.exe
and compile visual studio project with clang compiler instead of VC++14 (using "Platform Toolset" = LLVM-vs2014). undeclared 'char32_t' problem does not exist in this scenario.

**Comment by tritao** [comment]
The correct fix for the `char32_t` issue is to do something like:

```csharp
options.addArguments("-fms-compatibility-version=19.00");
```

We should remove all MS command line flags processing in the parser and move it to the managed MSVC toolchain code where it can make better decisions (as well as be more easily changed by the user).

About include directories, do you mind running and pasting the output of `MSVCToolchain.DumpSdks()`?

**Comment by vonzepp** [comment]
I tried all suggestions from https://llvm.org/bugs/show_bug.cgi?id=23275  including "-fms-compatibility-version=19.00"
The only thing that works in not using flag "-fms-compatibility".

Output of Dump SDK's:
```
Visual Studio SDKs:
        (14) C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\

Windows SDKs:
        (7,1) C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\
        (8,1) C:\Program Files (x86)\Windows Kits\8.1\
        (8,1) C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\

Windows Kits SDKs:
        (1) C:\Program Files (x86)\Windows Kits\8.1\
        (8) C:\Program Files (x86)\Windows Kits\8.0\
        (10) C:\Program Files (x86)\Windows Kits\10\

.NET Framework SDKs:

MSBuild SDKs:
        (4) C:\Windows\Microsoft.NET\Framework\v4.0.30319\
        (14) C:\Program Files (x86)\MSBuild\14.0\bin\
```
My configuration is clean Windows 7 SP1 x64 with full install VS2015 Enterprise (including .NET 4.6 SDK). No additional platform SDK's were installed.

**Comment by tritao** [comment]
I tried it here and it does work but you also need to remove `-fms-compatibility` from the parser setup code because it overrides the option passed in the managed side. I will clean it up later.

**Comment by vonzepp** [comment]
About NullReferenceException in GetSystemIncludes,
windowsSdkMajorVer = 10  in my case.
so in code:
```
            var windowSdk = (windowsSdkMajorVer != 0)
                ? windowSdks.Find(version =>
                    (int)Math.Floor(version.Version) == windowsSdkMajorVer)
                : windowSdks.Last();
```
windowSdks.Find did not find any matches and returns default value for 'ToolchainVersion' that contains null for ToolchainVersion.Directory.

**Comment by vonzepp** [comment]
ucrtPaths variable contains:
include\%UCRTVersion%\ucrt;

**Comment by tritao** [comment]
I developed the code testing with VS 2015 RC and there's no `%UCRTVersion%`. Guess I'll have to install the final version to test and reproduce your issue.

**Comment by vonzepp** [comment]
> you also need to remove -fms-compatibility

After removing "-fms-compatibility" all works even without 

> options.addArguments("-fms-compatibility-version=19.00");

**Comment by vonzepp** [comment]
Thank you for fast answers! All issues in that case are not critical, because they have workarounds. The real problem with VS2015 is https://github.com/mono/CppSharp/issues/555.

**Comment by vonzepp** [comment]
Finally > char32_t was fixed by setting:
driver.Options.ToolSetToUse = 190000000;
After that I was able to return "-fms-compatibility" option, problem was gone.

So, you was very close from the begining with suggestion:
> The correct fix for the char32_t issue is to do something like:
> 
> options.addArguments("-fms-compatibility-version=19.00");

**Comment by ddobrev** [comment]
@vonzepp if you still have problems, please reopen.

**Comment by vonzepp** [comment]
It works perfectly. Thank you!
