### ISSUE TITLE
Cannot Compile with VS2013 and recommended versions of LLVM/Clang

### ISSUE THREAD

**Issue by taylorcw** [mono/CppSharp#577]
I have been unsuccessful compiling CppSharp with the recommended versions of LLVM/Clang (or the head revision, master revision, stable revision, etc.). I get a number of compile errors like th ones below. I have searched the file histories in some of the files that are complaining that the virtual method definitions do not exist in the base class and have not found the methods that the CppSharp methods are attempting to override.

1>..\..\..\src\CppParser\Targets.cpp(873): error C3668: '`anonymous-namespace'::PPCTargetInfo::initDefaultFeatures' : method with override specifier 'override' did not override any base class methods
1>..\..\..\src\CppParser\Targets.cpp(2324): error C3668: '`anonymous-namespace'::X86TargetInfo::initDefaultFeatures' : method with override specifier 'override' did not override any base class methods
1>..\..\..\src\CppParser\Targets.cpp(4499): error C3668: '`anonymous-namespace'::ARMTargetInfo::initDefaultFeatures' : method with override specifier 'override' did not override any base class methods
1>..\..\..\src\CppParser\Targets.cpp(4294): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4294): error C2039: 'parseArchISA' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4294): error C3861: 'parseArchISA': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(4297): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4297): error C2039: 'parseArch' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4297): error C3861: 'parseArch': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(4300): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4300): error C2039: 'parseCPUArch' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4300): error C3861: 'parseCPUArch': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(4309): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4309): error C2039: 'getSubArch' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4309): error C3861: 'getSubArch': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(4310): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4310): error C2039: 'parseArchProfile' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4310): error C3861: 'parseArchProfile': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(4311): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4311): error C2039: 'parseArchVersion' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4311): error C3861: 'parseArchVersion': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(4351): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4351): error C2039: 'getDefaultCPU' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4351): error C2440: 'initializing' : cannot convert from 'llvm::StringRef' to 'const char *'
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>..\..\..\src\CppParser\Targets.cpp(4361): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4361): error C2039: 'getCPUAttr' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4361): error C2660: '`anonymous-namespace'::ARMTargetInfo::getCPUAttr' : function does not take 1 arguments
1>..\..\..\src\CppParser\Targets.cpp(4626): error C3083: 'ARMTargetParser': the symbol to the left of a '::' must be a type
1>..\..\..\src\CppParser\Targets.cpp(4626): error C2039: 'parseCPUArch' : is not a member of 'llvm'
1>..\..\..\src\CppParser\Targets.cpp(4626): error C3861: 'parseCPUArch': identifier not found
1>..\..\..\src\CppParser\Targets.cpp(5961): error C3668: '`anonymous-namespace'::SystemZTargetInfo::initDefaultFeatures' : method with override specifier 'override' did not override any base class methods
1>..\..\..\src\CppParser\Targets.cpp(6329): error C3668: '`anonymous-namespace'::MipsTargetInfoBase::initDefaultFeatures' : method with override specifier 'override' did not override any base class methods
1>..\..\..\src\CppParser\Targets.cpp(7620): error C2039: 'initDefaultFeatures' : is not a member of 'clang::TargetInfo'

Which revisions of LLVM/Clang is everyone using, and is the master of CppSharp known to compile and run with it?

Thanks in advance for any tips you can offer.

**Comment by ddobrev** [comment]
I saw you said you got the correct revisions of LLVM and Clang but this does look like changed API which suggests using different, presumably newer, versions. Could you please check that the versions you checked out match the ones in CppSharp/build/Clang-commit and CppSharp/build/LLVM-commit?

**Comment by taylorcw** [comment]
Thanks for that guidance. Using the revisions in the files you mentioned, it is compiling! I was using the recommendations on the Getting Started Guide, which appears to be outdated. It may be helpful to include in the Getting Started guide the pointer to use the commits in those two files rather than recommending a specific one in the guide itself.

**Comment by tritao** [comment]
We already link the two files from the Getting started guide, I could not mention any mention of a specific LLVM revision on the guide but I might have overlooked something. Where did you see those outdated revisions recommended on the guide?

**Comment by ddobrev** [comment]
@taylorcw  it seems the Clang API changed quite a little and it may be difficult for us to upgrade if we wait even more. On the other hand, we're both busy at present so I would really encourage you to try upgrading the code and send a pull.

**Comment by taylorcw** [comment]
Thanks, guys, I appreciate your help. I would love to contribute, and may
be able to do so, but I'm new enough to CppSharp, LLVM, and Clang that I
want to get to know them better before attempting to submit changes or
fixes. More later...

Thanks again,
-Taylor

**Comment by ddobrev** [comment]
@taylorcw I'm really glad to hear it. Feel free to ask any questions you might have.

**Comment by taylorcw** [comment]
Hi Dimitar,

Thanks for the quick response to the questions I had. CppSharp is compiling
and running like a champ now.

Are there some docs beyond what is on the wiki that would shed some light
on how to configure CppSharp?

Also, are there plans to support some basic STL containers like std::vector
and std::map?

Thanks again,
-Taylor

**Comment by ddobrev** [comment]
@taylorcw we definitely lack extensive documentation but https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md does contain some basics - the "Generating bindings" section. If that is not good enough for you, I can offer you an advanced example to look at - https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/QtSharp.cs, method Setup(Driver driver) in particular.

**Comment by taylorcw** [comment]
Hi Dimitar,

Thanks again for responding so quickly. I understand how hard it is to
produce documentation on a project that is moving quickly.

I have previously reviewed all of the docs that you recommend, and they
have certainly helped to get up and running with the basics. The QtSharp
project shows the usage of more advanced functionality, but since comments
in the code are very sparse, it is quite difficult to determine how each of
those sections of code evolved and what they really do.

Does there happen to be any other documentation that might help me better
understand the ABI, what can be done with it through CppSharp, and how to
achieve certain effects in transforming code from C++ to C#. Anything you
can offer would be a great help. Without further guidance, it's quite
difficult to see my way to the end of a project that requires more than a
straight-up wrapper.

I did have one specific question that you may be able to help with. I have
some concrete classes that derive from a template class (which is
specialized as part of the class declaration). When attempting to wrap
those classes, CppSharp generates a bunch of warnings like this:

C:\npoint\FirstParty/SharedLibraries/MoCapCore/include\ChannelSystem/Channel.h(423,35):
warning: inline function 'MoCapCore::cChannel<float>::KeyFrameRange' is not
defined

for all the methods that are defined in the template base class and not
specifically overridden in the derived class. Can CppSharp handle this type
of class structure?

Thanks again,
-Taylor

**Comment by ddobrev** [comment]
@taylorcw I am afraid that https://github.com/mono/CppSharp/tree/master/docs contains all the dedicated documentation we have. The only other pieces we have is some documentation directly in the source code (C# XML code comments), for example, some of our options are documented. The even worse part is that I don't see either me or @tritao extending it any time soon since we are both full with handling crucial features and bugs.

About your question, we do not handle templates. Types derived from template instantiations are fine, though, I am however not certain how we handle template-instantiated functions such as your example ("MoCapCore::cChannel<float>::KeyFrameRange"). There's one last option I could use to help you with but for that please contact me directly at the e-mail at the very bottom of https://github.com/mono/CppSharp .
