### ISSUE TITLE
Generating a .NET Wrapper for LLVM and Clang

### ISSUE THREAD

**Issue by palkarz** [mono/CppSharp#578]
Hi, guys. First and foremost, thank you for your efforts. This project will save tons of man-hours in the future (as it probably has already) and I can't thank you enough for spending your own time to save time for the rest of us. 

Since I currently have no tasks involving C/C++ interop and I can barely read C++, let along write anything useful in it, I saw CppSharp as an opportunity to play with LLVM and Clang from a .NET project. The wrappers for the C APIs for both LLVM and Clang got generated seamlessly, however I was unable to generate wrappers for the C++ APIs with either C# or CLI generator kind (both fail with different exceptions). The LLVM and Clang versions I used are the ones recommended by CppSharp. Since you obviously have all the requisites to reproduce this scenario, I don't think any further details are necessary.

Thanks again.

**Comment by ddobrev** [comment]
We definitely pay attention to build issues but while waiting, you could try our binary releases at https://github.com/mono/CppSharp/releases.

**Comment by tritao** [comment]
@ddobrev It seems like @palkarz didn't have any build issues, he even said he generated some bindings for LLVM and Clang C APIs.

About the issue, as part of Google Summer of Code we had someone working on generating bindings for Clang C++ APIs, you can find the work-in-progress pull request in https://github.com/mono/CppSharp/pull/519.

It's a pretty big task and still needs some work to be integrated back, we could use some more help to finish it :)
