### ISSUE TITLE
Crash when using multiple inheritance and calling a virtual function from a secondary base

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#579]
A branch called "crash_MI_virtual_from_secondary" contains a test.
The problem is that when the virtual function invokes the v-table delegate hook, it sends a pointer that is 2 * ptr_size ahead of the real pointer. Presumably this is because of the two v-table pointers, one in the primary and one in the secondary base. So that pointer is not found in the object map and an exception follows.

**Comment by ddobrev** [comment]
This bug does not exist in our latest code because it's been fixed by 6f8c942b0ac0162c32310f21a0f7492a0dca0797 .

**Comment by tritao** [comment]
Should we add the test from the branch?
