### ISSUE TITLE
Unable to find an entry point named '_ZN8CppSharp9CppParser13ParserOptionsC2Ev' in DLL 'CppSharp.CppParser.dll'.

### ISSUE THREAD

**Issue by iniside** [mono/CppSharp#583]
An unhandled exception of type 'System.EntryPointNotFoundException' occurred in CppSharp.Parser.CSharp.dll

I get these errors when trying to create bindings.

I have cloned latest version from github and builded it as Release/x86. I have copied over all generated files to the bin/Release folder inside my test app. 
I'm using Visual Studio 2015, for building CppSharp, clang and my test app.

**Comment by ddobrev** [comment]
This mangled symbol looks more like GCC than MSVC to me. Are you sure you compile the C++ part with MSVC?

**Comment by tritao** [comment]
Looks like your CppSharp.CppParser.dll was compiled with the wrong set of Clang bindings, which we keep here, https://github.com/mono/CppSharp/tree/master/src/CppParser/Bindings/CSharp. It should be picking up the `i686-pc-win32-msvc` folder. Please check in your VS solution which files the project is compiling.

**Comment by tritao** [comment]
Alternatively, please find one of our precompiled binary releases in https://github.com/mono/CppSharp/releases.

**Comment by iniside** [comment]
Thanks guys. Problem solved, I had wrong libraries in references for my C# app.
Your answeres got me thinking that it might be something much simpler than wrong build since everything worked on provided test apps.
