### ISSUE TITLE
Clean up managed v-tables in the C# front end upon exit

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#586]
Since the managed (patched) v-tables are created using Marshal.AllocHGlobal, we must destroy them using Marhsal.FreeHGlobal when they are not needed. Because they are static, we need to destroy them when the process is terminated. It can be done either using a static field with a destructor - https://stackoverflow.com/questions/4364665/static-destructor/18709110#18709110 - or with the help of AppDomain.CurrentDomain.ProcessExit/DomainUnload.

**Comment by ddobrev** [comment]
@genuinelucifer would you like to try this one?

**Comment by genuinelucifer** [comment]
@ddobrev I tried 2-3 methods for destruction. One of them involved wrapping all the VTable values into some other wrapper class ad use it's destructor instead. But, that was turning into problems.
.
I finally decided that using a static variable and using it's destructor (as in the thread you provided link to) is the best option here. Should I go with this approach?

**Comment by ddobrev** [comment]
@genuinelucifer I am really sorry about this delay, I changed my e-mail recently and I have not got used it checking it too.
Yes, I favour this approach myself and I am glad you've reached the same conclusion. Please go ahead.
