### ISSUE TITLE
Implicitly cast to a class default args generate invalid code if the class is used in MI

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#587]
If a type is used in multiple inheritance and has an implicit constructor and that constructor is used to assign a default value for an argument, the generated code is invalid because the argument of that implicit constructor can be cast to the type but not to its interface.
To reproduce this, enable multiple inheritance and default arguments in the options and add the following to the CSharp test project:

Bar(Items item); // to Bar - the implicit constructor

void defaultImplicitCtorEnum(Bar arg = Bar::Items::Item1); // to MethodsWithDefaultValues

**Comment by ddobrev** [comment]
@genuinelucifer thank you for fixing the bug with name-spaces. Could you please try this one next?
I think the solution is to change the call in the overload in such cases from:

Call(Bar.Items.Item)

to:

Call((Bar) Bar.Items.Item)

or:

Call(new Bar(Bar.Items.Item))

**Comment by genuinelucifer** [comment]
@ddobrev I've broken my build by trying to build llvm and clang all over
again. I'm using the version given by Joao but still a couple of errors are
left. I'll get back to this issue once I get everything working again.

**Comment by ddobrev** [comment]
@genuinelucifer I understand, take your time. Let us know if we can help.

**Comment by genuinelucifer** [comment]
@ddobrev Pls review #600

**Comment by ddobrev** [comment]
Fixed by 347d0cdbaf7fa9d93d29d5f2306825c8f32d03c2.
