### ISSUE TITLE
Getting started with pre-built binaries

### ISSUE THREAD

**Issue by g40** [mono/CppSharp#603]
How does one use the pre-built binaries? I cannot find a hint anywhere.

TAIA!

**Comment by ddobrev** [comment]
@g40 you add references to all of them except CppSharp.Runtime (as its name says, it's for the complete bindings to use at run-time) and CppSharp.CppParser (it's a C++ library). Then you need to ensure CppSharp.CppParser is copied to your output dir (you can add it to your project and change its properties to have it copied).
You can use https://gitlab.com/ddobrev/QtSharp as an example.

**Comment by g40** [comment]
@ddobrev Dimitar, thank you.
