### ISSUE TITLE
Problem with NULL wchar_t* in generated property

### ISSUE THREAD

**Issue by magnet31** [mono/CppSharp#606]
Hello. Great work.

CPPSharp generated the following property :
```        public string Name
        {
            get
            {
                var __ret = Internal.GetName_0(__Instance);
                return CppSharp.Runtime.Helpers.MarshalEncodedString(__ret, System.Text.Encoding.UTF32);
            }
         }```
from the following C++ method : 
```
const wchar_t * Foo::GetName()
{
	return _name;
}
```
When _name is NULL MarshalEncodedString raises an exception.
Is it by design (no character array shall ever be NULL) ? or a bug ?
Thanks.

**Comment by tritao** [comment]
This does look like a bug.

**Comment by tritao** [comment]
I've pushed a possible fix, let me know if it works for you.

**Comment by magnet31** [comment]
Actually, I just use your ready-to-use binaries. Maybe now is the time to get serious about CPPSharp so I can test your fix on your latest commits !  :^)
I will download your latest source and try to test against them. 
I'll keep you informed.
By the way, is it possible to generate a  C#   MyClass[ ]    from a C++     MyClass**       ?
Tks

**Comment by tritao** [comment]
We're not able to do that directly because we have no way of knowing the size of the array from the double pointer. It should be possible to support though if you can tell CppSharp how to obtain the size, either via a NULL pointer convention or an explicit array size parameter.

**Comment by magnet31** [comment]
Too bad. You guys are just a few lines of code away from being able to feed the Entity Framework Code First database generator. If you can do that, Microsoft is going to looooooove you. Thanks anyway and keep the good work.

**Comment by ddobrev** [comment]
@magnet31 we might be interested in completing C++# to the point where it can support this project you've mentioned. Could you please give some more details about it?

**Comment by magnet31** [comment]
Hi Dimitar.

Entity Framework is the ORM developped by Microsoft.

an ORM or Object Relationnal Mapping, maps the instances of a class to a line in a database table.

properties of the instance are mapped to columns in the database table. etc.

In the first version of Entity Framework (EF) the classes where generated from the tables in the database.

Say, for instance, we have generated a class Person from a database table tPersons. The following piece of code is all what it takes to insert a new line in the table tPersons:


using (var ctx = new MyModel()) {

  ctx.Persons.Add(new Person() { Name = "dupond" });

  ctx.SaveChanges()

}


What is probably going to interest you is what Microsoft calls "Code First" coming with the actual version of theEntity Framework. It inverses the process and generates a database from the C# classes.


Some to make a long story short :

C++ classes => CPPSharp => C# classes => EF  => database


The problem is that in order to generate a one-to-many relationship beetween table tA and tB, EF will look in class A for a property of type ICollection<B>. And for now CPPSharp cannot generate such a property from a C++ getter returning type **B.


I don't say it is the last problem to be solved to achieve seamless C++ to database generation.

But it is the one left blocking me.


There is a big C++ code base still in use or still in development (some people -like the scientists I am working with- don't want to give away their knowledge by developping C# code that can be reverse-engineered).

Obfuscation is an option still costly in terms of money and in terms of efficiency.


Now, what do you think ?


Frédéric Taillefer

Consultant .Net

E.U.R.L Magnet

+33 699 37 20 20


________________________________
De : Dimitar Dobrev <notifications@github.com>
Envoyé : jeudi 14 janvier 2016 19:34
À : mono/CppSharp
Cc : Frédéric Taillefer
Objet : Re: [CppSharp] Problem with NULL wchar_t* in generated property (#606)


@magnet31<https://github.com/magnet31> we might be interested in completing C++# to the point where it can support this project you've mentioned. Could you please give some more details about it?

[https://avatars0.githubusercontent.com/u/16383432?v=3&s=400]<https://github.com/magnet31>

magnet31<https://github.com/magnet31>
github.com
Follow magnet31 on GitHub and watch them build beautiful projects.


-

**Comment by ddobrev** [comment]
I understand now. I knew what EF was, I just couldn't see its relation to C++ but now I can thanks to your explanation.
The solution cannot be universal, as @tritao explained. However, C++# can be customised for specific bindings. In your case you must have some kind of an indicator (a field, a parameter) for the length of your MyClass** arrays - otherwise you wouldn't be able to use them even in C++ itself. So that information can be used in a custom pass which would generate C# arrays as you want.
An example of a custom pass you can see at https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/GetCommentsFromQtDocsPass.cs and the way it's used at the bottom of https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/QtSharp.cs.

**Comment by magnet31** [comment]
Thanks Dimitar, i will have a look at your custom pass.

Hope you good for your project.


Frédéric Taillefer

Consultant .Net

E.U.R.L Magnet

+33 699 37 20 20


________________________________
De : Dimitar Dobrev <notifications@github.com>
Envoyé : vendredi 15 janvier 2016 00:24
À : mono/CppSharp
Cc : Frédéric Taillefer
Objet : Re: [CppSharp] Problem with NULL wchar_t* in generated property (#606)


I understand now. I knew what EF was, I just couldn't see its relation to C++ but now I can thanks to your explanation.
The solution cannot be universal, as @tritao<https://github.com/tritao> explained. However, C++# can be customised for specific bindings. In your case you must have some kind of an indicator (a field, a parameter) for the length of your MyClass** arrays - otherwise you wouldn't be able to use them even in C++ itself. So that information can be used in a custom pass which would generate C# arrays as you want.

[https://avatars1.githubusercontent.com/u/602268?v=3&s=400]<https://github.com/tritao>

tritao (João Matos) · GitHub<https://github.com/tritao>
github.com
tritao has 33 repositories written in C#, C++, and Shell. Follow their code on GitHub.


An example of a custom pass you can see at https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/GetCommentsFromQtDocsPass.cs and the way it's used at the bottom of https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/QtSharp.cs.

-
