### ISSUE TITLE
Not able to find library

### ISSUE THREAD

**Issue by nicholasfay** [mono/CppSharp#607]
I am including the directory of the library file using:
options.addIncludeDirs(@"C:\Program Files (x86)\STEP Tools\ST-Developer 16\lib\i86_win32_vc12_md");
and providing a library to work with using:
options.Libraries.Add("cisdll.lib");
but the console output says that:
"The library can't be found"

What would be causing this issue, when I know that exact library is in that exact directory?

**Comment by tritao** [comment]
Try adding the full path to the library when adding it to the options.

**Comment by nicholasfay** [comment]
I added \cisdll.lib to the end of my path and still get the same error
and it points me to this line in Delegatepasses.cs within the VisitLibrary function
var unit = context.TranslationUnits.Last(u => u.IsValid && u.IsGenerated &&
                !u.IsSystemHeader && u.HasDeclarations);

**Comment by tritao** [comment]
The include directories are not related to the libraries.

You don't even need to provide the library, CppSharp will work fine without it, it's just to provide some better diagnostics in case of missing symbols.

So either comment the `options.Libraries.Add("cisdll.lib");` line, or try to pass the full path, i.e. `options.Libraries.Add("C:\path\cisdll.lib");`
