### ISSUE TITLE
C# generator does not consider some C++ functions.

### ISSUE THREAD

**Issue by sajivthomas** [mono/CppSharp#610]
Once its done with parsing all the header files and starts generating code it throws and error in the function 'GetVirtualCallDelegate' in this file \CppSharp\src\Generator\Generators\CSharp\CSharpTextTemplate.cs

The reason is that Driver.Delegates[method] fails since there is no entry for the key in the dictionary. The method in this case is: virtual ~DepthPacketProcessor();

**Comment by ddobrev** [comment]
I have reproduced a crash with the same dictionary but with another function. I am therefore not sure that what I've reproduced is your issue. When I have fixed it, I'll let you know so that you can test.

**Comment by sajivthomas** [comment]
@ddobrev thanks for the update.

**Comment by ddobrev** [comment]
@sajivthomas fixed by https://github.com/mono/CppSharp/commit/9ab71aeac7b70c00e3bd8bc0859ddb94d0f78b7c.
