### ISSUE TITLE
Reverse PInvoke support? Expose .NET types in native code?

### ISSUE THREAD

**Issue by denfromufa** [mono/CppSharp#613]

**Comment by ddobrev** [comment]
Hello @denfromufa . I am afraid we won't have time for this any time soon, not in the next 6 months anyway. Nevertheless, we are definitely interested in learning about your use case.

**Comment by denfromufa** [comment]
My use case is for pythonnet to support .NET, Mono, and CoreCLR from single
c# code base

**Comment by HinTak** [comment]
I am also interested in this to port something from windows to mono which was written that way - the C# side passes a few delegates to the C++/CLI side to invoke as function pointers.

**Comment by denfromufa** [comment]
@ddobrev any update on this? you mentioned something about 6 months.

**Comment by ddobrev** [comment]
@denfromufa @tritao has been working on such a project at https://github.com/tritao/MonoManagedToNative , you can check it out.

**Comment by tritao** [comment]
Take a look at https://github.com/mono/embeddinator-4000.
