### ISSUE TITLE
Problem compiling cppsharp solution

### ISSUE THREAD

**Issue by dowitdo** [mono/CppSharp#616]
Hello, I am new to CppSharp and I am trying to compile the CppSharp solution on Windows. I compiled llvm without issue. But I cannot compile the cppsharp project. I am getting the following error

'getDataLayoutString' : is not a member of 'clang::TargetInfo' in parser.cpp

Sure enough getDataLayoutString is not in ppSharp\deps\llvm\tools\clang\include\clang/Basic/TargetInfo.h. 

I tried using both 3.7.1 and 3.7.0 of llvm and clang, which I believe are the latest builds.

What am I missing?

Thanks.

**Comment by tritao** [comment]
Either use the revisions for LLVM and Clang specified in files `LLVM-commit` and `Clang-commit, or follow the instructions in https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md#downloading-the-llvm-and-clang-packages to download pre-built LLVM packages.
