### ISSUE TITLE
.NET Core generation support

### ISSUE THREAD

**Issue by benpye** [mono/CppSharp#629]
Whilst in an ideal world, it would be great to both run CppSharp on .NET and generate code for .NET Core I think currently it would suffice to just be able to generate code that is compatible with .NET Core. It would be great to be able to support all the new platforms that are to be added (OS X, Linux, FreeBSD) in the Microsoft framework, meaning that we wouldn't always need Mono there when wanting to use a CppSharp bound library.

**Comment by nathanaeljones** [comment]
+1. What specific issues have you run into?

**Comment by benpye** [comment]
The primary issue I have noticed is that SuppressUnmanagedSecurity is
emitted.

**Comment by ddobrev** [comment]
SuppressUnmanagedSecurity is unfortunately vital to us because it skips certain checks when calling into native code thus significantly increasing performance. In order to solve this, we need more details. For example, is the problem that SuppressUnmanagedSecurity causes some problem with .NET Core or rather that it doesn't exist at all? Is there an alternative to it? In case there is, is there a #define we can place in the generated code to detect .NET Core?

**Comment by benpye** [comment]
All P/Invoke's on CoreCLR effectively have this
https://github.com/dotnet/coreclr/issues/1605

**Comment by tritao** [comment]
If that is the only issue on .NET Core then we can easily fix it, though ideally we should also integrate CoreCLR on the CI system to test against it.

**Comment by JimSEOW** [comment]
can we have a simple tutorial or example using a known c++ library to port it to .NET Core? If such a tutorial already available, please share the links

**Comment by tritao** [comment]
@JimSEOW: You can use https://github.com/ddobrev/QtSharp as an example, or all the other open source projects linked on the README file. And you can also take a look at our test suite.

**Comment by JimSEOW** [comment]
Thanks @tritao, after extensive search through internet, I found (especially Japanese sites) offering step by step tutorials using the foo example. Thanks. cppSharp offers a much simpler experience than SWIG.

**Comment by ddobrev** [comment]
@benpye we still haven't fixed this issue after quite some time but there is a reason. Please feel free to use our e-mail for support if you would like to discuss this reason in more detail.

**Comment by jkoritzinsky** [comment]
@tritao the fix for dotnet/coreclr#22087 should be in Preview 4.

**Comment by tritao** [comment]
Awesome thanks for the fix! 👍

**Comment by cyberdecker** [comment]
To use the nuget package under netcore 2.2, it is needed to recompile this project and generate the output as nuget package?
