### ISSUE TITLE
Error generating code for return type overloaded subscript operator

### ISSUE THREAD

**Issue by tritao** [mono/CppSharp#630]
Add to `Common.h` TestIndexedProperties:

``` cpp
    void *operator[](size_t n) const;
```

Error:

```
../gen/Common/Common.cs(4936,38): error CS0111: A member `CommonTest.TestIndexedProperties.this[uint]' is already defined. Rename this member or use different parameter types
```

We need to check for this, maybe in CheckAmbiguousFunctions pass.

**Comment by ddobrev** [comment]
This has been fixed along the way. There was a different problem when binding such code but it was taken care of by https://github.com/mono/CppSharp/commit/48c6094f52cd68f8fe5279ebfcbd2850b8a55896 . Closing.
