### ISSUE TITLE
Support UTF8 strings

### ISSUE THREAD

**Issue by benpye** [mono/CppSharp#633]
UTF8 is often used as the encoding for strings in open source libraries, unfortunately there is currently no support for using UTF8 as the encoding. I believe for string parameters this would require some helper functions with the equivalent function of `Marshal.StringToHGlobalAnsi` and `Marshal.PtrToStringAnsi` and then changes at https://github.com/mono/CppSharp/blob/master/src/Generator/Generators/CSharp/CSharpMarshal.cs#L561 and https://github.com/mono/CppSharp/blob/master/src/Generator/Generators/CSharp/CSharpMarshal.cs#L183

**Comment by ddobrev** [comment]
We should most probably be able to reuse https://github.com/libgit2/libgit2sharp/blob/3010f8373313a47e9a889e8b3e61a30cd2eb359b/LibGit2Sharp/Core/EncodingMarshaler.cs and https://github.com/libgit2/libgit2sharp/blob/3010f8373313a47e9a889e8b3e61a30cd2eb359b/LibGit2Sharp/Core/Utf8Marshaler.cs.

**Comment by tritao** [comment]
Related: https://github.com/dotnet/coreclr/pull/4793

**Comment by mfkl** [comment]
What's the status of this?

**Comment by tritao** [comment]
Some simple support was added in https://github.com/mono/CppSharp/commit/688b09f8f1952764f24f2332b6f34354bd871b58.

This needs to be extended to handle the other marshaling direction in https://github.com/mono/CppSharp/blob/688b09f8f1952764f24f2332b6f34354bd871b58/src/Generator/Generators/CSharp/CSharpMarshal.cs#L676.

**Comment by ddobrev** [comment]
Fixed by https://github.com/mono/CppSharp/commit/b12acfcce74756c4240935c8df62aed1b2d40087.
