### ISSUE TITLE
Calling c# from c++

### ISSUE THREAD

**Issue by dowitdo** [mono/CppSharp#634]
Is there a way to pass a function pointer or add a callback function that is callable from the c++ dll?

I would like my c++ dll to call a function from my c# application.

**Comment by tritao** [comment]
Yes, you can use delegates to achieve this.

See:

https://github.com/mono/CppSharp/blob/d02192ed6651af1bcaa8287b0f0e97f6e65330ad/tests/Common/Common.h#L331

https://github.com/mono/CppSharp/blob/edf077fbfb88961ab87f172074bcceae1c54c014/tests/Common/Common.Tests.cs#L281

**Comment by dowitdo** [comment]
Sorry for not closing this issue. 

Thanks for the help Tritao
