### ISSUE TITLE
Install-Package : CppSharp 0.1.0 is not compatible with UAP,Version=v10.0.

### ISSUE THREAD

**Issue by erledzus** [mono/CppSharp#637]
Error message was received when attempting to use Package Manager from within Visual Studio 2015, in a solution with very simple Universal Windows projects

**Comment by tritao** [comment]
The packages published on NuGet are not official and do not seem to have been updated in a while.

I recommend using the official releases we provide on Github until we start publishing our own NuGet packages.

Is there any reason you need to use CppSharp itself under the Universal Windows Platform App?

I'm not familiar with this UAP model... but if you're just using CppSharp for bindings, you can create a normal app using CppSharp to generate the bindings code, and then the generated code itself should work under UAP.
