### ISSUE TITLE
Typo in Generator\Options.cs - DriverOptions.Libraries property referencing Module.Headers.

### ISSUE THREAD

**Issue by allisterb** [mono/CppSharp#649]
One line 12 the DriverOptions.Libraries property seems to be mistakenly referencing the Module.Headers property. This basically means you will always get a parser error when using both .lib libraries and .h headers. Changing it to point to Module.Libraries seems to get everything working again.

[typo.patch.txt](https://github.com/mono/CppSharp/files/266446/typo.patch.txt)

**Comment by tritao** [comment]
@ddobrev ?

**Comment by tritao** [comment]
Thanks, should be fixed.
