### ISSUE TITLE
No such file, impropert paths in solution, Visual Studio 2013, built as CI

### ISSUE THREAD

**Issue by Nanonid** [mono/CppSharp#660]
##### Brief Description
Followed exact process from ci builder for commit 02ed084fd850407bc30e7fe437d5cf513a07fc36
Followed the log in: https://ci.appveyor.com/project/tritao/CppSharp/branch/master 

Generated solution has improper paths for Object/Archive.h and ADT/SmallString.h

OS: Windows / OS X / Linux (include version and/or distro)
Microsoft Windows [Version 10.0.10586]

##### Used headers

local llvm

##### Used settings

from ci, x86, Visual Studio 2013, msvc 12, version 18.

Target: MSVC/GCC/Clang
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x86

Other settings 

##### Stack trace or incompilable generated code

CppSharp.AST -> C:\Users\user1\src\mono\CppSharp\build\vs2013\lib\Debug_x64\CppSharp.AST.dll
CppSharp.Runtime -> C:\Users\user1\src\mono\CppSharp\build\vs2013\lib\Debug_x64\CppSharp.Runtime.dll
Parser.cpp
c:\users\user1\src\mono\cppsharp\src\cppparser\Parser.h(10): fatal error C1083: Cannot open include file: 'llvm/Object/Archive.h': No such file or directory [C:\Users\user1\src\mono\CppSharp\build\vs2013\projects\CppSharp.CppParser.
vcxproj]
CppParser.cpp
c:\users\user1\src\mono\cppsharp\src\cppparser\Parser.h(10): fatal error C1083: Cannot open include file: 'llvm/Object/Archive.h': No such file or directory [C:\Users\user1\src\mono\CppSharp\build\vs2013\projects\CppSharp.CppParser.
vcxproj]
Comments.cpp
c:\users\user1\src\mono\cppsharp\src\cppparser\Parser.h(10): fatal error C1083: Cannot open include file: 'llvm/Object/Archive.h': No such file or directory [C:\Users\user1\src\mono\CppSharp\build\vs2013\projects\CppSharp.CppParser.
vcxproj]
AST.cpp
..\..\..\src\CppParser\AST.cpp(12): fatal error C1083: Cannot open include file: 'llvm/ADT/SmallString.h': No such file or directory [C:\Users\user1\src\mono\CppSharp\build\vs2013\projects\CppSharp.CppParser.vcxproj]

**Comment by tritao** [comment]
Did you use `build\premake5.exe --file=build\scripts\LLVM.lua download_llvm` to get a copy of LLVM?

Which LLVM paths do you get in the log when running Premake?

```
Using debug LLVM build: C:/projects/cppsharp/build/scripts/llvm-f79c5c-windows-vs2013-x86-Debug
Using release LLVM build: C:/projects/cppsharp/build/scripts/llvm-f79c5c-windows-vs2013-x86-RelWithDebInfo
```
