### ISSUE TITLE
TLSV1.0 bad cipher suites with Duplicati

### ISSUE THREAD

**Issue by glannes31** [mono/CppSharp#672]
##### Brief Description

OS:  OS X El capitan

Hello i have an issue with Duplicati  on MAC( https://github.com/duplicati/duplicati/issues/1836). 

On wiresharck , when i test a connexion with a webdav server with SLL , i see a client hello with 6 TLS_RSA cipher suites and then we have a handshake failure and internal error. 

For security reason, our server can't accept TLS_RSA cipher suite, it's out to date.

We see that :https://bugzilla.xamarin.com/show_bug.cgi?id=18222 

Windows is ok because the client hello have 12 cipher suites. 

How do you explain that mono do a client hello with only 6 cipher suites?  The problem is on mono side or Duplicati side ?

**Comment by tritao** [comment]
This issue seems unrelated to CppSharp, you should re-open it in Mono repo.

**Comment by glannes31** [comment]
@tritao  a link to the repo pls  ? I cant open issue in the mono repo ....

**Comment by tritao** [comment]
Oh right we do not use Github for issue tracking in Mono. Please open a new issue in Bugzilla explaining the problem in detail and link it here, I'll assign it to the right person.

**Comment by glannes31** [comment]
This what i do ;-) https://bugzilla.xamarin.com/show_bug.cgi?id=42399 tks for your answer @tritao
