### ISSUE TITLE
Disabling generation of dummy elements of fixed arrays.

### ISSUE THREAD

**Issue by Dia6lo** [mono/CppSharp#682]
Okay, I'm either blind or dumb, but I can't find a way to disable generating dummy fields for fixed arrays, i.e:

```cpp
double m_lastAccessTime[1024];
```

becomes:

```csharp
[FieldOffset(16)]
public fixed double m_lastAccessTime[1024];

[FieldOffset(24)]
public double __dummy_m_lastAccessTime_1;

...(Tons of dummies)

[FieldOffset(8200)]
public double __dummy_m_lastAccessTime_1023;
```
As you can see, I'm getting a lot of garbage code. How can I get rid of it?

**Comment by ddobrev** [comment]
I am afraid this hack is necessary to work around a bug in Mono: https://bugzilla.xamarin.com/show_bug.cgi?id=33571 . I have reported it nearly a year ago but nobody has paid any attention to it, in fact, a Mono project member even argued it wasn't a bug.

**Comment by Dia6lo** [comment]
Oh wow, that was unexpected, I'll try to figure out if it's possible to workaround it in other way. Thanks for reply.

**Comment by tritao** [comment]
If you only need to use the generated code with .NET then you can safely remove those dummy fields from generation. We have fixing this Mono bug in the roadmap so hopefully soon we can get rid of these workarounds.

**Comment by Dia6lo** [comment]
How can I do it via pass?

**Comment by ddobrev** [comment]
Unfortunately, you can't. You'll have remove the relevant code from the C# generator - https://github.com/mono/CppSharp/blob/573dc623f8887324636f9011c3e887c5eb7804cc/src/Generator/Generators/CSharp/CSharpSources.cs#L851 - and build C++# yourself.
