### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mwallnoefer** [mono/CppSharp#693]
I followed the instructions on https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md. 

> The dependencies can be automatically downloaded by running:
> 
> cd <CppSharp>\build
> premake5 --file=scripts/LLVM.lua download_llvm # on Windows

At this step I noticed that the Clang dependencies could not be downloaded. What to do in this case?

```
Downloading: https://dl.dropboxusercontent.com/u/194502/CppSharp/llvm/llvm-cccdd2-windows-vs2013-x86-RelWithDebInfo.7z
Error: .../CppSharp/build/scripts/Utils.lua:96: HTTP response code said error
The requested URL returned error: 404 Not Found
```

**Comment by ddobrev** [comment]
For a while now we've had a NuGet package at https://www.nuget.org/packages/CppSharp/ . It's 64-bit only but if this is not a problem do you, would you mind giving it a try?

**Comment by tritao** [comment]
Hi,

We're not supporting VS2013 anymore for pre-built LLVM packages. If you want to use you need to follow instructions to compile LLVM yourself.

If you use VS2015 it should work, file name is `llvm-cccdd2-windows-vs2015-x86-RelWithDebInfo.7z`.

**Comment by mwallnoefer** [comment]
Ah okay. Please add a notice to docs which states this decision, so others won't get confused.
