### ISSUE TITLE
Can't generate bindings in Xamarin Studio

### ISSUE THREAD

**Issue by pizzaeater** [mono/CppSharp#699]
Hi,
I'm trying to run simple example in Xamarin Studio (MacOS):

```
	class MainClass
	{
		public static void Main(string[] args)
		{
			Console.WriteLine("Hello CppSharp!");
			ConsoleDriver.Run(new SDL());
		}
	}
```

But get the following error:

> Assertion at mini-codegen.c:1310, condition `reginfo [sreg].born_in > 0' not met

Stacktrace:

>   at <unknown> <0xffffffff>
>   at <Module>.<CrtImplementationDetails>.LanguageSupport.{ctor} (<CrtImplementationDetails>.LanguageSupport*) <IL 0x00001, 0x0003f>
>   at <Module>..cctor () <IL 0x00002, 0x00047>
>   at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <IL 0x0001f, 0x000c6>
>   at <unknown> <0xffffffff>
>   at CppSharp.Parser.ParserOptions..ctor () <IL 0x00001, 0x0003f>
>   at CppSharp.Driver..ctor (CppSharp.DriverOptions,CppSharp.IDiagnostics) <IL 0x00025, 0x0014f>
>   at CppSharp.ConsoleDriver.Run (CppSharp.ILibrary) <IL 0x0001f, 0x0028f>
>   at TestApp.MainClass.Main (string[]) [0x00010] in /Users/devel/Projects/TestApp/TestApp/Program.cs:12
>   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <IL 0x00051, 0x001d2>

Native stacktrace:

> 	0   mono32                              0x00127e46 mono_handle_native_sigsegv + 342
> 	1   mono32                              0x0017b091 sigabrt_signal_handler + 145
> 	2   libsystem_platform.dylib            0x9f760ebb _sigtramp + 43
> 	3   ???                                 0xffffffff 0x0 + 4294967295
> 	4   libsystem_c.dylib                   0x9f5e9a5c abort + 141
> 	5   mono32                              0x002f1c11 monoeg_log_default_handler + 129
> 	6   mono32                              0x002f1d0b monoeg_assertion_message + 107
> 	7   mono32                              0x0012158c mono_local_regalloc + 19980
> 	8   mono32                              0x0005dd27 mono_codegen + 119
> 	9   mono32                              0x00061493 mini_method_compile + 12339
> 	10  mono32                              0x00062f23 mono_jit_compile_method_inner + 723
> 	11  mono32                              0x00066089 mono_jit_compile_method_with_opt + 777
> 	12  mono32                              0x00065d72 mono_jit_compile_method + 50
> 	13  mono32                              0x0012a4ed common_call_trampoline + 1085
> 	14  mono32                              0x0012a07a mono_magic_trampoline + 74
> 	15  ???                                 0x0043a188 0x0 + 4432264

If I comment the line with ConsoleDriver it works obviously.
I installed CppSharp as a NuGet package.

**Comment by tritao** [comment]
Looks like our Nuget package (courtesy of @ddobrev) only supports Windows 64-bit configurations at the moment.

For the moment, you can follow the instructions at https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md#common-setup.

**Comment by pizzaeater** [comment]
I've built everything, I have a gmake folder now with all files. I can't understand how it can help me :(

**Comment by tritao** [comment]
OK if you have built everything, you can link with the CppSharp .NET references.

Basically you want to reference from your project, `CppSharp.dll`, `CppSharp.AST.dll`, "CppSharp.Generator.dll`, `CppSharp.Parser.dll` and `CppSharp.Parser.CSharp.dll`.

And make sure `libCppSharp.CppParser.dylib` native library gets copied to the working directory of your executable.

**Comment by pizzaeater** [comment]
It works, thanks! We can close the issue.
