### ISSUE TITLE
Parser::ReadClassLayout parent bug

### ISSUE THREAD

**Issue by sk-havok** [mono/CppSharp#702]
##### Brief Description

While debugging a problem with multiple inheritance (will file another bug for that), I came across this in 
Parser::ReadClassLayout

```
auto Parent = static_cast<AST::Class*>(
        WalkDeclaration(RD, /*IgnoreSystemDecls =*/false));
LayoutBase LayoutBase;
LayoutBase.Offset = Offset.getQuantity();
LayoutBase.Class = Parent;
Class->Layout->Bases.push_back(LayoutBase);
```

From the code I've read, WalkDeclaration returns the Declaration of RD, not its parent.
The result is that Class gets itself as a base which surely is not intended.

**Comment by tritao** [comment]
It does look like a bug.

@ddobrev You rewrote this a couple months ago, what should we do?

**Comment by ddobrev** [comment]
There might be a bug but this is not it. Look at the calls of ReadClassLayout, the passed RD is the base declaration. I would agree the parameter could be named better, I guess I left it this way because of the original Clang code for dumping layouts, but this particular piece is correct.

**Comment by tritao** [comment]
Well I tried to check with the debugger, and for instance, for the `Foo2` class in Common test suite, we get two layout bases, itself and `Foo`.

**Comment by sk-havok** [comment]
@ddobrev passing the base class is clearly true for all the recursive ReadClassLayout calls. However it's not obvious to me that the one from Parser::WalkRecord is using the base

**Comment by ddobrev** [comment]
Indeed, I have just taken a better look at the code. A class does add itself as its base, this is a bug. I'll try fixing it later tonight.
