### ISSUE TITLE
Calling methods in interfaces doesn't work

### ISSUE THREAD

**Issue by sk-havok** [mono/CppSharp#703]
##### Brief Description

(Note: this could be related to and fixed by a fix to #702, I don't fully understand the code yet)

Apply the patch to Common.Native project to repro the bug.
[interfacemethods.txt](https://github.com/mono/CppSharp/files/548488/interfacemethods.txt)

In GetVirtualCallDelegate, there is a hardcoded reference to __OriginalVTables[0].
In the attached example, I believe calls to ImplementsAbstractFoo.baseFunction* should go through __OriginalVtables[1]. I have a local change which changes GetVTableIndex to return a (table index, slot index) instead of just slot_index which appears to fix the issue. (Additionally I had to add an additional pointer adjustment, but that may be due to #702)

**Comment by ddobrev** [comment]
@sk-havok I get invalid generated code with this patch. Handling multiple inheritance is explicitly enabled with an option because https://github.com/mono/CppSharp/issues/579 has not been fixed yet. Common does not have this option on. Have you perhaps enabled it?

**Comment by sk-havok** [comment]
My bad, I didn't see #579, it looks like the same issue.
My test was in a custom project (with the flag enabled), so ported it for an easier repro. I saw MI was enabled for the CSharp test so didn't realize there was a known problem with it.

**Comment by ddobrev** [comment]
@sk-havok I'll try fixing #579 as soon as possible. If it also fixes your problem, we'll just enable MI and remove the option.
