### ISSUE TITLE
Trying to build LLVM caused my system to freeze up

### ISSUE THREAD

**Issue by define-private-public** [mono/CppSharp#704]
##### Brief Description
I was following the guide here: https://github.com/mono/CppSharp/blob/master/docs/BuildingLLVM.md  to build CppSharp on my Linux machine.  I was at the last step where I was told to run `ninja`.

When running that step, I noticed my machine's RAM was being almost completely used up (20 GB), until all of it was.  Then my system froze and I had to restart it.  It was at step `[1785/1927]  Linking CXX executable bin/lli`.

OS: Windows / OS X / Linux (include version and/or distro)
Xubuntu Linux 16.04.01

**Comment by tritao** [comment]
Linking definitely takes a lot of memory... but I've never seen it take that much.
I compile it sometimes using a VM and it only has max 8GB I think.

Anyway we have pre-compiled LLVM binaries, can you try: https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md#downloading-the-llvm-and-clang-packages

**Comment by define-private-public** [comment]
Alright.  I tried it again and let it sit for about an hour.  I did notice it going up to around 16GB again, but eventually it did build successfully.

Is this possibly a memory leak in some of the build tools?  Right now, it seems like an absurd amount of memory to use for compiling/linking.

**Comment by tritao** [comment]
C++ linking of big projects really is that memory intensive, so I don't think there is any memory leak. The linker is invoked as the final step, so all the previous compile processes should be finished at that point.

Is it possible you have no swap partition configured on your Linux machines? That might explain the hang.

**Comment by define-private-public** [comment]
I've got about 20GB of swap space.

Seeing as this issue is resolved for me, should I close it?  Or is it something else to look into?
