### ISSUE TITLE
"this" pointer not adjusted for interfaces

### ISSUE THREAD

**Issue by sk-havok** [mono/CppSharp#707]
##### Brief Description

(Followup issue from #703)
See test case in https://github.com/sk-havok/CppSharp/commit/abcf79ace5965590a6c4023e8a75e41355fb37ac

Putting a breakpoint in ImplementsAbstractsFromPrimaryAndSecondary::abstractInSecondaryBase() shows "this" is off by 4 bytes.

**Comment by sk-havok** [comment]
In GetInstanceParam, with the method abstractInSecondaryBase,
from = {ImplementsAbstractsFromPrimaryAndSecondary}
to = {AbstractPrimaryBase} // should be AbstractSecondaryBase
so baseOffset is miscalculated as 0

**Comment by ddobrev** [comment]
@sk-havok thank you very much for this second test case. I think I'll be able to take a look tonight. Meanwhile, could you confirm your previous problem of https://github.com/mono/CppSharp/issues/703 has been fixed?

**Comment by sk-havok** [comment]
Yes thanks for the quick responses! I can confirm both #702 and #703 are fixed.

**Comment by ddobrev** [comment]
@sk-havok I have identified the problem and even tried a fix. Unfortunately, the fix only works for the MSVC ABI thus breaking our Unix builds. I'll have to test on OS X and fix this properly before I can close this bug.
