### ISSUE TITLE
More examples / Error with SDL example

### ISSUE THREAD

**Issue by lucmichalski** [mono/CppSharp#710]
Hi guys,

Hope you are doing all well and congrats for this interesting project !

I encountered some issues with CppSharp while trying the SDL example, and I would like to import some CMake based c++ librairies into Unity3D.

**Issue faced:**
 I could not build build the [SDL example](https://github.com/mono/CppSharp/tree/master/examples/SDL), because having the following error message:
"Error: ...t/CppSharpToolkit/CppSharp/examples/SDL/premake5.lua:3: no workspace in scope".

***OS / Distro***
My machine is Mac Book Pro (Sierra 10.12.1) with Xcode Editor.

**Install Process**
```
$ cd <CppSharp>\build
$ premake5-osx --file=scripts/LLVM.lua download_llvm
$ mono --version
Mono JIT compiler version 4.6.1 (mono-4.6.0-branch-c8sr0/abb06f1 Fri Sep 23 19:24:23 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
$ config=release_x32 make -C gmake
$ cd ../../examples/SDL
$ premake5 gmake
Error: ...t/CppSharpToolkit/CppSharp/examples/SDL/premake5.lua:3: no workspace in scope
```

**Context:**
I was wondering if you could provide more documentations about examples, and more of them too. I wanted to try CppSharp with a cool cross-platform package manager for CMake based projects, called "[Hunter](https://github.com/ruslo/hunter)" working awesomely [Polly](https://github.com/ruslo/polly), a collection of CMake toolchain files. And, the author made/hunterize lots of interesting packages (available at https://github.com/hunter-packages). 

**Goal:**
My goal is to wrap and import some c++ libs into Unity3D and use CppSharp for generating C# bindings, but the documentation, and examples are missing for a quick learning curve, and I have an error.

**Questions:**
1. How to solve the SDL example issue ?
2. There is an example folder in Hunter, and I was wondering if could have additional examples, with command lines or maybe, how to make a macro to generate C# bindings for these C++ librairies with CMake or Hunter ?

**Additional examples suggestions:**
1. https://github.com/hunter-packages/half **(Small Project)**
2. https://github.com/hunter-packages/thread-pool-cpp **(Small Project)**
3. https://github.com/hunter-packages/dlib **(Complex Project)**
4. https://github.com/hunter-packages/xgboost **(Complex Project)**

If you have any tips, tools are additional documentations, it would be awesome.

Have a good week !

Cheers,
L.

**Comment by tritao** [comment]
The SDL example is already included from the main build workspace, so you if you just build CppSharp you should also get an `SDL.exe` binary for generating SDL bindings in your `lib\<conf>` folder.

About your use case I think you should create a new project following the [Getting started guide](https://github.com/mono/CppSharp/blob/master/docs/GeneratingBindings.md) that knows how to add include and library paths for every library you want to bind.

It doesn't look like the Hunter packages provide a uniformized directory layout for includes so you will need to either hardcode them for each specific library or get them from CMake somehow if you want to make it work for any package out of the box.

I recommend you start with the simplest library to get a feel for how C++# works, follow the guide and generate some bindings.

Hope that helps, if not feel free to ask any more questions.

**Comment by tmm1** [comment]
> $ cd ../../examples/SDL
> $ premake5 gmake
> Error: ...t/CppSharpToolkit/CppSharp/examples/SDL/premake5.lua:3: no workspace in scope

Can someone please provide the correct commands to generate the SDL example by hand?

**Comment by tritao** [comment]
It should be in the main workspace. 

You can see here in the root Premake file: https://github.com/mono/CppSharp/blob/661609176a753e9e337c1aef36514349a6516368/build/premake5.lua#L48

So just follow the documented compilation guide and you should end up with an `SDL.exe` file.

**Comment by tmm1** [comment]
Here are the commands to generate bindings by hand:

```
mcs -lib:/path/to/CppSharp/build/gmake/lib/Release_x64 -r:CppSharp -r:CppSharp.AST -r:CppSharp.Generator sample.cs
MONO_PATH=/path/to/CppSharp/build/gmake/lib/Release_x64 mono sample.exe
```

**Comment by RotsiserMho** [comment]
I followed the getting started guide but SDL.exe was not created, nor was the SDL repo cloned.
