### ISSUE TITLE
BadFormatException on ConsoleDriver.Run()

### ISSUE THREAD

**Issue by Ryder25** [mono/CppSharp#711]
I made a simple C# project using the CppSharp nuget package v0.7.9.  When I run the project in debug mode I get BadFormatException for CppSharp.Parser.CLI on line "ConsoleDriver.Run(new SampleLibrary());".  How can I resolve this?

My lib file is 32 bit and I am using Windows 10 x64. The C# project is using AnyCPU with 32 bit preferred.

**Comment by ddobrev** [comment]
Please turn "32-bit preferred" off, it means the compiled executable is 32-bit which cannot work with the NuGet version of C++#.

**Comment by Ryder25** [comment]
With 32-bit preferred off, I am now getting FileNotFoundException:

Could not load file or assembly 'CppSharp.Parser.CLI.dll' or one of its dependencies.

**Comment by ddobrev** [comment]
Please ensure CppSharp.CppParser.dll is located next to your executable. If you install the NuGet on your executable, it will work too.

**Comment by Ryder25** [comment]
Hmm, both CppSharp.CppParser.dll is there as well as CppSharp.Parse.CLI.dll. I imagine the Nuget package installed all the dlls properly with the executables.

I get the same error with your CppSharp.Parser.Gen.exe app that I downloaded from https://github.com/mono/CppSharp/releases/tag/CppSharp

**Comment by ddobrev** [comment]
Please do not mix the binaries like that. The C++# at the link you posted is 32-bit, the NuGet is 64-bit.

**Comment by Ryder25** [comment]
This is all tested separately. I'm not mixing the binaries. 

I'm just getting this same error both with my app using the NuGet, as well as your app from the link in a completely separate folder.

**Comment by ddobrev** [comment]
I understand. I am afraid, though, that I cannot tell what the problem is. The only idea I have at the moment is for you to download http://www.dependencywalker.com/ , open CppSharp.Parser.CLI.dll and check its bitness and dependencies.

**Comment by Ryder25** [comment]
Ok, here's an image of what's missing. Do you have any ideas about what I need here?

http://imgur.com/a/Q5AjM

**Comment by tritao** [comment]
What Visual Studio version are running?

It looks like you're missing some up-to-date C library DLLs that are usually distributed with VS.

**Comment by ddobrev** [comment]
@Ryder25 I assume you do not use VS 2015. In this case please install https://www.microsoft.com/en-us/download/details.aspx?id=53840 and try again.

**Comment by Ryder25** [comment]
Yes you are right. I just installed that package, and my app started working. Thanks!

Now when I run it, I am only getting an Std.cs file.

I created a Project1.lib static library, with the header file Foo.h:
`#pragma once

class Foo
{
public:

	int a;
	float b;
};

int FooAdd(Foo* foo);`

Here is my SampleLibrary class:
`    class SampleLibrary : ILibrary
    {
        public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            options.LibraryName = "Sample";
            options.Headers.Add(@"Foo.h");
            options.Libraries.Add(@"Project1.lib");
        }

        public void Postprocess(Driver driver, CppSharp.AST.ASTContext ctx)
        {

        }

        public void Preprocess(Driver driver, CppSharp.AST.ASTContext ctx)
        {

        }

        public void SetupPasses(Driver driver)
        {

        }
    }`

I made sure that the header file, and lib file are in the directory with my exe. What am I doing wrong?

**Comment by ddobrev** [comment]
You need the paths to your headers and libs too.

**Comment by tritao** [comment]
You can try to set `driver.Diagnostics.Level = DiagnosticKind.Debug;` before generation and see if any of the diagnostic output helps you find the issue.

**Comment by Ryder25** [comment]
ddobrev, you are right. I don't know why I thought the file names would be enough.

Thanks for your help, and tips!
