### ISSUE TITLE
Get/Set function with different return/arg type gets converted to property with return type

### ISSUE THREAD

**Issue by Ryder25** [mono/CppSharp#712]
I have a C++ class as follows:
 ```cpp
class SomethingBla
{
	public:
		enum BlaType{ One, Two };
                void SetBlaType(BlaType bla_type);
                const BlaType& GetBlaType();
}
```

This gets converted in C# to property:
```csharp
        public SomethingBla.BlaType* BlaType
        {
            get
            {
                // returns BlaType*
                var __ret = __Internal.BlaType_0((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = value;
                // Takes BlaType, not BlaType*
                __Internal.SetBlaType_0((__Instance + __PointerAdjustment), __arg0);
            }
        }
```

Not sure if this is a bug necessarily, or if I need to do something special in my ILibrary class to remove this property conversion. Imo, by default if the Get/Set function types are not the same, it should leave them as functions rather than creating a property.

**Comment by ddobrev** [comment]
It's not a bug. const BlaType& and BlaType are the same from a C# point of view. Could you please explain what exactly the problem is that you have with the property?

**Comment by ddobrev** [comment]
@Ryder25 I have actually just noticed the star. Maybe we should just return "BlaType" instead. We'll think about it.

**Comment by tritao** [comment]
It does look like a bug to me. We just unified our getter/setter to property code last week and looks like this issue is a behavior of the new code.

For now, you can disable the pass using this code:

`driver.Context.TranslationUnitPasses.Passes.RemoveAll(item => item is GetterSetterToPropertyPass);`

**Comment by ddobrev** [comment]
I cannot tell when this was fixed but it's no longer an issue.
