### ISSUE TITLE
Add a sample project to 'Getting Started'

### ISSUE THREAD

**Issue by guitarflow** [mono/CppSharp#720]
I'm an OS X guy and I'm now about to port my app to Windows.
It's been years since I last worked and developed on Windows so I struggled for several hours to get this to run (this is of course not your fault).

Now, everything works, but I can't for the life of me figure out where to put my C++ files (Headers and Libs) so that the library will find it (there's no mention anywhere in the doc and I also can't determine the correct folder from the driver options)!

If you could provide a sample project to the Getting Started guide, it would have saved me TONS and I also think it would be VERY HELPFUL to others.

Thanks in advance!

**Comment by ddobrev** [comment]
Your proposal is definitely reasonable and we'll have it in mind. Meanwhile, please use our own bindings as an example: https://github.com/mono/CppSharp/blob/master/src/CppParser/ParserGen/ParserGen.cs#L79 .

**Comment by tritao** [comment]
Thanks for suggestion, we definitely should improve our getting started experience.

**Comment by guitarflow** [comment]
Thanks guys! Let me also thank you for the great work! This project is exactly what I was looking for.

Could you possibly tell me where the headers and libraries are supposed to live for CppSharp to find them?

**Comment by tritao** [comment]
By default it will look for them in the working directory, but you can also change the search locations using the `LibraryDirs` and `IncludeDirs` options, like @ddobrev linked.

**Comment by guitarflow** [comment]
Sorry I missed that. Thanks for the information.
I found out that "." works when added as LibraryDir but when I try that as include directory, I get an exception (FileNotFound).

All good now! Thanks and keep up the good work!
