### ISSUE TITLE
Getting started with CppSharp - another thing missing

### ISSUE THREAD

**Issue by guitarflow** [mono/CppSharp#722]
Sorry for going on your nerves again ... 
I thought I had it all figured out but I am just now struggling with another DllNotFoundException when trying to use the generated bindings.

If there's any chance for you to tell me what I'm doing wrong I'd be grateful!
I uploaded a ZIP containing three projects:
- a native C++ project creating a static library
- a project generating the bindings
- a project using the bindings

Building the C++ library works, so does the generation of bindings. Only when using the bindings, I'm getting errors...

If you want, you can also provide these sample projects to help other users getting started.

Thanks so much in advance!

[CppSharpGettingStartedProjects.zip](https://github.com/mono/CppSharp/files/673186/CppSharpGettingStartedProjects.zip)

**Comment by tritao** [comment]
I can't check your sample in more detail but after a quick look I noticed you have no DLL export annotations on your native `MyTestClass`.

Make sure the symbols are being correctly exported, you can `Dependency Walker` to open the compiled DLL and make sure. 

Another thing to have in mind is to make sure of the bitness (32/64bit) of the compiled DLL, and match it with the .NET executable.

**Comment by ddobrev** [comment]
If it's the bitness, the exception would've been different - BadImageFormatException. So the cause is @tritao 's first suggestion.

**Comment by guitarflow** [comment]
I found the reason for the DllNotFoundException using Dependency Walker! I apparently needed to install more VS 2015 additions (a system DLL was missing). 

But thanks for the dllexport hint! It was definitely missing as well.
Just FYI: the missing dllexport statements cause an EntryPointNotFoundException.
