### ISSUE TITLE
Question: Does this support generating virtual/overridable methods?

### ISSUE THREAD

**Issue by pauldotknopf** [mono/CppSharp#724]
What if I have a C++ class that has a virtual method with a default implementation?

```c++
class Test
{
public:
    virtual void TestMethod() { /*default implementation*/ }
}
```

```c#
public class Test
{
    public virtual void TestMethod()
   {
   }
}
public class Derived : Test
{
    public override TestMethod()
    {
        // uncommenting the base call will prevent the parent from being called
        base.TestMethod();
    }
}
```

Is something like this do-able? Not sure you can do this in the p-invoke world.

**Comment by tritao** [comment]
Yeah this should work, we support virtual overrides. You can even pass the managed instance back to C++ and virtual calls in native code will call your derived methods.
