### ISSUE TITLE
Possible to set directory, so generator finds header files itself?

### ISSUE THREAD

**Issue by Linchy** [mono/CppSharp#727]
I have a header that refs headers, that refs more headers and so on. Do I need to explicitly define them all?

Currently I am doing:

```
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleDriver.Run(new SampleLibrary());

            Console.Read();
        }
    }

    public class SampleLibrary : ILibrary
    {
        public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            options.LibraryName = "example_bin"; 
            options.Headers.Add(@"C:\Git\libigl\include\igl\lscm.h");
            options.Headers.Add(@"C:\Git\libigl-example-project\build\Interop.h");
            options.Libraries.Add(@"C:\Git\libigl-example-project\build\Debug\example_bin.lib");
        }

        public void SetupPasses(Driver driver)
        {
           // throw new NotImplementedException();
        }

        public void Preprocess(Driver driver, ASTContext ctx)
        {
           // throw new NotImplementedException();
        }

        public void Postprocess(Driver driver, ASTContext ctx)
        {
           // throw new NotImplementedException();
        }
    }
```

and get the output:

```
Parsing libraries...
A file from 'C:\Git\libigl-example-project\build\Debug\example_bin.lib' was not found
Parsing code...
Error parsing 'C:\Git\libigl\include\igl\lscm.h'
C:\Git\libigl\include\igl/lscm.h(13,10): fatal: 'Eigen/Dense' file not found
Error parsing 'C:\Git\libigl-example-project\build\Interop.h'
C:\Git\libigl-example-project\build\Interop.h(3,10): fatal: 'igl/lscm.h' file not found
CppSharp has encountered an error while parsing code.
```

`Eigen/Dense` then contains 10 more headers, which each contain more headers. Is it possible to setup some working directory filepath or something to get this working? Or does the c# binary need to be somewhere in the c++ directory?

**Comment by ddobrev** [comment]
You only need to add the headers you want wrappers for. However, you do need to add all of your include directories in your options so that our parser knows where to look for dependencies.

**Comment by tritao** [comment]
As @ddobrev said, you need to set the include directories in the options.

**Comment by Linchy** [comment]
What is the code for that? I can't see anything in 'options.`

**Comment by ddobrev** [comment]
Please take a look at our examples, such as https://github.com/mono/CppSharp/blob/master/examples/SDL/SDL.cs#L17 .

**Comment by Linchy** [comment]
Ah I don't have that option, I downloaded the binary from [0][1], `CppSharp-0.7.12-vs2015-x32.zip`. So perhaps this is out of date.

[0] https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md
[1] https://github.com/mono/CppSharp/releases

**Comment by tritao** [comment]
You will find those methods on a separate `ParserOptions` type.

Try `var parserOptions = driver.ParserOptions;`.

**Comment by Linchy** [comment]
Oh yes working now, thanks.
