### ISSUE TITLE
Need a way to indicate that one header depends on the macros in another header

### ISSUE THREAD

**Issue by mydogisbox** [mono/CppSharp#73]
I have two headers where one header depends on the macros defined in the other header, but the second header doesn't include the first header.  The assumption is that the first header will always be included in a file before the second header.  As a result, I'm getting errors in the second header.

Currently I am resolving this issue by creating a third header which includes the other two headers in the appropriate order.  It would be nice to have some way of indicating this dependency in code rather than having to create another header.

**Comment by tritao** [comment]
I suggest just creating a new header file that includes the ones you need, or fixing the original code.
