### ISSUE TITLE
Have build server publish the built binaries for OSX/Linux.

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#737]
Maybe I still just haven't looked in the right place yet, I can't seem to find the binaries for download.

I see that there is conveniently a build server that has successfully built on multiple platforms. And that there are releases available for download. But upon downloading the most recent release, it appears to just be source code?

**Comment by ddobrev** [comment]
What platform do you need binaries for? We only offer those for Windows 32 and 64, there are links on our main page.

**Comment by jamesford42** [comment]
Ah, I found it. I needed the win32 ones and found where you indicated; I did not realize the build status indicator was click-through-able (well, for two of them, as you said).

**Comment by tritao** [comment]
Closing, we have https://github.com/mono/CppSharp/issues/765 tracking this.
