### ISSUE TITLE
CleanUnitPass assumes unit.FilePath has a directory name

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#738]
In this screenshot's situation, unit.FilePath is "myheader.h".
I believe Path.GetDirectoryName returns an empty string (maybe null?) but in any case, passing the result through to Path.GetFullPath seems to be invalid.

![image](https://cloud.githubusercontent.com/assets/155688/22400151/eacf88fe-e572-11e6-8994-f70f49acd365.png)

**Comment by ddobrev** [comment]
Thank you for your report. The obvious fix would be to add a check in our code but I am curious to know how your file path ended up containing just a file name. Where is your header located?

**Comment by jamesford42** [comment]
That is just how the project is set up. There is not a /src/ subdirectory below the .vxproj location, so there are a few headers that are commonly included (ie, "common.h") which are in the root alongside the .vxproj

**Comment by ddobrev** [comment]
Do I correctly conclude that you have no include directories in your configuration?

**Comment by jamesford42** [comment]
parseOptions.AddIncludeDirs(@".\");

Apparently that line is important else it finds nothing btw.

**Comment by ddobrev** [comment]
Thank you. We definitely have a bug here but I cannot fix it right now. Please work around it by assigning '.' to the local 'includeDir' if it turns out empty, I think Path.GetFullPath should be able to resolve it.

**Comment by jamesford42** [comment]
It's fine, I have the ability to rebuild cppsharp now (though technically that work-around is insufficient, get directory name for ".\filename.ext" does not return anything different from "filename.ext').

**Comment by ddobrev** [comment]
My mistake. What I meant was:

`var includeDir = Path.GetDirectoryName(unit.FilePath);`
`if (string.IsNullOrWhiteSpace(includeDir))`
`    includeDir = ".";`
`includeDir = Path.GetFullPath(includeDir);`

**Comment by tritao** [comment]
Should be fixed with @ddobrev suggestion.
