### ISSUE TITLE
.cs output per .h input - mode broken?

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#739]
An (unknown) older version of CppSharp I had up till now been using would output one .cs file per .h. Now it seems to be creating only one giant .cs. 

Digging around in the settings I noticed the 'unitybuild' option which is at least documented as doing exactly this, but it still output a single file when i tried it.

Stepping through the code...
src\Generator\Generator.cs; line 80

Normally `GenerateSingleTemplate` is called from here, and it seems to, well, only generate a single cs file... If I instead set the execution line to call `GenerateTemplates` I do get multiple output cs files. Maybe this conditional should be something like... IsCShapreGenerator && !UnityBuild - not really sure.

**Comment by tritao** [comment]
Yeah @ddobrev changed the behaviour here a few weeks back.

Unity build is different in that it allows parsing of all the native headers as if they were just one giant source file.

I think I'd also like to have a dedicated option for this, as sometimes having one file per `.h` is preferable.

**Comment by thejuskambi** [comment]
Is there any update on this? I would like to create different .cs file for each .h file.

**Comment by ddobrev** [comment]
We restored the option for a .cs file per .h in August 2017.
