### ISSUE TITLE
Crash in VectorType.Visit in a system include.

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#741]
I'm getting a NotImplementedException from VectorType.Visit. I am not attempting to use a VectorType. In fact I don't even know exactly what this is referring to. But it appears to be trawling through some system headers which are ultimately not going to be exported (because they are system headers).

![image](https://cloud.githubusercontent.com/assets/155688/22401382/53a0f4ee-e596-11e6-8ba4-2f6c8a3b4f74.png)

**Comment by tritao** [comment]
Guess we just need to stub these out, since it's in an system header it doesn't really matter if we ignore it.
