### ISSUE TITLE
Wrong program name on CLI help text under Mono

### ISSUE THREAD

**Issue by tritao** [mono/CppSharp#745]
##### Brief Description

When running the new CLI under Mono, the wrong program name `mono-sgen32` shows up.

```mono CppSharp.CLI.exe

Usage: mono-sgen32 [OPTIONS]+ [FILES]+
Generates target language bindings to interop with unmanaged code.
```

OS: OS X

**Comment by tritao** [comment]
@zillemarco ˆ

**Comment by zillemarco** [comment]
Yes sure, do I name it CppSharp.CLI like on Windows?

**Comment by ddobrev** [comment]
Fixed by https://github.com/zillemarco/CppSharp/commit/6faa5918844c8a9560fc3a4679416066a4edaddf.
