### ISSUE TITLE
Global namespace ::System not qualified

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#747]
Should you have a library that contains a namespace System, generated code can end up with a generated internal field "System.Collections.Concurrent.ConcurrentDictionary" which fails to build.

I see quite a few other things being prefixed with global:: maybe this one slipped through the cracks?

**Comment by tritao** [comment]
Yep, should be easy to fix.

**Comment by ddobrev** [comment]
@jamesford42 @tritao is correct, it's just a matter of typing "global::" in our code. In fact, it will be quite easy to you as well. I understand you have already set up a development environment for C++# anyway so could you please send us a pull request with the fix? You need to just search for "ConcurrentDictionary" in our Generator project and you'll find the string to change.

**Comment by ddobrev** [comment]
@jamesford42 in addition, please regenerate our parser bindings after you adding the change but before sending your pull. It's really easy, you just have to run the CppSharp.Parser.Gen project.

**Comment by tritao** [comment]
It's not that easy due to the needed headers for regenerating other platforms. By default it will only generate for Windows, so don't worry too much about the parser bindings, there's no need to re-generate them anyway.

**Comment by ddobrev** [comment]
@jamesford42 @tritao 's correct, we do not contain the headers in question in the repository. Perhaps we should, @tritao and I will discuss it later on. Meanwhile, please heed his advice and stick just to the fix, we'll regenerate the bindings ourselves.

**Comment by jamesford42** [comment]
Sorry guys, I got deep into deadlines. Had to halt my effort to update to most recent CppSharp, as it did not actually fix any known issues for my project.

**Comment by tritao** [comment]
No problem, which issues are most problematic to your project?

**Comment by jamesford42** [comment]
1. Exposing static classes.
2. Exposing types with private constructors (because they are always and exclusively allocated by C++ code).
3. Various options which I make use of were behaving buggy: emit individual code files per header included, only rewrite files that have changes, dont include std types, dont include system types.
4. Hidden private members still emitted within internal types (as previously metioned, this was particularly problematic for private constructors, but also applies to private fields that are intentionally hidden and unknown to C#.
5. Array types used as either arguments or fields both have significant issues.
