### ISSUE TITLE
Handle all primitive types in internal layouts in the generated C#

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#771]
We have the following piece in the C# generator:

    // we do not support the primitives below yet because their representation in C# is problematic
    if (coreType.IsPrimitiveType(PrimitiveType.LongDouble) ||
        coreType.IsPrimitiveType(PrimitiveType.Int128) ||
        coreType.IsPrimitiveType(PrimitiveType.UInt128) ||
        coreType.IsPrimitiveType(PrimitiveType.Half))
        return;

This is troublesome now that we have an option for generating sequential layouts. We need to find a way to represent such fields and include them in our internal layouts.

**Comment by tritao** [comment]
We can use fixed-size buffers.

https://msdn.microsoft.com/en-us/library/zycewsya.aspx
