### ISSUE TITLE
Is there a way to get CppSharp into a docker image, without compiling? NuGet?

### ISSUE THREAD

**Issue by pauldotknopf** [mono/CppSharp#775]
I'd like to run a docker container to generate my C# bindings. I will be using a Debian 64bit docker file. Is there a way to get CppSharp precompiled, for installation in the image?

**Comment by ddobrev** [comment]
@pauldotknopf we have a task at https://github.com/mono/CppSharp/issues/765 for publishing the Linux binaries from our CI. They are built on Ubuntu 64 so they should work for you on Debian. The task is not difficult but we just haven't had the time to complete it. If you need it immediately, you could either help out or check our support options at https://github.com/mono/CppSharp#support.

**Comment by pauldotknopf** [comment]
I recommend building on Debian, instead of Ubuntu. Debian-built libraries are easier to support on Ubuntu, than vice-versa.

**Comment by tritao** [comment]
Should be pretty easy to get a Docker container up following the scripts from Travis: https://github.com/mono/CppSharp/blob/master/.travis.yml

If you do create a Dockerfile, please send us a pull request, I'll integrate it in the Travis build so we can update the image automatically for official releases.

**Comment by tritao** [comment]
We have everything on NuGet these days.
