### ISSUE TITLE
What is the deal with Std-templates.cpp

### ISSUE THREAD

**Issue by pauldotknopf** [mono/CppSharp#776]
I see this generated and copied to my output directory.

Should I be including the .cpp file into by generated dlls, so that this types are exported?

**Comment by ddobrev** [comment]
STD is not properly supported in the C# generator yet so please just ignore this file.

**Comment by pauldotknopf** [comment]
It looks like by generated bindings is trying to use it though.

```c#
public static int Echo(string peerHost, ushort peerPort, string callingAETitle, string calledAETitle)
{
    var __allocator0 = new global::Std.Allocator();
    var __basicString0 = new global::Std.basic_string(peerHost, __allocator0);
    var __arg0 = *(global::Std.basic_string.__Internal*) __basicString0.__Instance;
    var __allocator2 = new global::Std.Allocator();
    var __basicString2 = new global::Std.basic_string(callingAETitle, __allocator2);
    var __arg2 = *(global::Std.basic_string.__Internal*) __basicString2.__Instance;
    var __allocator3 = new global::Std.Allocator();
    var __basicString3 = new global::Std.basic_string(calledAETitle, __allocator3);
    var __arg3 = *(global::Std.basic_string.__Internal*) __basicString3.__Instance;
    var __ret = __Internal.Echo_0(__arg0, peerPort, __arg2, __arg3);
    __basicString0.Dispose(false);
    __allocator0.Dispose();
    __basicString2.Dispose(false);
    __allocator2.Dispose();
    __basicString3.Dispose(false);
    __allocator3.Dispose();
    return __ret;
}
```

Are you saying I can't expose types with ```std::string```?

**Comment by ddobrev** [comment]
I know for certain it doesn't work on macOS. If it does on Linux, it is by chance. If you want to try it, compile Std-templates.cpp into a library called Std-templates and ship it along with your binding.

**Comment by tritao** [comment]
Support for std::string is still a bit experimental, @ddobrev should be improving it this month.

**Comment by vitalyster** [comment]
Got the same generated output for std::string, where to get Std.basic_string ?
