### ISSUE TITLE
Partially defined structs not being treated as IntPtr

### ISSUE THREAD

**Issue by pauldotknopf** [mono/CppSharp#779]
Imagine the following simple c api.

```c
enum medx_dicom_response
{
  ok,
  error
}
struct medx_dicom_server;

medx_dicom_response test1(
    medx_dicom_server** server
);

medx_dicom_response test2(
    medx_dicom_server* server
);

medx_dicom_response test3(
    medx_dicom_server* server
);

medx_dicom_response test4(
    void*
);

medx_dicom_response test5(
    void**
);

medx_dicom_response test6(
);
```

With this API, only ```test4```, ```test4``` and ```test6``` get generated.

I think the other methods should be generated with an IntPtr (or maybe something more strongly typed? does't matter).

**Comment by ddobrev** [comment]
Could you please tell us if you got C++# as binaries or built it from source?

**Comment by realvictorprm** [comment]
Hey @pauldotknopf I'm currently working on this issue. Stand by ;)

**Comment by realvictorprm** [comment]
- [x]  Add C# generation
- [ ] Add CLI generation

#797
