### ISSUE TITLE
Build of program failed due to VCVarsQueryRegistry.bat not found

### ISSUE THREAD

**Issue by realvictorprm** [mono/CppSharp#784]
##### Brief Description
After solving my last issue I know have runtime problems. The title says the main problem.
It occures at `ConsoleDriver.Run(new Program());`.

I'm using Windows 10 with VS 2017. Latest CppSharp release 0.8.6.

I suppose it's because of VS 2017. For the batch file is searched in the wrong directories (it assumes VS2015 I think).

**Comment by ddobrev** [comment]
@realvictorprm we would love support for VS 2017 ourselves and it's not even that difficult to add. However, we're really busy these days so I would like to ask for your help. Unless there were major changes in the way VS 2017 is registered, the fix should be just a matter of adding an enum member at https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L17 and handling it at https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L114. If you decide to give it a try, let me know if I can help.

**Comment by tritao** [comment]
The directory layout of VS2017 also changed, so I think we'll have to update those parts in https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L146.

**Comment by realvictorprm** [comment]
I think there's no way around participation. I wouldn't like to throw away the hours solving those small issues.

Also the Lua Script for downloading and installing the dependencies needs an update

**Comment by realvictorprm** [comment]
@tritao The whole ecosystem changed so it's needed to handle this separate.

**Comment by tritao** [comment]
Sounds good, closing since we have other issues tracking VS 2017.
