### ISSUE TITLE
Support for VS 2017

### ISSUE THREAD

**Issue by realvictorprm** [mono/CppSharp#785]
After having issue because of VS 2017 I think it's fine to suggest that support for VS 2017 has to be tested too. If there's something we users/devs can do for helping tell us.

Okay seems like I'm taking responsibility for this. Here is the list of current To-do's:

- [x] Fix lua script for building the dependencies  (Comming in next commit!)
- [x] Fix build xml for VS 2017 (rather dependency issue than issue of CppSharp) 
- [x] Fix code for searching MSBuild vars
- [x] Update Premake5 tools (Comming in next commit!)
- [x] Try fixing parsing issues through updating to a newer clang version

**Comment by ddobrev** [comment]
@realvictorprm thank you for your offer. I have posted some initial guidelines at https://github.com/mono/CppSharp/issues/784#issuecomment-285626195 .

**Comment by realvictorprm** [comment]
@ddobrev shouldn't we link issues related to that here and not in the issues? I would consider this as overview for the progress.

**Comment by realvictorprm** [comment]
Just for documentation. 
*Premake5 tools were outdated and will therefore be updated with the next commit!*

**Comment by realvictorprm** [comment]
The SSL error is due to the updated premake5 binaries. It's an issue of them currently. Don't know what to do...

**Comment by tritao** [comment]
Thanks for taking charge of this @realvictorprm.

Let me know if I can help, do you need a Premake5 build for Windows with the code from the PR?

**Comment by realvictorprm** [comment]
I'm currently making not a pull request because it would break the Travis-CI due to the SSL issue of premake5. So if the Premake5-build would work without any SSL issue this would help a lot. 

I planned to update the mac binaries too but actually they don't have to be updated (no VS for mac), but they're still not up-to-date).

**Comment by realvictorprm** [comment]
Unfortunately I'm having some issues. A pre working version is currently available on my fork. However standard library stuff does not work correctly currently.

**Comment by tritao** [comment]
Thanks to @realvictorprm most of the bits for supporting VS2017 have been merged. Only some parsing errors at runtime remain which we assume will be fixed with an update to Clang.

**Comment by damageboy** [comment]
One thing that seems to be missing is VS2017 builds for LLVM/windows or alternatively a patch to the script to use the 2015 build for 2017

**Comment by ddobrev** [comment]
@damageboy that package was just the VS 2015 one renamed. I'll restore it now.

**Comment by ddobrev** [comment]
@damageboy done but please have in mind that you might get errors while parsing. We need to update our LLVM build but we've had trouble to do so.

**Comment by tritao** [comment]
Yeah we did have the 2017 build package at one point, guess it was lost when moving from Dropbox to Github.

**Comment by ddobrev** [comment]
Fixed by https://github.com/mono/CppSharp/commit/d7daed827373e52ab5e365640be4b2770f9acb6f .
