### ISSUE TITLE
Bindings are incomplete

### ISSUE THREAD

**Issue by wagnerma** [mono/CppSharp#788]
I try to generate bindings for the gnugpg lib gpgme. Some functions are generated and usable, but some are missing compared to the SWIG version, for example the method gpgme_new method is missing.

OS: Windows 10

Used headers: gpgme.h and gpg-error.h

Used settings:
```
        public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            options.OutputDir = "..\\..\\..\\..\\GpgmeLibrary";
            var module = options.AddModule("libgpgme");
            module.Headers.Add("C:\\Program Files (x86)\\GnuPG\\include\\gpg-error.h");
            module.Headers.Add("C:\\Program Files (x86)\\GnuPG\\include\\gpgme.h");
        }

```
Target: C#

The header files and genrated code is placed at google drive

https://drive.google.com/drive/folders/0B1EIYV0ihMjCQk05UjUyMkNnems?usp=sharing

**Comment by ddobrev** [comment]
This function is most probably ignored. @tritao and I have both been really busy lately but if you would debug it yourself, I could give you some initial guidelines what to check and where.

**Comment by tritao** [comment]
I think this is the same issue as https://github.com/mono/CppSharp/issues/779.

**Comment by wagnerma** [comment]
Yep, it seems there is an issue with anonymous structures like
```
struct gpgme_context;
typedef struct gpgme_context *gpgme_ctx_t;

```
It is a way in C to hide implementation details. Only a pointer to the anonymous opject is available.

**Comment by tritao** [comment]
Closing since we have other issue tracking this.
