### ISSUE TITLE
Declarations, adding a children should be equivalent to setting the parent

### ISSUE THREAD

**Issue by realvictorprm** [mono/CppSharp#792]
##### Brief Description
Child's are added to a parent currently in this way (F# code):
```
let someenum = new Enumeration ()
let enumitem = new  Enumeration.Item()
do enumitem.namespace <- someenum //Why? Shouldn't add do this?!
do someenum.Items.Add (enumitem)
``` 

However, if we developers only look on how the methods are named this isn't intuitive to us.

We would like to see that _add_ is only needed for accomplishing the same.

**Comment by tritao** [comment]
Closing as we're unlikely to spend time on this, feel free to send a PR :)
