### ISSUE TITLE
Unable to override TranslationUnitPasses

### ISSUE THREAD

**Issue by daverobo** [mono/CppSharp#802]
Some TranslationUnitPasses are forcibly added to Driver.Context and cannot be overwritten. This is done in Driver.SetupPasses(ILibrary) method after ILibrary.SetupPasses(Context) is called.

The issue seems to be that the ILibrary.Preprocess(...) method is called before the ILibrary.SetupPasses(...) method. If the calling order was reversed then the TranslationUnitPasses could be modified in ILibrary.Preprocess(...) method.

This could be fixed in ConsoleRunner.Run(ILibrary) by swapping lines [1] and [2] below. Possibly this is how the ILibrary interface was originally designed to work?

```
    public static class ConsoleDriver
    {
        public static void Run(ILibrary library)
        {
            ...
[1]        library.Preprocess(driver, driver.Context.ASTContext);
[2]        driver.SetupPasses(library);
            driver.ProcessCode();
            library.Postprocess(driver, driver.Context.ASTContext);
```

CppSharp 0.8.6 from nuget.org

OS: Windows 7 SP1 64-bit

Using a basic implementation of ILibrary based on examples.
driver.Options.GeneratorKind = GeneratorKind.CSharp
All other options (except include directories and headers) are default.

Sorry don't know how to do the git pull request thingy.

**Comment by ddobrev** [comment]
So you want Preprocess to occur after the passes are set up so that users can remove passes they don't want. This is a reasonable suggestion but we need to check if it breaks any existing behaviour. So what I can do is help you add a pull request. When you do, our CI will pick it up and show if there are any errors. If not, I'll try it with QtSharp too and merge if there are no issues.
The way you make a pull request is actually quite simple:
1. Fork the project (in this case CppSharp) by using the aptly named button at the top right;
2. Make your change and commit;
3. Go back to the original project and open the tab of "Pull Requests";
4. Click "New pull request" at the top right;
5. Click the link "compare across forks";
6. Select your fork and click "Create pull request".

Still, I would like to know what problem with the existing passes you have. Perhaps it's unintended - or outright incorrect - behaviour of some pass which we would really like to know about in order to fix it whenever time permits.

**Comment by realvictorprm** [comment]
I could do the pull request for you @daverobo ;)

**Comment by daverobo** [comment]
My original problem is that function names were being transposed from lower case + underscores into camel case without underscores. I just wanted the function names to remain the same.

Browsing through the source code (Generator\Driver.cs) I noticed the call to `TranslationUnitPasses.AddPass(new CaseRenamePass(..., RenameCasePattern.UpperCamelCase))` and suspect this was the culprit. This code has since changed slightly but probably does the same thing (https://github.com/mono/CppSharp/blob/master/src/Generator/Driver.cs#L340). This pass is added after the call to ILibrary.SetupPasses() (https://github.com/mono/CppSharp/blob/master/src/Generator/Driver.cs#L295) so cannot be customised.

I installed Git, forked CppSharp, then cloned CppSharp, llvm, and clang to my desktop. Couldn't build llvm so installed the binaries instead. Tried to build CppSharp using Visual Studio 2015 but it complains it cannot find llvm-config.h; probably because the llvm build never finished successfully. So I probably need to get the llvm build working first.

**Comment by tritao** [comment]
You should not need to build LLVM yourself, this is why we provide pre-built binaries.

See https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md#downloading-the-llvm-and-clang-packages.

**Comment by ddobrev** [comment]
@daverobo I see. Please add the pull request and if everything works properly, we'll merge and you'll be able to remove the renaming pass.

**Comment by daverobo** [comment]
Thanks tritao. I didn't notice that option before.

> Alternatively, if on Windows, just double click on <CppSharp>/build/DownloadDeps.bat

DownloadDeps.bat didn't work with a double click:
```
D:\CppSharp\build>"premake5" --file=scripts/LLVM.lua download_llvm
Error: ...D:/CppSharp/build/scripts/LLVM.lua:56: Unknown MSVC compiler version, run in VS command prompt.

D:\CppSharp\build>goto quit

D:\CppSharp\build>pause
Press any key to continue . . .
```
From the "Developer Command Prompt for VS2015":

D:\CppSharp\build>DownloadDeps.bat
```
D:\CppSharp\build>"premake5" --file=scripts/LLVM.lua download_llvm
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-cccdd2-windows-vs2015-x86-RelWithDebInfo.7z
Error: ...D:/CppSharp/build/scripts/Utils.lua:96: SSL connect error
schannel: failed to retrieve ALPN result
D:\CppSharp\build>goto quit
D:\CppSharp\build>pause
Press any key to continue . . .
```
Different kind of broken. Probably related to this curl issue (https://github.com/curl/curl/issues/840) which is presumably baked into premake5. Tried to identify specific version of premake5 application but failed. Replaced it with the latest version anyway (https://github.com/premake/premake-core/releases/download/v5.0.0-alpha11/premake-5.0.0-alpha11-windows.zip).
```
D:\CppSharp\build>DownloadDeps.bat

D:\CppSharp\build>"premake5" --file=scripts/LLVM.lua download_llvm
Downloading: https://github.com/mono/CppSharp/releases/download/CppSharp/llvm-cccdd2-windows-vs2015-x86-RelWithDebInfo.7z
Error: ...D:/CppSharp/build/scripts/Utils.lua:96: SSL peer certificate or SSH remote key was not OK
Cert verify failed: BADCERT_NOT_TRUSTED

D:\CppSharp\build>goto quit
D:\CppSharp\build>pause
Press any key to continue . . .
```
Another kind of broken. LLVM.lua just downloads llvm-cccdd2-windows-vs2015-x86-RelWithDebInfo.7z and unpacks it so I decide to do it myself. Unpacked the 7z archive into D:\CppSharp\build\scripts, built the visual studio project files (again), then started the build:
```
GenerateProjects.bat
msbuild vs2015\CppSharp.sln /p:Configuration=Release;Platform=x86

    526 Warning(s)
    0 Error(s)

Time Elapsed 00:02:57.75
```
Success! Stay tuned for the code change and git pull request (couple of days).

**Comment by tritao** [comment]
Heh, yeah, looks like you found a bunch of annoying HTTP issues in curl and Premake, hopefully upstream will get them sorted out.

About this issue, the lack of flexibility of the pass system has been on my mind before and would definitely like to see some improvements done to it. Ideally we'd have some more methods to allow external users to modify the order and even removal of the passes before execution. 

Let us know if you have any questions regarding the PR.
