### ISSUE TITLE
Linux-Build not compatible with mono 4.8

### ISSUE THREAD

**Issue by giladlevi** [mono/CppSharp#803]
I have try to compile CppSharp on linux and i got an error:
traceback...
fatal error /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)

only downgrade to mono 4.6.2 solved me the problem.
please add it to the requirements and .travis.yml too.

**Comment by ktngoykalolo** [comment]
you could fork the project, add the modification and make a pull request.

**Comment by realvictorprm** [comment]
What have you used @giladlevi?
We need more details.

**Comment by giladlevi** [comment]
I used mono 4.8.1.

**Comment by realvictorprm** [comment]
Which compiler @giladlevi ? Gcc or clang 😉 ?

**Comment by giladlevi** [comment]
gcc

**Comment by realvictorprm** [comment]
@giladlevi let's talk in the managed interop gitter

**Comment by spacepluk** [comment]
I'm not sure if it's the same but I'm getting this when I try to build on Arch Linux with Mono 5.0.0.

https://gist.github.com/spacepluk/9109738837f6e9c257516bd1edf7e1b8

**Comment by tritao** [comment]
Closing, re-open if still an issue with latest Mono.
