### ISSUE TITLE
Question about getting-start with CppSharp

### ISSUE THREAD

**Issue by jinnan** [mono/CppSharp#810]
I've worked a lot with c++ and I'm learning c#/Xamarin to create a cross-platform app.
My collegue sent me some c++ class which I should add to my shared project in Xamarin.

- My first question : is that possible to generate c# "code" directly from c++ source code with CppSharp? 

- My second question is I don't know where to put my c++ .lib and .h (newbie question)

I followed the manual at : https://github.com/mono/CppSharp/wiki/Getting-Started But I've got stuck ..

1. I created a new c# project and I installed CppSharp from NuGet.
2. I've implemented ILibrarby as shown below and I've complied it with success: 

```
class DllDemoGenerator : ILibrary{
        static void Main(string[] args)
        {
            ConsoleDriver.Run(new DllDemoGenerator());
        }

        void ILibrary.Postprocess(Driver driver, ASTContext ctx)
        {
        }

        void ILibrary.Preprocess(Driver driver, ASTContext ctx) { }

        void ILibrary.Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            var module = options.AddModule("Test");
            module.Headers.Add("Test.h");
            module.Libraries.Add("Test.lib");
        }

        void ILibrary.SetupPasses(Driver driver) { }
 }
```

3. Then I tried following things:
	+ I added .h and .lib to my c# project, I  got file .h and .lib not found error
	+ I copied .h and .lib into the folder of .exe of my c# project, same error

	Error I've got :

> 	"Parsing libraries...      
> 	A file from 'Test.lib' was not found     
> 	Parsing code...                      
> 	A file from 'Test.h' was not found      
> 	Processing code... " 

	
Someone can help me, please?

OS: Windows with VS 2017

**Comment by realvictorprm** [comment]
You're missing headers @JINNan. Which headers are required for Test.h?

**Comment by JINNan** [comment]
@realvictorprm    I've #include "stdafx.h" in my Test.h , which has :
```
#include "targetver.h"

#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers

#include <iostream>
#include <stdio.h>
#include <vector>
```
It's generated by visual studio by default. How can I add them while using CppSharp?

**Comment by ddobrev** [comment]
@jinnan Headers and Libraries only contain the file names. You need to additionally add their paths to respectively IncludeDirs and LibraryDirs.

**Comment by jinnan** [comment]
@ddobrev I'm not familiar with lib/dll things:(
For example, if I have test.h including sample.h,
Where should I put these files? should I add some codes in my setup too?

**Comment by ddobrev** [comment]
Your test.h is located in some directory. You need to add that directory to Module.IncludeDirs.

**Comment by jinnan** [comment]
@ddobrev OK, thanks! I'll test it next Monday.

**Comment by ktngoykalolo** [comment]
I guess that there could be a FAQ in the wiki, because I notice that a lot of newbies have issues with properly getting started. let's see how we can add more details on the getting started pages. some fundamentals on C++ are needed to use CppSharp.

**Comment by ktngoykalolo** [comment]
another question : why does cppsharp map char-to-system::byte ??

**Comment by jinnan** [comment]
Yeah, great idea @ktngoykalolo. It would be very helpful if there's a detailed example about how to import a library, maybe with a real dll/lib or something using commonly used parameters (includeDirs, path of libs, etc).

By the way, I've generated my binding codes with success. Thank you all :)

**Comment by tritao** [comment]
`char` in the C language represents an 8-bit signed/unsigned (depends on implementation) integer type, hence why we map it to `byte`. Since C does not provide an distinct type for 8-bit integers and characters we cannot figure out which particular usage of `char` refers to.

We do provide an `MarshalCharAsManagedChar` option which you can try.

**Comment by ktngoykalolo** [comment]
thanks @ddobrev  for the clear explanation, I did try to use MarshalCharAsManagedChar but for some members return types, they still output to System::Byte.
