### ISSUE TITLE
Building for Windows x86 fails, .Gen projects use VS2017 includes when built with VS2015

### ISSUE THREAD

**Issue by Holo-Krzysztof** [mono/CppSharp#814]
##### Brief Description
I've followed the build instructions for Windows from the documentation, but when trying to compile I get a lot of "constexpr variable '_Memcpy_move_offset' must be initialized by a constant expression" errors in xstring. I've noticed that the file in question is located within the Visual Studio 2017 folder, even though I want to use (and have generated a 2015 project).
Is there a way to choose the MSVC version manually or is the problem I'm having completely unrelated to that?

OS: Windows 10.14393.969

Target: MSVC

**Comment by ddobrev** [comment]
@Holo-Krzysztof the problem is https://github.com/mono/CppSharp/issues/815 which I have just reported. Unless you'd like to help with it, you can work around it by hard-coding VS2015 to your SetupMSVC call.

**Comment by Holo-Krzysztof** [comment]
Where can I find that call?

**Comment by ddobrev** [comment]
Simply open you generated CppSharp solution and search.

**Comment by Holo-Krzysztof** [comment]
Got it, thanks. It builds without errors now.

**Comment by tritao** [comment]
For a more long-term solution, we can generate a C# file at build time, say `BuildInformation.cs` or something which provides the preferred VS version (according to the VS action used by Premake). We can also store extra data in the future like the Git revisions for C++#, LLVM and Clang to aid troubleshooting issues.

**Comment by realvictorprm** [comment]
I'm sorry, I should have taken care of this too I think.

Am 11.04.2017 14:00 schrieb "João Matos" <notifications@github.com>:
