### ISSUE TITLE
include\functional(218,11): error: cannot use typeid with -fno-rtti

### ISSUE THREAD

**Issue by Ark-kun** [mono/CppSharp#819]
This is the first time I try to use CppSharp.
I try to build a wrapper around the Cntk library.
I'm on Windows 10.0.14393 and  I have Visual Studio versions 2010, 2012, 2015, 2017 installed.
I get the following error when I use the simple setup code:

>Parsing libraries...
>Parsing code...
>Error parsing 'CNTKLibrary.h'
>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(218,11): error: cannot use typeid with -fno-rtti
>CppSharp has encountered an error while parsing code.

```
        public void Setup(Driver driver) {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            var module = options.AddModule("CntkLibrary");
            module.IncludeDirs.Add(@"a:\CNTK\Source\CNTKv2LibraryDll\API\");
            module.Headers.Add(@"CNTKLibrary.h");
            driver.ParserOptions.SetupMSVC(VisualStudioVersion.VS2015);
        }
```

**Comment by tritao** [comment]
This is because we unfortunately hardcode the `no-rtti` option, see https://github.com/mono/CppSharp/blob/master/src/CppParser/Parser.cpp#L285.

You can try compiling CppSharp without this line or maybe try adding `ParserOptions.AddArguments("-frtti")`.

The long-term fix is to remove the compiler arguments code from `Parser.cpp` and move it all to managed code.

**Comment by Ark-kun** [comment]
>You can try compiling CppSharp without this line or maybe try adding ParserOptions.AddArguments("-frtti").

For some reason, with `ParserOptions.AddArguments("-frtti")` I'm getting the following error:
> error: unknown argument: '-frtti'

I'm not getting such unknown argument error when I use `ParserOptions.AddArguments("-fno-rtti")`.
That's weird. Maybe the `-frtti` option is missing from the version of clang used in CppParser...?

**Comment by ChrisJMarshall** [comment]
I've also hit this issue whilst trying to get CppSharp to work with Boost::Signals2. I couldn't find any way to enable RTTI without rebuilding CppSharp from source with the no-rtti option removed. In my case it was possible in the end to work around the problem a different way but it would be much better if there was a setting in CppSharp that allowed the user to enable RTTI.

**Comment by trmcnealy** [comment]
I'm getting a similar error:
VTK\include\vtkTypeTemplate.h(94,33): error: cannot use typeid with -fno-rtti
error: unknown argument: '-frtti'

ParserOptions.AddArguments("-frtti") doesnt work

Rebuilding CppParser on Windows 7 with an existing build of LLVM/Clang is generating to many errors...

**Comment by tritao** [comment]
The build should work. We recently updated our Clang builds, so make sure to run `DownloadDeps.bat` again, in case you have the old version.

About the overall RTTI issue, we're planning to get fix for this one soon.
