### ISSUE TITLE
Stack mismatch when bool param passed from C++ to C# 

### ISSUE THREAD

**Issue by giladlevi** [mono/CppSharp#834]
I have a c++ class that I inherits from and overrides some virtual functions.

The C++ virtual function looks like this:
```c++
virtual void OnSomething(bool iAmABool) {};
```

C++ stores booleans (at least on VC++) as 1-byte.
Therefore, when C++ calls the generated delegate it will push 1 byte onto the stack (for example, in the case of x86 thiscall)
The generated delegate on the c# side will looks like this:
```c#
[SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.ThisCall)]
internal unsafe delegate void Action_bool(bool instance);
```
This signature uses the c# bool type for the delegate definition which apparently consumes 4 bytes off the stack.

This leads to a most unfortunate mismatch, where 3 bytes of the c# bool are basically random garbage read from the stack.

**Comment by ddobrev** [comment]
Thank you for your report. We know where the bug is so since we're satisfied with the code you sent the last time, I would like to let you know I'll be happy to provide any assistance you might need should you decide to try fixing this one as well.

**Comment by giladlevi** [comment]
@ddobrev I did it, I'll open a pull request.
Please take a look on issue https://github.com/mono/CppSharp/issues/831 that I wrote also few days ago. I already fixed it also, maybe can I open 2 pull requests?

**Comment by ddobrev** [comment]
@giladlevi excellent, please do.
About #831, I am a little surprised you managed. It's not trivial. I would be curious indeed to see your solution.
