### ISSUE TITLE
Template support in CppSharp

### ISSUE THREAD

**Issue by BlueSolei** [mono/CppSharp#836]
##### Description
I try to create a binding to a simple specialized template, but no code is get generated.
I tried both C# and C++\CLI targets.
Code is like this:
```cpp
template<class T>
struct Property
{
	T value;
};
typedef Property<int> PropertyInt;
```
CppSharp version 0.8.10
OS: Windows 7
Target: MSVC 2015 update 3
Any help will be appreciated.

**Comment by ddobrev** [comment]
Support for templates is upcoming, it should be complete by the end of June.
