### ISSUE TITLE
Exception with boost::signals2

### ISSUE THREAD

**Issue by ChrisJMarshall** [mono/CppSharp#861]
I'm working on a project in MSVC 2017 on Windows for which I'm experimenting with using CppSharp to generate C++/CLI wrappers. I'm also experimenting with using boost::signals2 which is causing problems for CppSharp. At this stage I'm not trying to generate wrappers for the signals (though ultimately it would be great to expose them as .NET events) just get CppSharp to be able to read the headers without failing.

Some of the issues were just problems with the combination Boost and Clang on Windows that I've now managed to work around. I also hit issues due to CppSharp hard coding '-fno-rtti' though I've managed to work around these too.

The current problem is a crash in CppSharp when parsing size_t_fwd.hpp when it's referenced from signals2. The problem manifests in CppSharp.DeclConverter.VisitClassTemplate. spec is of type ClassTemplateSpecialization, however the call to Visit finds an object in Declarations with a matching key the type of which is actually CppSharp.AST.Class. When this is returned VisitClassTemplate attempts to cast it to AST.ClassTemplateSpecialization which results in an InvalidCastException.

Attached is a sample program using to reproduce this exception using the NuGet packages for CppSharp and Boost on VS2017. Just build and run the WrapperGeneratorDC project.
[CppSharpIssue1.zip](https://github.com/mono/CppSharp/files/1066537/CppSharpIssue1.zip)

**Comment by tritao** [comment]
Thanks for the issue report and repro information.

Until we can get someone to look into this and fix it, you can try to ignore the header / types involved and see if it gets you any further.

**Comment by ChrisJMarshall** [comment]
Hi tritao,
Thanks for your suggestion. I tried this one again but I'm still having problems. The only way I can see to ignore headers/types (looking at SDL example) is by calling ctx.IgnoreHeadersWithName in Preprocess. Unfortunately this exception is occurring before Preprocess gets called. The top of the call stack is :
`CppSharp.Parser.dll!CppSharp.ASTConverter.Convert() Line 403 + 0x1f bytes	C#
CppSharp.Parser.dll!CppSharp.ClangParser.ConvertASTContext(CppSharp.Parser.AST.ASTContext context) Line 113 + 0xa bytes	C#
CppSharp.Generator.dll!CppSharp.Driver.ParseCode() Line 206 + 0x29 bytes	C#
CppSharp.Generator.dll!CppSharp.ConsoleDriver.Run(CppSharp.ILibrary library) Line 488 + 0xa bytes	C#`

Can you suggest any other workaround?

**Comment by mohtamohit** [comment]
I have compiled my findings over this issue [here](https://docs.google.com/document/d/1Z5sOhJdv6V0b97ZFUShSip-zJKJLoQssgwg6SgUDSog/edit?usp=sharing).  These details might be helpful for future reference.

**Comment by ChrisJMarshall** [comment]
Just to let you know that this no longer seems to be a problem on newer versions of CppSharp. If this is due to something you guys have done then thank you.

**Comment by ddobrev** [comment]
@ChrisJMarshall it most probably is but I cannot tell what. :) Nevertheless, I am happy it works for you now.
