### ISSUE TITLE
Error parsing file, corecrt.h not found

### ISSUE THREAD

**Issue by 7Hazard** [mono/CppSharp#865]
##### Brief Description

CoreCRT.h wasn't found, even though CRT SDK is installed.

##### Used settings

Target: MSVC using NuGet package

##### Errors

Error parsing 'header.h'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\crtdefs.h(10,10): fatal: 'corecrt.h' file not found

**Comment by 7Hazard** [comment]
I added 
module.IncludeDirs.Add("C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/ucrt");
and it works. But I still believe this shouldn't be necessary, it solved my issue however.

**Comment by realvictorprm** [comment]
Uh what's wrong. LookS like I need to check my code again.

**Comment by 7Hazard** [comment]
Some extra info
Using MSVC version 2017 caused this error with strings:
`xstring(1905,26): error: constexpr variable '_Memcpy_move_offset' must be initialized by a constant expression`

The following solved the issue, written in the Setup method:
`var popt = driver.ParserOptions;
            popt.SetupMSVC(VisualStudioVersion.VS2015);`

**Comment by realvictorprm** [comment]
@7hazard this is a known issue due to clang.

**Comment by realvictorprm** [comment]
@7Hazard What is the content of the folder "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0" ? Are folders named "shared", "um", "winrt" and "ucrt" in there too?

**Comment by 7Hazard** [comment]
Yes @realvictorprm

**Comment by realvictorprm** [comment]
Strange situation then. Do you have multiple folders in the root folder above? (so multiple windows 10 sdk's)

**Comment by 7Hazard** [comment]
Yes

![](http://i.imgur.com/zMnbNhc.png)

Im not sure if you're misunderstand but, it DID solve my issue adding that as include folder in my generator.
