### ISSUE TITLE
Bad includes from CLI Generator when renaming outputs with GenerateName

### ISSUE THREAD

**Issue by ChrisJMarshall** [mono/CppSharp#868]
OS: Windows
Target: MSVC

##### Brief Description
I was using a the GenerateName property of Driver.Options to provide a function that modified the names of my output files (adding "Wpr" to the end of the name in this case) to make it easier to identify the automatically generated wrappers. This worked until I tried to generate a wrapper for a class that made use of another wrapped class. The cpp file for the dependent wrapper tried to #include the other wrapper on it's original rather than modified name.

Please let me know if you need more information to reproduce this.

**Comment by tritao** [comment]
Thanks for the bug report.

@ddobrev This one should be easy to fix, please assign this to whoever is available.

**Comment by ddobrev** [comment]
@tritao will do. Mohit should be done with another user's bug tomorrow so I'll have him take care.
