### ISSUE TITLE
Documentation comments in C++/CLI wrappers require three slashes

### ISSUE THREAD

**Issue by ChrisJMarshall** [mono/CppSharp#870]
OS: Windows
Target: MSVC
Generator: CLI

##### Brief Description
When I use Doxygen style ('///') comments CppSharp tries to replicate them as MSVC XML documentation comments in the wrapper, but unfortunately only uses two slashes ('//') rather than three ('///') for the generated comments. Visual Studio requires three slashes to identify a documentation comment.

**Comment by tritao** [comment]
This one should be easy to fix, want to try sending a PR with a fix? We can guide you through the process if you need some guidance.

**Comment by ddobrev** [comment]
Fixed by @ktopouzi at https://github.com/mono/CppSharp/commit/d7c8a61ecc2d29e78a21f6605f39877cf093d004#diff-fe0069ea5f91d37a96644b6c1096b2a0R146 .
