### ISSUE TITLE
Failed to compile source

### ISSUE THREAD

**Issue by 7Hazard** [mono/CppSharp#879]
##### Brief Description

Failure to compile source VS2017, using Visual Studio 2017 Developer Command Prompt v15.0.26430.13
OS: Windows

##### Used source

Last commit before this issue

##### Used settings

Premake for windows, Generate Project for Visual Studio 2017 (following the docs)
Target: MSVC

##### Stack trace or incompilable generated code

![](http://i.imgur.com/CM6lKuS.png)
[Complete gist of compilation output](https://gist.github.com/7Hazard/80108133b9bed1c05fa2f3432ae48976)

**Comment by tritao** [comment]
The real issue comes earlier in the output:

```
  Error parsing 'StandardLib.h'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\crtdefs.h(10,10):
  fatal: 'corecrt.h' file not found
```

Looks like https://github.com/mono/CppSharp/issues/865.

**Comment by 7Hazard** [comment]
Back then, I was able to compile the source. And in issue [#865](https://github.com/mono/CppSharp/issues/865), I was using the precompile NuGet package to generate the .cs bindings.

Attempting to compile for Visual Studio 2015 also fails.
[Gist of complete compilation output](https://gist.github.com/7Hazard/dcaf40e4e9cd1ee3c15e615be3252b18)

**Comment by tritao** [comment]
VS2015 fails because it tries to use the includes from VS2017, see https://github.com/mono/CppSharp/issues/814.

Closing for now as both issues mentioned here already have open issues.
