### ISSUE TITLE
Error parsing with VS 2017

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#885]
Using VS 2017 causes this error during parsing:
xstring(1905,26): error: constexpr variable '_Memcpy_move_offset' must be initialized by a constant expression

It's non-standard C++ which Clang cannot cope with. It might be a Clang bug. I have sent a report at https://bugs.llvm.org/show_bug.cgi?id=33735 . We'd best wait for their reply before deciding what to do.

**Comment by realvictorprm** [comment]
Thanks so much @ddobrev for investigating this!
