### ISSUE TITLE
Invalid code generated from typedef function pointers

### ISSUE THREAD

**Issue by Hirnschwamm** [mono/CppSharp#898]
##### Brief Description
Hello,
I am trying to wrap an API written in C. In the API there are functions that take a typedef function pointer as an argument, like so:

`PJ_DEF(pj_status_t) pjsip_register_uri_parser( char *scheme,
					       pjsip_parse_uri_func *func)`

with the following typedef:

`typedef void* (pjsip_parse_uri_func)(pj_scanner *scanner, pj_pool_t *pool,
				     pj_bool_t parse_params);`

From this CppSharp generates the following incompilable C#-Code:

`public static int PjsipRegisterUriParser(sbyte* scheme, Func<global::System.IntPtr, global::pjsua.PjScanner scanner, global::pjsua.PjPoolT pool, int parse_params> func) {...}`

The way I see it the typeparameters in the C#-Delegate should not have the identifiers left over. Is this a bug or am I simply using CppSharp wrongly?

OS: Windows, using the CppSharp NuGet package version 0.8.13 with Visual Studio 2017
Target: MSVC

**Comment by tritao** [comment]
Looks like a bug, should be easy to get fixed.

**Comment by Hirnschwamm** [comment]
If possible I would like to take a crack at fixing this. 
I have a question though: Do you think the problem lies with the parser or the generator component? After debugging the issue and looking through the codebase I noticed that the superfluous identifiers for the type parameters are already present in the parsed abstract syntax tree. Is it necessary to prevent this from happening or should the code generator just ignore the identifiers when generating the output? 
Any tips would be much appreciated, thanks in advance.

**Comment by ddobrev** [comment]
@Hirnschwamm thank you for your offer. I have to leave now but I can help you get started. You need to debug CSharpSources.GenerateFunction, FormatMethodParameters in particular. You could paste your function in one of our tests and debug from there - after you've followed our build instructions and generated your solution, paste the function in Common.h along with any dependencies to ensure it compiles, then set Common.Gen as your start-up project, run and debug.

**Comment by tritao** [comment]
Hey @Hirnschwamm, any progress on fixing the bug?

**Comment by Hirnschwamm** [comment]
Hi, sorry I haven't been following up on the issue. I haven't had the time recently. If this is a pressing matter I would propose a more experienced developer fixes this since I can not promise to deliver a fix immediately.
