### ISSUE TITLE
error: expected ';' after top level declarator

### ISSUE THREAD

**Issue by DevSidious** [mono/CppSharp#928]
Considering the following header file:

```
#ifndef HEADER_D1_SRTP_H
#define HEADER_D1_SRTP_H

#ifdef  __cplusplus
extern "C" {
#endif

#define SRTP_AES128_CM_SHA1_80 0x0001
#define SRTP_AES128_CM_SHA1_32 0x0002
#define SRTP_AES128_F8_SHA1_80 0x0003
#define SRTP_AES128_F8_SHA1_32 0x0004
#define SRTP_NULL_SHA1_80      0x0005
#define SRTP_NULL_SHA1_32      0x0006

int SSL_CTX_set_tlsext_use_srtp(SSL_CTX *ctx, const char *profiles);
int SSL_set_tlsext_use_srtp(SSL *ctx, const char *profiles);

STACK_OF(SRTP_PROTECTION_PROFILE) *SSL_get_srtp_profiles(SSL *ssl);
SRTP_PROTECTION_PROFILE *SSL_get_selected_srtp_profile(SSL *s);

#ifdef  __cplusplus
}
#endif

#endif
```

CppSharp fails to parse this with:

`C:\Dir\header.h(135,34): error: expected ';' after top level declarator`

Line 135:

`STACK_OF(SRTP_PROTECTION_PROFILE) *SSL_get_srtp_profiles(SSL *ssl);`

This issue pops up quite a bit on the web in a CLang context. Any ideas on how to make CppSharp immune to such annoyances ?

**Comment by ddobrev** [comment]
Are you sure you include all dependencies in your configuration of C++#? For example, where are STACK_OF, SRTP_PROTECTION_PROFILE and SSL defined?

**Comment by tritao** [comment]
If this is the full header file you're passing to CppSharp, then as @ddobrev said it's missing a lot of definitions which is expected to fail.

CppSharp behaves just like a C++ compiler, if in doubt just try to pass the header through GCC or Clang.

**Comment by DevSidious** [comment]
@ddobrev, @tritao 

That's the full header file, I just left out some 100+ lines of license text.

The full log for this particular header is:

```
Error parsing 'C:\headers\include\openssl\srtp.h'
C:\headers\include\openssl\srtp.h(132,33): error: unknown type name 'SSL_CTX'
C:\headers\include\openssl\srtp.h(133,29): error: unknown type name 'SSL'
C:\headers\include\openssl\srtp.h(135,1): error: unknown type name 'STACK_OF'
C:\headers\include\openssl\srtp.h(135,34): error: expected ';' after top level declarator
C:\headers\include\openssl\srtp.h(136,1): error: unknown type name 'SRTP_PROTECTION_PROFILE'
C:\headers\include\openssl\srtp.h(136,56): error: unknown type name 'SSL'
```

Errors **1-3** & **5-6** are expected, because **srtp.h** does not include the headers where those types are defined. To my mind however, error **4** is unexpected.

There are other header files missing includes and they fail like this:

```
Error parsing 'C:\headers\include\openssl\dtls1.h'
C:\headers\include\openssl\ossl_typ.h(86,9): warning: Warning, overriding WinCrypt defines
C:\headers\include\openssl\dtls1.h(114,2): error: unknown type name 'SSL_SESSION'
C:\headers\include\openssl\dtls1.h(175,2): error: unknown type name 'SSL3_BUFFER'
C:\headers\include\openssl\dtls1.h(176,2): error: unknown type name 'SSL3_RECORD'; did you mean 'USN_RECORD'?
```

```
Error parsing 'C:\headers\include\tls.h'
C:\headers\include\tls.h(187,1): error: unknown type name 'time_t'; did you mean 'size_t'?
C:\headers\include\tls.h(188,1): error: unknown type name 'time_t'; did you mean 'size_t'?
C:\headers\include\tls.h(201,1): error: unknown type name 'time_t'; did you mean 'size_t'?
C:\headers\include\tls.h(204,1): error: unknown type name 'time_t'; did you mean 'size_t'?
C:\headers\include\tls.h(205,1): error: unknown type name 'time_t'; did you mean 'size_t'?
```

Based on what I see in my logs and what information floats around on the web, the `error: expected ';' after top level declarator` does not appear to be related to unknown types.

**Comment by ddobrev** [comment]
@DevSidious as accurate as Clang is, you cannot be certain it can always behave precisely when types are missing because this can be interpreted in various ways. Ensure all macros are defined and if you then still get the error, we can talk more.

**Comment by tritao** [comment]
Unfortunately, if that is indeed the case, I'm afraid to say that is just badly written C code. 

Are we talking about this header file in particular? https://github.com/openssl/openssl/blob/master/include/openssl/srtp.h

If so, it seems like your version is missing the `# include <openssl/ssl.h>` part, which one would guess defines those missing types.

**Comment by DevSidious** [comment]
@ddobrev I'm onto that.

@ddobrev @tritao 

Would it be possible to configure **CppSharp** to search for types in the entire `module.Headers` collection even if a particular header file does not specifically include the source header for the type ? Now **THAT** would be something useful beyond belief.

**Comment by ddobrev** [comment]
@DevSidious I am afraid not. CppSharp does not "search", it simply parses the input headers. We don't want to, cannot and will not work with invalid input.

**Comment by tritao** [comment]
We already search for those "missing" types in the case of forward declarations (we call them incomplete types).

But in this case, what you're suggesting would be actually changing the C language (and the Clang compiler), which makes no sense in practice. What you want is for us to accept invalid C code and fix it after the fact.

**Comment by DevSidious** [comment]
@tritao 

No, it's the srtp.h in the LibreSSL tarball: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.5.5.tar.gz . However, it does miss the `# include <openssl/ssl.h>` .

**Comment by tritao** [comment]
That usually means the header is not intended to be included directly, but by some other header file that includes it (and defines the other necessary stuff previously).

I took a quick look at the tarball, and if you look inside `ssl.h`, you can see it includes those headers (after defining all the necessary types, line 886):

```
#include <openssl/ssl2.h>
#include <openssl/ssl3.h>
#include <openssl/tls1.h>	/* This is mostly sslv3 with a few tweaks */
#include <openssl/dtls1.h>	/* Datagram TLS */
#include <openssl/ssl23.h>
#include <openssl/srtp.h>	/* Support for the use_srtp extension */
```

This means you should only be passing the `ssl.h` header to CppSharp, and nothing else.

**Comment by DevSidious** [comment]
@tritao @ddobrev , you guys must be my lucky charm or something. @tritao 's suggestions and a bit of fiddling with CppSharp's driver setup and I got myself a fresh juicy wrapper.

Thanks guys!
