### ISSUE TITLE
Make Linux 32 Bit avail for cross-compile

### ISSUE THREAD

**Issue by wolfgangmauer** [mono/CppSharp#939]
Still not working for 32-Bit ???!!!!!
I like to have QtSharp, but not get CppSharp build on Linux-32 (no premake5-linux-32)!!!

**Comment by realvictorprm** [comment]
@ddobrev do we provide only a premake version for 64 bit?

**Comment by ddobrev** [comment]
@realvictorprm I'm afraid so, same goes for the parser bindings.

**Comment by realvictorprm** [comment]
We seriously need to fix that 😅

**Comment by wolfgangmauer** [comment]
It would be nice if you put focus more to Linux and not to windows :-)

**Comment by tritao** [comment]
There's only so much we can work on given our limited development resources.

If someone's willing to sponsor the feature, we'll work on it.

**Comment by wolfgangmauer** [comment]
I know this project is a lot of work...
BUT, if this project should make sense for "users", running/working on Linux(32) should not be a feature!?
I "like" to have QtSharp(ANY CPU/PLATFORM INDEPEND) as described in "Users" but neither QtSharp nor CppSharp can't be build on my ubuntu :-(

**Comment by realvictorprm** [comment]
On the other hand I wonder why people are still using 32 bit that extensively

**Comment by DevSidious** [comment]
@wolfgangmauer 

http://www.theregister.co.uk/2016/07/05/linux_letting_go_32bit_builds_on_the_way_out/

32 bit seems a burden and a waste of resources for most teams.

**Comment by realvictorprm** [comment]
@DevSidious nice hahaha :smile:
