### ISSUE TITLE
Adding the latest version of CppSharp to .NET project

### ISSUE THREAD

**Issue by StephanBueeler** [mono/CppSharp#945]
I'd like to use the latest version of CppSharp to for my .NET project. Since there is no release yet, I need to use the master. I'm trying to get it working with this build:

[windows-vs-x86](https://ci.appveyor.com/project/tritao/CppSharp/branch/master/artifacts)

Just adding the DLL's by reference doesen't seem to work for me. When I try to add "CppSharp.CppParser.dll" I get following error:

![invalid](https://user-images.githubusercontent.com/19504656/30051274-ac745696-9221-11e7-9a6c-7329c3f24b73.JPG)

I'm obviously doing something wrong here. Any advice how to add this new version?

**Comment by ddobrev** [comment]
@StephanBueeler you don't need to add this DLL, you only need to ensure it's copied to your outpur dir so that the other DLL-s can find it.

**Comment by StephanBueeler** [comment]
Got it.
