### ISSUE TITLE
C# bindings for C++ library

### ISSUE THREAD

**Issue by mapo80** [mono/CppSharp#950]
I've created a c# bindings for libpostal library ([link to LibPostalNet][1]).

I've used CppSharp to create bindings. It works but I don't how to convert this code :

    typedef struct libpostal_address_parser_response
    {
        size_t num_components;
        char** components;
        char** labels;
    }
    libpostal_address_parser_response_t;

CppSharp converts code in this way :

    public sbyte** Components
    {
        get
        {
            return (sbyte**)((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*)__Instance)->components;
        }
    
        set
        {
            ((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*)__Instance)->components = (global::System.IntPtr)value;
        }
    }
    
    public sbyte** Labels
    {
        get
        {
            return (sbyte**)((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*)__Instance)->labels;
        }
    
        set
        {
            ((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*)__Instance)->labels = (global::System.IntPtr)value;
        }
    }

Code should return a string array of num_components length.

Can you help me to solve this?

  [1]: https://github.com/mapo80/LibPostalNet

**Comment by ddobrev** [comment]
I am afraid you'll have to convert the pointers yourself. We don't know how many items there are in a returned array unless it's defined so. We also do not so far have such flexibility as to enable the user to select the size - in your case "num_components" - of the array himself at configuration time. So what you can do is define another part of the containing class, declare new properties returning arrays and have them call the generated properties and convert from and to the pointers.

**Comment by mapo80** [comment]
Sorry, I'm new with this kind of problem. To solve this I've to make changes on c++ library or Can I solve only editing c# bindings.
Thx.

**Comment by ddobrev** [comment]
@mapo80 you need to add a new C# partial class to your project and add your properties there.

**Comment by mapo80** [comment]
Ok, thanks I've understood your suggestions. Last question, I try to find how to convert pointer to pointer in array but no luck, do you have a snippet that can help me to solve this problem?

Thx.

**Comment by ddobrev** [comment]
@mapo80 to begin with, it would be a little easier if you used the MarshalCharAsManagedChar. Then you iterate over the pointer using "num_components". Then you need the length of each string - do you know it?

**Comment by tritao** [comment]
The strings should be null-terminated, so you should loop through the array (up to `num_components`and call [`Marshal.PtrToStringAuto`](https://msdn.microsoft.com/en-us/library/ewyktcaa.aspx) on each entry.

**Comment by mapo80** [comment]
Hi guys, thanks for your answers.
Author of libpostal has answered my question and has said are null-terminated strings.
Here is his answer:
https://github.com/openvenues/libpostal/issues/248#issuecomment-328395222

Later I'll try your suggestions.

Thx.

**Comment by mapo80** [comment]
Hi, thanks to you I've fixed errors.
This is snippet:

`    public partial class LibpostalAddressParserResponse
    {
        public Dictionary<string, string> Results
        {
            get
            {
                var _results = new Dictionary<string, string>();

                unsafe
                {
                    for (int buc = 0; buc < (int)NumComponents; buc++)
                    {
                        sbyte* pLabel = Labels[buc];
                        sbyte* pComponent = Components[buc];

                        _results.Add(Marshal.PtrToStringAnsi((IntPtr)pLabel), Marshal.PtrToStringAnsi((IntPtr)pComponent));
                    }
                }

                return _results;
            }
        }
    }`

Thanks very much.
