### ISSUE TITLE
Calling base class method in .Net Core 2.0

### ISSUE THREAD

**Issue by cnx-jd** [mono/CppSharp#951]
I've been doing some testing with CppSharp on Linux using .Net Core 2.0. Mostly things have been working as expected with simple classes. However, when I added a base class with an abstract method, I started to get some crashes. I then switched to running with Mono and things worked again.

OS: Linux x64 (Ubuntu 14.04)
.Net Core 2.0 
Mono 5.2

Here's my test header file.
```
struct handle{
    int ref;
    const char* name;
} ;

class baseObj 
{
    public:
        virtual handle getHandle() = 0;
};

struct data {
    double time;
    const char* message;
};

class customObj : public baseObj
{
    public:
        int value1;
        int value2;
        data result;               

        void execute();
        handle getHandle();
};
```

##### Used settings

Target: Linux,  GCC 4.8

Here's my CppSharp settings I'm using to generate the interop code.
```
 driver.Options.GeneratorKind = Generators.GeneratorKind.CSharp;
 driver.Options.OutputDir = "....";
            
 driver.Options.Compilation.Platform = TargetPlatform.Linux;
 driver.Options.Compilation.Target = CompilationTarget.SharedLibrary;
            
 var module = driver.Options.AddModule("Test");
 module.IncludeDirs.Add("/.../include");
 module.Headers.Add("test.hpp");
```

I have a simple test executable that creates an instance of the C++ class, and tries to call a few methods and access some data.

```
var x= new CustomObj();        
x.Execute();           
Console.WriteLine(x.Result.Message);   //Works in both .Net Core and Mono
Console.WriteLine(x.Handle.Name);     // Only works in Mono
```

When executing from Mono, the results are correct, but when running from .Net core I get errors when trying to access a return value of a method defined in my baseObj class (seg fault when reading the string, and an invalid number when accessing the integer)

Any idea why .Net Core wouldn't be able to access the base class method return value? Am I missing any settings needed for this? I'm happy to keep using Mono for now, but ideally I'd like to use .Net Core for the project I'm looking at. Thanks.

**Comment by tritao** [comment]
Hey, thanks for reporting this, unfortunately neither me nor @ddobrev will have time to check this in the near future.

**Comment by hanbim520** [comment]
Does it work on net 2.0? I want to use CppSharp on unity3D.

**Comment by tritao** [comment]
Entire test suite is passing with .NET Core now.
