### ISSUE TITLE
LLVM.lua script is not compatible with localized cl.exe

### ISSUE THREAD

**Issue by skyline75489** [mono/CppSharp#952]
##### Brief Description

OS: Windows 10 x64

##### Used settings

I'm using VS Simplified Chinese version.

##### Stack trace or incompilable generated code

LLVM.lua uses the regex `Version (%d+)%.%d+%.%d+%.?%d* for (%w+)'` to match the VC++ version. However my `cl.exe` output looks like this:

```plaintext
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]
```

The matching failed miserably. I suspect this failure also applies to other languages.

**Comment by realvictorprm** [comment]
outch, okay we definitely should find a way to recognize the version in a better way

**Comment by realvictorprm** [comment]
@ddobrev shouldn't a match against only the number be enough?

**Comment by skyline75489** [comment]
Actually I've tried matching against number. Seems to work.

**Comment by realvictorprm** [comment]
@skyline75489 I suppose so but I'm not sure whether this is fine enough

**Comment by tritao** [comment]
@skyline75489 Mind sending a PR with that fix? We have no way of testing chinese locale here.

**Comment by skyline75489** [comment]
I'd like to do so. But I'm not sure if this will work with other languages. I think we should maybe consider using something "language-neutral" way?

**Comment by tritao** [comment]
Wait, which CppSharp revision are you using?

On master we already seem to be matching on number: https://github.com/mono/CppSharp/blob/master/build/scripts/LLVM.lua#L60

**Comment by skyline75489** [comment]
Yeah, I'm using an old version actually. Didn't realize it until now. I'm using CppSharp-0.7.5

**Comment by skyline75489** [comment]
I'll just close this for now. If anyone else finds their languages are not supported, this issue could be a reference.

**Comment by realvictorprm** [comment]
I remember, last time this was edited I had problems with using it for german PC's :joy:
