### ISSUE TITLE
Invalid chars in the path error with last release

### ISSUE THREAD

**Issue by zillemarco** [mono/CppSharp#957]
Using the last release, installed via Nuget package, my implementation of the `ILibrary` gives the error `Error 0x80070057: invalid characters found inside the path` immediately after `Setup` has been called.

This error isn't related with one of the paths I'm trying to compile or anything else I provide to CppSharp since even leaving the `Setup` completely empty I get this error.

My supposition is that there is a problem searching for my Visual Studio 2017 installation folders because, after getting the previous error, I get another error saying `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\crtdefs.h(10,10): fatal: 'corecrt.h' file not found`, which should be found inside the Visual Studio SDKs folders.

If no-one knows about this I'll gladly debug this out.

**Comment by ddobrev** [comment]
@zillemarco we do not know about this bug. Any help, even just debugging, is welcome.

**Comment by zillemarco** [comment]
@ddobrev alright, no problem.

**Comment by zillemarco** [comment]
@ddobrev I've found the culprit. When looking for the Visual Studio 2017 system includes, a regex is used to find the Win10SDK. The regex on my installation doesn't work since the sdk on my machine has this ID `Microsoft.VisualStudio.Component.Windows10SDK.14393`, but the regex expects a dot after the build number `Regex(@"Windows10SDK\.(\d+)\.")`. Remove the last dot from the regex fixed the issue, but is this right? Maybe you have put the dot at the end for some reason

**Comment by ddobrev** [comment]
@zillemarco please just add a ? after . and send a pull.

**Comment by realvictorprm** [comment]
Huh VS 2017 compatibility sucks. 
Implementing this stuff was no big fun :/ 

@ddobrev where is this dot coming from :D

**Comment by realvictorprm** [comment]
Ah I know why. All fine, didn't know that there are cases where the dot isn't needed.

**Comment by ddobrev** [comment]
@realvictorprm I didn't either. Boy, how many less bugs we'd have if I knew everything in advance...

**Comment by zillemarco** [comment]
@ddobrev if you find a way to know things in advance please let us all know :D

**Comment by zillemarco** [comment]
Eh, no time no code here :D 
I've been pretty busy at work...now I need CppSharp there too ;)

No problem BTW, always happy to help :)
