### ISSUE TITLE
Incorrect returned values when v-table generation and virtual members are involved

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#96]
To reproduce, add any virtual method to Qux in CSharpTemp.h; TestMultipleInheritance's going to fail at Assert.That(baz[0], Is.EqualTo(50)); .

**Comment by genuinelucifer** [comment]
@ddobrev  @tritao I would like to work on this issue. I have reproduced it successfully. Please provide some guidance in this regard.

**Comment by ddobrev** [comment]
@genuinelucifer this one could be little more difficult. Do you mind finishing https://github.com/mono/CppSharp/issues/334, https://github.com/mono/CppSharp/issues/383 and https://github.com/mono/CppSharp/issues/402 first?

**Comment by genuinelucifer** [comment]
@ddobrev Perfectly fine. I will try to finish those first and then come to it. :+1:

**Comment by ddobrev** [comment]
Fixed by 6f8c942b0ac0162c32310f21a0f7492a0dca0797.
