### ISSUE TITLE
Set function with boolean return

### ISSUE THREAD

**Issue by Enumer8** [mono/CppSharp#960]
Before NuGet release 0.8.14, if there was a set function with a boolean return value, the function would not become a set property. With NuGet release 0.8.14, the set function now becomes a property.

Original cpp code:
```
struct Example
{
   int getValue();
   bool setValue(int);
}
```

Before, I used to be able to use the struct in C# like:
```
Example example = new Example();
if ( example.SetValue(4) )
{
   // do something
}
```

Now, all I have is:
```
Example example = new Example();
example.Value = 4; // How do I see the boolean return value?
```

Is there a way to use the old behavior, or alternatively, is there a way to somehow see the boolean return value? (I don't want to disable properties all together, because I still want the get to work.) I guess if there isn't, then I'll have to change the return type to size_t or something else.

The change occurred in commit 973fdafdfe06d9ed9aca06650263e0c3b0fb08d8 to file src/Generator/Passes/GetterSetterToPropertyPass.cs.

**Comment by ddobrev** [comment]
@u255436 could you please share what value did your setter return? What happens if you execute the code in either case? In case the code was only executed if the value changed, would it work to just:

```csharp
if (example.Value != 4)
{
    example.Value = 4;
    // do something
}

?

**Comment by u255436** [comment]
@ddobrev, that could work assuming the value is just a simple value. In general though, arbitrary code could be run on set. For example, maybe you have to save a file, create a log entry, send a message over the network, or anything else that could fail. It's possible that the value will match, but the other function didn't work.

Perhaps the solution would be to generate the set property for convenience, but also generate the SetValue() for completeness (in case the return value is necessary).

**Comment by tritao** [comment]
I like that solution.

**Comment by ddobrev** [comment]
@u255436 @tritao yes, it does sound neat. @u255436 would you mind sending a pull? If not, you'll have it in the next release.
