### ISSUE TITLE
How to include missing libraries in order to parse code

### ISSUE THREAD

**Issue by StephanBueeler** [mono/CppSharp#963]
##### Brief Description
I want to parse basic C++ code. My programm is just a copy of following example: 

https://github.com/mono/CppSharp/blob/master/examples/Parser/Parser.cs

When I run the programm it states that the inluded libraries are required: 

System.Exception: Couldn't parse source code. C:\Path\ToFile\FlatFileTest.cpp(1,10): fatal: 'stdafx.h' file not found

Do I have to include every library by hand or is there a way to do it automatically? Or is there any workaround? And why does this even require the libraries?

##### Stack trace or incompilable generated code

Test method Tests.ClassFileLoaderCppTest.LoadTest threw exception: 
System.Exception: Couldn't parse source code. C:\Path\ToFile\FlatFileTest.cpp(1,10): fatal: 'stdafx.h' file not found
    bei Sas.FABA.BuildTools.Common.ClassFileLoaderCPP.GetAstContext(String file, String folder) in C:\Dir\Cake\Source\Common\ClassFileLoaderCPP.cs:Zeile 152.
   bei Sas.FABA.BuildTools.Common.ClassFileLoaderCPP.<>c__DisplayClass2_0`1.<Load>b__3(<>f__AnonymousType0`1 data) in C:\Dir\Cake\Source\Common\ClassFileLoaderCPP.cs:Zeile 59.
   bei System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Sas.FABA.BuildTools.Common.ClassFileLoaderCPP.Load[T](String folder, String filePattern, LoaderFilters filters) in C:\Work\Cake\Source\Common\ClassFileLoaderCPP.cs:Zeile 41.
   bei Tests.ClassFileLoaderCppTest.LoadTest() in C:\Dir\Cake\Source\Tests\ClassFileLoaderCppTest.cs:Zeile 15.

**Comment by ddobrev** [comment]
@StephanBueeler do you pass this FlatFileTest.cpp to C++#? If you do, you shouldn't. C++# only works with headers to generate an API. CPP-s contain implementations, not interfaces, so C++# can not, should not and will not work with them.

**Comment by StephanBueeler** [comment]
@ddobrev Yes I do. Because I just want to use a small portion of C++#.
My main goal is to parse cpp-Testfiles to extract the methodname and its attributes (like TESTCASE_AUTHOR, TESTCASE_DESCRIPTION etc.). I want to use C++# to do this, because Clang seems to be a more difficult solution.
Is this possible? And if not, have you got any other idea of doing this?

**Comment by ddobrev** [comment]
@StephanBueeler aren't all methods you want parsed declared in a header as well? Why don't you parse the headers instead? Is the reason that those attributes are only declared in the CPP? If so, is there a way you could move them to the headers?

**Comment by tritao** [comment]
@ddobrev That's irrelevant for the issue at hand. Stephan would face the same issue with headers.

@StephanBueeler Look at the [`ParserOptions`](https://github.com/mono/CppSharp/blob/master/src/Parser/ParserOptions.cs) class, it provides methods for setting up the include context in the parser for Visual Studio.

**Comment by ddobrev** [comment]
@tritao if the methods are declared in the headers along with those attributes, the latter would be parsed as macros and @StephanBueeler would be able to read them from the AST.

**Comment by tritao** [comment]
It makes zero difference to Clang whether the source code we pass comes
from a .c or .h file. The issue here is an incorrect include search setup.

**Comment by ddobrev** [comment]
@tritao I was assuming the content of that CPP. If that content is actually declarations rather than definitions, then yes, the extension doesn't matter. Anyway, I hope you're right that this can be fixed with a simple configuration.

**Comment by ddobrev** [comment]
@StephanBueeler if @tritao is right and you get this to work with just configuration, please close this issue.

**Comment by tritao** [comment]
@StephanBueeler How did you end up fixing the issue? Post here so people can find the solution next time.

**Comment by StephanBueeler** [comment]
@tritao I didn't. I haven't had time to work on this problem, but now I'm on it again.
I've made this simple method "GetASTContext" in order to parse a file.
[GetASTContextMethod.txt](https://github.com/mono/CppSharp/files/1410707/GetASTContextMethod.txt)

It's basically your same exact example, but I still have problems with the following appearing issue:

When I parse the source file, following exception appears:
[GetASTContextMethodException.txt](https://github.com/mono/CppSharp/files/1410749/GetASTContextMethodException.txt)

It seems that I'm missing some header files, but how can I find and include them ?

**Comment by tritao** [comment]
Maybe try going for a newer language version, C++11 or C++14.

**Comment by StephanBueeler** [comment]
That brought me further. Now, looking at the ASTContext, something came into my mind.
I am trying to parse C++ code to read out the contents of "#defines".  It appears that they don't show up in the AST tree.  Am I missing a setting or is this by design?

If there are any other ways to do this such as inline methods I may be able to do this.  Would this help?  If not I may just need to parse the values out by text parsing.

Thanks in advance for all your help.

**Comment by ddobrev** [comment]
@StephanBueeler you should be able to find them in the lists of macros declaration have.

**Comment by StephanBueeler** [comment]
I'm back with two more questions:
1. Is it possible to ignore all header files and parse just one simple file?
2. When trying to parse following file:
[ErrorFile.txt](https://github.com/mono/CppSharp/files/1445877/ErrorFile.txt)
It throws a System.InvalidCastException: 'The object of type "CppSharp.AST.Class" couldn't be converted to "CppSharp.AST.ClassTemplateSpecialization".' Is this an error by me?

**Comment by ddobrev** [comment]
1. The headers you want parsed are those added to Module.Headers, however, dependencies are parsed as well;
2. We might have a bug. Do you use the NuGet or master? If it's the latter, please try debugging and post the results.
