### ISSUE TITLE
Dublicated identifier in enum binding.

### ISSUE THREAD

**Issue by MEikermann** [mono/CppSharp#965]
##### Brief Description
For enums with definitions like NAME_A = 10 and NAME__A = 20,
CppSharp will change the latter definition to NAME_A. The generated
CSharp binding will then fail to compile since NAME_A is redefined.

OS: Windows / OS X / Linux (include version and/or distro)

##### Used settings

Target: MSVC

Other settings 
Current Nuget package in a VS2017 project.

**Comment by vamsibulusu** [comment]
@ddobrev Any help on where to start? I've gone through the generatingbindings.md and developers manual.

**Comment by ddobrev** [comment]
@vamsibulusu first add a test to our suite in order to reproduce the problem. Then you can start debugging from our generator.
