### ISSUE TITLE
Error EXEC : error 0x80070057: Illegal characters in path.'  in GetSystemIncludesVS2017

### ISSUE THREAD

**Issue by ChrisJMarshall** [mono/CppSharp#977]
OS: Windows
Target: MSVC
Generator: CLI

##### Brief Description
I tried to upgrade my project to 0.8.14 from 0.8.11 and I'm getting an error 'EXEC : error 0x80070057: Illegal characters in path.' before 'Parsing Libraries' followed by a failure to find corecrt.h . I've managed to debug the source and the problem appears to be in GetSystemIncludesVS2017. For me sdk.GetId() returns "Microsoft.VisualStudio.Component.Windows10SDK.14393" without a trailing dot. This fails to match regexWinSDK10Version. Removing the dot from the regex or adding a question mark to the end (to make the dot optional) fixes this for me.

**Comment by ddobrev** [comment]
@ChrisJMarshall this bug has already been fixed in https://github.com/mono/CppSharp/commit/2b9bf29a70b10281e0759b39e893ccb555fdeb0c exactly the way you say. It's going to enter the next release, until then you can use master.

**Comment by ChrisJMarshall** [comment]
Thanks for the speedy response. Didn't spot the existing bug.

**Comment by ispysoftware** [comment]
it's unfortunate that this is the version on nuget...
