### ISSUE TITLE
Stack exhaustion on FindVSVersion endless recursive loop (in 0.8.14 release)

### ISSUE THREAD

**Issue by Alien-AV** [mono/CppSharp#981]
When trying to run a minimal example of the code, I get a StackOverflowException, on an endless loop of FindVSVersion recursive calls. Doesn't reproduce on 0.8.13.

VS2015
OS: Windows
Target: MSVC

**Comment by ddobrev** [comment]
@Alien-AV if it doesn't occur with 0.8.14 I assume you're using C++# built from source code. In this case may I ask you to debug it and share your findings? It should be something simple, that code is pretty trivial.

**Comment by Alien-AV** [comment]
Editing - it doesn't reproduce on 0.8.13.
I didn't build it from source code, I'll build it and look into it though.
Currently the assumption is that the check `if (vsSdk.IsValid)` at https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L160 always fails, and there is no "else" clause.

**Comment by tritao** [comment]
Can you post the output of `MSVCToolchain.DumpSdks()`? You can write a simple console program referencing `CppSharp.dll` for this.

**Comment by Alien-AV** [comment]
I've installed Visual Studio 2017 since my post, and this worked around the issue - I succeeded to create bindings (building in VS2015).

I'll post the current output of DumpSdks still (after installing VS2017):

> Visual Studio SDKs:
>         (12) C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\
>         (14) C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
>         (15) C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE
> 
> Windows SDKs:
>         (7.1) C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\
>         (8) C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\
>         (8.1) C:\Program Files (x86)\Windows Kits\8.1\
>         (8.1) C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\
>         (10) C:\Program Files (x86)\Windows Kits\10\
> 
> Windows Kits SDKs:
>         (1) C:\Program Files (x86)\Windows Kits\8.1\
>         (10) C:\Program Files (x86)\Windows Kits\10\
> 
> .NET Framework SDKs:
> 
> MSBuild SDKs:
>         (2) C:\Windows\Microsoft.NET\Framework\v2.0.50727\
>         (3.5) C:\Windows\Microsoft.NET\Framework\v3.5\
>         (4) C:\Windows\Microsoft.NET\Framework\v4.0.30319\
>         (12) C:\Program Files (x86)\MSBuild\12.0\bin\
>         (14) C:\Program Files (x86)\MSBuild\14.0\bin\

**Comment by ddobrev** [comment]
@Alien-AV while I am happy you got your problem solved, I am really sorry you couldn't debug it. Our free time is limited and we cannot afford to replicate your previous environment - VS 2015 without VS 2017 - in order to track the bug down. Still, if you could manually disable VS 2017 in our code, for example my removing the respective enum member, and try again. This way you should only test for VS 2015 and therefore reproduce the crash - assuming you've now built C++# from source code. Let me know if you try.

**Comment by Alien-AV** [comment]
I wouldn't mind removing VS 2017 temporarily to debug, but
I'm currently failing to build C++# from source.

I have a few issues with it, I wonder if I should open issues on each separately:

- Some files in `build\vs2015\gen\` folder are missing.
- Also, variable amount of errors like: `Error	CS0006	Metadata file 'path\to\CppSharp\build\vs2015\projects\..\lib\Release_x86\CLI.CLI.dll' could not be found` pop up when building.
- Projects aren't generated with 64bit flavor.
- I tried to force them to via `"premake5" --file=premake5.lua vs2015 --arch=x64`, but it turned out I'd have to build 64bit LLVM on my own.
- I tried building 64bit LLVM, but despite setting a flag for 64bit (`premake5.exe --file=scripts/LLVM.lua build_llvm --arch=x64`), it didn't want to build in "VS2015 x64 Native Tools Command Prompt", only x86. So I'm not sure the result is 64bit even.

**Comment by ddobrev** [comment]
@Alien-AV thank you for trying to help.
Please save your time with a 64-bit build, compiling Clang takes a long time. About the other issue: did you follow our instructions about using GenerateFiles.bat?

**Comment by Alien-AV** [comment]
I followed instructions from [GettingStarted.md](https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md), namely:

1. Run DownloadDeps.bat successfully
2. Run GenerateProjects.bat successfully
3. Build in Visual Studio

I'll try reverting the repo and going through the steps again, since I've toyed around with building clang etc, not sure how much that could have affected.

**Comment by ddobrev** [comment]
@Alien-AV in addition, CLI.CLI.dll is a generated file. What most probably happens is that generation fails for you. To debug, set a .Gen project as the starting one and debug instead of building the whole solution.

**Comment by tritao** [comment]
The build process itself relies on running CppSharp, so it could very well be failing with the same problem as this issue. The only thing that needs to be building is `CppSharp.dll`. If that builds, then you can use it from a simple console project and try to debug the issue by calling `FindVSVersion`.

**Comment by Alien-AV** [comment]
When I run CppSharp.Parser.Gen in VS2015: `\CppSharp\src\CppParser/Helpers.h(10,10): fatal: 'cstdint' file not found` is printed. What could be the cause?


Sidenote:
As far as I can tell, in 2017 it doesn't happen, as the build of the whole project finishes successfully.
I needed to use the console instructions for that (`msbuild vs2017\CppSharp.sln /p:Configuration=Release;Platform=x86`).
Hitting the "Run" button in GUI said "object of type class library can't be started directly".
Not sure why the 2 approaches (GUI vs CLI) give different results.

**Comment by ddobrev** [comment]
@Alien-AV this sound like a separate issue so please report it as such.
About this current issue, I would really like your help. Could you please try the following: disable th branch of code for VS 2017 and see if you get the endless recursion?

**Comment by ytka** [comment]
@ddobrev I think that the problem is caused by the following code.

``` 
       //src/Core/Toolchains/MSVCToolchain.cs
        public static VisualStudioVersion FindVSVersion(VisualStudioVersion vsVersion)
        {
            if (vsVersion != VisualStudioVersion.Latest)
            {
                var vsSdk = GetVSToolchain(vsVersion);
                if (vsSdk.IsValid)
                    return vsVersion;
            }

            // we don't know what "latest" is on a given machine
            // so start from the latest specified version and loop until a match is found 
            for (var i = VisualStudioVersion.Latest - 1; i >= VisualStudioVersion.VS2012; i--)
            {
                vsVersion = FindVSVersion(i);
                if (vsVersion != VisualStudioVersion.Latest)
                    return vsVersion;
            }

            return VisualStudioVersion.Latest;
        }
```

The amendment is as follows.
```
        public static VisualStudioVersion FindVSVersion(VisualStudioVersion vsVersion)
        {
            // we don't know what "latest" is on a given machine
            // so start from the latest specified version and loop until a match is found 
            for (var i = VisualStudioVersion.Latest - 1; i >= VisualStudioVersion.VS2012; i--)
            {
                var vsSdk = GetVSToolchain(i);
                if (vsSdk.IsValid)
                    return i;
            }

            return VisualStudioVersion.Latest;
        }
```

**Comment by jongkeor** [comment]
Good.
~~~
        public static VisualStudioVersion FindVSVersion(VisualStudioVersion vsVersion)
        {
            // we don't know what "latest" is on a given machine
            // so start from the latest specified version and loop until a match is found 
            for (var i = VisualStudioVersion.Latest - 1; i >= VisualStudioVersion.VS2012; i--)
            {
                var vsSdk = GetVSToolchain(i);
                if (vsSdk.IsValid)
                    return i;
            }

            return VisualStudioVersion.Latest;
        }
~~~

**Comment by ddobrev** [comment]
Regardless whether this is still an issue, the approach itself is obsolete as we have long switched to looking headers up with Clang. This piece is only left for backward compatibility and most probably won't be extended for VS 2019 or later.
