### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by mfkl** [mono/CppSharp#995]
##### Brief Description

[This struct field](https://github.com/mfkl/libvlcsharp/blob/36717c1ca2cd1e2f2ae4ff373750290fa960c3ee/libvlcsharp/include/vlc/libvlc.h#L506`), which generates a property with CppSharp throws on this [line](https://github.com/mfkl/libvlcsharp/blob/36717c1ca2cd1e2f2ae4ff373750290fa960c3ee/Sample/Generated/libvlc.cs#L387) when called in a [while loop](https://github.com/mfkl/libvlcsharp/blob/36717c1ca2cd1e2f2ae4ff373750290fa960c3ee/Sample/Manual/libvlc.cs#L347). It works for the first few elements though, but then throws instead of returning null?

##### OS: Windows / OS X / Linux (include version and/or distro)
Windows 10 1709.
CppSharp 0.8.14 x64 from nuget

##### Used headers
See above.

##### Used settings
[Settings](https://github.com/mfkl/libvlcsharp/blob/master/libvlcsharp/Program.cs)

##### Stack trace or incompilable generated code
Not much.
```Exception thrown: 'System.AccessViolationException' in Sample.exe
An unhandled exception of type 'System.AccessViolationException' occurred in Sample.exe
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.```

**Comment by tritao** [comment]
Any idea why it throws? The code looks correct to me.

**Comment by mfkl** [comment]
Not sure but [this code](https://github.com/mfkl/libvlcsharp/blob/c6829f4fb2ef56cf331cc432f7c04f61d4f9ca06/Sample/Manual/libvlc.cs#L315) seems to work. 
It does throw the same exception when I try to release the object though (by calling libvlc C function that's supposed to release the memory). 

Do you have any general advice to debug or get more information about AccessViolation exceptions?

**Comment by tritao** [comment]
It usually means you are trying to access memory that you are not allowed to. I usually just use a debugger and step through the code to figure these out.

**Comment by mfkl** [comment]
Right. I'll keep investigating. Thanks.
